src/Nethermind/Nethermind.EvmPlayground/Program.cs

This allows pushing of variable length hexadecimal values, e.g.:
PX 0a
PX 8e21a363dce22ff6057deef7c074062037f571
Case is insensitive, but an even number of nibbles must be provided.  A maximum of 32 bytes (64 nibbles) are allowed, since the longest `PUSH` opcode available in EVM is `PUSH32`.

add macro expansion of PX opcode for pushing hex values

---

src/Nethermind/Nethermind.Benchmarks/Evm/BitwiseAnd.cs
src/Nethermind/Nethermind.Benchmarks/Evm/BitwiseNot.cs
src/Nethermind/Nethermind.Benchmarks/Evm/BitwiseOr.cs
src/Nethermind/Nethermind.Benchmarks/Evm/BitwiseXor.cs
src/Nethermind/Nethermind.Benchmarks/Program.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

|   Method |       Mean |     Error |    StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |-----------:|----------:|----------:|------:|------:|------:|------:|----------:|
|  Current | 28.5806 ns | 0.1132 ns | 0.0945 ns |  1.00 |     - |     - |     - |         - |
| Improved |  0.6117 ns | 0.0220 ns | 0.0195 ns |  0.02 |     - |     - |     - |         - |
|   Method |       Mean |     Error |    StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |-----------:|----------:|----------:|------:|------:|------:|------:|----------:|
|  Current | 22.9990 ns | 0.4591 ns | 0.4714 ns |  1.00 |     - |     - |     - |         - |
| Improved |  0.3141 ns | 0.0114 ns | 0.0096 ns |  0.01 |     - |     - |     - |         - |
|   Method |       Mean |     Error |    StdDev …

Vector based VM bitwise operators and benchmarks for #713

---

src/Nethermind/Nethermind.Cli/Modules/EthCliModule.cs
src/Nethermind/Nethermind.DataMarketplace.Test/ContractInteractionTest.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs
src/Nethermind/Nethermind.JsonRpc.Test/Data/SerializationTestBase.cs
src/Nethermind/Nethermind.JsonRpc.Test/Eip1186/ProofCollectorTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Eip1186/ProofConverterTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/ProofCollectorTests.cs
src/Nethermind/Nethermind.JsonRpc/Eip1186/AccountProof.cs
src/Nethermind/Nethermind.JsonRpc/Eip1186/ProofCollector.cs
src/Nethermind/Nethermind.JsonRpc/Eip1186/StorageProof.cs
src/Nethermind/Nethermind.JsonRpc/Eip1186/SyncingResultConverter.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModuleFactory.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthModule.cs
src/Nethermind/Nethermind.JsonRpc/ProofCollector.cs
src/Nethermind/Nethermind.Store/IStateReader.cs
src/Nethermind/Nethermind.Store/ITreeVisitor.cs
src/Nethermind/Nethermind.Store/StateReader.cs
src/Nethermind/Nethermind.Store/TreeDumper.cs
src/Nethermind/Nethermind.Store/TrieNode.cs
src/Nethermind/Nethermind.Store/TrieStatsCollector.cs

Adds an implementation of EIP-1186
We are using a Tree Visitor implementation that collects the information to build a proof for the account and storage values. We use the fact that the state and storage DBs are together.

Get proof 741

---

src/Nethermind/Nethermind.Runner/Controllers/MainController.cs

Using the JSON RPC endpoint in a reverse proxy environment was returning 404's as ASP.Net's MVC routing didn't match to the rpc route.
Example: 
1. a request for `http://rpc.example.com/goerli/nethermind` is reverse proxied to `http://<nethermind-client>:8345`
2. the HTTP request will carry the path portion (`/goerli/nethermind`) untouched to nethermind
3. ASP.Net MVC routing in nethermind has no way to route this path and will respond with a `404`
The proposed fix will make the route on `MainController` to act as a "catch-all" route to ignore the path segments.
We would need this fix to run Nethermind in our RPC stack at Slock.it

Add wildcard routing for RPC

---

src/Nethermind/Nethermind.Core/IJsonSerializer.cs
src/Nethermind/Nethermind.Core/Json/EthereumJsonSerializer.cs
src/Nethermind/Nethermind.Core/Json/IdConverter.cs
src/Nethermind/Nethermind.Core/Json/UnforgivingJsonSerializer.cs
src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcRequest.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcResponse.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
src/Nethermind/Nethermind.Runner/RunnerAppBase.cs
src/Nethermind/Nethermind.Runner/Startup.cs

It adds support for JSON RPC requests in the form of "67" or 67 or "0x1234" or 2312423415552531523423423423424 or "some-long-guid-here".
It makes one more step towards getting rid of the UnforgivingJsonSerializer.
It simplifies the IJsonSerializer API.
It optimizes the serialize / deserialize calls from EthereumJsonSerializer so they reuse serializers.
Fixes #983

IdConverter and serialization changes

---

src/Nethermind/Nethermind.Benchmark/Evm/BitwiseAndBenchmark.cs
src/Nethermind/Nethermind.Benchmark/Evm/BitwiseNotBenchmark.cs
src/Nethermind/Nethermind.Benchmark/Evm/BitwiseOrBenchmark.cs
src/Nethermind/Nethermind.Benchmark/Evm/BitwiseXorBenchmark.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

This PR provides an improvement over bitwise operations for non SIMD-enabled executions. It shows a tremendous gain for non-vectorized (up to 10-15 times faster).
It does it by treating `Span<byte>` as `ref ulong` and then using ref arithmetic and the fact that the size of the span is known up front, to batch computation and skip boundary checks.
Before
|   Method |       Mean |     Error |    StdDev | Ratio | Allocated |
|--------- |-----------:|----------:|----------:|------:|----------:|
|  Current | 38.3080 ns | 0.8547 ns | 2.1285 ns |  1.00 |         - |
| Improved |  0.7642 ns | 0.0574 ns | 0.1237 ns |  0.02 |         - |
After
|   Method |      Mean |     Error |    StdDev | Ratio | RatioSD | Allocated |
|--------- |----------:|----------:|----------:|------:|--------:|----------:| …

Bitwise speed up for execution in a non vectorized environments

---

src/Nethermind/Nethermind.Core/Extensions/Bytes.cs

This PR makes `ByteArrayToHexViaLookup32Safe` a bit faster (~20-25%) by:
1. unrolling the loop with `ref` arithmetic
1. skipping redundant length checks
It potentially shows how this optimization can be done in other places
Before
|     Method |      Mean |    Error |   StdDev | Ratio | RatioSD | Allocated |
|----------- |----------:|---------:|---------:|------:|--------:|----------:|
| SafeLookup | 121.43 ns | 1.760 ns | 1.646 ns |  1.84 |    0.09 |     280 B |
|   HexMateA |  71.45 ns | 2.265 ns | 6.608 ns |  1.00 |    0.00 |     280 B |
After
|     Method |     Mean |    Error |   StdDev | Ratio | RatioSD | Allocated |
|----------- |---------:|---------:|---------:|------:|--------:|----------:|
| SafeLookup | 97.17 ns | 2.011 ns | 4.198 ns |  1.46 |    0.09 |     280 B |
|   HexMateA …

ByteArrayToHexViaLookup32Safe made faster

---

src/Nethermind/Nethermind.Blockchain.Test/Synchronization/FastSync/NodeDataDownloaderTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Synchronization/MeasuredProgressTests.cs
src/Nethermind/Nethermind.Blockchain/TxPools/TxPool.cs
src/Nethermind/Nethermind.Blockchain/TxPools/TxPoolConfig.cs
src/Nethermind/Nethermind.Core.Test/SortedPoolTests.cs
src/Nethermind/Nethermind.Core/SortedPool.cs
src/Nethermind/Nethermind.Mining/Ethash.cs
src/Nethermind/Nethermind.Mining/EthashCache.cs
src/Nethermind/Nethermind.Mining/FullDataSet.cs
src/Nethermind/Nethermind.Mining/IEthashDataSet.cs
src/Nethermind/Nethermind.Network/P2P/HelloMessageSerializer.cs
src/Nethermind/Nethermind.sln.DotSettings

(also rebased on top of the other PR - pending_limits)
Waiting for Task.Result outside of a lock.
Removing old epochs from cache.
string interning on client ids and capabilities.
Array Pool used for ethash uint[][]

ethash optimizations

---

src/Nethermind/Nethermind.Core/Crypto/Keccak512.cs
src/Nethermind/Nethermind.HashLib/Crypto/SHA3/KeccakBase.cs
src/Nethermind/Nethermind.HashLib/Hash.cs
src/Nethermind/Nethermind.HashLib/HashCryptoNotBuildIn.cs
src/Nethermind/Nethermind.HashLib/Nethermind.HashLib.csproj
src/Nethermind/Nethermind.Mining/Ethash.cs
src/Nethermind/Nethermind.Mining/EthashCache.cs
src/Nethermind/Nethermind.Mining/FullDataSet.cs
src/Nethermind/Nethermind.Mining/IEthashDataSet.cs

An evening play with ethash resulting in the following improvement showed by benchmark
|   Method |     Mean |     Error |   StdDev |Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |---------:|----------:|---------:|-----:|------:|------:|------:|----------:|
| Before   | 25.07 ms | 0.6110 ms | 1.733 ms | 1.00 |     - |     - |     - | 261.91 KB |
| After changing Hashimoto   | 24.04 ms | 0.4697 ms | 0.8707 ms| 1.00 |     - |     - |     - | 223.91 KB |
| After improving EthashCache | 24.53 ms | 0.4897 ms | 0.8831 ms |  1.00 |     - |     - |     - |   2.84 KB |
The first important improvement was moving the allocation of the array in `Hashimoto` outside of the loop. The second, was improving `Keccak512` to be able to run it on `Span<uint>`, which caused the benchmark to drop …

Less allocatey ethash

---

src/Nethermind/Nethermind.JsonRpc/Data/ProofConverter.cs
src/Nethermind/Nethermind.Store/Proofs/AccountProof.cs
src/Nethermind/Nethermind.Store/Proofs/AccountProofCollector.cs

currently `proof_call` delivers a array of AccountProofs, but we don't know the address of the proof.
So adding the address fixes this issue

add Address to the AccountProof

---

src/Nethermind/Nethermind.Evm.Test/Tracing/ProofTxTracerTests.cs
src/Nethermind/Nethermind.Evm/Tracing/CallOutputTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofBlockTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofTxTracer.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Proof/ProofModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofModule.cs
src/Nethermind/Nethermind.Store/IStateTracer.cs
src/Nethermind/Nethermind.Store/StateProvider.cs

Removes the system account from the proof list unless the system account was actually referred to in some way beyond the SENDER read.
an account will included if one of these conditions are true:
- the account is the sender and gasPrice>0
- the account code or storage is used in one of these opcodes BALANCE, CREATE, CALL, CALLCODE, DELEGATECALL, STATICCALL, EXTCODECOPY, EXTCODESIZE or EXTCODEHASH
- the accounts storage is used in an SLOAD

proofs with system accounts

---

src/Nethermind/Nethermind.Serialization.Json/IdConverter.cs

There is an incredibly high probability that this won't work with only these changes, but I thought I would give it a try and help kickstart an actual fix.
https://www.jsonrpc.org/specification#request_object
Note that according to the JSON-RPC specification, `null` is an allowed value for `id`.  The server should be blindly returning whatever value the client gives, as long as it is a number, string, or null.
I actually believe there is a secondary problem here in that you are using `Integer` during the `ReadJson` process and while discouraged, doubles are supported for the `id` field.  Similarly, you are returning `BigInteger` values for the ID, but BigIntegers are not supported in JSON, only doubles are, so any situation in which you are returning a `long` or `BigInteger` (rather than …

Adds support for null ID to match JSON-RPC specification.

---

src/Nethermind/Nethermind.Blockchain.Test/Synchronization/EthSyncPeerPoolTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Synchronization/FastSync/NodeDataDownloaderTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Synchronization/OldStyleFullSynchronizerTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Synchronization/SyncThreadTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Synchronization/SynchronizerTests.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/EthSyncPeerPool.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/FastBlocks/FastBlocksDownloader.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/FastSync/NodeDataDownloader.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/IEthSyncPeerPool.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/PeerSelectionOptions.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/PeerSelectionOptionsExtensions.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/SyncPeerAllocation.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/SyncServer.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/Synchronizer.cs
src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs

Changes the concept of peer refresh to a broader idea of refresh task - short sync tasks that are executed in a queue outside of a syn peer allocation pool.The queue already existed but was not reacting to hint block and may have lead to delayed execution of reorgs.
Removes the sticky synchronize blocks allocation that was using a different 'free' approach - finish sync. Simplified it by always freeing it the same way as any non-replacable allocation is.
Passes the BorrowOptions further down and renames to PeerSelectionOptions.
Removes non-obvious EnsureBest invocations as the Best peer should be always assigned when borrow is called.

refresh tasks added

---

src/Nethermind/Nethermind.Core.Test/RipemdTests.cs
src/Nethermind/Nethermind.Crypto/Ripemd.cs
src/Nethermind/Nethermind.Evm/Precompiles/Ripemd160PrecompiledContract.cs

Important in two cases:
1) it actually sometimes fails during the ethereum tests
2) unlikely scenario of this being executed at the same time in JSON RPC and block processor (which means it will happen)

threadlocal ripemd

---

src/Nethermind/Nethermind.Blockchain.Test/Find/LogFinderTests.cs
src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Deposits/BlockchainBridgeBuilder.cs
src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Modules/NdmModule.cs
src/Nethermind/Nethermind.Facade.Test/BlockChainBridgeTests.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModuleFactory.cs
src/Nethermind/Nethermind.Runner.Test/EthereumRunnerTest.cs
src/Nethermind/Nethermind.Runner.Test/NUnitLogManager.cs
src/Nethermind/Nethermind.Runner/Ethereum/Steps/DatabaseMigrations.cs
src/Nethermind/Nethermind.Store.Bloom/BloomStorage.cs

1. Change bloom migration to include ChainLevelInfo.HasBlockOnMainChain for old blocks.
2. Add warnings to logs when nbloom migration cannot find header.
3. Add errors to logs when LogFinder cannot find block.
4. Add NUnitLogManager to Initialize runner smoke tests for better diagnostics of failures in this test

Additional fixes for bloom migration and searching logs

---

src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs
src/Nethermind/Nethermind.DataMarketplace.Test/ContractInteractionTest.cs
src/Nethermind/Nethermind.Evm.Test/Tracing/EstimateGasTracerTests.cs
src/Nethermind/Nethermind.Evm.Test/TransactionProcessorTests.cs
src/Nethermind/Nethermind.Evm/RefundHelper.cs
src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/CallOutputTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/EstimateGasTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofTxTracer.cs
src/Nethermind/Nethermind.Evm/TransactionProcessor.cs
src/Nethermind/Nethermind.Evm/TransactionSubstate.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs
src/Nethermind/Nethermind.Facade.Test/BlockChainBridgeTests.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthModuleTests.cs

Gas estimator needs to take account multiple events:
* refunds
* gas barriers when the gas level is checked but not used (with stipend or SSTORE with stipend)
* refunds from SELFDESTRUCT
* various types of nesting

estimator taking into account stipend and gas pressure and refunds

---

src/Nethermind/Nethermind.Blockchain/PendingTransactionSelector.cs

Too much log clutter on sealing nodes

Move rejecting transaction log messages to debug level

---

.github/workflows/dappnode-update.yml

We did some changes on our repo and this allows us to have an auto-generated DAppNodePackage every time that you tag a new release.

Update dappnode-update.yml to dispatch events to nethermind repo

---

src/Nethermind/Nethermind.Blockchain/IBlockTree.cs
src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs
src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs
src/Nethermind/Nethermind.Synchronization.Test/BeamSync/BeamBlockchainProcessorTests.cs
src/Nethermind/Nethermind.Synchronization.Test/BeamSync/BeamSyncDbTests.cs
src/Nethermind/Nethermind.Synchronization.Test/OldStyleFullSynchronizerTests.cs
src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorTests.cs
src/Nethermind/Nethermind.Synchronization/BeamSync/BeamBlockchainProcessor.cs
src/Nethermind/Nethermind.Synchronization/BeamSync/BeamSyncDb.cs
src/Nethermind/Nethermind.Synchronization/BeamSync/CompositeStateSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/ISyncModeSelector.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/ISyncProgressResolver.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/PendingSyncModeSelector.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/StaticSelector.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs

to avoid BeamProcessor to write to a wrong DB and ensure a safe switch for the target write database in the beam sync DB we introduce a three step lock
SyncModeSelector invokes three events - Preparing, Changing and Changed, thus allowing the listeners to synchronize with each other

Tri stage transition

---

src/Nethermind/Nethermind.Network/Discovery/DiscoveryManager.cs
src/Nethermind/Nethermind.Runner/NLog.config

Changes trace log from dark gray to magenta as dark gray is not visible on some terminals.

use magenta colour for tracing

---

src/Nethermind/Nethermind.Synchronization.Test/SyncThreadTests.cs

The test sometimes fails, probably because of parallel runs

to prevent setup is correct from failing

---

src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs
src/Nethermind/Nethermind.Network/PeerManager.cs

It changes the eagerness of looking for now peers. To avoid resource usage I rbing it back to old behaviour. Both behaviours are correct and both are passing tests so no tests changes required.

check max peers again

---

src/Nethermind/Nethermind.Network.Test/EnodeTests.cs

testing only the first 3 bytes since the dns is load balancing google.com

allow for subnet

---

src/Nethermind/Nethermind.Core/ClientVersion.cs
src/Nethermind/Nethermind.Core/Platform.cs
src/Nethermind/Nethermind.Core2.Configuration/ClientVersion.cs
src/Nethermind/Nethermind.EthStats/Integrations/EthStatsIntegration.cs

* Better OS Names ("Windows", "macOS" instead of "Microsoft Windows", "Darwin")
* Display only OS Name. It is generally a good security practice to not disclose OS/Kernel version.
```
Nethermind/v1.8.61-1-9e6f95184-20200712/X64-Linux 4.19.76-linuxkit/Core3.1.5
Nethermind/v1.8.61-1-9e6f95184-20200712/X64-Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64/Core3.1.5
Nethermind/v1.8.61-1-9e6f95184-20200712/X64-Microsoft Windows 6.3.960/Core3.1.5
```
```
Nethermind/v1.8.61-1-9e6f95184-20200712/X64-Linux/Core3.1.5
Nethermind/v1.8.61-1-9e6f95184-20200712/X64-macOS/Core3.1.5
Nethermind/v1.8.61-1-9e6f95184-20200712/X64-Windows/Core3.1.5
```

Improve Client Version

---

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloadContext.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs

If the response can only send receipts for 50 blocks due to soft message size limit and the request is for 512 blocks then we should respond with TxReceipt[52][] and not TxReceipt[512][] where null is set for each value beyond 52.

resize responses from receipt requests so they are not filled with nulls

---

src/Nethermind/Nethermind.Blockchain.Test/Proofs/ReceiptTrieTests.cs
src/Nethermind/Nethermind.Serialization.Rlp/ReceiptMessageDecoder.cs

Just found that there is an unnecessary memory allocation when deserializing receipts

removed unnecessay allocation

---

src/Nethermind/Nethermind.JsonRpc.Test/Modules/BoundedModulePoolTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcModuleProvider.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
src/Nethermind/Nethermind.JsonRpc/Modules/BoundedModulePool.cs
src/Nethermind/Nethermind.JsonRpc/Modules/IRpcModulePool.cs
src/Nethermind/Nethermind.JsonRpc/Modules/IRpcModuleProvider.cs
src/Nethermind/Nethermind.JsonRpc/Modules/NullModuleProvider.cs
src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs
src/Nethermind/Nethermind.JsonRpc/Modules/SingletonModulePool.cs
src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsClient.cs

The aim of this PR is to improve performance of JsonRPC in Nethermind. The potential improvements that are considered after an inital review are listed below. They are grouped by a performance opportunity and followed by more nested action points.

JsonRPC performance improvements

---

src/Nethermind/Nethermind.Evm/EvmState.cs

This PR simplifies pooling of `EvmState` without running `.Count` on every rental

EvmState pools simplified a bit

---

src/Nethermind/Nethermind.Core.Test/Buffers/LargerArrayPoolTests.cs
src/Nethermind/Nethermind.Core/Buffers/LargerArrayPool.cs
src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs

This PR introduces a limited in size `LargeArrayPool` that should be able to help with large buffers used from time to time. The assumptions are as follows:
1. for small arrays, less than 1MB `ArrayPool<byte>.Shared` is used with its default bucketing behavior
1. for arrays bigger than 1MB but less than 8MB, one of two buffers provided in `LargeArrayPool` is used. No bucketing, just using 8MB chunks
1. for arrays bigger that 8MB, the default `ArrayPool<byte>.Shared` is used again. This will probably allocate but it's highly unlikely that it'll be used by any real-world evm example.

LargeArrayPool introduced

---

src/Nethermind/Nethermind.Benchmark/Core/LruCacheAddAtCapacityBenchmarks.cs
src/Nethermind/Nethermind.Core.Test/Caching/LruCacheTests.cs
src/Nethermind/Nethermind.Core/Caching/LruCache.cs

This is a speculative PR proposing changes for the implementation of the LRU cache.
Previous version was based on `LinkedList<T>`,  `LinkedListNode<T>` and `LruCacheItem`. It had following properties:
- each of this types is a class, therefore it allocates an object header
- `LinkedListNode<T>` contains three references: `previous`, `next` and the `list`. The value is stored in the `item`
- `LruCacheItem` contains the key (needed for `.Replace` operation) and the actual value.
When profiling a runner, I found large amounts of objects allocated for the purpose of `LinkedListNode<T>` and `LruCacheItem`.
This PR changes the approach to use an **array of structs** and implementing a linked list on to of it. It removes some memory overhead as a single array item consist of:
- `prev` and `next` …

Potentially cheaper array based LRU cache

---

src/Nethermind/Nethermind.Network.Stats/INodeStatsManager.cs
src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network.Test/PeerComparerTests.cs
src/Nethermind/Nethermind.Network/NodeStatsManagerExtension.cs
src/Nethermind/Nethermind.Network/PeerComparer.cs
src/Nethermind/Nethermind.Network/PeerManager.cs

2020-12-01 17:10:35.9864|Peer update loop failure System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'Nethermind.Network.PeerComparer'.
at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
at Nethermind.Network.PeerManager.SelectAndRankCandidates() in /src/Nethermind/Nethermind.Network/PeerManager.cs:line 540
at …

Make PeerManager more resilient to unexpected failure

---

src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs

This should allow increase the maximum body size (default ~28.8 MiB) for JSON RPC requests.

Introduce config parameter JsonRpc.MaxRequestBodySize

---

src/Nethermind/Nethermind.Abi/Nethermind.Abi.csproj
src/Nethermind/Nethermind.Blockchain/Nethermind.Blockchain.csproj
src/Nethermind/Nethermind.Config/Nethermind.Config.csproj
src/Nethermind/Nethermind.Consensus/Nethermind.Consensus.csproj
src/Nethermind/Nethermind.Core/Nethermind.Core.csproj
src/Nethermind/Nethermind.Crypto/Nethermind.Crypto.csproj
src/Nethermind/Nethermind.Db/Nethermind.Db.csproj
src/Nethermind/Nethermind.Evm/Nethermind.Evm.csproj
src/Nethermind/Nethermind.Facade/Nethermind.Facade.csproj
src/Nethermind/Nethermind.Grpc/Nethermind.Grpc.csproj
src/Nethermind/Nethermind.JsonRpc/Nethermind.JsonRpc.csproj
src/Nethermind/Nethermind.KeyStore/Nethermind.KeyStore.csproj
src/Nethermind/Nethermind.Logging/Nethermind.Logging.csproj
src/Nethermind/Nethermind.Monitoring/Nethermind.Monitoring.csproj
src/Nethermind/Nethermind.Network.Stats/Nethermind.Network.Stats.csproj
src/Nethermind/Nethermind.Network/Nethermind.Network.csproj
src/Nethermind/Nethermind.PubSub/Nethermind.PubSub.csproj
src/Nethermind/Nethermind.Serialization.Json/Nethermind.Serialization.Json.csproj
src/Nethermind/Nethermind.Specs/Nethermind.Specs.csproj
src/Nethermind/Nethermind.State/Nethermind.State.csproj
src/Nethermind/Nethermind.Synchronization/Nethermind.Synchronization.csproj
src/Nethermind/Nethermind.Trie/Nethermind.Trie.csproj
src/Nethermind/Nethermind.TxPool/Nethermind.TxPool.csproj
src/Nethermind/Nethermind.Wallet/Nethermind.Wallet.csproj
src/Nethermind/Nethermind.WebSockets/Nethermind.WebSockets.csproj

A reference assembly is one that has all implementation and dependencies stripped out.  This is very useful for plugin authors because it means they can just reference this file in their plugin and get IDE support, auto-complete, comment documentation, etc.
`Deterministic` should *probably* be applied to this entire repository (helps with auditing final build artifacts), but specifically it is recommended for ReferenceAssemblies which is why I have enabled it here.
Upon building after this change `src\Nethermind\Nethermind.Api\bin\Release\net5.0\ref` will contain a `Nethermind.Api.dll` that is 24KB large.  Users can then reference it in their Plugin projects with:
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>net5.0</TargetFramework>
<Nullable>enable</Nullable> …
```

Makes the API produce a reference assembly.

---

src/Nethermind/Nethermind.Api/IApiWithNetwork.cs
src/Nethermind/Nethermind.Runner/Ethereum/Api/NethermindApi.cs
src/Nethermind/Nethermind.Runner/Program.cs

This makes it so `Api.WebSocketsManager` can be non-null, which makes it easier to use in plugins who want to use it.  Previously, this was unconditionally instantiated and assigned immediately after the builder finished and there aren't any code paths that set it to null, so it was *effectively* not null but in a way the static analyzer couldn't follow.

Moves WebSocketsManager instantiation to API Builder.

---

src/Nethermind/Nethermind.Monitoring/Config/IMetricsConfig.cs
src/Nethermind/Nethermind.Monitoring/Config/MetricsConfig.cs
src/Nethermind/Nethermind.Monitoring/MonitoringService.cs

This adds a configurable `ExposePort` to expose Prometheus metrics via HTTP port. This functionality is disabled if not configured.
Prometheus is generally set up with polling from services and PushGateway is more intended as a workaround and for very short-lived processes.
Let me know what you think and if you want any structural changes in the config - opting for keeping backwards compatibility without making the config too messy.

Add option to expose Prometheus metrics for pulling

---

src/Nethermind/Nethermind.DataMarketplace.Consumers.Infrastructure/NdmConsumersModule.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Infrastructure/Persistence/InMemory/Repositories/DepositDetailsInMemoryRepository.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Infrastructure/Persistence/Mongo/Repositories/DepositDetailsMongoRepository.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Infrastructure/Persistence/Rocks/Repositories/DepositDetailsRocksRepository.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Infrastructure/Persistence/DepositDetailsRocksRepositoryTests.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Infrastructure/Persistence/Mongo/DepositDetailsMongoRepositoryTests.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Infrastructure/Persistence/ProviderRocksRepositoryTests.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Deposits/DepositManagerTests.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Deposits/DepositProviderTests.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Deposits/DepositReportServiceTests.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Shared/ConsumerServiceBackgroundProcessorTests.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers/Deposits/Domain/DepositDetails.cs
src/Nethermind/Nethermind.DataMarketplace.Consumers/Shared/Services/ConsumerServicesBackgroundProcessor.cs
src/Nethermind/Nethermind.DataMarketplace.Tools.Refunder/Program.cs

There was a bug with `ConsumerServiceBackgroundProcessor` - it was trying to refund deposit even if all of the units was consumed. 
It was caused by reading deposits from `DepositRepository` and not from `DepositManager`.
While reading from repo - there was always 0 consumed units since we need to calculate consumed units with `DepositUnitsCalculator` used in reading with manager.

Will not try to refund consumed deposit

---

src/Nethermind/Nethermind.Cli/Modules/ParityCliModule.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/ParityModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Parity/EthProtocolInfo.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Parity/IParityModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Parity/ParityModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Parity/ParityNetPeers.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Parity/PeerInfo.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Parity/PeerNetworkInfo.cs
src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network/P2P/ISession.cs
src/Nethermind/Nethermind.Network/P2P/Session.cs
src/Nethermind/Nethermind.Network/PeerManager.cs
src/Nethermind/Nethermind.Network/ProtocolsManager.cs
src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModules.cs

* JsonRpc response
* CLI response
* returning number of active peers
* returning number of connected peers
* returning max number of active peers
* returning PeerInfo[] object (array of all active peers)
* returning peer id
* returning peer name
* returning list of capabilities
* returning PeerNetworkInfo object
* returning peer local address
* returning peer remote address
* returning EthProtocolInfo
* returning protocol version
* returning difficulty
* returning head (headhash)
* test for standard case, Node=null, Session=null

adding parity_netPeers

---

.github/workflows/codeql-analysis.yml

Followed the guidance from the build message:
1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results. | Analyze Nethermind code (csharp): .github#L1
-- | --

codeQlImpr

---

Dockerfile

This will make it so by default users will at least get an anonymous volume, and tooling will be able to notice the volume and prompt the user for naming of non-anonymous volumes.

Adds a volume for the database.

---

.github/workflows/docker-build.yml

If you have a fork of this repository, this job tries to run on commit but fails because secrets aren't available.  This failure results in emails being sent to the author.
This conditional should make it so it only runs as part of this repository.

Makes docker-build workflow only run as part of tihs repository.

---

src/Nethermind/Nethermind.WebSockets/Extensions.cs

This allows modules to utilize the rest of the path for module-specific things like `ws://nethermind:8545/my_module/watch/contract_address/`.

Uses the first segment of the path instead of the last for web socket module name.

---

src/Nethermind/Nethermind.Runner/configs/mainnet_pruned.cfg

2GB works for me, though I don't know if it is "optimal".  I'm open to setting it to some other default that is perhaps more reasonable if this one isn't, but I believe we can all agree that 256MB is *not* a reasonable default.  😄

Changes mainnet pruning cache size to 2GB.

---

.github/workflows/cc-build.yml
.github/workflows/on-issue-alert.yml
.github/workflows/state-runner-docker.yml

These GitHub workflows are set to execute on push to master or normal GitHub interactions **AND** they require secrets that forks won't have.  By disabling this on forks, it makes it so users who fork this repository won't get email spammed with GitHub workflow run failures.

Disables some workflows on forks.

---

src/Nethermind/Nethermind.Analytics/AnalyticsPlugin.cs
src/Nethermind/Nethermind.Api/Extensions/IPlugin.cs
src/Nethermind/Nethermind.Consensus.Clique/CliquePlugin.cs
src/Nethermind/Nethermind.Consensus.Ethash/EthashPlugin.cs
src/Nethermind/Nethermind.Consensus.Ethash/NethDevPlugin.cs
src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs
src/Nethermind/Nethermind.PubSub.Kafka/KafkaPlugin.cs
src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs

This will allow plugins to dispose async stuff, such as HTTP/WebSocket connections.
Also fixes a warning around async disposal of components (the missing async/await was being complained about, even though it wasn't required).

Makes `INethermindPlugin` `IAsyncDisposable`.

---

.github/workflows/configs-update.yml

Necessary because the scripts reference etherscan secrets that aren't available to forks.

Disables config updating for forks.

---

src/Nethermind/Nethermind.Blockchain.Test/Consensus/NullSignerTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Consensus/SignerTests.cs
src/Nethermind/Nethermind.TxPool/ITxSealer.cs
src/Nethermind/Nethermind.TxPool/ITxSigner.cs
src/Nethermind/Nethermind.TxPool/TxNonceTxPoolReserveSealer.cs
src/Nethermind/Nethermind.TxPool/TxSealer.cs

Minor changes to use ValueTask in sealers as well as signers.

use value task consistently

---

src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs
src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs

I've noticed that the SliceWithZeroPaddingEmptyOnError method is overly complicated with lots of redundant code, so I fixed it

Simplify SliceWithZeroPaddingEmptyOnError method

---

src/Nethermind/Nethermind.GitBook/ConfigGenerator.cs
src/Nethermind/Nethermind.GitBook/MetricsGenerator.cs
src/Nethermind/Nethermind.GitBook/RpcAndCliDataProvider.cs
src/Nethermind/Nethermind.GitBook/SharedContent.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs

After recent changes in naming (IModule => IRpcModule etc) automated docs generating still had old names and stopped working.
This quick fix:
* changing names for new ones
* changing metrics names from CamelCase to prometheus_convention_ones
* fixing way of searching configs and metrics files
* adding some content to the new RPC eth_createAccessList  description

Gitbook docs generating update after renaming RPC classes

---

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs

Rationale:
https compression is off by default to prevent [BREACH ](https://en.wikipedia.org/wiki/BREACH) and [CRIME ](https://en.wikipedia.org/wiki/CRIME) attacks. Those attacks are based on coockies. We don't use coockies in JSON RPC, though we are not vulnerable. Some more details here: https://github.com/h5bp/server-configs-nginx/issues/72#issuecomment-472808075

Enable compression for https

---

src/Nethermind/Nethermind.Core.Test/Encoding/TxDecoderTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityStyleTracerTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
src/Nethermind/Nethermind.Serialization.Rlp/ReceiptMessageDecoder.cs
src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs
src/Nethermind/Nethermind.Serialization.Rlp/RlpBehaviors.cs
src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
src/Nethermind/Nethermind.State/Proofs/ReceiptTrie.cs
src/Nethermind/Nethermind.State/Proofs/TxTrie.cs

for eth_sendRawTransaction
GETH, OE - don't use additional wrapping
Nethermind and probably Besu, TurboGeth - use additional wrapping.
I'm changing Nethermind to be like Geth/OE

Send raw transaction fix

---

src/Nethermind/Chains/poacore.json
src/Nethermind/Chains/sokol.json

We are going to activate Berlin HF on POA Core and Sokol at `~10:00 am UTC, May 24`. Block number for `POA Core` is  `21364900`. Block number for `POA Sokol` is `21050600`. Relates to https://github.com/openethereum/openethereum/pull/398.

Berlin HF on POA Core and Sokol

---

src/Nethermind/Nethermind.Dsl/ANTLR/Interpreter.cs
src/Nethermind/Nethermind.Dsl/ANTLR/Token.cs
src/Nethermind/Nethermind.Dsl/Grammar/DslGrammar.g4

Implemented IS and NOT:
- Added IS and NOT alongside '==' and '!=" as Boolean Operators in the DslGrammar.g4 grammar file, as well as the necessary adjustments to GetNextBlockElement() and GetNextTransactionElement(), which define the two operations in the Interpreter class of Interpreter.cs

IS and NOT Operators

---

src/Nethermind/Nethermind.Core.Test/Caching/LruCacheTests.cs
src/Nethermind/Nethermind.Core/Caching/LruCache.cs
src/Nethermind/Nethermind.Runner.Test/MemoryHintManTests.cs
src/Nethermind/Nethermind.Trie/CachingStore.cs
src/Nethermind/Nethermind.Trie/MemoryAllowance.cs

#2988 
When a big value as the used in the issue description is set as ```MemoryHint```, the ```Nethermind.Trie.MemmoryAllowance.TrieNodeCacheCount``` value will overflow because it is casted to ```int```, causing that the ```maxCapacity``` of the ```LruCache``` could be negative therefore the first time ```LruCache.Set``` is called it will try to remove the first element that doesn't exist.
This PR add the following changes: 
- Cast to ```int``` after divison when computing ```Nethermind.Trie.MemmoryAllowance.TrieNodeCacheCount```
- Thow ```ArgumentoOutOfRangeException``` when LruCache constructor is called with a ```maxCapacity``` lower than 1.
- Add test to check  ```maxCapacity``` argument validation.
- Add test to check big values as HintMemory.

#2988 Exception when memory hint is too big

---

src/Nethermind/Nethermind.Runner/configs/ndm_consumer_xdai.cfg

Would be great to enable HealthChecks plugin by default to check node status when having node connection issues in NDM. Telling whether the node is synced or not won't be easy to most users.

Enable HealthChecks by default in ndm_consumer_xdai.cfg

---

.github/workflows/run-nethermind-tests-with-code-coverage.yml
.github/workflows/run-nethermind-tests.yml
.github/workflows/run-vault-integration-tests.yml
Dockerfile.e2e

- introducing concurrency group for standard tests which run after each commit (previous, not finished runs will be canceled upon new commit)
- standard tests to run on ubuntu machine only to reduce the total time of each run under 10 minutes
- standard tests with code coverage are to be run on each OS system, the coverage report however will be produced only on Linux

first attempt to get rid of queues on pushes

---

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj

Changes to `Nethermind.Runner.csproj`. Creates plugin folder after building Nethermind and copies the HealthChecks.dll to the outdir post build.

create plugins folder after build + copy HealthChecks plugin do outdir

---

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs

Resolves #3052
While adding eth_subscribe I added class ReceiptCanonicalityMonitor, which is getting receipts of old blocks (after reorganization), is changing flag "Removed" to true and inserting these changed receipts (and these rollbacked receipts are sended to subscribers).
Inside PersistentReceiptStorage, in method Insert, we are setting in DB reference from tx to block and it was overwritten by removed txs.
I changed it to be overwritten only if flag "Removed" of TxReceipt is false.

Fix transactions pointing to wrong block

---

src/Nethermind/Nethermind.Network/Timeouts.cs

Increase timeout for GetHeaders/GetBlock/GetReceipts/GetState to 10s, this helps:
1. When the payload are big and throughput is small
2. When latency gets high
Increase network timeout

Increase Eth timeout from 3 to 10 seconds

---

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
src/Nethermind/Nethermind.Runner/configs/goerli.cfg
src/Nethermind/Nethermind.Runner/configs/goerli_beam.cfg

This PR increases default MemoryHint in Goerli config from 384MB to 768MB.
On other testnets it's like:
Ropsten: 1024MB
Rinkeby: 1024MB
I decided to use the 768MB value (same as in Goerli archive config) to not be too radical in increasing, but considered even 1024MB as on other testnets. Do you think 768MB will be the proper value for now? Open for discussion.
changing default config

Increase default MemoryHint in Goerli config

---

src/Nethermind/Nethermind.Evm.Test/TransactionSubstateTests.cs
src/Nethermind/Nethermind.Evm/TransactionSubstate.cs

Resolves #3207
- converting from byte array to string
Encoding.ASCII.GetString were returning whitespaces instead of proper values. Changed it to simple .ToHexString.

Fix revert error

---

src/Nethermind/Nethermind.Runner/NLog.config

I'm guessing the sync report moved at some point, and the NLog.config was just never updated.
- Corrects sync peer report  in sample NLog.config.
I did run with this change locally and it allowed me to block the sync report, without this change I wasn't able to.

Fixes outdated NLog.config.

---

src/Nethermind/Nethermind.Config/ConfigProvider.cs
src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rocks/Statistics/DbMetricsUpdater.cs
src/Nethermind/Nethermind.Db.Test/DbMetricsUpdaterTests.cs
src/Nethermind/Nethermind.Db.Test/InputFiles/CompactionStatsExample_AllData.txt
src/Nethermind/Nethermind.Db.Test/InputFiles/CompactionStatsExample_MissingIntervalCompaction.txt
src/Nethermind/Nethermind.Db.Test/InputFiles/CompactionStatsExample_MissingLevels.txt
src/Nethermind/Nethermind.Db.Test/Nethermind.Db.Test.csproj
src/Nethermind/Nethermind.Db/Metrics.cs
src/Nethermind/Nethermind.Monitoring/Metrics/MetricsUpdater.cs
src/Nethermind/Nethermind.Runner/configs/goerli.cfg

- Nethermind.Db.Metrics has been extended with a dictionary that stores dynamic metrics that can be added online
- Multiple DB Config settings has been added to configure stats processing
- We can now extract Compaction stats and Database Stats from RocksDb

Add dynamic metrics and extract RocksDb stats

---

src/Nethermind/Ethereum.VM.Test/VMTestBase.cs
src/Nethermind/Nethermind.Evm.Test/TransactionProcessorTests.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs

Fix incorrect assert before processing tx in 1559. From 1559 spec:
We ignored the first substract part.

1559 balance assert fix

---

src/Nethermind/Chains/hive.json
src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs
src/Nethermind/Nethermind.Core/BaseFeeCalculator.cs
src/Nethermind/Nethermind.Core/Eip1559Constants.cs
src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecLoaderTests.cs
src/Nethermind/Nethermind.Specs.Test/Specs/hive.json
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpec.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs

Add parameters to the gensis:
- eip1559BaseFeeMaxChangeDenominator
- eip1559ElasticityMultiplier
- eip1559BaseFeeInitialValue
Thanks to that, we have the same genesis as OpenEthereum, which is expected by xdai.

Added support for extra 1559 parameters in the genesis 

---

src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ITraceRpcModule.cs

trace_call is missed in the docs: https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/trace
I think by accident.

trace_call is missed in the docs

---

src/Nethermind/Nethermind.Config.Test/ConfigProvider_FindIncorrectSettings_Tests.cs
src/Nethermind/Nethermind.Config/ArgsConfigSource.cs
src/Nethermind/Nethermind.Config/ConfigProvider.cs
src/Nethermind/Nethermind.Config/EnvConfigSource.cs
src/Nethermind/Nethermind.Config/INoCategoryConfig.cs
src/Nethermind/Nethermind.Config/JsonConfigSource.cs
src/Nethermind/Nethermind.Config/NoCategoryConfig.cs

Fixes  #3248 
More configuration options is going to be handled including ones without a Category.
When running the Runner we should observe if there are any warnings related to incorrect configuration.
For example:
2021-07-26 19-55-35.4491|Incorrect config settings found:
ConfigType:EnvironmentVariable(NETHERMIND_*)|Category:|Name:QAZ
ConfigType:JsonConfigFile|Category:JsonRpcConfig|Name:TracerTimeout

Fix incorrect config valiation

---

src/Nethermind/Nethermind.Blockchain/BlockTreeExtensions.cs
src/Nethermind/Nethermind.Blockchain/LogTraceDumper.cs
src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs
src/Nethermind/Nethermind.Blockchain/Producers/BlockProducerBase.cs
src/Nethermind/Nethermind.Blockchain/Producers/MultipleBlockProducer.cs
src/Nethermind/Nethermind.Blockchain/Producers/TriggerWithCondition.cs
src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockProducer.cs
src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs
src/Nethermind/Nethermind.JsonRpc/Converters/TxReceiptConverter.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/ConsensusModuleTests.Setup.cs
src/Nethermind/Nethermind.Mev.Test/BundlePoolTests.cs
src/Nethermind/Nethermind.Mev.Test/MevRpcModuleTests.TestMevRpcBlockchain.cs
src/Nethermind/Nethermind.Mev.Test/TestBundlePool.cs
src/Nethermind/Nethermind.Mev/Data/BundleEventArgs.cs
src/Nethermind/Nethermind.Mev/IMevConfig.cs
src/Nethermind/Nethermind.Mev/MevConfig.cs
src/Nethermind/Nethermind.Mev/MevPlugin.cs
src/Nethermind/Nethermind.Mev/Source/BundlePool.cs
src/Nethermind/Nethermind.Mev/Source/IBundlePool.cs
src/Nethermind/Nethermind.Mev/Source/IBundleTxSource.cs

1. Improve dumps on consensus issues:
- Delete invalid blocks before dump
- Add Receipt dump
- Make dumps from least resource intensive to most (Receipts, Parity, Geth)
- Handle exceptions when dump fails
- Improve json serialization of a dump
2. Build bundle blocks only when bundles are available. When bundles are not available for block, then blocks for those bundles will not be created.
3. Change default MevConfig.MaxMergedBundles to 1.

MEV  build only when bundle + consensus diagnose improvements

---

src/Nethermind/Nethermind.Core/Extensions/IntExtensions.cs
src/Nethermind/Nethermind.Init/Steps/StartEthStatsClient.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolInfoProviderTests.cs
src/Nethermind/Nethermind.Network/P2P/P2PProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/P2PProtocolInfoProvider.cs

- eth_protocolVersion -> ETH66
- ethStats changed like below (I observed that geth is working like that)

Changed to ETH66 in EthStats and eth_protocolVersion

---

src/Nethermind/Nethermind.Blockchain/Rewards/BlockRewardType.cs

Make BlockRewardType labels have values same as BenefactorKind
This is not a functional change, nothing is changing how the reward mechanism works. BlockRewardType enum types are only used by label and their int value isn't used anywhere. This can cause confusion though and is inconsistent with BenefactorKind.

Make BlockRewardType values consistent with BenefactorKind

---

src/Nethermind/Nethermind.Core/Caching/LruCache.cs
src/Nethermind/Nethermind.Core/Caching/LruKeyCache.cs

Fixes 
ERROR|52|Couldn't correctly add or remove transactions from txpool after processing block 12991869 (0x39416672b6a326f403743d3895e50cacff56b2d4e59f1e9b9a6c0182ce44529e). System.NullReferenceException: Object reference not set to an instance of an object.
ERROR|40|Couldn't correctly add or remove transactions from txpool after processing block 13009572 (0x9b674d60ff2d0a4016594f7c2169e1ba02de0fc68f0b9447e9cedf8035caaa2a). System.NullReferenceException: Object reference not set to an instance of an object.
ERROR|46|Couldn't correctly add or remove transactions from txpool after processing block 13070711 (0x56d832257fb398d28013abe33038a47cc0c23943d392d3c0bda45e4d8cc1ccc0). System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A …

Synchronize LruKeyCache.Clear

---

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/BlockHeadersMessageSerializerTests.cs

- one "OmmersHash" is not renamed to "UnclesHash" and is breaking tests build now.
It was merged in eth66 branch and wasn't included in renaming PR merged yesterday, but prepared earlier.

One more ommer -> uncle

---

src/Nethermind/Nethermind.Evm.Test/Tracing/ParityLikeTxTracerTests.cs
src/Nethermind/Nethermind.Evm/ByteCodeBuilder.cs
src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

Fixes potential overflow on ReportMemoryChange on wrong stack parameters -> reported from FuzzyVM tests.
I've tested it on, test provided by @MariusVanDerWijden, it worked, but failed with GethTracer attached. Decided not to add this test to codebase after the fix as I don't find it relevant. Added a simple test instead.

Fix ReportMemoryChange dataOffset overflow

---

src/Nethermind/Nethermind.AuRa.Test/AuRaBlockProducerTests.cs
src/Nethermind/Nethermind.Mev.Test/MevRpcModuleTests.TestMevRpcBlockchain.cs
src/Nethermind/Nethermind.Mev.Test/MevRpcModuleTests.cs
src/Nethermind/Nethermind.Mev/MevRpcModule.cs

eth_sentBundle decoding transaction was missing RlpBehaviors.SkipTypedWrapping, causing non-legacy transactions to fail.

Fix tx's decoding in eth_sentBundle for non-legacy transactions

---

src/Nethermind/Nethermind.Blockchain.Test/ReorgTests.cs
src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs

Fixes #3444 
The branch will be reversed earlier to process blocks in the correct order.

newHeads subscription gets incorrect blocks when re-org

---

src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/LogsSubscription.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/NewHeadSubscription.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/NewPendingTransactionsSubscription.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/Subscription.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SyncingSubscription.cs

Fixes #3457
Partially Fixes #3444
Subscription messages will be queued up and sent in order.

Send subscription messages in order

---

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs

Removes ThreadLocal from TrieStore
Testing on RPC and validator nodes

Move TrieStore to single batch

---

src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/InitializeBlockchainAuRa.cs
src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs
src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/TxAuRaFilterBuilders.cs
src/Nethermind/Nethermind.Consensus.AuRa/Transactions/LocalTxFilter.cs
src/Nethermind/Nethermind.Consensus.AuRa/Transactions/ServiceTxFilter.cs
src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TransactionExtensions.cs
src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxCertifierFilter.cs

Fix IsServiceTransaction by allowing all 0 gas price transactions to be service transactions when processing and validator transactions to be service transactions when producing block
Test on POA Core

POA Core hotfix

---

src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EstimateGas.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EthCall.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
src/Nethermind/Nethermind.Specs/TestSpecProvider.cs

Fixes | Closes | Resolves #3574
Disable 3607 for RPC calls

disable 3607 for eth call

---

src/Nethermind/Chains/kovan.json

We can sync it with next smoke tests... cc: @1swaraj

Update Kovan chainspec

---

src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs

Improved error handling for TraceRpcModule when InsufficientBalanceException is thrown. 

Improved error handling for trace rpc module.

---

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs

Fixes #3659
- adding alphabetical ordering of capabilities in Hello handler
Bug description:
1. We initialize P2P.
2. We handle P2P Hello:
https://github.com/NethermindEth/nethermind/blob/93cde2024a82b17f2e6c82e86a2410366ad8aebd/src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs#L106-L119
3. In Hello handler, in foreach loop, we can have not alphabetical order, i.e. Eth before Aa
4. Eth protocol requested.
5. Eth is initializing. We have only P2P and Eth. Status message is sent (it is in eth62 Init())
6. Aa protocol requested.
7. Aa protocol is initializing, order in AdaptiveCodeResolver changed

Add alphabetical ordering of capabilities in Hello handler

---

src/Nethermind/Chains/sokol.json

We are going to activate London on Sokol testnet at block 24114400 (Mon Dec 13 2021 11:00 UTC). Please, make a new release with it to let Sokol validators update in time.

London hard fork on Sokol

---

README.md

This fixes usage with Fedora 35. Same as Ubuntu 21.10 fix. Matched
"find" usage with existing Fedora symlinks. Tested on `registry.fedoraproject.org/fedora:35` docker image.
- Adds instructions to make a symlink for libdl in Fedora 35.

Add additional symlink for Fedora 35

---

src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- Break execution of CREATE/CREATE2 when account already has max nonce.
This change is fixing 86 hive consensus tests (out of 99 failing because of CREATE/CREATE2). Constantinople is still failing. I will investigate it next week. Other test (sstoreGas_d0g0v0_Constantinople) is failing only on Constantinople too, so probably problem is in other place than related with this PR.
It's covered in hive consensus tests

Fix CREATE/CREATE2 when account has max nonce

---

src/Nethermind/Ethereum.Blockchain.Test/RevertTests.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- delete only PrecompileRipemd160 and do nothing with other precompiles in order to pass hive consensus tests.
There are special cases from the time of post-Shanghai-attack account clearing which were ignored in our ethereum tests, but we need to deal with them to pass hive tests - we are failing 18 of them because of this issue.
After change from this PR we are passing all of them, all RevertTests.
We were failing 12 tests because of not deleting PrecompileRipemd160 (0x0000000000000000000000000000000000000003) and 6 tests because of unexpected deleting of other precompiles. As only deleting of this exact precompile is expected by hive tests, I refactored our VirtualMachine to meet this expectations.
I don't like this kind of hacky fixes (and I'm not 100% sure if it will not break …

Fix hive RevertPrecompiledTouch tests

---

src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs
src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Blockchain/IBlockTree.cs
src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs
src/Nethermind/Nethermind.Hive/HiveRunner.cs
src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs

- ~~retry up to 10 times if result of suggesting block is CannotAccept (because of BlockTree lock)~~
We are irregularly failing about 50-75 hive consensus tests because of suggesting blocks when BlockTree is already in use. ~~This PR is adding retries if SuggestBlock is failing because of temporarily locked BlockTree.~~
Hive consensus tests run from this branch on VM no longer fail because of this.
- add SuggestBlockAsync, which is waiting for BlockTree to be able to add new block.
It is covered by hive consensus tests

Fix flaky hive tests

---

src/Nethermind/Nethermind.Config.Test/ConfigProvider_FindIncorrectSettings_Tests.cs
src/Nethermind/Nethermind.Config/ConfigItemAttribute.cs
src/Nethermind/Nethermind.Config/INoCategoryConfig.cs
src/Nethermind/Nethermind.Config/NoCategoryConfig.cs
src/Nethermind/Nethermind.Runner/Program.cs

Resolves #3774
- Add description attribute to all parameters from the _NoCategory_ category.
- Don't add NoCategory configs dynamically as Command Line options, because some are already added explicitly in _Programs.cs_ and some are only Environment Variable configs
- Add additional information about available Environment Variables when `--help` is run
```
...
--Wallet.DevAccounts                                         Number of auto-generted dev accounts to work with. Dev accounts will have private keys from 00...01 to 00..n (DEFAULT: 10)
Configurable Environment Variables:
NETHERMIND_CLI_SWITCH_LOCAL - Defines host value for CLI function "switchLocal". (DEFAULT: http://localhost)
NETHERMIND_CORS_ORIGINS - Defines CORS origins for JSON RPC. (DEFAULT: *)
NETHERMIND_ENODE_IPADDRESS - Sets …
```

Add documentation to all parameters shown by --help

---

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
src/Nethermind/Nethermind.TxPool/Filters/FeeTooLowFilter.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

- Don't filter out local transactions because of too low fee when adding to TxPool

Accept underpaid local txs in FeeTooLowFilter

---

.github/workflows/run-nethermind-tests-with-code-coverage.yml
.github/workflows/run-nethermind-tests.yml
src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.TestAccountAbstractionRpcBlockchain.cs
src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationPoolTests.cs
src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs
src/Nethermind/Nethermind.AccountAbstraction/IAccountAbstractionConfig.cs
src/Nethermind/Nethermind.AccountAbstraction/Source/CompareReplacedUserOperationByFee.cs
src/Nethermind/Nethermind.AccountAbstraction/Source/CompareUserOperationByNonce.cs
src/Nethermind/Nethermind.AccountAbstraction/Source/CompetingUserOperationEqualityComparer.cs
src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs
src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationSortedPool.cs
src/Nethermind/Nethermind.TxPool/Collections/TxSortedPoolExtensions.cs

Resolves #3790  
Resolves #3798

[AA] Only allow max 10 User Operation per sender, Implement op fee replacement

---

src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

- pick and broadcast declared percent (PeerNotificationThreshold) of best persistent transactions instead of random transactions
- broadcast persistent transactions only when their MaxFeePerGas >= CurrentBaseFee
- remove stale transactions from persistent transactions

Broadcast best persistent txs instead of random

---

.github/workflows/run-nethermind-tests-with-code-coverage.yml
src/Nethermind/Nethermind.Hive/HiveRunner.cs

- change timeout in HiveRunner from infinite to 5 seconds. Hive consensus tests connected with DAO transition will pass now.
- update ethereum tests
- fix run-nethermind-tests-with-code-coverage.yml similar to run-nethermind-tests.yml fixed in last PR with ethereum tests update
It's tested by hive tests

Set timeout in HiveRunner and update ethereum tests

---

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTests.cs
src/Nethermind/Nethermind.Synchronization.Test/LatencySyncPeerMock.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncPeerMock.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
src/Nethermind/Nethermind.TxPool/ITxPoolPeer.cs
src/Nethermind/Nethermind.TxPool/PeerInfo.cs
src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

- we are broadcasting hashes of recently incoming txs every 1s. We were including small amount of hashes of persistent txs to every message. Now we will not include it.
- we will send txs from persistent broadcast as full transactions after processing of every block. Every tx with `MaxFeePerGas > BaseFee` will be rebroadcasted.
- this change is fixing a bug reported by POA - transaction with currently too low fee should be rebroadcasted and mined right after base fee drop (we were sending only hashes and `_pendingHashes` in `PooledTxsRequestor` were blocking every hash after first ask)
I refactored already existing tests

Refactor persistent broadcast

---

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs
src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs

Add max logged size parameter to JSON RPC config which sets the maximum length of logged JSON RPC service parameters

Move logged request param size to json rpc config

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs

Fixes | Closes | Resolves #3606
Recover blockTree with genesis when missing head on corrupt tree.
Make UpdateHeadBlock safer.

Recover when missing head on start

---

src/Nethermind/Nethermind.Benchmark.Runner/Program.cs
src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
src/Nethermind/Nethermind.Precompiles.Benchmark/Nethermind.Precompiles.Benchmark.csproj

- fix setup of EVM benchmarks, broken after VM refactoring
- update Benchmark.Runner to run in dotnet 6.0
- update BenchmarkDotNet.Diagnostics.Windows nuget to 0.13.1

Fix EVM benchmarks

---

src/Nethermind/Nethermind.Network.Stats/INodeStats.cs
src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
src/Nethermind/Nethermind.Network.Test/NodeStatsTests.cs
src/Nethermind/Nethermind.Network.Test/Stats/NodeTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs

Closes #1188 
* add method for padded string
* pad IP and port values
* remove `ClientId` from `SyncPeerProtocolHandlerBase.ToString()`
* split_Append()_ calls for better lisibility and performance
* update tests
* padded variables in `Node` class possible because private properties (and set only in one place)
Tests were updated to reflect changes in padding display

feat: align sync peers reports columns

---

src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

Improves a `VirtualMachine` execution for a simple test case with a few operations over `Uint256` by 4%, introducing `[SkipLocalsInit]` on the execution of the EVM. EVM has a large stack (over 200 variables) and cleaning, according to benchmarks may take a while. Of course this is a one time setup for execution, the longer it runs, the less is saved by stack init.
- `[SkipLocalsInit]`  + a benchmark
|             Method |        Mean |     Error |    StdDev | Ratio | RatioSD |
|------------------- |------------:|----------:|----------:|------:|--------:|
|        ExecuteCode | 1,892.39 ns | 24.949 ns | 23.338 ns | 25.82 |    0.45 |
| …

EVM now skips locals init

---

src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationSubscribeTests.cs
src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs
src/Nethermind/Nethermind.AccountAbstraction/Subscribe/NewPendingUserOpsSubscription.cs
src/Nethermind/Nethermind.AccountAbstraction/Subscribe/NewReceivedUserOpsSubscription.cs
src/Nethermind/Nethermind.AccountAbstraction/Subscribe/UserOperationSubscriptionParam.cs

- When making a newPendingUserOperations or newReceivedUserOperations sub, the user will receive only the hash unless they set the includeUserOperations field to true

[Account Abstraction] Make default subscription give only RequestId

---

src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs

- skip deleting blocks in read only mode.
In hive tests we have exceptions because of trying to delete blocks in read only mode. This PR is fixing it.

BlockchainProcessor: skip DeleteInvalidBlocks in ReadOnly mode

---

src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationSubscribeTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Find/LogFinderTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs
src/Nethermind/Nethermind.Blockchain/Processing/ProcessingStats.cs
src/Nethermind/Nethermind.Blockchain/Receipts/FullInfoReceiptFinder.cs
src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptsRecovery.cs
src/Nethermind/Nethermind.Blockchain/Receipts/InMemoryReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsEventArgs.cs
src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecovery.cs
src/Nethermind/Nethermind.Init/Steps/InitializeBlockTree.cs
src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs
src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/LogsSubscription.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SubscriptionFactory.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloadContext.cs
src/Nethermind/Nethermind.TxPool.Test/ReceiptStorageTests.cs

Fixes | Closes | Resolves #3839
- make fast receipt sync ~2x faster by not recovering sender during fast sync - after changes most of the time disc i/o is a bottleneck instead of CPU
- recover data only when we need to serve it
- update recovered data in db and cache to avoid recovering it again in future
- ~~invoke `ReceiptsInserted` event only for removed receipts (subscription with new receipts is invoked by `NewHeadBlock` event)~~
- in `LogsSubscription` use `Get()` from `ReceiptFinder` instead of `ReceiptStorage` in order to go through recovery process before sending logs
- simplify `Get(block)` in `PersistentReceiptStorage` - reuse `Get(blockHash)`. Drop old-style db search in `Get(block)`. It unify returned data for both methods (before we were returning `TxReceipt[]{null}` in …

Refactor receipt recovery

---

src/Nethermind/Nethermind.Blockchain.Test/Receipts/ReceiptsRecoveryTests.cs
src/Nethermind/Nethermind.Blockchain/Find/LogFinder.cs
src/Nethermind/Nethermind.Blockchain/Receipts/FullInfoReceiptFinder.cs
src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecovery.cs
src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecoveryResult.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloadContext.cs

- fix bug introduced in https://github.com/NethermindEth/nethermind/pull/3956
- change type returned by TryRecover from bool to newly added enum ReceiptsRecoveryResult
- add tests for TryRecover

Fix receipts download

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs

Clean up and add tests around beacon pointers

---

Dockerfile

Changes the Debian image to Ubuntu and fixes the symlink issue that is introduced on Ubuntu
Fixes 
- Updated Dockerfile image to use Ubuntu instead of Debian.

Change base docker image to Ubuntu

---

Dockerfile

Fixes
Fixes the if statement in the Dockerfile to correct amd64 not building. 
I've tested this on the following architectures + ubuntu verisons: 
```
PRETTY_NAME="**Ubuntu 20.04.4** LTS"
Linux localhost 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 **x86_64 x86_64 x86_64** GNU/Linux
PRETTY_NAME="**Ubuntu 22.04** LTS"
Linux localhost 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 **x86_64 x86_64 x86_64** GNU/Linux
PRETTY_NAME="**Ubuntu 20.04.4** LTS"
Linux 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:14:11 UTC 2022 **aarch64 aarch64 aarch64** GNU/Linux
PRETTY_NAME="**Ubuntu 22.04** LTS"
Linux …
```

Fix Dockerfile if statement

---

src/Nethermind/Nethermind.Blockchain.Test/Find/LogFinderTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
src/Nethermind/Nethermind.Blockchain/Find/ResourceNotFoundException.cs
src/Nethermind/Nethermind.Blockchain/Receipts/InMemoryReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/NullReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/ReceiptMigrationTests.cs

Fixes #3983
- Added `HasBlock` method to `IReceiptStorage`.
- `ReceiptPersistentStorage` implemented it by checking its cache first, then the blocks column.
- `LogFinder` will check `HasBlock` on first and last block and will throw `ResourceNotFoundException` if receipt not found.
- `EthRpcModule` will return resource not found code when `ResourceNotFoundException` is encountered.
- [ X] Yes
- [ X] Yes
- Tested by running a clean DB. During fast sync after header was downloaded, query for block where the header already download. Confirmed error is returned.
- Queried again after full sync. Confirmed logs was returned.

Fix eth_getlogs not returning error when receipt is unavailable

---

scripts/syncSettings.py
src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.TestAccountAbstractionRpcBlockchain.cs
src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionConfig.cs
src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs
src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationSimulator.cs
src/Nethermind/Nethermind.AccountAbstraction/IAccountAbstractionConfig.cs
src/Nethermind/Nethermind.Runner/configs/goerli_aa.cfg
src/Nethermind/Nethermind.Runner/configs/goerli_mev_aa.cfg
src/Nethermind/Nethermind.Runner/configs/mainnet_aa.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_aa.cfg

New mainnet entrypoint was deployed, we should make that the default in our node
Also, Create2Factory config option is no longer needed since we have already reworked the tracing and simulation logic

[AA] Update configs to latest EntryPoint, Removed create2factory config param

---

src/Nethermind/Nethermind.Network.Discovery/DiscoveryConfig.cs
src/Nethermind/Nethermind.Network.Discovery/NettyDiscoveryHandler.cs

Resolves #3974
- Change default max bucket size to 12 following geth default https://github.com/ethereum/go-ethereum/blob/master/p2p/discover/v4wire/v4wire.go#L113
- Added warning message when trying to send payload that is too large.
- [X ] Bugfix (non-breaking change which fixes an issue)
- Confirmed warning shows up if bucket size is 16.
- Did not found other warning so far when bucket size is set to 12.

Reduce default max bucket size and warn on payload too large

---

src/Nethermind/Nethermind.Cli.Test/SanitizeCliInputTests.cs
src/Nethermind/Nethermind.Cli/Modules/CliModuleLoader.cs
src/Nethermind/Nethermind.Cli/Program.cs

- Fix CLI input sanitizing, so it works and additionally checks for \x0000
- Stop considering the base class one plugin discovery

Fix input clean up; ignore base plugin class

---

src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs

- post merge we are processing blocks and adding receipts when processing NewPayload, but we shouldn't return those receipts until they are forkchoice updated.
For optimization we will firstly look for canonical block and we will look for any block only if canonical one will not be found
It's tested in engine hive tests

+2 hive tests. Merge/latest block after payload

---

src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs

Do not return non-canonical receipts.
Move code for logIndexStart from eth_getTransactionReceipt to BlockchainBridge.GetReceiptAndEffectiveGasPrice
This is in-line what Geth does as well as should fix Transaction Reorg engine hive test

Do not return non-canonical receipts.

---

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
src/Nethermind/Nethermind.TxPool/Comparison/CompareReplacedTxByFee.cs

- always allow replacement of zero fee tx
More context: replacement of 0-fee transactions is needed for AuRa whitelisted accounts. Allowing general replacement of 0-fee transactions has much less complexity than loading whitelisted accounts from contract and allowing such replacement only for these accounts.

Allow replacement of zero fee transactions

---

src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

Enable JsonRpc if disabled and if merge is enabled.
- Enable jsonrpc config and disable url without engine api if merge is enabled and jsonrpc is disabled.
- Throw an exception if no engine rpc module is configured at all.
- Verified engine api endpoint is open when json rpc config is enabled.
- Verified exception is thrown when no url with engine api is configured.
- We can also, don't update the config and just throw validation error.
- We can also, replace the whole config with a default merge jsonrpc config.

Enable jsonrpc when merge is enabled

---

src/Nethermind/Nethermind.Runner/configs/goerli.cfg
src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorSnapSyncTests.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs

Resolves #4108
- Enable SnapSync for mainnet and goerly by default
- Disable snap sync if the node has been already fully synced before
Manual testing should cover:

Disable snap sync if state has ever been sycned

---

src/Nethermind/Nethermind.Blockchain.Test/Validators/HeaderValidatorTests.cs
src/Nethermind/Nethermind.Consensus/Validators/HeaderValidator.cs

Fixes  #4050
- Added validation for when long field in header that is not expected to be negative is set to negative. Not 
- Kiln can sync.

Add validation for wrong field range

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.RelayBuilder.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/IPayloadPreparationService.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/GetPayloadV1Handler.cs

Remove the wait for GetPayload if payload is not ready

---

src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs
src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Module/IRpcRpcModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Module/RpcRpcModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/ModuleType.cs

Closes #3972
Replicate geth's `rpc_modules` command. so that `geth attach` would work.
- Add `RpcRpcModule`.
- Call method, got
```
{'jsonrpc': '2.0', 'result': {'eth': '1.0', 'proof': '1.0', 'debug': '1.0', 'trace': '1.0', 'personal': '1.0', 'txPool': '1.0', 'net': '1.0', 'parity': '1.0', 'subscribe': '1.0', 'web3': '1.0'}, 'id': 12}
```
- Specify ipc port to `~/.ethereum/geth.ipc`, run `get attach`, call `eth.getBlockByNumber(1)`, seems to return a block.
`Rpc` module is not turned on by default on most config.

Add `Rpc` rpc modules

---

src/Nethermind/Ethereum.Test.Base/GeneralStateTest.cs
src/Nethermind/Ethereum.Test.Base/GeneralStateTestEnvJson.cs
src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs
src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs
src/Nethermind/Ethereum.Transition.Test/MetaTests.cs
src/Nethermind/Nethermind.Core/BlockHeader.cs
src/Nethermind/Nethermind.Core/Timers/TimerWrapper.cs
src/Nethermind/Nethermind.Network.Dns/EnrLeaf.cs
src/Nethermind/Nethermind.Network.Dns/EnrLinkedTree.cs
src/Nethermind/Nethermind.Network.Dns/EnrTreeBranch.cs
src/Nethermind/Nethermind.Network.Dns/EnrTreeRoot.cs
src/Nethermind/Nethermind.State.Test.Runner/StateTestRunner.cs
src/Nethermind/Nethermind.State/IStateProvider.cs

Update hive tests for gray glacier

---

src/Nethermind/Nethermind.Api/IApiWithNetwork.cs
src/Nethermind/Nethermind.Api/NethermindApi.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncPeer.cs
src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/PeerRefresherTests.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PeerRefresher.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs
src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
src/Nethermind/Nethermind.Synchronization/Peers/IPeerDifficultyRefreshPool.cs
src/Nethermind/Nethermind.Synchronization/Peers/IRefreshablePeerDifficultyPool.cs
src/Nethermind/Nethermind.Synchronization/Peers/ISyncPeerPool.cs
src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs

- Update peer refreshing to use FCU's hashes.
- Update peer refreshing to use FCU's hashes. It will now only disconnect if the finalized block is not available from the peer.
- Ropsten can sync to head.

Fcu peer refresher

---

src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergePluginTests.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs

Fixes inconsistent test
- When processing is done quickly enough, NewPayload will exit here https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs#L140.
- When processing is slow/throttled, NewPayload will get AlreadyKnown here https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs#L264 as BlockTree.IsKnownBlock does not check if the block is not on main chain.
- Added throttle to block processor in test.
- Fix Accepted considered invalid.
**Comments about testing , should you have …

Fix inconsistently failing test

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

Fix NewPayloadV1Handler to answer Syncing when processing timeout hits. Fix FCU to properly handle this situation.

MSF8 fixes

---

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/WitnessModuleRpcTests.cs
src/Nethermind/Nethermind.State.Test/Witnesses/WitnessCollectorTests.cs
src/Nethermind/Nethermind.State.Test/Witnesses/WitnessingStoreTests.cs
src/Nethermind/Nethermind.State/IWitnessCollector.cs
src/Nethermind/Nethermind.State/NullWitnessCollector.cs
src/Nethermind/Nethermind.State/Witnesses/WitnessCollector.cs

Fixes | Closes | Resolves https://github.com/NethermindEth/nethermind/issues/4196
- Make witness collection work only with the state provider
1. Sync with any network, shutdown the client, enable WitnessProtocol and specific DiagnosticMode as below, start it up, multi-threading errors appear
2. grep "witness" messages with DEBUG log enabled, confirm witness collected is the same as for master
```
{
...
"Init": {
"DiagnosticMode" : "VerifyTrie"
},
"Sync": {
...
"WitnessProtocolEnabled": true
},
}
```

Add witness for StateProvider only

---

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs

Fix low initlaized peer after fcu update.
- Set IsInitialized if header is known ahead of time when added (likely happen after a reconnection).
- Set IsIniitlalized even on FCU head refresh.

Fix low initialized peer

---

src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs
src/Nethermind/Nethermind.Trie/Pruning/ITrieStore.cs
src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs

Fixes #4233
Fix exception on shutting down when TrieStore attempt to dispose batch while another thread is updating it. 
- Dont shotdown first on start. TrieStore already in dispose stack.
- Run ropsten with full sync only. Start and stop 10 consecutive time during sync, no more exception. Previously it would take less than 5 tries.

Fix rocksdb error when shutting down and processing at the same time.

---

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs

- Increase BlockchainProcessor exception log level to warn
- Rider seems to auto remove the space.
Can compile and run.

Increase BlockchainProcessor exception log level to warn

---

src/Nethermind/Nethermind.Core/Extensions/CancellationTokenExtensions.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.DelayBlockImprovementContextFactory.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContext.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/Boost/BoostBlockImprovementContext.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs

- Fix an issue that caused the `BlockImprovementContext.CancellationTokenSource` to be disposed multiple times
- Add unit test to verify we can ask multiple times using the same `payloadId` without errors

Fix issue in payload disposing and add unit test for asking multiple times by the same `payloadId`

---

.github/workflows/run-discord-announcement.yml

Adds a new Github action that will trigger on a new Github release. This action will post an announcement to the Discord channel with the latest changelog. 
I've added an example announcement below, we could change the "design" in the future. 

Add Discord announcement workflow on new release

---

src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs

Fixes issue on kurtosis when peer return empty array on request body.

Fix sync peer disconnected when peer has no body

---

src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs
src/Nethermind/Nethermind.Consensus/Tracing/IGethStyleTracer.cs
src/Nethermind/Nethermind.Core.Test/Builders/TestItem.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs
src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs
src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugRpcModule.cs

Resolves #4133 
- `debug_traceBlockByNumber` now accepts `latest` and `finalized` as a block number value
- `debug_traceBlock`, `debug_traceBlockByNumber`, and `debug_traceBlockByHash` methods has been unified and refactored
Test cases has been added for `debug_traceBlock`, `debug_traceBlockByNumber`, and `debug_traceBlockByHash` methods.
Further refactoring, unification, and new test cases on the Debug module will be done along with the other sub-tasks of #4210.

Accept "latest" and "finalized" as block number values for debug_traceBlockByNumber method

---

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj

- Moves `ItemGroup` that collects plugins dlls to be inside a Target, so that wildcards are only expanded after we have already built the plugins projects
**Issue**:
If you just clone the repository for the first time and build the solution either from your ide or by running `dotnet run src/Nethermind/Nethermind.sln`, you'll notice that plugins are not copied to the plugins output folder (`src/Nethermind/Nethermind.Runner/bin/<Release or Debug>/netX.x>/plugins`) as expected. As a workaround, you can just rebuild the `Nethermind.sln` solution or the `Nethermind.Runner` project, this will copy the plugins to the plugins folder as …

Copy plugins correctly first time we build solution

---

src/Nethermind/Nethermind.Trie.Test/Pruning/TestPruningStrategy.cs
src/Nethermind/Nethermind.Trie.Test/PruningScenariosTests.cs
src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs

Fixes #4275
Fix TrieException due to pruning when a lower block produce sami storage root as newer block which causes it's `LastSeen` number to be reduced which will cause it to be memory pruned as no longer needed.
- Ensure LastSeen does not get reduced

Fix probably cause of trie exception

---

src/Nethermind/Nethermind.Trie.Test/Pruning/TestPruningStrategy.cs
src/Nethermind/Nethermind.Trie.Test/PruningScenariosTests.cs
src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs

- Added more pruning test scenario.
- Added test for sidechain of at least lenght 2.
- Added test with two consecutive sidechain.
- Added test which trigger memprune but not persist.
- Fixes trie exception on the scenario.

More pruning scenario

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/TimeoutUtils.cs

Fixes NewPayload return Invalid on block processing failure (not validation failure)
- Created a `TimeoutOn` extension method to simplify timeout handling.
- Uses await where possible instead of using task state, also does not handle unknown exception until in `EngineModule`.
- Set result type to failure on exception.
- Ran on ropsten. New block processed normally.

Set result to failure on block processing exception

---

src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs
src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidBlockInterceptor.cs

Fix invalid block interceptor intercep generated block instead of suggested block. This is a problem because well crafted block can essentially hang block processing by sending an invalid block which when processed result in a hash of a valid block on main chain.
- Mark suggested block as invalid instead of generated block.
This seems to be a cause of failed hive test on a different branch when trying to move NP to `ACCEPTED` where possible, but for some reason, not on master.

Fix invalid block interceptor intercepted wrong block

---

src/Nethermind/Nethermind.Hive/HivePlugin.cs
src/Nethermind/Nethermind.Hive/HiveRunner.cs

- remove tracer from HiveRunner - we will not process blocks twice anymore
- drop `BlockAddedToMain` event. Now we can collect info about not-processed blocks from recently added `BlockProcessingQueue` event: `BlockRemoved`
- after this change we are passing hive engine test `Long PoW Chain Sync`

Remove tracer from HiveRunner

---

src/Nethermind/Nethermind.Consensus/IPoSSwitcher.cs
src/Nethermind/Nethermind.Consensus/NoPoS.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/PoSSwitcherTests.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/MergeHeaderValidator.cs
src/Nethermind/Nethermind.Merge.Plugin/MergeSealValidator.cs
src/Nethermind/Nethermind.Merge.Plugin/PoSSwitcher.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs
src/Nethermind/Nethermind.Synchronization/SyncServer.cs

Fix issues that we noticed during transition on GSF5

Gsf5 fixes

---

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs

- Remove TrieStore allocations by using ArrayPoolList
- Small refactors

Remove TrieStore allocations by using ArrayPoolList

---

src/Nethermind/Nethermind.Core/Block.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloadContext.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs

Fix downloader hangs when peer response with no body.
- Allow downloader and merge block downloader to process block partially.
- In RequestBodies, exit early if peer response with no body at all.
- In RequestReceipts, exit early if block does not have body when it should have body.
- In DownloadBodies, throw exception when block should have body but does not.

Fix downloader hangs in some case

---

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EstimateGas.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EthCall.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.FeeHistory.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.GasPrice.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/FilterTests.cs
src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs

Fixes #4360 
The `JsonRpc.GasCap` is now handled like in Geth, i.e. when it's `0`, then the gas limit is set to max.
The change is in `TransactionForRpc.cs`. Other files have been modified due to a small refactoring.

Treat `JsonRpc.GasCap=0` as max cap

---

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/ChainLevelHelper.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs

- Remove ChainLevelHelper.GetNextHeader.

Remove upper limit for ChainLevelHelper.GetNextHeader

---

src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs

Fixes | Closes | Resolves  #4348
The most recently persisted state block number are not saved during shutdown. Need to update the disposal order so it will be saved.
- The most recently persisted state block number is persisted too
Tested manually: persisted state block number changes after restart

Fix of saving the best persisted state block number

---

src/Nethermind/Nethermind.Core/Crypto/Keccak.cs
src/Nethermind/Nethermind.Core/IKeyValueStore.cs
src/Nethermind/Nethermind.Db/DbExtensions.cs
src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Synchronization.Test/OldStyleFullSynchronizerTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncThreadTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
src/Nethermind/Nethermind.Synchronization/SyncServer.cs
src/Nethermind/Nethermind.Trie/Pruning/ITrieStore.cs
src/Nethermind/Nethermind.Trie/Pruning/NullTrieStore.cs
src/Nethermind/Nethermind.Trie/Pruning/ReadOnlyTrieStore.cs
src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs

- SyncServer.GetNodeData goes through keystore in order to be able to return not persisted data
- Add IReadOnlyKeyStore to better handle abstractions

Respond to GetNodeData with unpersisted nodes

---

src/Nethermind/Nethermind.AccountAbstraction/Subscribe/UserOperationSubscriptionParam.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/FilterTests.cs
src/Nethermind/Nethermind.JsonRpc/IJsonRpcParam.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/Filter.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/TransactionsOption.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SubscriptionFactory.cs

Fixes #4384
Added support for the `blockHash` parameter to the `eth_getLogs` RPC method. When this parameter is specified, the `fromBlock` and `toBlock` parameters are ignored if provided.

Implement support for the "blockHash" parameter

---

src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidHeaderInterceptorTest.cs
src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidBlockInterceptor.cs
src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidHeaderInterceptor.cs

Insure invalid blockhash does not get tracked as this could be an attack vector.
- Check in trackers if the error is invalid blockhash. 
- No regression in hive test.
- Still syncing goerli....

Ensure invalid blockhash is not tracked

---

src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs
src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs
src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Blockchain/BlockTreeMethodOptions.cs
src/Nethermind/Nethermind.Blockchain/Find/IBlockFinder.cs
src/Nethermind/Nethermind.Blockchain/IBlockTree.cs
src/Nethermind/Nethermind.Blockchain/InvalidBlockException.cs
src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs
src/Nethermind/Nethermind.Consensus.AuRa/Validators/AuRaValidatorBase.cs
src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
src/Nethermind/Nethermind.Consensus/Processing/IBlockchainProcessor.cs
src/Nethermind/Nethermind.Consensus/Processing/ProcessingOptions.cs
src/Nethermind/Nethermind.Core/Extensions/EnumExtensions.cs
src/Nethermind/Nethermind.Core/Nethermind.Core.csproj
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/IInvalidChainTracker.cs
src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidChainTracker.cs

- NewPayloadV1Handler ShouldProcessBlock method was introduced. This decides if block should be processed and with what ProcessingOptions flags it will be processed. For reorging terminal blocks it removes IgnoreParentNotOnMainChain flag. **This is main fix for Goerli transition issue.** We are also waiting for the hive tests to get more sophisticated in order to be able to catch this issues in them.
- BlockchainProcessor to return full block on InvalidBlock exception and event.
- BlockTreeLookupOptions.AllowInvalid to also look into (latest) invalid blocks.
- BlockTree will keep full recent invalid blocks instead of just hashes.
- InvalidChainTracker to use invalid block parent directly rather than doing lookup.
- InvalidChainTracker will use BlockTreeLookupOptions.AllowInvalid | …

Fix Goerli transition issue

---

.github/workflows/run-discord-announcement.yml

Changes the regex to match the changelog in github releases properly.
- changed the regex in the discord announcement action to better match the changelog. 
Tested locally with multiple release changelogs (1.13.2 till 1.13.6) and works as it should.

fix: change regex to get correct changelog value

---

src/Nethermind/Nethermind.JsonRpc/JsonRpcLocalStats.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs

by default our EngineHost is not null so we were always logging:
"Json RPC EnginePort and EngineHost should be specified" as warning with default configuration. 
What is more, I added logger for one path without logger in newPayload

Important logging fixes

---

src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeBlockTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ITraceRpcModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ParityTxTraceFromStore.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TxTraceFilter.cs

Fixes #4165. Closes #4419.
This is a revised and optimized version of PR #4419.
This also changes trace module from arrays to enumerables to avoid unnecessary allocations.
Besides unit tests, the changes have been tested on Goerli as follows:
1. Transfer funds from account A to an unused account B and then back to account A. Succeded as expected.
2. Transfer funds from account A to account B and then from an unused account C to account A. Failed as expected.

Revise and optimize the RPC method `trace_callMany`

---

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
src/Nethermind/Nethermind.Runner/configs/goerli.cfg
src/Nethermind/Nethermind.Runner/configs/goerli_mev.cfg
src/Nethermind/Nethermind.Runner/configs/goerli_shadowfork.cfg
src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
src/Nethermind/Nethermind.Runner/configs/mainnet_aa.cfg
src/Nethermind/Nethermind.Runner/configs/mainnet_mev.cfg
src/Nethermind/Nethermind.Runner/configs/mainnet_shadowfork.cfg

Resolves #4443
- Disable WitnessProtocol from default configs, this is due to Besu cannot parse our Hello message and cannot connect to us (issue on Besu side)

Disable WitnessProtocol from default configs

---

src/Nethermind/Nethermind.Runner/Program.cs

Fixes #4039
If Nethermind is downloaded from sources, it's easy to forget to make a library link that fixes RocksDb native dependency loading
- Load libdl.so.2 if libdl.so was not found
- The client runs and shutdowns without problems on fresh linux installation after being downloaded as an archive/installed as a ppa package and in any other case too

Improve native rocksdb dependencies loading

---

src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs
src/Nethermind/Nethermind.Synchronization/Blocks/FastSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/Blocks/FullSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/ISyncFeed.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncFeed.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/Synchronizer.cs

Fixes | Closes | Resolves #4049
Fast headers sync requires heavy database writes on request preparation which was not interruptible before this fix
- Interrupt fast headers sync properly

Cancel sync properly on shutdown

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs

- Add failing test for case where we get the same new payload but we don't cache it, so we returned SYNCING instead of processing and returning VALID or INVALID
- Fix: Check if block was processed when result is `AlreadyKnown`
- Add failing test for case where we get the same new payload, which is invalid but won't be detected until processing, if the block processing queue is not empty we correctly return syncing the first time we get it, but we'll cache the wrong value for that payload, so the second time, if we still haven't processed the block we will return valid, even though the block is invalid and has not been processed.
- Fix: we were setting the value in the cache to the result of the payload pre-processing validation and we were just ignoring the result of the processing.
- …

Fixes in new payload handler

---

src/Nethermind/Nethermind.Config/EnvConfigSource.cs
src/Nethermind/Nethermind.Config/ExitCodes.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

UX improvements for merge configuration + log fix

UX improvements for Merge configuration

---

src/Nethermind/Nethermind.Hive/HivePlugin.cs

- It seems that the chainfile is loaded after syncing has started causing the loading to fail on some case.
- `InitRpcModules` is run by `RegisterRpcModules` which is run after `InitializeNetwork` which is where `StartSync` is called.
- `InitNetworkProtocol` is called by `InitializeNetwork` right before `StartSync`. 
- Move the hive runner from `InitRpcModules` to `InitNetworkProtocol`.
- On test `Two Block Post-PoS Re-org to Higher-Total-Difficulty PoW Chain (local-nethermind)"` confirmed that the chainfile is loaded before syncing start.
- Change should not affect production code.
- No hive test regression.
If this is a relatively large or complex change, …

Fix hive load chainfile after sync started

---

scripts/deployment/publish-downloads.sh

- Changes **--fail-with-body** to **--fail** because the Ubuntu 20 runner is using an older curl version that doens't support --fail-with-body. (Ubuntu 22 runner does support this)

Fix publish-downloads.sh script 

---

src/Nethermind/Nethermind.Network.Test/SnapProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs

Fix disconnecting peers during snap sync by incrementally increase snap sync's response byte limit until its latency goes too high. Latency threshold was set low since 3s+ still causes some snap sync failure. Previously, snap request was too large and was also causing FCU peer refresh to fail which trigger peer disconnect.
Alternatively just reducing the respone bytes to fixed 200KB works also.
- Auto adjust response bytes.
- Goerli can sync to head.
- Performance implication is unclear.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Fix disconnecting peers during snap sync

---

src/Nethermind/Nethermind.Blockchain/BlockTree.AcceptVisitor.cs
src/Nethermind/Nethermind.Blockchain/Visitors/DbBlocksLoader.cs
src/Nethermind/Nethermind.Blockchain/Visitors/IBlockTreeVisitor.cs
src/Nethermind/Nethermind.Blockchain/Visitors/StartupBlockTreeFixer.cs
src/Nethermind/Nethermind.Merge.Plugin/MergeProcessingRecoveryStep.cs

- in `MergeProcessingRecoveryStep` check if block is post merge even if it's `TotalDifficulty` is `null`
- during `ReviewBlockTree`, if `block.TotalDifficulty` is `null` or `0`, set correct `TD`
Tested:

Fix db recovery

---

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PostMergeBlocksSyncPeerAllocationStrategy.cs
src/Nethermind/Nethermind.Synchronization.Test/AllocationStrategies/BySpeedStrategyTests.cs
src/Nethermind/Nethermind.Synchronization/Peers/AllocationStrategies/BySpeedStrategy.cs

Extract speed related logic to BySpeedStrategy.
- Extract speed related logic to BySpeedStrategy.
- Added some unit test.
Goerli can sync to head

Minor `PostMergeBlocksSyncPeerAllocationStrategy` refactor

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/GetPayloadBodiesV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs

This method will be needed soon to reduce number of requests between CL <> EL. I renamed it to adjust the latest spec:
https://github.com/ethereum/execution-apis/pull/218/files

Rename engine_getPayloadBodies to adjust latest spec

---

src/Nethermind/Nethermind.Runner/Program.cs

Fixes #4231
if file system is readonly stick to console logging + minor cleanup.

fix GetCriticalLogger with readonly file system exception

---

src/Nethermind/Nethermind.KeyStore/FileKeyStore.cs

File key store fails when Scrypt is used and parameters high enough to cause stack overflow are passed
- Make Scrypt more stable

Ensure scrypt does not fail

---

src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rocks/Nethermind.Db.Rocks.csproj

It seems that write receipt was a significant bottleneck during old receipts, which was also a recent change. A small change reduces it significantly. Still running smoke test to see if the sync time change. I'm seems to be limited by something else I guess, not much change on my sync time.
- Uses write batch to save transaction to block mapping.
- Added a lock to batch list or it will throw as sync dispatch runs in prallel.
Running smoke....

Reduce old receipts response time

---

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PeerRefresher.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs
src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs

- Do not disconnect peer on timeout. 
- If passed exception in ReportRefreshFailed is an OperationCanceledException, do not disconnect the peer.
Running smoke....

Do not disconnect peer on timeout

---

src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconSync.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/ChainLevelHelper.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.Merge.cs
src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorFastSyncTests.cs
src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorTests.Scenario.cs
src/Nethermind/Nethermind.Synchronization/IBeaconSyncStrategy.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs

Fix incremental sync when fast sync is enabled by adding fast sync lag post merge.
- Added `lastBlockToIgnore` param to chain level helper get headers.
- Implemented by fetching extra header, then removing them before returning the header list.
- In multisyncmodeselector, Replace `best.Peer.Block` to `best.TargetBlock` which is the `BeaconPivot.ProcessDestination`. 
- Hive test passes. Sync test all passed. Only one from transition test as expected.
- Goerli can sync to head.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose …

Fix incremental sync hive test with fast sync

---

src/Nethermind/Nethermind.sln

- remove stale references from `Nethermind.sln`
Locally I wasn't able to build solution without removing it. It is a problem in case of fresh clone - otherwise `Gmp` and `Int` files still exist in `src` folder, pulling changes doesn't remove it

Fix Nethermind.sln

---

src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
src/Nethermind/Nethermind.Network.Test/NodeStatsTests.cs

Fix node speed does not update after some time as observation count increase. This means node that suddenly become slower does not get its speed reflected.
- Uses different speed calculation.
- []  No

Fix node speed does not update

---

src/Nethermind/Nethermind.Config/ExitCodes.cs
src/Nethermind/Nethermind.Core/Exceptions/IExceptionWithExitCode.cs
src/Nethermind/Nethermind.Core/Exceptions/InvalidConfigurationException.cs
src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs
src/Nethermind/Nethermind.Init/Steps/InitializeNodeStats.cs
src/Nethermind/Nethermind.Init/Steps/InitializePlugins.cs
src/Nethermind/Nethermind.Init/Steps/StartLogProducer.cs
src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/EthereumStepsManagerTests.cs
src/Nethermind/Nethermind.Runner/Program.cs
src/Nethermind/Nethermind.Runner/configs/mainnet.cfg

Exit early on error (#4220)

---

.github/workflows/run-nethermind-tests-with-code-coverage.yml

- remove `MathGmp` project from `Code Coverage` workflow
After last changes and removing some projects from `src` directory, `Code Coverage` workflow is broken and there is a need to remove stale project.

Fix Code Coverage workflow

---

src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.cs
src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs
src/Nethermind/Nethermind.Blockchain.Test/ReorgTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Network.Test/P2P/SessionTests.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/EthereumStepsManagerTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs

Fix unit tests never pass consistently. When combined with #4686 and #4685 all unit tests was able to pass on a single run, most of the time, usually three consecutive succesful runs, before something fails randomly. Tests no longer hangs. On a lenovo legion 5 with Ryzen 7 5800H, all tests runs betwen 1 minute to 1 minute 15 second with CPU utilization almost 100% all the time.
- If failing is waiting for manual reset event, increase timeout in general.
- If can convert to `Assert.That(() => *, Is.After(*))` convert to that.
- Some test have event handler registered after call that triggers that handler,
- If all fails, add [Retry(3)].
**In case you checked yes, did you write …

Fix unit tests does not pass consistently

---

src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/BeaconPivotTests.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconHeadersSyncFeed.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconPivot.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconSync.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/ChainLevelHelper.cs

Fix issue where when restarting after some time, and sync pivot is updated to be ahead of what has already synced, beacon header sync will not download back to processed block as it stopped at sync pivot.  ChainLevelHelper also assume this.
- Make `BeaconPivot.PivotDestination` the head if head is not genesis.
- Added a config `Sync.StrictMode` that disable `chainMerged` optimization so that node can recover without resync.
Hive test passed with strict mode off.
Running with it on...
If this is a relatively large or complex change, kick off the discussion by explaining why …

Fix stuck when restarting with a new pivot

---

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs

- Hangs seems to originate from native code. 
- So, best I can do is to make sure no writes happens after dispose is called.
- Add write limit.
- Make sure no set happens after `Dispose`.
- Randomly exit a synced sepolia node.
- Randomly exit a syncing sepolia node.

Fix rocksdb test will hang sometimes

---

src/Nethermind/Nethermind.TxPool/Filters/UnknownSenderFilter.cs
src/Nethermind/Nethermind.TxPool/Metrics.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

- Moved DeployedCodeFilter to the end of txPool checks. It is reducing CPU and disk reads quite significantly. 
- Added new TxPool metric: PendingTransactionsWithExpensiveFiltering
As a next thing, we could work on building better filters without state access. Things have improved for sure, but I'm still observing occasional load from the first filter, which is reading the state:

TxPool optimization - moving DeployedCodeFilter

---

src/Nethermind/Nethermind.JsonRpc/JsonRpcLocalStats.cs

Resolves #4618 
- Added time unit to JSON RPC report (part of log)
Although this is a very simple change, the micro sign (µ) might not display correctly in the console log as it appears that Nlog console target uses OS dependent encoding by default. If this turns out to be a problem, a further change might be done to change Nlog configuration to use utf-8 encoding.

Added time unit (microseconds) to JSON RPC report (log)

---

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs

This reverts commit 720c3f061c1208ae2cfdfdb7471249db5bfe2b8f.
We cannot sync, looks like we can have access to disposed batch in read-only mode
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Attempted to read a disposed batch State0'.
at Nethermind.Db.Rocks.DbOnTheRocks.RocksDbBatch.get_Item(Byte[] key) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 451
at Nethermind.Trie.Pruning.TrieStore.IsPersisted(Keccak keccak) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 352
at Nethermind.Synchronization.SnapSync.SnapProviderHelper.IsChildPersisted(TrieNode node, Int32 childIndex, ITrieStore store) in /root/src/nethermind/src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs:lin …
```

Revert "Fix rocksdb test will hang sometimes (#4686)"

---

src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- It seems that we hide precompile contract exceptions. This should allow it to show up. Not sure if we should directly enable it all the time or only when debug is enabled.
- We should've crash completely IMO.
- Log exception on debug.
- Shows up in hive test.

Log on precompiled contract error

---

src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs
src/Nethermind/Nethermind.Network/PeerManager.cs

Probably fix #2413 
It was observed that peer that get added via `PeerPoolOnPeerAdded` does not get filtered for disconnect delay or chainid. This result int reconnecting to peers that was already known to be on a different chain id or peer that should have delay.
- Add some basic check for PeerPoolOnPeeradded.
Smoke test can sync to processing normally. No noticable change in peer pool.

Fix peer that should not get connected was connected

---

src/Nethermind/Nethermind.Synchronization.Test/SyncProgressResolverTests.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs

Fix #4526 
On sepolia, it seems that the whole range of address can be downloaded in a single get address range request, meaning it will store a valid state root immediately, causing `FindBestFullState` to found a valid state root when snap sync have not downloaded storage or codes. Verified by logging the tree root after `AddAccountRange`, which matches a block state root.
-Add a check for `IsSnapGetRangesFinished`.
Resynced sepolia a couple of time. Issues is no longer reproducable.
If this is a relatively large or complex change, kick off the discussion by explaining why …

Fix sepolia invalid block

---

src/Nethermind/Nethermind.Core/Timers/TimerFactory.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncReportTest.cs
src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs

Fixes #4622
Fixing incorrect logs for old receipts and old bodies. The ancient barriers were ignored.

AncientBarriers for old bodies & old receipts logging

---

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/RlpxPeerTests.cs
src/Nethermind/Nethermind.Network/Config/INetworkConfig.cs
src/Nethermind/Nethermind.Network/Config/NetworkConfig.cs
src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs

Fixes issue with old bodies download capped by unknown force.
- Add P2PHandlerThreadCount config.
- Set default thread count to ProcessorCount - 2.
Running smoke...

Enable multithreading on P2P deserialization workload

---

src/Nethermind/Nethermind.Network.Enr.Test/NodeRecordSignerTests.cs
src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs

Closes #3708
-throws when enr record rlp recieved is bigger than 300 bytes

ENR records limited to 300 bytes

---

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/RlpxPeerTests.cs
src/Nethermind/Nethermind.Network/Config/INetworkConfig.cs
src/Nethermind/Nethermind.Network/Config/NetworkConfig.cs
src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs

Reverts NethermindEth/nethermind#4637

Revert "Enable multithreading on P2P deserialization workload"

---

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
src/Nethermind/Nethermind.Synchronization.Test/AllocationStrategies/BySpeedStrategyTests.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncBatchSizeTests.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
src/Nethermind/Nethermind.Synchronization/Blocks/SyncBatchSize.cs
src/Nethermind/Nethermind.Synchronization/Peers/AllocationStrategies/BySpeedStrategy.cs

- Fix forward sync stuck on slow peer as it will keep picking peers with speed, which will always be one as only one was tried.
- Modified BySpeedStrategy to pick peer with no speed as long as number of peer with known speed is less than 5.
- Modified BlockDownloader to not cancel current download immediately. It will continue processing downloaded blocks before checking if a better peer is available.
- About 24 to 32 mainnet smoke tests. None stucked on slow peers.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …

Fix forward sync may stuck on slow peer

---

src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolInfoProviderTests.cs
src/Nethermind/Nethermind.Network.Test/ProtocolsManagerTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs
src/Nethermind/Nethermind.Network/ProtocolsManager.cs

Fixes | Closes | Resolves https://github.com/NethermindEth/nethermind/issues/3491
- drop old `eth` capabilities (`eth62`, `eth63`, `eth64`, `eth65`)
- remove handlers
- adjust tests

Remove pre `eth66` network items

---

scripts/syncSettings.py

- Removes deprecated testnets (rinkeby, ropsten and kovan) from syncSettings.py since etherscan api is no longer available for this networks and this is causing the gh action to fail. See https://github.com/NethermindEth/nethermind/actions/runs/3212233312/jobs/5250917933

Remove depreated testnets from syncSettings.py

---

src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs

- If HealthChecksUI and HealthChecks are not user will see warning and UI would not be added.
- Small refactoring
- [ x ] Refactoring (no functional changes, no api changes)
- [ x ] No
If this is a relatively large or complex change, kick off the discussion …

Disable HealthChecksUI if HealthChecks is not enabled

---

.github/workflows/build-nethermind-docker-images.yml
.github/workflows/build-nethtest-hive-docker-images.yml
.github/workflows/release-nethermind.yml
Dockerfile
Dockerfile.dev
scripts/deployment/build-runner.sh
src/Nethermind/Directory.Build.props
src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj

Refactors product versioning and fixes that for Docker images.
**IMPORTANT!** With this change, before branching a new release from the `master` branch, the product version must be bumped up in `Directory.Build.props`. The release Git tag must always match the version defined in `Directory.Build.props`.
- The product version is now hardcoded in [`Directory.Build.props`](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Directory.Build.props)
- GitHub Actions and Docker files have been updated in accordance with the abovementioned change
The following scripts have been tested:
- `build-nethermind-docker-images.yml`
- …

Refactor product versioning and revise Docker files

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.DelayBlockImprovementContextFactory.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.MockBlockImprovementContextFactory.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.StoringBlockImprovementContextFactory.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContext.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContextFactory.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/Boost/BoostBlockImprovementContext.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/Boost/BoostBlockImprovementContextFactory.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/IBlockImprovementContext.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/IBlockImprovementContextFactory.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs

Now using Stopwatch [independent](https://stackoverflow.com/a/12509159/1973207) of system Date time settings.
Resolves #4666
- Switched from DateTimeOffset bound to UtcNow to a single Stopwatch bound to the PayloadPreparationService
- Updated, relevant use cases
Introduced the use of a Stopwatch to in PayloadPreparationService instead of UtcNow as @LukaszRozmej suggested. No UtcNow passing is needed for it now.
As suggested in #4666 approach to utilize N best blocks was not required and was not employed due to heavy dependency on TimeSpans of surrounding code.
related to block creation.
No new tests were created in this PR, as old code coverage is relevant.

Fix issue 4666

---

src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs

Probably fixes #4776
- Missed lock on `ResetStateRoot` which may cause the pending request to happen at the same time as a current state sync processing, which may explain fast sync corruption.
- Wrap with loc.

Make sure reset state root is in a lock

---

src/Nethermind/Nethermind.Runner/Logging/NLogConfigurator.cs
src/Nethermind/Nethermind.Runner/NLog.config
src/Nethermind/Nethermind.Runner/Program.cs

- Created an 'all' target group in NLog, which include seq.
- In NLogConfigurator, only replace loglevel if pattern == '*'.
- This mean we can specify specific rule to have trace/debug log and publish them to seq.
- Also cleanup NLog.config a bit.
- Add `all` target group in NLog.
- Add rule to only replace seq rule with pattern == '*'.
- Add logic to disable seq if MinLevel is off.
- Tested to be able to specify multisyncmodeselector trace and it appear in seq.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …

Allow sending some trace to seq

---

src/Nethermind/Nethermind.Blockchain.Test/Validators/TestSealValidator.cs
src/Nethermind/Nethermind.Consensus.AuRa/AuRaSealValidator.cs
src/Nethermind/Nethermind.Consensus.Clique/CliqueSealValidator.cs
src/Nethermind/Nethermind.Consensus.Ethash/EthashSealValidator.cs
src/Nethermind/Nethermind.Consensus/ISealValidator.cs
src/Nethermind/Nethermind.Consensus/NethDevSealEngine.cs
src/Nethermind/Nethermind.Consensus/NullSealEngine.cs
src/Nethermind/Nethermind.Consensus/SealEngine.cs
src/Nethermind/Nethermind.Consensus/Validators/AlwaysValid.cs
src/Nethermind/Nethermind.Consensus/Validators/HeaderValidator.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/MergeSealEngine.cs
src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidHeaderSealInterceptor.cs
src/Nethermind/Nethermind.Merge.Plugin/MergeSealValidator.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs

- skip timestamp validation if `header` is `uncle` (as in comment: https://github.com/ethereum/tests/blob/develop/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestamp4.json#L4)
- refactor `EthashSealValidator`
This PR is fixing 6 hive consensus tests:
- 3x`incorrectUncleTimestamp4` (https://github.com/ethereum/tests/blob/develop/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestamp4.json)
- 3x`incorrectUncleTimestamp5` (https://github.com/ethereum/tests/blob/develop/BlockchainTests/InvalidBlocks/bcUncleHeaderValidity/incorrectUncleTimestamp5.json)
It's covered by hive tests

Do not validate timestamp for uncles (fix 6 hive tests)

---

src/Nethermind/Nethermind.Core.Test/SizeExtensionsTests.cs
src/Nethermind/Nethermind.Core/Extensions/IntExtensions.cs
src/Nethermind/Nethermind.Core/Extensions/SizeExtensions.cs

- Moved SizeExtensions to SeparateFile from IntExtensions, and swapped int methods with long in order to avoid cast overflow.
with the old impl doing the following : 
```
long j = Int64.MaxValue / (1024 * 1024 * 1024);
Console.WriteLine(j.GiB());
```
gives …

Refactored SizeExtensions to avoid overflow

---

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/RlpxPeerTests.cs
src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs

- Fix issue with user complaining that P2P port not following specified local ip.
- Specified local IP for P2P listening port, like https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs#L161
- Confirmed can sync normally without specifying IP.
- Confirmed if I specify IP that is not available, it will fail to start.
- Confirmed I can specify local ip explicitly.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …

Set local IP explicitly for P2P.

---

src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/JwtTest.cs
src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs

This PR slightly improves the RPC JWT authentication.
- Renamed the `MicrosoftJwtAuthentication` class to `JwtAuthentication` as it's a standard JWT authentication, nothing Microsoft-specific
- Replaced `Random.NextBytes` with the secure `RandomNumberGenerator.GetBytes`
- Slightly optimized string comparisons
- Improved error messages
- Removed duplicated functionality by utilizing the already existing one
Actually, the class is better called `JwtAuthenticator` and not `JwtAuthentication` but for now, let's leave it as it is.

Refactor JWT authentication

---

src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Logging/PathUtils.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncReportTest.cs

Fixes https://github.com/gnosischain/pm/issues/143
- Adds MixHash and Beneficiary to the fields of the tx header that will be used in the context of tx execution when using eth_call

fix eth_call mix_hash and beneficiary

---

src/Nethermind/Nethermind.Runner/configs/chiado.cfg
src/Nethermind/Nethermind.Runner/configs/chiado_archive.cfg
src/Nethermind/Nethermind.Runner/configs/xdai.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_aa.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_archive.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_mev.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_nethermind_testnet.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_testnet.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_themerge.cfg
src/Nethermind/Nethermind.Runner/configs/xdai_validator.cfg

- Set default value for chiado and xdai `Merge.SecondsPerSlot` to 5 instead of 12

Set chiado and xdai `Merge.SecondsPerSlot=5`

---

src/Nethermind/Nethermind.Config/Enode.cs
src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs

Fixes | Closes | Resolves #4876
- parse `DiscoveryPort` if `enode` contains it, according to spec https://ethereum.org/en/developers/docs/networking-layer/network-addresses/#enode
- add plenty of tests

Fix enode parsing

---

src/Nethermind/Nethermind.Consensus/TxFilterAdapter.cs
src/Nethermind/Nethermind.TxPool/Filters/AlreadyKnownTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/DeployedCodeFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/FeeTooLowFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/GapNonceFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/GasLimitTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/IIncomingTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/LowNonceFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/MalformedTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/NullHashTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/NullIncomingTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/ReusedOwnNonceTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/TooExpensiveTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/UnknownSenderFilter.cs
src/Nethermind/Nethermind.TxPool/TxFilteringState.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

- First filter that reads SenderAccount from state will save a copy of this data inside new struct: TxFilteringState. If any other filter needs account data it will read it from TxFilteringState. So we read account data only once.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Yes
- [ x ] No

Reduce number of reads from AccountState inside TxPool::SubmitTx

---

src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs

- Fix snap sync may finish early in very rare case.
- Make sure request counter is incremented before queue is dequeued.

Fix snap sync may miss node in very rare case

---

.github/workflows/run-nethermind-tests-with-code-coverage.yml
.github/workflows/run-nethermind-tests.yml

Temporarily changed some of the test workflow runner images from `ubuntu-latest` to `ubuntu-20.04` because of `libdl` issues coming from RocksDB v6.
These changes should be reverted with the migration to RocksDB v7.

Temporarily switch to `ubuntu-20.04` image

---

src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
src/Nethermind/Nethermind.Specs/KnownHashes.cs

- Add fork id tests for Gnosis and Chiado
The exact same tests were implemented in Erigon (https://github.com/ledgerwatch/erigon/pull/6110) and merged already.
I also had a comment regarding the unchanged fork id after the latest hardfork (block 21735000, GIP-31):
> Feels like there's an issue with the latest hardfork (https://docs.gnosischain.com/specs/hard-forks/21735000), as the fork id didn't change?
Not sure if that's intentional because it's not a major hardfork (i.e. Berlin, London, etc) or a bug?

test: fork ids for Gnosis and Chiado

---

src/Nethermind/Nethermind.Monitoring.Test/MetricsTests.cs
src/Nethermind/Nethermind.Monitoring/Metrics/MetricsController.cs

Fixed Building Gauge Names, Added unit tests.
Resolves Prometheus Gauge Names issue
Naming was messed up for standard metrics gauges. Now fixed and test covered. 
- regexp fix
- added unit test of default and developer-specified Gauge Names
Default:
Developer-specified:

Fixed Building Gauge Names

---

src/Nethermind/Nethermind.Evm.Test/Eip3860Tests.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

Fixes | Closes | Resolves #4933 
- changed gas usage and nonce increment for eip-3860, when init code size exceed limit
- full gas cost of CREATE/CREATE2 opcode should be deducted when 3860 init code size limit is exceeded
- nonce should be incremented when 3860 init code size limit is exceeded
As stated in #4933, there may be further changes to EIP3860 which might modify functionality in this scenario.

fixed eip-3860 gas usage and nonce when init code length exceeded

---

src/Nethermind/Nethermind.State.Test/PatriciaTreeTests.cs
src/Nethermind/Nethermind.State.Test/SnapSync/RecreateStateFromAccountRangesTests.cs
src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedHealingTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromAccountRangesTests.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
src/Nethermind/Nethermind.Trie/PatriciaTree.cs

Fixes #4831
- The sepolia fix now depends on snap range flag being stored to prevent it from restarting snap range as snap range is enabled at start up.
- This remove the sepolia fix and prevent snap ranges from saving state root.
- Revert sepolia fix.
- Add flag to skip saving state root on snap range.
- Confirm sepolia issue is still reproducable if root hash was set.
- With change, can sync up to validating block 5 consecutive time.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …

Do not save stateroot in snap phase 1

---

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs

Fix #4943 
- When calling trace, the blockchainproccessor is run, and the metrics is (probably?) wrongly updated. This seems to be an unexpected behaviour.
- Additionally `nethermind_blocks` mentioned in its description as total number of block processed. Strictly speaking, this is not what we implement, which is the current block height. Even our own dashboard uses this as block height instead of total blocks processed. So I'm not gonna change this behaviour.
- If readonly chain, don't update metrics.
- Tested manually, before `trace_block` would cause metric on my …

Fix `nethermind_blocks` update when a trace block is called.

---

src/Nethermind/Ethereum.Test.Base/EthereumTestResult.cs

Fixes  #4973
This PR changes the state test result, so the (already present) stateroot is not ignored by the json outputter. 
Tested locally; 
```
user@debian-work:~/workspace/nethermind/src/Nethermind/Nethermind.State.Test.Runner$ ./bin/release/net6.0/linux-x64/publish/nethtest -n -i  ~/QubesIncoming/work/statetest_filled.json
[
{
"name": "randomStatetestmartin-Wed_10_02_29-14338-0_d0g0v0_",
"pass": true,
"fork": "Byzantium",
"stateRoot": "0xa2b3391f7a85bf1ad08dc541a1b99da3c591c156351391f26ec88c557ff12134"
}
]
user@debian-work:~/workspace/nethermind/src/Nethermind/Nethermind …
```

Make state test runner output state root, fixes #4973

---

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/ChainLevelHelper.cs

- When force restart condition is triggered, the log shows up multiple time as the downloader restart, until an FcU happen, which can take 10 second or until the CL synced.
- This can be alarming.
- Dont set the flag if its already set.

Do not set force restart beacon sync flag if already set

---

src/Nethermind/Nethermind.State.Test.Runner/StateTestRunner.cs

This PR removes the 'hang' that happens in the state test runner, which for some reason blocks, waiting for an <enter>-press after execution. 
Note: I do not know the reason why it was added, but it has annoyed me for years. In case it is highly important, for some obscure reason, let me point out that the same effect can be achieved via the `-w` option. 
I mean, maybe (?) 
I mean, I didn't _write_ tests, but here's me testing that it works, first, and then testing that `-w` achieves the same blocking wait. 
```
user@debian-work:~/workspace/nethermind/src/Nethermind/Nethermind.State.Test.Runner$ ./bin/release/net6.0/linux-x64/publish/nethtest -n -i …
```

state test runner: remove blocking wait for input

---

src/Nethermind/Nethermind.State.Test.Runner/StateTestTxTracer.cs
src/Nethermind/Nethermind.State.Test.Runner/StateTxTraceEntry.cs

Related to #4955
https://github.com/NethermindEth/nethermind/issues/4955#issuecomment-1335243073
This changes the output `memSize` to be an integer, which is aligned with geth, erigon and besu. 
Results below
```
user@debian-work:~/workspace/nethermind/src/Nethermind/Nethermind.State.Test.Runner$ ./nethtest -m --trace --input ./00000006-naivefuzz-0.json  2>&1 | head -n 3 
{"pc":0,"op":96,"gas":"0xb4213","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opname":"PUSH1","error":""}
{"pc":2,"op":96,"gas":"0xb4210","gasCost":"0x3","memSize":0,"stack":["0x2"],"depth":1,"refund":0,"opname":"PUSH1","error":""} …
```

state runner: make memsize int

---

src/Nethermind/Nethermind.State.Test.Runner/Program.cs
src/Nethermind/Nethermind.State.Test.Runner/StateTestRunner.cs
src/Nethermind/Nethermind.State.Test.Runner/StateTestTxTracer.cs

Fixes #4955
Closes #4998
- This changes the memory reporting, so that even if -m is used (disable memory), the memSize is still accurate.

Make StateTestTxTracer always trace memory size

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Core/Exceptions/IInternalNethermindException.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/ZeroNettyP2PHandlerTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroNettyP2PHandler.cs
src/Nethermind/Nethermind.Trie/TrieException.cs

- Fixes probable cause of sometimes all peer disconnects.
- This is due to `TransactionsMessage` handler which checks for account from state where the root was set to head which was wrongly set in block tree during fixing corruption attempt, which causes trie exception as state was not downloaded yet.
- The fixing corruption attempt is wrongly started due to beacon header binary search left pointer which starts at lowest beacon header which is not moved by forward sync. If the pivot of the bsearch hit a beacon header during the search, the issue does not appear which is the reason why it is random.
- On any exception on handler, by default peer will get disconnected, meaning any peer which try to broadcast transaction to nethermind with this situation will get disconnected.
- Added …

Fix corruption attempt causes trie exception on state reader causing peer disconnection

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/IGetPayloadBodiesByRangeV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/GetPayloadBodiesByHashV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/GetPayloadBodiesByRangeV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

- Adjusts getPayloadBodiesByHash to the current spec
- Implementation of getPayloadBodiesByRange https://github.com/ethereum/execution-apis/pull/218
Have been tested manually with sepolia node.
Hive tests:
[rpc](https://github.com/NethermindEth/nethermind/actions/runs/3607950388)
[rpc-compat](https://github.com/NethermindEth/nethermind/actions/runs/3607951625)
[engine](https://github.com/NethermindEth/nethermind/actions/runs/3607949387)

GetBodiesByRangeV1 implementation

---

src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs

- The log line in broadcast persistent tx is spammy during sync as the head changes a lot, which causes this function to be triggered a lot.
- Not sure if this is needed, but it would be nice.
- Limit persistent tx broadcast rate to once per second.

Throttle persisted tx broadcast to once per second.

---

src/Nethermind/Nethermind.GitBook/Nethermind.GitBook.csproj

- Update .net version in Gitbook project
I think it should solve the problem with generating docs:
Similar changes like proposed in this PR were made when moving from .net 5 to .net 6

Update .net version in Gitbook project

---

src/Nethermind/Nethermind.Blockchain.Test/Find/LogFinderTests.cs
src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs

- When bloom is disable, eth_getLogs returns logs in opposite block orders. CL don't like this.
- Reverse back the order to match behaviour when bloom is available.

Fix eth_getLogs returns logs in opposite order when blooms is disabled

---

src/Nethermind/Nethermind.Consensus/Producers/BuildBlocksOnlyWhenNotProcessing.cs
src/Nethermind/Nethermind.Network.Test/P2P/SessionTests.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs

Fix randomly failing `should_cancel_triggering_block_production` unit test, and some other.
- Make sure cancellation token throws.

Fix some randomly failing test

---

src/Nethermind/Nethermind.Synchronization.Test/AllocationStrategies/BySpeedStrategyTests.cs
src/Nethermind/Nethermind.Synchronization/Peers/AllocationStrategies/BySpeedStrategy.cs

Fix #5014
- It was observed in sepolia where during snap sync sometimes nethermind account request timed out on a peer. The peer got sleep as expected, it then try another peer, which also timed out, which then got sleep, then got allocated back to the first peer, then timeout again. 
- This should change the peer allocation to try other peer also if it has the same speed.
- Add a clause to randomly try other peer if it has the same speed.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …

If two peer have same speed, randomly try the other one.

---

src/Nethermind/Nethermind.Network/P2P/Request.cs
src/Nethermind/Nethermind.Specs/MainNetSpecProvider.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.Merge.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs

Fixes #5043
- It turns out TaskCompletionSource.SetResult may run it's continuation (task that is waiting for its result) synchronously. See [this](https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/).
- So this means, when MSMS activate a forward sync feed via `SyncDispatcher.UpdateState` which locks `_feedStateManipulation`, it's `TrySetResult` will continue `SyncDispatcher.Start` from line 162 where it wait for `dormantTaskLocal` synchronously. 
- This execution which held `_feedStateManipulation` lock may continue further into `MergeBlockDownloader.Dispatch` and remains until it attempt to download something (anything async).
- If however, `SyncPeerAllocation.Replaced` is triggered before any download is queue (likely during …

Fix/deadlock due to TCS setresult behaviour

---

scripts/deployment/publish-ppa.sh

21.10 Impish is no longer supported as of July, the current short term release is 22.10 Kinetic. cc: https://lists.ubuntu.com/archives/ubuntu-security-announce/2022-July/006681.html https://lists.ubuntu.com/archives/ubuntu-announce/2022-October/000285.html
- Changes scripts/deployment/publish-ppa.sh to current Ubuntu versions.
Drops Ubuntu 21.10, adds 22.10.
21.10 EOL announcement: https://lists.ubuntu.com/archives/ubuntu-security-announce/2022-July/006681.html
22.10 release announcement: https://lists.ubuntu.com/archives/ubuntu-announce/2022-October/000285.html

Update targeted Ubuntu versions

---

src/Nethermind/Nethermind.Facade/Filters/FilterManager.cs
src/Nethermind/Nethermind.Facade/Filters/FilterStore.cs

Resolves #2076
- Reuse enumerable, skip filtering via ToArray

Improve FilterManager enumerator use

---

src/Nethermind/Nethermind.Benchmark.Runner/Program.cs
src/Nethermind/Nethermind.Benchmark/Core/ByteArrayToHexBenchmarks.cs
src/Nethermind/Nethermind.Benchmark/Core/FromHexBenchmarks.cs
src/Nethermind/Nethermind.Core.Test/BytesTests.cs
src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Core/Extensions/Int64Extensions.cs
src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
src/Nethermind/Nethermind.JsonRpc.Benchmark/UInt256ToHexStringBenchmark.cs

Is now x4.8 times faster, and Bytes.ByteArrayToHexViaLookup32Safe, Bytes.ToHexString and SpanExtensions.ToHexString all share the same implementation, rather than having 3 different ones
|   Method | ScenarioIndex |       Mean |     Error |    StdDev | Ratio | RatioSD |
|--------- |-------------- |-----------:|----------:|----------:|------:|--------:|
| Improved |             0 |  45.281 ns | 0.3482 ns | 0.4993 ns |  0.21 |    0.00 |
|  Current |             0 | 215.867 ns | 0.6967 ns | 0.9991 ns |  1.00 |    0.00 |
|          |               |            |           |           |       |         |
| Improved |             1 |   2.206 ns | 0.2604 ns | 0.3897 ns |  0.91 |    0.17 |
|  Current |             1 |   2.417 ns | 0.0265 ns | 0.0388 ns |  1.00 |    0.00 |
|          | …

Increase by x4.8 performance of ToHexString

---

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconHeadersSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs

- Cache counts and reuse if ConcurrentDictionary not changed
- Reuse ConcurrentDictionary enumerator
- Iterate rather than using Linq when calculating
Removes the allocations from `ShouldBuildANewBatch`

Reduce allocations in Queue and Memory estimations

---

src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationSimulator.cs
src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs
src/Nethermind/Nethermind.Blockchain.Test/TransactionGasPriceComparisonTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/FeeHistory/FeeHistoryOracle.cs
src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
src/Nethermind/Nethermind.Specs.Test/CustomSpecProvider.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs

- Refactor & Optimize- mainly ChainSpecBasedSpecProvider

ForkId calculation polish

---

.github/workflows/run-nethermind-tests-with-code-coverage.yml
.github/workflows/run-nethermind-tests.yml
Dockerfile
README.md
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rocks/Nethermind.Db.Rocks.csproj
src/Nethermind/Nethermind.Db.Test/RocksDbTests.cs

- The RocksDB package has been updated to v7.7.3
- Removed `rocksdb` from `brew install` in README
- Removed RocksDB dependency workaround from `Dockerfile`
- Brought back GitHub Actions workflows runners to `ubuntu-latest` changed in #4927 and #5041

Migrate to RocksDB v7

---

src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs

- NoMatchingCapability status seems to be the second highest initiate disconnect reason and it does not have a disconnect delay, meaning it will try again after about 30 second, which it will fail...
- Add the failed validation event so that it won't try the same peer again.
- Does not seems to do much in terms of peer discovery though...
(graph is before, after, before, after)
- Add `ReportFailedValidation` call when no capability match.

Fix NoMatchingCapability failure does not have disconnect delay

---

src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs
src/Nethermind/Nethermind.Core/Specs/ForkActivation.cs
src/Nethermind/Nethermind.Core/Specs/ISpecProvider.cs
src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V67/Eth67ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/ProtocolsManagerTests.cs
src/Nethermind/Nethermind.Network/ForkInfo.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V64/Eth64ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V67/Eth67ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs
src/Nethermind/Nethermind.Network/ProtocolsManager.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
src/Nethermind/Nethermind.Specs/MainNetSpecProvider.cs

- Don't calculate ForkId's on every call with linear scan.
- Calculate them on startup
- Then use binary search to find correct one
Passes all existing tests.

Precalculate ForkId's rather than calculate them on every connection

---

src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs

> Have you ever wondered why during sync nearly half of the disconnect reason is ClientQuitting? Well wonder no more! Because its not... Its just the status we use when the connection got abruptly disconnected. Also, most of it is actually not abruptly disconnect. The peer send `TooManyPeer` status, but the status was processed after the close completion handler, which is why it does not show up on metric.
- Add a one second delay to allow actually disconnect message to be processed.
- Change the status to `TcpSubsystemError` instead, which make significantly more sense. It does not look like anyone is using it...
- Tested mannually. Some abrupt disconnect remains. Most of it turns out to be `TooManyPeers`.

Fix strange ClientQuitting disconnect reason metric

---

src/Nethermind/Nethermind.Db/Blooms/FileReader.cs
src/Nethermind/Nethermind.Db/Blooms/FixedSizeFileStore.cs

Use the new "Thread-Safe File IO" introduced in .NET 6.0 rather than maintaining a position and locking https://devblogs.microsoft.com/dotnet/file-io-improvements-in-dotnet-6/#thread-safe-file-io
- Use the [RandomAccess](https://learn.microsoft.com/en-us/dotnet/api/system.io.randomaccess?view=net-7.0) class to do reads and writes with specified offsets rather than maintain a separate position needing locking

Allow concurrent file access

---

src/Nethermind/Ethereum.Transition.Test/MergeToShanghaiTests.cs

- add class `MergeToShanghaiTests`
- standard update of ethereum tests. New tests:

Update ethereum tests, add class `MergeToShanghaiTests`

---

src/Nethermind/Nethermind.Cli.Test/StatementHistoryManagerTests.cs
src/Nethermind/Nethermind.Cli/Console/StatementHistoryManager.cs
src/Nethermind/Nethermind.Cli/Program.cs

Fixes #4910
- Nothing is added to a file when a secured command is received.
- Minor optimizations
- IFileSystem interface for mock testing

Fix secured commands appearance in cli history

---

.github/workflows/release-nethermind.yml
scripts/deployment/publish-github.sh

- Updated release workflow to handle pre-release versions
- Publishing pre-release versions to GitHub and Docker Hub only
- Require approval for any step after the build: `Build -> Approval -> Publish to Homebrew, GitHub, Downloads, Docker, PPA`
- Revised some namings
To test, tag a pre-release like `x.y.z-label` and run the workflow.
Maybe it's worth adding a default tag for pre-release Docker images. Say, `latest-preview`, `latest-unstable`, or just `unstable`.

Improve pre-release version deployment

---

src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/NettyHandshakeHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/OneTimeLengthFieldBasedFrameDecoderTests.cs
src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
src/Nethermind/Nethermind.Network/Rlpx/OneTimeLengthFieldBasedFrameDecoder.cs
src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs

- Fix random `CorruptedFrameException`.
- Seems to be due to the `MessageLengthFieldBasedFrameDecoder` docoding more than one message, while it was intended to only be used during handshake, hence, one packet.
- Create a subclass that decode only one message.
- Clear metrics indicating that this exception no longer happens.

Fix corrupted frame exception

---

src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/NettyHandshakeHandlerTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroNettyP2PHandler.cs
src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameDecoder.cs
src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameMerger.cs

- Minor pipeline cleanup.
- Use context allocator where context is available. Its possible to configure the allocator specially for the channel which can be useful in the future to reduce memory limit for example.
- Make sure bytebuffer is released on handler removed.
- Seems to run

Minor pipeline allocator cleanup

---

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/ReceiptsMessageSerializerTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ProtocolHandlerBase.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Messages/ReceiptsMessage.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Messages/ReceiptsMessageSerializer.cs

Fix #5116
- Occationally there are unexplainable run with lots of dropping peers. 
- Closer inspection shows that the node is disconnecting peers due to error in forward sync, specifically empty receipt received.
- Anyway, it turns out that there is a bug in the receipt deserialization logic which can get triggered if the first element of the byte buffer allocated in ZeroNettyP2PHandler is equal to Rlp.OfEmptySequence[0].
- Fix deserialization bug.
- Added extra check in ProtocolHandlerBase that helped me debug this issue.
- Can by triggered manually by something like this in `ZeroNettyP2PHandler`.
```
IByteBuffer output = PooledByteBufferAllocator.Default.Buffer(uncompressedLength + 1);
output.WriteByte(Rlp.OfEmptySequence[0]);
output.ReadByte();
```

Fix randomly failing receipt deserialization

---

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs
src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs

- Add limit to batched jsonrpc request, set to 100.
Manually tested via a python script.

If batch size is too large, return an error

---

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs

Reduces RAM consumption for ForceProcessing requests. Keeping original flow and logic that can be updated in the future.
Minimal flag checks
flag checks added
- Tested on mainnet locally (working)
- Tested on sepolia block production by Angkor team (working)
- tested with Kamil's special test project
Covered by existing tests

Reduce RAM consumption for ForceProcessing requests

---

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network/ProtocolsManager.cs

- disable eth68 capability for now because spec is not final: https://eips.ethereum.org/EIPS/eip-5793
If we would release version with eth68 protocol in current form and spec will change (is still a draft), we could end up with non-compatible eth68 protocols

Disable eth68 for now because spec is not final

---

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs
src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs

Closes #4968
In sending local tx immediately after receiving it:
- to peers connected via `eth67` or lower, not send blob tx at all (added checks in `SyncPeerProtocolHandlerBase`)
- to peers connected via `eth68` or higher, send hash of blob tx (added logic in `Eth68ProtocolHandler`)
In sending persistent txs after processing every new block:
- just skip blob txs when preparing msg to send (I also consider sending blob txs as hashes here)
Sending new form of `NewPooledTransactionHashesMessage` with hashes of recently added txs (not local) is already implemented in `Eth68ProtocolHandler`
We might need to add broadcasting hashes of blob txs from persistent broadcast - right now there is actually no point in adding blob txs to persistent txs, as we are not broadcasting it later at all (we …

Refactor broadcasting for a needs of EIP-4844

---

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs

- `ZeroProtocolHandlerBase` does not implement `IZeroProtocolHandler` so subclass (SnapProtocolHandler) will have it's packet copied from a `ZeroPacket` to a `Packet` in `Session`, then copied back again to `ZeroPacket` in `ZeroProtocolHandlerBase`. 
- Implement IZeroProtocolHandler.
- Mainnet can sync

Add IZeroProtocolHandler interface to ZeroProtocolHandlerBase

---

src/Nethermind/Nethermind.Blockchain.Test/TransactionSelectorTests.cs
src/Nethermind/Nethermind.Blockchain.Test/TransactionsExecutorTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs
src/Nethermind/Nethermind.Core/Transaction.cs
src/Nethermind/Nethermind.Evm/IntrinsicGasCalculator.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs

The incorrect transactions should be removed from TxPool.
[TransactionSelectorTests.cs](https://github.com/NethermindEth/nethermind/compare/bugfix/eip3860_badBlock?expand=1#diff-0aeb6aa49e73b456afe5d8fc101788ef2463dadc1ba83c29858a24adfe4abdb7) and [TransactionsExecutorTests.cs](https://github.com/NethermindEth/nethermind/compare/bugfix/eip3860_badBlock?expand=1#diff-35501d8b35eb4f35e5fc254b4b578ed1d2a4714bb59bf0fe0e84c52ea9639fae) was refactored because I planned to add these changes to BlockProcessor.BlockProductionTransactionPicker.cs https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockProductionTransactionPicker.cs
However, TxValidator will be the better place, because we will reject the blocks sooner in the …

Bugfix/eip3860 reject invalid TXs from TxPool

---

src/Nethermind/Nethermind.Consensus/Withdrawals/WithdrawalProcessor.cs
src/Nethermind/Nethermind.Core.Test/Builders/TestItem.cs
src/Nethermind/Nethermind.Core.Test/Builders/WithdrawalBuilder.cs
src/Nethermind/Nethermind.Core.Test/Encoding/WithdrawalDecoderTests.cs
src/Nethermind/Nethermind.Core/Nethermind.Core.csproj
src/Nethermind/Nethermind.Core/Withdrawal.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
src/Nethermind/Nethermind.Serialization.Rlp/WithdrawalDecoder.cs

Don't merge for now.
Engine API: https://github.com/ethereum/execution-apis/pull/354
EIP-4895: https://github.com/ethereum/EIPs/pull/6325

Withdrawals wei -> gwei

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
src/Nethermind/Nethermind.Core.Test/Encoding/ReceiptDecoderTests.cs
src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rpc/RpcColumnsDb.cs
src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
src/Nethermind/Nethermind.Db/DbExtensions.cs
src/Nethermind/Nethermind.Db/IDbWithSpan.cs
src/Nethermind/Nethermind.Db/MemDb.cs
src/Nethermind/Nethermind.Db/ReadOnlyDb.cs
src/Nethermind/Nethermind.Network.Benchmark/InFlowBenchmarks.cs
src/Nethermind/Nethermind.Network.Test/P2P/SerializerTester.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/ZeroNewBlockMessageSerializerTests.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/HobbitTests.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/SnappyTests.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/ZeroNettyFrameMergerTests.cs
src/Nethermind/Nethermind.Network/MessageSerializationService.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Messages/PooledTransactionsMessageSerializer.cs
src/Nethermind/Nethermind.Network/Rlpx/Packet.cs
src/Nethermind/Nethermind.Network/ZeroMessageSerializerExtensions.cs
src/Nethermind/Nethermind.Serialization.Rlp/IByteBufferExtensions.cs
src/Nethermind/Nethermind.Serialization.Rlp/Nethermind.Serialization.Rlp.csproj
src/Nethermind/Nethermind.Serialization.Rlp/NettyRlpStream.cs
src/Nethermind/Nethermind.Serialization.Rlp/RlpDecoderExtensions.cs

- Encode block, header and receipts into netty stream instead of a byte array.
- Together with #5144, this reduce LOH allocation caused by `byte[]` significantly.
- Does not do anything to memory allocation rate though. Seems to increase gen 0 allocation.
(graph is after, before on mainnet)
- Encode block, header and receipts into netty rlp stream.
- Mainnet can sync.

Encode block, header and receipt writes with netty rlp stream

---

src/Nethermind/Nethermind.Config/ConfigProvider.cs
src/Nethermind/Nethermind.Grpc/Servers/GrpcServer.cs
src/Nethermind/Nethermind.Mev/Source/BundlePool.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
src/Nethermind/Nethermind.Synchronization/FastSync/PendingSyncItems.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
src/Nethermind/Nethermind.Trie/PatriciaTree.cs

Rather than doing extra work to get and exact count (which can be freezing/locks or cause allocations); use `IsEmpty` for ConcurrentCollections which is more light weight as it doesn't need to synchronise to count.

Use IsEmpty for ConcurrentCollections rather than doing work to .Count

---

src/Nethermind/Nethermind.Benchmark/Core/ByteArrayToHexBenchmarks.cs
src/Nethermind/Nethermind.Benchmark/Core/FromHexBenchmarks.cs
src/Nethermind/Nethermind.Core.Test/BytesTests.cs
src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Core/Extensions/Int64Extensions.cs
src/Nethermind/Nethermind.JsonRpc.Benchmark/UInt256ToHexStringBenchmark.cs

Were used to validate https://github.com/NethermindEth/nethermind/pull/5009; however that's long since been merged

Remove Obsolete Old methods used for validity checking

---

src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs
src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
src/Nethermind/Nethermind.Core.Test/Blockchain/BasicTestBlockchain.cs

- Fix trieexception caused by attempting to execute block when parent's state root is missing. Block is wrongly attempted due missed fast sync transition.
- In some case, state sync just execute twice and it would still synced fine.
- Add unit test.
- Fix issue.
- Add check to prevent executing when parent's state root is missing.

Fix fast sync transition block missed

---

src/Nethermind/Nethermind.Consensus/Producers/PayloadAttributes.cs
src/Nethermind/Nethermind.Core/Specs/ForkActivation.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs
src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Shanghai.cs
src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.Paris.cs
src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.Shanghai.cs
src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

Implemented https://github.com/ethereum/execution-apis/pull/337 that unifies Engine API failure responses.
Withdrawals Hive tests passing.

Unify Engine API failure responses

---

src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs

Fixes #5021
The issue seems to be a very rare race condition. either we should lock or try catch and ignore the exception.
- locks the cancellationTokenSource before cancellation or disposing.
its almost impossible to simulate this situation

fix to CancellationTokenSource has been disposed.

---

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/TransactionsMessage.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Messages/NewPooledTransactionHashesMessage.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Messages/NewPooledTransactionHashesMessage68.cs

Closes #4917
- increase max count of hashes in `NewPooledTransactionHashesMessage68` from 1024 to 2048 to be the same as in old `eth65` hashes msg
- add field `MaxPacketSize` in `TransactionsMessage`. Max size is 102400 bytes, same as in Geth (https://github.com/ethereum/go-ethereum/blob/793f0f9ec860f6f51e0cec943a268c10863097c7/eth/protocols/eth/broadcast.go#L29)
- refactor `FulfillPooledTransactionsRequest` in `Eth65ProtocolHandler` to limit `PooledTransactionsMessage` by accumulative size of txs instead of tx count
- refactor `SendNewTransactions` in `SyncPeerProtocolHandlerBase` to limit `TransactionsMessage` by accumulative size of txs instead of tx count

Refactor TxBroadcaster to limit messages by size

---

src/Nethermind/Nethermind.Core/MeasuredProgress.cs

Resolves #5183
`InitializeFeed()` now calls `PostFinishCleanUp()` which sets `UtcEndTime` and stops updating current
Before
After
- Resets `UtcEndTime` when new data comes in

Reset UtcEndTime when new data comes in

---

src/Nethermind/Nethermind.Blockchain/Synchronization/ISnapSyncPeer.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/GetByteCodesMessage.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs
src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncBatch.cs
src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
src/Nethermind/Nethermind.Synchronization/StateSync/StateSyncDispatcher.cs

Resolves #4377
- Pass the .Chunk => `List<>` directly through rather than `.ToArray`ing it since its only locally used can be modified directly
- Introduce a private class that presents `List<StateSyncItem>` as `IReadOnlyList<Keccak>` and use a static class of one for less common allocations; rather than Linq `.Select(x => x.hash).ToArray()`

TreeSync remove two .ToArray allocations

---

src/Nethermind/Nethermind.Crypto/AesEngineX86Intrinsic.cs
src/Nethermind/Nethermind.Crypto/EciesCipher.cs
src/Nethermind/Nethermind.Network/Rlpx/FrameCipher.cs
src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs

- Use `System.Runtime.Intrinsics.X86.Aes` when supported
- Based on the [BouncyCastle foray into intrinsics](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/crypto/engines/AesEngine_X86.cs); then optimized heavily on top to work with Jit behavour and asm output; as per the [Intel® Advanced Encryption Standard (AES) New Instructions Set](https://www.intel.com/content/dam/doc/white-paper/advanced-encryption-standard-new-instructions-set-paper.pdf) white paper.
Generates clean hardware accelerated asm for the encypt+decrypt methods compared to the software version. E.g. the encrypt 256 is below
```asm
; Method Encode256:ProcessRounds(byref):this
G_M000_IG01:                ;; offset=0000H
sub      rsp, 40
vzeroupper 
G_M000_IG02:                ;; offset=0007H
mov      rax, gword …
```

Use hardware accelerated Aes on x64

---

src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

- Implemented `engine_exchangeCapabilities` method as specified in [the spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/common.md#engine_exchangecapabilities)
- In addition, the execution client warns if it has more methods (considers only the activated ones on its end) than found in the consensus client.

Implement `engine_exchangeCapabilities` method

---

src/Nethermind/Ethereum.Blockchain.Test/Eip3855Tests.cs
src/Nethermind/Ethereum.Blockchain.Test/Ethereum.Blockchain.Test.csproj

- added class `Eip3855Tests`
- added path to `EIPTests`, moved to different directory in tests repo

Update ethereum tests, add Eip3855Tests

---

src/Nethermind/Nethermind.Api/IApiWithBlockchain.cs
src/Nethermind/Nethermind.Api/NethermindApi.cs
src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs
src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs
src/Nethermind/Nethermind.HealthChecks/NodeHealthService.cs
src/Nethermind/Nethermind.JsonRpc/IRpcCapabilitiesProvider.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

#5185 
- New interface IRpcCapabilitiesProvider
- Both HealthChecks plugin and ExchangeCapabilities access capabilities through this interface

Integrate EngineCapabilities into HealthChecks

---

src/Nethermind/Nethermind.Evm/VirtualMachine.cs

Handle tracing different pre EIP-2
Fixed pre-Homestead parity-like tracing for create transactions that don't have enough gas for created code.
When actual processing happens this is handled [here](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs#L377) but wasn't handled well in tracing code.
Tested on mainnet blocks, compared to parity traicng

pre-Homestead tracing fix

---

src/Nethermind/Nethermind.Benchmark.Runner/Nethermind.Benchmark.Runner.csproj
src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj

Enable .NET 7.0 [Dynamic PGO](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-7#performance) and on stack replacement 
Example of experiences in the wild https://petabridge.com/blog/dotnet7-pgo-performance-improvements/
With this one weird trick

Use Dynamic Profile-Guided Optimization

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadBodiesByRangeV1Handler.cs

Revised the last known block handling in `engine_getPayloadBodiesByRangeV1`: Replaced the `IBlockTree.BestSuggestedBody` with `IBlockTree.Head`.
Hive tests [passing](https://github.com/NethermindEth/nethermind/actions/runs/4127444345)

Revise last known block handling in `engine_getPayloadBodiesByRangeV1`

---

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncPeersReportTests.cs
src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs

- Add direction to sync peer report. 
- Make it easy to know if the peer is incoming or outgoing connection.
- Looks like this:
```
===[Active][Sleep ][Peer (ProtocolVersion/Head/Host:Port/Direction)    ][Transfer Speeds (L/H/B/R/N/S)      ][Client Info (Name/Version/Operating System/Language)     ]
--------------------------------------------------------------------------------------------------------------------------------------------------------------
[H     ][      ][Peer|eth67|16589240|  91.65.190.110:30404|Out][     |  338|     |     |     |     ][Nethermind/v1.16.1+644fe89f/linux-x64/dotnet7.0.2]
[HBR   ][      ][Peer|eth66|16589240|   72.18.53.167:30303|Out][     |  181| 3608| 5504|     |     ][Nethermind/v1.14.5+380bf9c9/linux-x64/dotnet6.0.10]
[H     ][ …
```

Add session direction to sync peer report

---

src/Nethermind/Nethermind.Init/MemoryHintMan.cs
src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network/Config/INetworkConfig.cs
src/Nethermind/Nethermind.Network/Config/NetworkConfig.cs
src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
src/Nethermind/Nethermind.Runner.Test/MemoryHintManTests.cs

- Add a cap to netty arena count to prevent high LOH allocation on high core count machine.
- Note that there seems to be a bug where previous dotnetty config was not getting applied sometimes. If that was the case, the dotnetty default config is 16MB chunk size, with (logical cpu count * 2) arena count. 
- Graph is goerli sync, 1st has 8 arena, 2nd has 64 arena, 3rd has 4 arena. Chunk size would be 16MB, 2MB, 32MB.
- Note, all three run uses the same 128MB budget, but during old blocks, all allocate more than 1 chunk per arena. For 8 and 4 arena, LOH for bytes array reduced significantly. GC stats is less smooth likely because GC count is lower. No significant difference between 8 and 4 arena. Note, during bodies sync new chunks are created in all case, however, with 8 and 4 arena, it is …

Add cap to arena count

---

src/Nethermind/Nethermind.Benchmark/Store/TrieNodeBenchmarks.cs
src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
src/Nethermind/Nethermind.Trie/NodeType.cs
src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
src/Nethermind/Nethermind.Trie/TrieNode.cs

This PR reduces the size of a single node by `16 bytes`, from `80 bytes` to `64 bytes`. This impact the timing though. 
Replaces #4581
```bash
BenchmarkDotNet=v0.13.4, OS=Windows 11 (10.0.22621.1105)
12th Gen Intel Core i9-12900HK, 1 CPU, 20 logical and 14 physical cores
DefaultJob : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
```
|        Method |     Mean |     Error |    StdDev |   Gen0 | Allocated |
|-------------- |---------:|----------:|----------:|-------:|----------:|
| PropertiesSet (before) | 7.509 ns | 0.0954 ns | 0.0846 ns | 0.0064 |      80 B |
| PropertiesSet (after) | 7.081 ns | 0.0677 ns | 0.0633 ns | 0.0051 |      64 B |
- collapsing numeric values into a single field reduces object size from `80B` to …

Trie node memory optimization

---

src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationTracer.cs
src/Nethermind/Nethermind.Benchmark/State/StorageCellBenchmark.cs
src/Nethermind/Nethermind.Evm.Test/TestAllTracerWithOutput.cs
src/Nethermind/Nethermind.Evm/Tracing/AccessTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/AlwaysCancelTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/CallOutputTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/CompositeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/EstimateGasTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/FeesTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofTxTracer.cs
src/Nethermind/Nethermind.Mev/BeneficiaryTracer.cs
src/Nethermind/Nethermind.Mev/Execution/TxBundleSimulator.cs
src/Nethermind/Nethermind.State.Test.Runner/StateTestTxTracer.cs
src/Nethermind/Nethermind.State/IStorageProvider.cs
src/Nethermind/Nethermind.State/IStorageTracer.cs
src/Nethermind/Nethermind.State/NullStorageTracer.cs
src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs
src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
src/Nethermind/Nethermind.State/StorageProvider.cs
src/Nethermind/Nethermind.State/TransientStorageProvider.cs

This PR changes the semantics of `readonly struct StorageCell` passing from by-value to by-ref. The change is visible in the decompiled ASM where an example call to the trace. Effectively, the whole copy over vector registers is skipped.
This might look like a small change but as the `StorageCell` is involved in several calls down the line (see `StorageProvider.Get), it can save some time on not copying the readonly value and just pass it by ref.
```asm
;before
vmovdqu   ymm0,ymmword ptr [rbx]
vmovdqu   ymmword ptr [rsp+28],ymm0
mov       rdx,[rbx+20]
mov       [rsp+48],rdx
lea       rdx,[rsp+28]
mov       r11,7FF938B00488
call      qword ptr [r11]
;after
mov       rdx,rdi
mov       rcx,[rbx]
mov       r11,7FF938AF0498
call      qword ptr [r11]
```
- use `in`  modifier, a.k.a by-ref …

StorageCell byref

---

src/Nethermind/Directory.Build.props

- Bump master version to 1.18.0-unstable
Why now? 
I think it would be better to have release branch with 1.17.0-unstable to know exactly where we branched from master and every following commit on master is already a part of new version.

Bump master to 1.18.0-unstable

---

src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs
src/Nethermind/Nethermind.Core/Crypto/Signature.cs
src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs
src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Crypto/EciesCipher.cs
src/Nethermind/Nethermind.Crypto/OptimizedKdf.cs
src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
src/Nethermind/Nethermind.Evm/ZeroPaddedSpan.cs
src/Nethermind/Nethermind.Network.Benchmark/InFlowBenchmarks.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/EciesCipherTests.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/HobbitTests.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/TestWrappers/ZeroFrameDecoderTestWrapper.cs
src/Nethermind/Nethermind.Network.Test/Rlpx/ZeroNettyFrameDecoderTests.cs
src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs
src/Nethermind/Nethermind.Network/Rlpx/Handshake/AckMessageSerializer.cs
src/Nethermind/Nethermind.Network/Rlpx/Handshake/AuthMessageSerializer.cs
src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameDecoder.cs
src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs

- `.AsSpan().Slice(x,y)` => `.AsSpan(x,y)` rather than creating span then slicing, do all in one operation
- Strongly typed `FrameMacProcessor` to change to direct calls from interface calls as it is called a lot (also to see if they'd naturally inline which they didn't)
- return input array when `PadLeft(this byte[] bytes` causes no changes

.AsSpan().Slice(x,y) => .AsSpan(x,y)

---

src/Nethermind/Nethermind.Benchmark/Store/TrieNodeBenchmarks.cs
src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
src/Nethermind/Nethermind.Trie/NodeType.cs
src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
src/Nethermind/Nethermind.Trie/TrieNode.cs

Repeats  #5259 with no faulting node by opting out from one check for the genesis block.
This PR reduces the size of a single node by `16 bytes`, from `80 bytes` to `64 bytes`. This impact the timing though. 
```bash
BenchmarkDotNet=v0.13.4, OS=Windows 11 (10.0.22621.1105)
12th Gen Intel Core i9-12900HK, 1 CPU, 20 logical and 14 physical cores
DefaultJob : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
```
|        Method |     Mean |     Error |    StdDev |   Gen0 | Allocated |
|-------------- |---------:|----------:|----------:|-------:|----------:|
| PropertiesSet (before) | 7.509 ns | 0.0954 ns | 0.0846 ns | 0.0064 |      80 B |
| PropertiesSet (after) | 7.081 ns | 0.0677 ns | 0.0633 ns | 0.0051 |      64 B |
- …

Trie node memory optimization fixed

---

src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
src/Nethermind/Nethermind.Trie/TrieNode.cs

This PR pushes further with memory optimizations of `TrieNode`, that were initiated in #5259. `TrieNode` is an object that is cached in memory and usually has ~350,000 objects of this type allocated. This PR cuts another 16 bytes from the class.
- make `storageRoot` a part of data so that only leaves allocate it (reduce footprint by 8 bytes for non-leaves)
- remove `FullRlp` reference and delegate to `_rlpStream.Data`
- amend `GetMemorySize` as it was previously (**thorough review required**) double counting the data (once under FullRlp, once under rlpstream)
```bash
BenchmarkDotNet=v0.13.4, OS=Windows 11 (10.0.22621.1105)
12th Gen Intel Core i9-12900HK, 1 CPU, 20 logical and 14 physical cores
DefaultJob : .NET 7.0.0 …
```

TrieNode further memory optimizations

---

src/Nethermind/Nethermind.Benchmark/State/StorageTreeBenchmark.cs
src/Nethermind/Nethermind.State/Nethermind.State.csproj
src/Nethermind/Nethermind.State/StorageTree.cs

This PR optimizes `StorageTree` component, removing some allocations and making it a bit faster in general. Please be minded that benchmarks are capped by the Keccak calculation so for precached indexes (1-1024) the gains will be much bigger.
- `StorageTree.Get` & `StorageTree.Set` 
- got rid off the allocation
- reuse buffer
```bash
BenchmarkDotNet=v0.13.4, OS=Windows 11 (10.0.22621.1105)
12th Gen Intel Core i9-12900HK, 1 CPU, 20 logical and 14 physical cores
DefaultJob : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
```
|    Method |     Mean |    Error |   StdDev |   Median |   Gen0 | Allocated |
|---------- |---------:|---------:|---------:|---------:|-------:|----------:|
| Set_index (before) | 494.3 ns | 23.55 ns …

StorageTree opitimization

---

src/Nethermind/Nethermind.Network/P2P/MessageDictionary.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs

- Dispose the couple ones that weren't
- Remove one that is unnecessary (can enumerate and remove from a concurrent dict at same time)

Dispose ArrayPoolList after use

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs
src/Nethermind/Nethermind.Consensus.Ethash/NethDevPlugin.cs
src/Nethermind/Nethermind.EthStats/EthStatsPlugin.cs
src/Nethermind/Nethermind.Init/Steps/StartBlockProducer.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconPivot.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroNettyP2PHandler.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoaderExtensions.cs

-Reduced severity of some warnings (@kamilchodola you might like it)
-Changed confusing beaconPivot logs. When it was logged as a full block it prints IsPostMerge flag = false
- [] No
Synced withdrawal-devnet-7.

Logs cleanup

---

src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Core/Extensions/HexConverter.cs
src/Nethermind/Nethermind.Db.Test/SimpleFilePublicKeyDbTests.cs
src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs

- Operate over `Span<byte>` rather than allocating strings via `ReadAllLines` and `string.Split`
Before
After

Remove 15MB of string allocations in SimpleDb.LoadData

---

src/Nethermind/Nethermind.Config.Test/ConfigFileTestsBase.cs
src/Nethermind/Nethermind.Config/ConfigProvider.cs
src/Nethermind/Nethermind.Core/Extensions/TypeExtensions.cs
src/Nethermind/Nethermind.Core/TypeDiscovery.cs
src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs
src/Nethermind/Nethermind.Monitoring.Test/MetricsTests.cs
src/Nethermind/Nethermind.Runner/Program.cs

- Singleton the discovery with locking (if loading, wait till loaded)
- Use Dictionary to go from O(N^2) to O(N)
- Exclude system and dependency dlls from discovery
- Avoid constructing `.FullName` from `AssemblyName`
- Single pass the dependency of dependency of ... loading
- Skip looking at dependencies of anything already loaded
Before
After
Also about x3.8 times faster

Remove 35MB of allocations in TypeDiscovery

---

src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/SyncStatusListTests.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastBlockStatus.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastBlockStatusList.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs

- Pack 4 x `FastBlockStatus` per byte rather than 1, saving ~24MB in total from `ReceiptsSyncFeed` and `BodiesSyncFeed` combined

Remove 28MB of permanent allocations from SyncStatusList (32MB -> 8MB)

---

src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
src/Nethermind/Nethermind.Db.Rocks/RocksDbExtensions.cs
src/Nethermind/Nethermind.Db/DbExtensions.cs

- RocksDb *may* return a non-null empty item, deallocate also when pointer is not null
- Not sure if this is actually an issue (does it always return `null` for zero length items?), so just for completeness

Release non-null empty spans

---

src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
src/Nethermind/Nethermind.Crypto/Secp256K1Curve.cs

- Move from `BigInteger` to `UInt256` in `TxValidator.ValidateSignature`
Removes all per txn allocations for TxValidator:

ValidateSignature move from BigInteger to UInt256

---

src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- Missing `ReportActionEnd`
Testing by tracing old blocks.

Add missing ReportActionEnd on pre-Homestead blocks that are out of gas on create

---

src/Nethermind/Ethereum.Blockchain.Test/Eip3651Tests.cs

- added class `Eip3651Tests`
Intentionally `stEOF` tests are not inclluded - it is not merged yet and we are failing it

Update ethereum tests, add `Eip3651Tests`

---

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network/ProtocolsManager.cs

- This reverts https://github.com/NethermindEth/nethermind/pull/5140

Bring back eth68

---

src/Nethermind/Nethermind.Blockchain.Test/Visitors/StartupTreeFixerTests.cs
src/Nethermind/Nethermind.Network/NetworkStorage.cs
src/Nethermind/Nethermind.Network/PeerPool.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncPeersReportTests.cs

Rebased #5271 as was having issues with github 🤔
- Only full refresh and parse from DB when nodes change
- Don't allocate fresh node prior to checking if node already exists (compare prior rather then post)
- Reduces by about ~10MB/min (see trace below)

Remove 14MB from RunPeerCommit allocations

---

src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs

Fixes #4611 
When a user provides a config value for `JwtSecretFile` and the file is not found, the node will create a secret by itself. 
This add a warning `"The authentication secret hasn't been found in <configured path> so it has been automatically created."` instead of a simple info log.

fix missing jwt warning

---

scripts/syncSettings.py

We cannot update configs because of PoaCore Section. Is this network still supported?

Remove PoaCore from config update

---

src/Nethermind/Nethermind.Serialization.Rlp/NettyRlpStream.cs
src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs

- Reduce multiple virtual calls to single one
- Use single reverse endienness intrinsic rather than multiple ors and shifts
- Move exceptions out of flow
- Reduce stack zeroing 320 bytes -> 128 bytes
- Reduce asm size 441 bytes -> 132 bytes
- Remove 256 bytes of preamble push + pop
It gets called quite a lot: 
```diff
; Method Nethermind.Serialization.Rlp.RlpStream:DeserializeLength(int):int:this
G_M000_IG01:
<       push     r14
<       push     rdi
<       push     rsi
<       push     rbp
<       push     rbx                         ; five pushes (reg -> memory)
<       sub      rsp, 80
<       xor      eax, eax
<       mov      qword ptr [rsp+28H], rax     ; zero 64 bits of stack
<       vxorps   xmm4, xmm4
<       vmovdqa  xmmword ptr [rsp+30H], xmm4     ; zero 128 bits of stack
< …
```

Optimize RlpStream.DeserializeLength

---

src/Nethermind/Nethermind.Trie/TrieNode.cs

This PR brings TrieNode again to its size, making it bigger to ensure that writes to its properties are more atomic
- make properties not bit-wise

TrieNode propertied not bit-wise

---

src/Nethermind/Nethermind.Evm/EvmStack.cs

- Load and endianness swap in one instruction
- Tail call for Int256
- Move exceptions out of flow
- Move tracing loops out of flow

Optimize EvmStack

---

src/Nethermind/Nethermind.Consensus/Comparers/GasPriceTxComparer.cs
src/Nethermind/Nethermind.Core/Transaction.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/PooledTxsRequestor.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs
src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs
src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs
src/Nethermind/Nethermind.TxPool/Filters/AlreadyKnownTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/BalanceTooLowFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/BalanceZeroFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/DeployedCodeFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/FeeTooLowFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/GapNonceFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/GasLimitTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/LowNonceFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/MalformedTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/NullHashTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/NullIncomingTxFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/UnknownSenderFilter.cs
src/Nethermind/Nethermind.TxPool/ITxPoolConfig.cs
src/Nethermind/Nethermind.TxPool/Metrics.cs
src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs
src/Nethermind/Nethermind.TxPool/TxPoolConfig.cs

Resolves #4793
Updated #5158 rebased on `Refactor tx filtering` #5281 (main branch)
* Changes `FeeTooLowFilter` for `BalanceTooLowFilter`
* Early accept on local or non-full txn pool prior to checking state
* Introduces `FeeTooLowFilter` early which just considers gas fee without accessing state
* Reject transactions with zero balance before checking txns
* Introduce new metric `PendingTransactionsUnresolvableSender`
* Introduce new metric `PendingTransactionsGasLimitTooHigh`
* Introduce new metric `Metrics.PendingTransactionsZeroBalance`
* Introduce new metric `PendingTransactionsTooLowBalance`
* Introduce new metric `PendingTransactionsPassedFiltersButCannotCompeteOnFees`
* Introduce new metric `PendingTransactionsMalformed`
* Introduce new metric `PendingTransactionsLowNonce`
* Add …

Filter low gas txns early

---

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj

- `BinaryFormatterSerialization` is deprecated and unsafe, so jettison all the code for it from the builds
- `UTF7Encoding` is deprecated and unsafe, so jettison all the code for it from the builds
- Don't think Globalization is particularly used, so jettison all the data for it from the builds (also make some string conversions faster)

Remove unused runtime features

---

src/Nethermind/Nethermind.Core.Test/Encoding/BlockInfoDecoderTests.cs
src/Nethermind/Nethermind.Serialization.Rlp/BlockInfoDecoder.cs

- fix calculating content length of empty sequence
in `GetLength` return `Rlp.OfEmptySequence.Length` instead of `Rlp.LengthOfSequence(Rlp.OfEmptySequence.Length)` (1 instead of 2)
It's a fix for changes merged 2 weeks ago in https://github.com/NethermindEth/nethermind/pull/5114

Fix `BlockInfoDecoder`

---

src/Nethermind/Nethermind.Init/Steps/InitDatabase.cs

- Seems that database may be initialized without memory hint being applied.
- This is important because writebuffersize which effect l0 file size depends on memory hint.
- Can be confirmed by adding a `Thread.Sleep` in `MemoryHintMan`. 
- Make sure to apply memory hint before database starts.
- Tested manually. The write/read amplification during sync is actually similar, with or without the memory setup properly.

Fix memory hint not applied to database sometimes

---

src/Nethermind/Nethermind.Evm/EvmStack.cs
src/Nethermind/Nethermind.Evm/EvmState.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

Since in same scenario with https://github.com/NethermindEth/nethermind/issues/5386
Ran out of stacks
- Dispose `previousState` even when exception

Stronger guarantees of state return during failures

---

src/Nethermind/Nethermind.Core/Caching/LruCache.cs
src/Nethermind/Nethermind.Trie/CachingStore.cs

This PR changes LruCache snapshot into an array. As the snapshot is used only in pruning and requires no Dictionary interface, it can be provided with an array that saves on comparisons, hashing and more.
- `LruCache.Clone` is array returning

LruCache faster snapshot

---

src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs

- If blocks suggested too fast new blocks can be added to the clean up list while it is being enumerated causing an enumeration exception to be thrown. Remove from `ConcurrentDictionary` directly, no need for the second list

Fix exception in CleanupOldPayloads from concurrent use of List

---

src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/Nethermind.Synchronization.csproj

- Change `ConcurrentDictionary` to `ConcurrentHashSet`
- Managed to get an increase of total 8464.70bps -> total 8756.95bps
- Could be incidental, need more tests
- Allocates a bit less
Sync faster on my test

In FastHeadersSyncFeed change ConcurrentDictionary to ConcurrentHashSet

---

src/Nethermind/Nethermind.Core.Test/BytesTests.cs
src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
src/Nethermind/Nethermind.Trie/PatriciaTree.cs

- Make `TraverseContext` readonly and pass via `in` ref (chonky struct)

Make TraverseContext readonly and pass via in

---

src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/InitializeBlockchainAuRa.cs
src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
src/Nethermind/Nethermind.TxPool/Filters/BalanceZeroFilter.cs
src/Nethermind/Nethermind.TxPool/Filters/FeeTooLowFilter.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

Another approach for https://github.com/NethermindEth/nethermind/pull/5409
I don't really like passing bool flag to TxPool, but don't have better idea. Open for suggestions.
If there is priority contract:
- change `BalanceZeroFilter` to not filter out any transactions because of zero balance of sender account
- remove zero fee check
Tests are passing from this branch:
https://github.com/NethermindEth/nethermind/actions/runs/4377073528/jobs/7660066366

Fix posdao tests - disable filters only if there is priority contract

---

src/Nethermind/Nethermind.Runner/Program.cs

- Switch off DotNetty's Resource Leak Detector as it is the largest single allocator; and isn't adding high value as there are currently no leak errors being reported

Switch off DotNetty ResourceLeakDetector

---

src/Nethermind/Nethermind.Network/NetworkStorage.cs

Change https://github.com/NethermindEth/nethermind/pull/5294 over regenerated the `NetworkNode[]` as it regenerated it on every change.
This change massively reduces the allocations by waiting for a request for the array to regenerate it rather than doing it on each change.
- Wait till request for `NetworkNode[]` to regenerate

Only clear NetworkNode cache on changes

---

src/Nethermind/Nethermind.Merkleization/Merkle.cs

- Move from using hand written Bit manipulation based operation in Merke class to using Builtin methods in the BitOperations class
- 
BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.22621.1265/22H2/2022Update/SunValley2)
Intel Core i5-8265U CPU 1.60GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores
DefaultJob : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
|                    Method |             Argument |       Mean |     Error |    StdDev |     Median | Allocated |
|-------------------------- |--------------------- |-----------:|----------:|----------:|-----------:|----------:|
|         NextPowerOfTwoOld |                    0 |  1.7146 ns | 0.1994 ns | 0.5818 ns |  1.6501 ns |         - |
| …

Migrate To use BitOperation Class for BinaryOperations

---

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rocks/Statistics/DbMetricsUpdater.cs
src/Nethermind/Nethermind.Db.Test/DbMetricsUpdaterTests.cs

- Fix rocksdb statistics not showing up for column family.
- Add db statistics for column family.
Confirmed metrics show up on prometheus endpoint.
```
nethermind_receipts_transactions_db_interval_compaction_seconds 0
```

Fix missing db statistics for column family

---

src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs

- Fix fast header disconnecting peers due to some IO causing a race issue.
- Dont disonnect peer when a batch does not match next expected batch but match parent of lowest inserted header.
- Seems to work.

Fix fast header disconnecting peers sometimes

---

src/Nethermind/Nethermind.Mev/Nethermind.Mev.csproj

Adds Deterministic and `ProduceReferenceAssembly` to `Nethermind.Mev`
All projects should have this set, but this is the one that broke my plugin so it is the one I am submitting a PR for.  Ideally, anytime a new project is created this is automatically added to it.  Alternatively, perhaps there could be a linter check or something that verifies these lines get added to all projects?
It is necessary for anyone building plugins that live external to this repository/project as the reference assemblies are needed to build against.

Adds Deterministic and ProduceReferenceAssembly to Nethermind.Mev

---

src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs
src/Nethermind/Nethermind.TxPool/Filters/DeployedCodeFilter.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

Removes 3 state lookups per txn add
- Pass `Account` to `AddCore` to avoid ***2 additional lookups*** of account
- `DeployedCodeFilter` doesn't need to look up account removing an ***additional lookup of account***
- Capture closure in constructor to avoid `Func` allocation per call in `UpdateBuckets()`
- Use concrete types to avoid enumerator allocations via interface
- ~~Use an intra-block Address -> Account cache~~
- Reuse a `ThreadStatic` `TxFilteringState` rather than allocating each txn
- Drop Linq use in TxPool
- Return `UInt256?` `GasBottleneck` change rather than `Action` to change gas to avoid allocating an `Action` per gas change
- Only resnapshot on change

Reduce state access for TxPool

---

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rocks/Statistics/DbMetricsUpdater.cs

- Turns out the crash that I keep encountering after full pruning is the db metrics updater trying to get metrics from a disposed rocksdb.
- Stop metrics updater on dispose.
- Tested to reliably no longer crash.

Fix crash after full pruning complete when db metrics is enabled

---

src/Nethermind/Ethereum.Blockchain.Block.Test/Eip4895WithdrawalsTests.cs
src/Nethermind/Ethereum.Blockchain.Block.Test/MetaTests.cs

- added class `Eip4895WithdrawalsTests`
- adjusted `MetaTest` to work fine with `4895-withdrawals` (starting with digit and `-` inside)

Update ethereum tests, add `Eip4895WithdrawalsTests`

---

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs
src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPruningDiskTest.cs
src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Blockchain/FullPruning/FullPruner.cs
src/Nethermind/Nethermind.Blockchain/IBlockTree.cs
src/Nethermind/Nethermind.Blockchain/OnUpdateMainChainArgs.cs
src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs

- If full pruning is started after new head event which is triggered by blockchainproccessor where the branch have more than one block, some of the block state will be missed causing trie exception after pruning complete.
- This is because blockchainprocessor will process the branch first before triggered new head event multiple time. Full pruning will start switching duplicating writes after the first event, and assume the writes for the other blocks will start after that, but that does not happen as it was already processed.
- This PR add another event `OnUpdateMainChain` which would get triggered per processing branch instead of multiple time. Ideally the event should be in BlockchainProcessor, but turns out there is a dependency issue so it can't refer to it without a bigger refactor. …

Fix random trie exception after pruning

---

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs
src/Nethermind/Nethermind.Core.Test/InMemoryBatch.cs
src/Nethermind/Nethermind.Core.Test/TestMemDb.cs
src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs
src/Nethermind/Nethermind.Db/MemDb.cs

- Use write batch for writes in full pruning that periodically write instead of writing on each node.
- Does not reduce pruning time but significantly reduce write iops and system cpu time. 
Graph is after, before, after. Third have another optimization (#5463).
Ok, it reduce it a little bit. My SSD is getting hot I suppose?
- Use write batch for writes in full pruning.
- Modified TestMemDb to simulate batch behaviour more correctly. Confirmed without final batch dispose, tests would fail.
- Seems to work many consecutive times.

Use write batch for full pruning write

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconPivot.cs

- Removed the ugly log ⬇️ 
It was duplicated with https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Blockchain/BlockTree.cs#L216
- Don't print BeaconPivot when it is null
- Changed one Warn to Info
I've run unsynced/synced nodes a few times. Of course, there is no need to sync the node to test it.

Small improvement in startup logs

---

src/Nethermind/Nethermind.Core/LogEntry.cs
src/Nethermind/Nethermind.Core/TransactionReceipt.cs
src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
src/Nethermind/Nethermind.Evm/ByteArrayExtensions.cs
src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
src/Nethermind/Nethermind.Evm/EvmState.cs
src/Nethermind/Nethermind.Evm/ExecutionEnvironment.cs
src/Nethermind/Nethermind.Evm/Precompiles/PointEvaluationPrecompile.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs
src/Nethermind/Nethermind.Evm/ZeroPaddedSpan.cs
src/Nethermind/Nethermind.Merkleization/Merkle.cs

Less extreme approach than https://github.com/NethermindEth/nethermind/pull/5367 for some quick wins
- Don't use local functions that take hidden copies of very large structs (e.g. `ExecutionEnvironment`)
- Change `ExecutionEnvironment` `readonly struct` and use `ref readonly` to refer to it rather than take copy
- `ref readonly` to refer to `TxExecutionContext` rather than take copy
- Move all the `CallResult` struct returns out of the loop, and use goto error pattern (both reduces code duplication and stack space)
- ReadOnlyMemory<byte>.Empty -> default (Jit does less work and doesn't think it needs to save space for a variable)
- Reduce stack clearance (Method stack clearance 8928 bytes -> 8304 bytes, -624 bytes)
- Reduce method size (Method asm 33454 bytes -> 27349 bytes, -6105 bytes) …

Reduce VirtualMachine.Execute call stack

---

.github/workflows/hive-consensus-tests.yml

- update workflow of hive consensus tests.
After adding Shanghai there is 89k tests. Now there will be 68 jobs (instead of 53 before). We might have some timeouts, but we can do nothing about it, as single, indivisible tests are generating it - it was taking 4,5-5h before and after adding Shanghai is close to 6h - sometimes pass, sometimes timeout hit. Testing run: https://github.com/NethermindEth/nethermind/actions/runs/4540612392 (looks okayish after 1 rerun of failed tests)

Update hive consensus workflow and ethereum tests

---

src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs
src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs
src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
src/Nethermind/Nethermind.Trie/TrieNode.cs

This reverts commit 5488e31b2c0ef18f37e3f5900e92ea07c7752ffb.
Reverted this PR, because after investigation i've find out that this one causes Full Node not being able to sync properly.
On goerli node after around 500k blocks processed there was a TrieException.
Confirmed that 3 times (branch with this change vs without).
How to reproduce:
Nethermind.Runner.exe --config goerli_archive --Pruning.Mode=Hybrid
Wait for ~520k of blocks to be processed.
**OBSERVATION**
I've notice that if I'll run a branch WITHOUT this PR to about 400k blocks processed, stop gracefully node, switch to branch WITH this PR and wait for this 520k barrier, it will progress fine (may fail later in the process).
Because of that I assume, that this corrupts database earlier but it is being visible on 520 BUT node …

Revert "Reduce TrieNode allocations (#5457)"

---

src/Nethermind/Nethermind.Benchmark/Core/FromHexBenchmarks.cs
src/Nethermind/Nethermind.Core/Collections/ThrowHelper.cs
src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Core/Extensions/HexConverter.cs

- Vectorize `HexConverter.TryDecodeFromUtf16` for x64 and Arm as per https://github.com/dotnet/runtime/pull/82521

Vectorize HexConverter.TryDecodeFromUtf16

---

src/Nethermind/Nethermind.Db.Rocks/ColumnsDb.cs
src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
tools/HiveConsensusWorkflowGenerator/Program.cs

- Consolidate column family and default column family options into one. 
- Makes testing config way easier. Also make sure db config is applied to column family.
- Use the same function to declare main config and column family config.
- Does not seems to affect receipts db size.

Fix column families does not use the same config as default column

---

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs

Fix #5522
- On early full sync, the time within block precessing is less than 1ms, so the report shows -1.
- Change passed in time from millisecond to microsecond.
- Tested to work manually.

Fix processing speed is -1.

---

src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs

- `Environment.TickCount64` is already in milliseconds whereas `StopWatch.GetTimestamp` needs conversion based on `StopWatch.Frequency` (isn't the same Ticks as DateTime Ticks)

Use Environment.TickCount64 rather than StopWatch.GetTimestamp

---

src/Nethermind/Nethermind.Core.Test/Encoding/ReceiptMessageDecoderTests.cs
src/Nethermind/Nethermind.Serialization.Rlp/CompactLogEntryDecoder.cs
src/Nethermind/Nethermind.Serialization.Rlp/CompactReceiptStorageDecoder.cs
src/Nethermind/Nethermind.Serialization.Rlp/ReceiptArrayStorageDecoder.cs
src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs

- After logging in RLP code, these show up.
```
The type is Nethermind.Serialization.Rlp.AccountDecoder Nethermind.Serialization.Rlp.IRlpDecoder`1[Nethermind.Core.Account]
The type is Nethermind.Serialization.Rlp.ByteStreamDecoder Nethermind.Serialization.Rlp.IRlpDecoder`1[System.Byte]
The type is Nethermind.Serialization.Rlp.ShortStreamDecoder Nethermind.Serialization.Rlp.IRlpDecoder`1[System.Int16]
The type is Nethermind.Serialization.Rlp.UShortStreamDecoder Nethermind.Serialization.Rlp.IRlpDecoder`1[System.UInt16]
The type is Nethermind.Serialization.Rlp.IntStreamDecoder Nethermind.Serialization.Rlp.IRlpDecoder`1[System.Int32]
The type is Nethermind.Serialization.Rlp.UIntStreamDecoder Nethermind.Serialization.Rlp.IRlpDecoder`1[System.UInt32]
The type is …
```

Make sure compact receipt does not get registered as global receipt decoder.

---

src/Nethermind/Nethermind.Consensus/Producers/PayloadAttributes.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs

Fixes #5563
- Included withdrawals in payload id computation
- Moved the `PayloadPreparationService.ComputeNextPayloadId` method to `PayloadAttributesExtensions.ComputePayloadId`
This PR adds withdrawals to payload id computation. The rest of the logic remains intact.

Include withdrawals in payload id computation

---

src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs
src/Nethermind/Nethermind.Blockchain/BlockTree.cs

#5519 
- If td for given block inside blockInfos db is zero we will set td to null even if it should be zero. This pr checks genesis difficulty and ttd to set td of this block.

Zero total difficulty in FindBlock

---

src/Nethermind/Nethermind.Abi.Test/AbiTests.cs
src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
src/Nethermind/Nethermind.Core/Resettables/Resettable.cs
src/Nethermind/Nethermind.Trie/BatchedTrieVisitor.cs

Very minor
- Dispose two additional ArrayPoolLists
- Refactor existing ones to use `using`
- Use `ArrayPool<T>.Shared` directly rather than storing in field (Jit can then devirtualise)

Return a couple additional ArrayPoolLists

---

src/Nethermind/Nethermind.Overseer.Test/Framework/TestBuilder.cs

- Fix path from `net6.0` to `net7.0` and change mode from `Debug` to `Release` depending on build

Fix Overseer path for .NET version update and config state

---

.github/workflows/nethermind-tests.yml
src/Nethermind/Nethermind.Init/Metrics.cs
src/Nethermind/Nethermind.Monitoring/Metrics/MetricsController.cs

To make requests like `avg(state_db_size{Network="Gnosis",Version=~"1.18.0.*"}` possible we have to add tags to every metric 
- Adds tag to every metric
- Changes BuildTimestamp to unix seconds

Add tags to every metric

---

src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs
src/Nethermind/Nethermind.Api/Extensions/IConsensusPlugin.cs
src/Nethermind/Nethermind.Api/IApiWithBlockchain.cs
src/Nethermind/Nethermind.Api/IApiWithNetwork.cs
src/Nethermind/Nethermind.Api/IBasicApi.cs
src/Nethermind/Nethermind.Api/Nethermind.Api.csproj
src/Nethermind/Nethermind.Api/NethermindApi.cs
src/Nethermind/Nethermind.AuRa.Test/AuRaPluginTests.cs
src/Nethermind/Nethermind.Consensus.AuRa/AuRaPlugin.cs
src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/AuRaNethermindApi.cs
src/Nethermind/Nethermind.Init/Steps/InitializeBlockProducer.cs
src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs
src/Nethermind/Nethermind.Init/Steps/StartBlockProducer.cs
src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.BlockProducer.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
src/Nethermind/Nethermind.Mev/MevPlugin.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/EthereumStepsManagerTests.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/ReceiptMigrationTests.cs
src/Nethermind/Nethermind.Runner/Ethereum/Api/ApiBuilder.cs

Enables strict null checks in Nethermind.Api
- NethermindApi now have constructor
- Few fields made nullable

Enable nullability in Api

---

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs

- Ratelimiter is also used for compaction reads and reads with custom priority. So write bytes per sec is actually wrong.
- Add direct io flags. Direct io bypass the OS's block cache. Tend to help with memory pressure, althought its unclear if its because its slower.
- Rename param.

Rename WriteBytesPerSec to BytesPerSec and add direct io flag.

---

src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptConfig.cs
src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptConfig.cs
src/Nethermind/Nethermind.Init/Steps/InitializeBlockTree.cs

- Increase max block depth from 1000 to 10000 and make it configurable.
- Does not matter if bloom is on.
- Teku's default max request is 10000.

Add config for eth_getLogs max block depth

---

src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs

less hacky version than  #5642

 Reduce SyncStatusList lock contention v2

---

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs

Right now `eth/67` and `eth/68` capabilities are not enabled when they should if:
- node is in archive mode (`SnapSync` and `FastSync` flags are `false`)
- there is no state
Capabilites are enabled if node with any state is restarted.
It is a bit problematic for 4844 testnets and very problematic for 4844 hive tests.
It is not affecting production nodes right now, but would be a problem for archive nodes after dropping `eth/66` by Geth
After this fix, `eth/67` and `eth/68` capabilities would be enabled always for archive nodes (when `FastSync` is `false`)

Fix eth capabilities for archive nodes

---

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
src/Nethermind/Nethermind.Blockchain/Nethermind.Blockchain.csproj
src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/InMemoryReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/NullReceiptStorage.cs
src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
src/Nethermind/Nethermind.Core.Test/TestMemColumnDb.cs
src/Nethermind/Nethermind.Core/Extensions/Int64Extensions.cs
src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
src/Nethermind/Nethermind.Db/DbExtensions.cs
src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs
src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/ReceiptMigrationTests.cs

- Prefix receipt's data key with block number like erigon. 
- Reduced write amplification during sync. Total write goes down from 5TB to 2.65TB.
- Does not noticably increase disk space use (in my run the one without blocknumber is actually slighly higher). This is likely because rocksdb have delta compression turned on by default for keys, so multiple keys with same prefix got compressed really well.
- Unexpectedly did not improve RPC performance, nor does it reduce iops. I guess on SSDs at least, it just reduce write amplification. ~~Maybe with readahead flag it'll do something.~~ not even with readahead. I guess 50iops per receipts means something else is using it...
- Tested on non-compact receipts as compact receipts still need to load blocks.
- Address receipts by blocknum+hash.
- …

Receipt key with block number

---

src/Nethermind/Nethermind.Cli/Modules/NodeCliModule.cs

#5650 
- Swap args in ternary condition

Fix misplaced arguments 

---

src/Nethermind/Nethermind.JsonRpc/Modules/Admin/PeerInfo.cs
src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network.Test/Stats/NodeTests.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroNettyP2PHandler.cs
src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs

#5657 
- Align port and ip only when printing peer report
- A bit of refactoring

Align only in peer report

---

src/Nethermind/Nethermind.Cli/Program.cs

Closes #5582
- Add an extra `-a|--address` option to specify a node address
- Default address is still `http://localhost:8545`
Manually tested on Linux (Fedora 37). There is no automated test suite for CLI options since there are only 2, color scheme and the newly introduced address (I don't think it's worth to add unit tests for this).

Add support for specifying address in CLI

---

.github/workflows/sync-testnets.yml

Syncs two testnets on master branch.
Will output logs after sync for some detailed analysis.
Will do only Forwards Sync, Beacon Sync, Snap Ranges and State Healing + additional 1 minute to process few blocks afterwards.
Action is started multiple times and green.
https://github.com/NethermindEth/nethermind/actions/runs/4948894182
Add some checks which will help to recognize if sync is OK (need to be very basic one which will catch obvious issues)
Maybe some docker image creation speed up (some local image which will be faster instead of pushing to docker-hub but not sure if possible). - **DONE**
Slightly better VM for Sepolia to sync faster but is okaish.

Add sync testnets after master merge

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Core/ChainLevelInfo.cs

- Moved some logic related to `ChainLevelInfo` from `BlockTree` into `ChainLevelInfo`.
- Make `BlockTree` slightly less intimidating.

Move some logic from blocktree into chain level info

---

src/Nethermind/Nethermind.Trie.Test/TrieNodeResolverWithReadFlagsTests.cs
src/Nethermind/Nethermind.Trie/TrieNodeResolverWithReadFlags.cs

- Fix `HintCacheMiss` read flags was missed causing trie visitor to not run with that flag, which nullify #5463.
- On worst case, this reduces verify trie throughput from 1.5M nodes per sec to 0.5M nodes persec.
- On slower speed, probably does not make any difference.

Fix missed cache miss hint

---

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs

- Fix accidentally set LowPriority write flag when DisableWal is set causing snap sync to be very slow.
- Snapsync can now reach above 250k node per sec, which seems to be the limit with low priority write.

Fix accidentally set low priority

---

src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeTxTracerTests.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

Resolves #5717
- Don't apply EXTCODESIZE optimization if tracing

Don't apply EXTCODESIZE optimization if tracing

---

src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationTracer.cs
src/Nethermind/Nethermind.Evm.Test/TestAllTracerWithOutput.cs
src/Nethermind/Nethermind.Evm/Tracing/AccessTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/AlwaysCancelTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/CallOutputTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/CompositeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/Debugger/DebugTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/EstimateGasTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/FeesTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs
src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofTxTracer.cs
src/Nethermind/Nethermind.Evm/TransactionSubstate.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs
src/Nethermind/Nethermind.Mev/BeneficiaryTracer.cs
src/Nethermind/Nethermind.Mev/Execution/TxBundleSimulator.cs
src/Nethermind/Nethermind.State.Test.Runner/StateTestTxTracer.cs

- Reduce exceptions in Evm processing (caused via revert decoding); as they are expensive

Reduce exceptions in Evm

---

src/Nethermind/Nethermind.Consensus.Ethash/Ethash.cs
src/Nethermind/Nethermind.Core/Crypto/Keccak.cs
src/Nethermind/Nethermind.Evm/Precompiles/EcRecoverPrecompile.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs
src/Nethermind/Nethermind.Network/Rlpx/Handshake/AuthMessageSerializer.cs
src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
src/Nethermind/Nethermind.State/Witnesses/WitnessingStore.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs

- Now Keccak isn't backed by a separate array; using `.ToArray` to construct from a Span is just an unneeded allocation

Keccaks: Skip unneeded array allocations

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Blockchain/Blocks/BlockStore.cs
src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/SyncStatusListTests.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastBlockStatus.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastBlockStatusList.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs

- Make `FastBlockStatusList` methods atomic reducing lock requirements
- Increase some LruCache sizes to match the scan length + n

Less contention for OldReceipts and OldBodies

---

src/Nethermind/Nethermind.Core/Crypto/PublicKey.cs
src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
src/Nethermind/Nethermind.Network.Stats/NodeStatsManager.cs
src/Nethermind/Nethermind.Network/Peer.cs
src/Nethermind/Nethermind.Network/PeerManager.cs
src/Nethermind/Nethermind.Network/PeerPool.cs

When the number of connected Peers is not at max (fairly common) and the Peer's db is fairly mature; the reconnection will accesses the `NodeStatsManager`'s nodeStats ConcurrentDictionary more frequently than the VM calls UpdateGas (which is every op executed)
- Cache hashcode in Node
- Replace locking in NodeStatsLight with `Volatile.Read` and `Interlocked.Increment`
- Stop NodeStatsManager timer running while executing
- Cache INodeStats object in Peer rather than looking it up from ConcurrentDictionary on each method call
- Throttle `PeerManager` if in a hot discovery loop; by up to 50ms per set of candidates

Less aggressive peer discovery

---

src/Nethermind/Nethermind.Core/Crypto/PublicKey.cs
src/Nethermind/Nethermind.Network.Benchmark/NodeStatsCtorBenchmarks.cs
src/Nethermind/Nethermind.Network.Discovery.Test/RoutingTable/NodeBucketItemTests.cs
src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs
src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucket.cs
src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucketItem.cs
src/Nethermind/Nethermind.Network.Stats/INodeStats.cs
src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs
src/Nethermind/Nethermind.Network.Stats/NodeStatsManager.cs
src/Nethermind/Nethermind.Network.Test/NetworkStorageTests.cs
src/Nethermind/Nethermind.Network.Test/NodeStatsTests.cs
src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs
src/Nethermind/Nethermind.Network/NetworkStorage.cs
src/Nethermind/Nethermind.Network/Peer.cs
src/Nethermind/Nethermind.Network/PeerManager.cs
src/Nethermind/Nethermind.Network/ProtocolsManager.cs

- Reduce calls to `DateTime.UtcNow` by factor of 100 (e.g. 3M -> 30k)
- After going through 1k peers for discovery wait TIME_WAIT before continuing to allow sockets to clear
- After going through all previously known peers for discovery wait TIME_WAIT before starting again to allow sockets to clear
- NetworkStorage: `HashSet<PublicKey>`+`List<NetworkNode>` -> `Dictionary<PublicKey, NetworkNode>`

Reduce datetime calls in peer discovery by factor of 100

---

src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
src/Nethermind/Nethermind.Evm/EvmStack.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- Reduce conversions `int` -> `UInt256`
- Single reg256 copy for `SaveWord` rather than invoking `Span.CopyTo`

More efficient EvmPooledMemory

---

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs

- ConcurrentDictionary can be iterated and have items removed from it at same time

Remove from ConcurrentDict directly rather than building secondary list

---

src/Nethermind/Nethermind.TxPool/Filters/BalanceZeroFilter.cs
src/Nethermind/Nethermind.TxPool/TxPool.cs

- Will be currently be rejected later in pipeline by `BalanceTooLowFilter`; however that iterates and considers all txs from the account; can do an earlier reject in `BalanceZeroFilter` just for the current tx in solation

Add fast test for balance < tx.Value + gas

---

src/Nethermind/Nethermind.Consensus/Tracing/ITracer.cs
src/Nethermind/Nethermind.Consensus/Tracing/Tracer.cs
src/Nethermind/Nethermind.Evm.Test/Nethermind.Evm.Test.csproj
src/Nethermind/Nethermind.Evm.Test/TransactionProcessorTraceTest.cs
src/Nethermind/Nethermind.Evm.Test/VirtualMachineTestsBase.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/ITransactionProcessor.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityStyleTracerTests.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofModuleFactory.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceModuleFactory.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
src/Nethermind/Nethermind.Mev/Execution/TracerFactory.cs

#5680 
- Now some of trace_* functions use Execute instead of trace.
- Do not refund in noValidation mode

Fix gas fees accounting in TransactionProcessor.Trace 

---

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
src/Nethermind/Nethermind.Trie/TrieNode.cs

- During `PruneCache` it can add Keccak's to TrieNodes that are small enough to be Rlp'd in parent so shouldn't have a Keccak.
- This change just generates the key rather than altering the TrieNode; thus treating it as readonly

Don't add Keccaks during cache pruning

---

src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network.Stats/Model/NodeClientType.cs
src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloaderLimits.cs
src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs

- Move detailed (line per peer) to Debug
- Add diversity to single line logs
```
2023-06-09 06:42:15.8209|Allocated sync peers 72(72)/100 | Geth (51.39 %), Nethermind (30.56 %), erigon (13.89 %), besu (2.78 %), Unknown (1.39 %)
2023-06-09 06:42:30.9419|Peers | with known best block: 71 | all: 71 | Geth (52.11 %), Nethermind (30.99 %), erigon (14.08 %), besu (2.82 %)
```

Move detailed peer logging to debug, add diversity

---

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs

Mild follow up to https://github.com/NethermindEth/nethermind/pull/5789
- Reuse batch Dictionary to reduce allocations
- Skip creating the batch if is empty

Reuse batch Dictionary and skip empty batches

---

src/Nethermind/Nethermind.Core/Specs/ISpecProvider.cs
src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs
src/Nethermind/Nethermind.HealthChecks/NodeHealthService.cs
src/Nethermind/Nethermind.JsonRpc/IRpcCapabilitiesProvider.cs
src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.RelayBuilder.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExchangeCapabilitiesHandler.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

Correct fix to @flcl42 workaround hotfix https://github.com/NethermindEth/nethermind/pull/5787 
If Canun is not set in chainspec we won't send V3 methods
If Shanghai is not set in chainspec we won't send V2 methods etc
Let's be careful about gnosis because it will mean that we will use V1 for gnosis.
Before merging requires testing with gnosis nodes and one mainnet. I will do it after the reviews

Bugfix - exchangeCapabilites based on ChainSpec

---

.github/workflows/hive-consensus-tests.yml
.github/workflows/hive-tests.yml
tools/HiveConsensusWorkflowGenerator/Program.cs

- fix patching `Dockerfile` after recent changes in base hive repo
- adjust workflow generator
In the future it will be nice to drop current logic of creating docker and patching `Dockerfile` and start using recently added `Dockerfile.git` which makes possible to run hive directly from git branch. Added issue: https://github.com/NethermindEth/nethermind/issues/5807 
tested manually in git workflows, is working fine

Fix for hive workflows

---

.github/workflows/build-nethermind-docker-images.yml

- Build docker image with "master" tag on each commit (for tests usage)

Add a master build docker image for each commit on master branch

---

src/Nethermind/Nethermind.Merge.Plugin.Test/ChainSpecBasedSpecProviderTests.TheMerge.cs
src/Nethermind/Nethermind.Specs.Test/ChainParametersTests.cs
src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs

-fixed bugfix for EIP2537 activation
-added test that will control the list of properties in two classes

Fixed eip2537 activation

---

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
src/Nethermind/Nethermind.Core/Buffers/LargerArrayPool.cs
src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs
src/Nethermind/Nethermind.Evm.Benchmark/EvmStackBenchmarks.cs
src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs
src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs
src/Nethermind/Nethermind.Evm.Test/CmpTests.cs
src/Nethermind/Nethermind.Evm.Test/SimdTests.cs
src/Nethermind/Nethermind.Evm/ByteArrayExtensions.cs
src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
src/Nethermind/Nethermind.Evm/EvmStack.cs
src/Nethermind/Nethermind.Evm/EvmState.cs
src/Nethermind/Nethermind.Evm/IEvmMemory.cs
src/Nethermind/Nethermind.Evm/IVirtualMachine.cs
src/Nethermind/Nethermind.Evm/Metrics.cs
src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

As there are a large number of `CALL`/`DELEGATECALL`/`STATICCALL` per transaction and each call becomes both a call and call back the `ExecuteCall`/`Code` method is executed many times. On currently on entering the method it zeros 9136 bytes of stack.
Some blocks can make up to 4k+ calls meaning 8k+ method entries for these heavy blocks or 70MB. Also the method is 26.5kb of asm which reduces the Jits willingness to optimize and is a large code chunk for a hot loop.
e.g. in the example below 7 blocks execute 724 txs which calls ExecuteCall 10.5k times meaning 92MB of stack needs to be cleared
This change reduces to to 1328 bytes of stack or 78MB less in the example above; and reduced the hot loop from 26.5kB to 17.2kB so is more likely to be hotter in the CPU L1 execution cache (32KB - …

Reduce Evm Stackspace clearing

---

src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
src/Nethermind/Nethermind.Network.Stats/Model/NodeClientType.cs
src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloaderLimits.cs

- Add missing peer types to limit calcs

Add missing peer types to limits

---

src/Nethermind/Nethermind.Runner/NLog.config
src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs

- Don't use decimal percentages in peers report. Are only max 100 peers so going to decimal places doesn't add anything

Don't use decimal percentages in peers report

---

src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs

- Adjust some request threshold for snap request queuing.
- Reduces the amount no request to dispatch during snap sync, but sync time too inconsistent to know for sure if it affect anything.
- Increase storage queue size before skipping account range request.
- Check for high code queue first before dequeing not full storage queue.
- Slight refactor.
- Adjust threshold.
- Definitely can sync.

Adjust snap request threshold

---

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
src/Nethermind/Nethermind.Logging.NLog/NLogLogger.cs
src/Nethermind/Nethermind.Runner/NLog.config

- Use non wrapping timer
- Offload logging to background thread

Use better processing timer for logging

---

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
src/Nethermind/Nethermind.Runner/NLog.config

- Don't use DarkGray as doesn't show up on some systems

Don't use DarkGray

---

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs
src/Nethermind/Nethermind.Merge.Plugin/Data/ForkchoiceStateV1.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncReportTest.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs

- Better spacing. 
- Remove decimals on Blk/s. 
- Introduce block numbers in ForkChoice message.

Even more logging improvements. 

---

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs

- `readonly struct` ProcessingBranch should be passed via `in`

Pass ProcessingBranch via in

---

src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- Skip `.ToArray` for zeros as already have the array

Skip alloc for zero sstore

---

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PivotUpdator.cs

- decrease frequency of log `Potential new pivot block hash: {finalizedBlockHash}. Waiting for pivot block header. {_attemptsLeft} attempts left` to once per 10s instead of once per 1s
Other pivot-related log (`Waiting for Forkchoice message from Consensus Layer to set fresh pivot block. {_attemptsLeft} attempts left`) is already set to once per 10s. `Potential new pivot` is appearing for longer period of time only when there is a problem with peering, like recently on goerli network and in such scenario logs are a bit obfuscated. It's not really needed every second, so this PR is decreasing frequency

Decrease pivot logs frequency to once per 10s instead of per 1s

---

src/Nethermind/Directory.Packages.props

Since recent Nethermind versions don't work on macOS x64, this PR updates the RocksDB package that addresses dependency issues with bzip2 on that platform.
The RocksDB version has _not_ been changed.
I suggest this be included in the upcoming v1.20.0 release. And as a next step, upgrade to RocksDB v8.3.

Fix RocksDB dependency issues on macOS x64

---

src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs

**This PR is changing `MaxSizeOfTxForBroadcast` from 128KB (as initially proposed here https://eips.ethereum.org/EIPS/eip-5793#motivation) to 4KB (as recently changed in Geth https://github.com/ethereum/go-ethereum/pull/27618)**
- after adding tx to TxPool, tx hash is collected
- every 1s we are sending tx hashes collected in last 1s to all peers (announcing transactions)
- announcing (sending tx hash) to all peers just after adding it to the TxPool or to persistentTxs pool
- after processing of every block (so on mainnet every ~12s) reannouncing top 5% of local txs, after ensuring that `MaxFeePerGas >= current basefee`
- broadcasting (sending full tx) to all peers just after adding it to the TxPool or to persistentTxs pool
- after processing of every block (so on mainnet every ~12s) …

Decrease `MaxSizeOfTxForBroadcast` from 128KB to 4KB

---

src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs

#5700 
During file update client might be terminated, so last line might be broken.
- Do not throw on malformed data

Ignore last broken line in FileDb

---

src/Nethermind/Nethermind.Core.Test/Encoding/ShardBlobTxDecoderTests.cs
src/Nethermind/Nethermind.Core/Transaction.cs
src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs
src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
src/Nethermind/Nethermind.TxPool/NetworkTransactionSizeCalculator.cs
src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs

- fix calculating length of blob-type transactions
Without `RlpBehaviors.InMempoolForm` in `GetLength` of `ITransactionSizeCalculator` actual blobs were not included in calculation of tx size.
While calculating content length we were not entering here:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs#L724-L732
Which caused not adding size of actual blobs:
https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs#L677-L684
And it causes, that we are sending huge messages on 4844 devnets which are rejected by peers (e.g. `PooledTransactionsMessage` with size 147x bigger than expected and 19x bigger than biggest possible 6-blob tx). Also our …

Fix length calculations of blob-type txs

---

src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
src/Nethermind/Nethermind.Evm/EvmStack.cs
src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs
src/Nethermind/Nethermind.Evm/ZeroPaddedSpan.cs

- Unconditionally reduce gas and then check if out of gas at end of loop to reduce method size
- Skip unnecessary conversions to `UInt256` and operations on that type when can be done on smaller native type (e.g. `ulong`)
- Faster `Vector256` clears rather than `Span`.`Slice`.`Clear()`

Evm optimisations

---

src/Nethermind/Nethermind.Core/Buffers/LargerArrayPool.cs

- Use `AllocateUninitializedArray` for `LargerArrayPool`; the array is cleared after rent anyway so don't need to double clear

Use AllocateUninitializedArray for LargerArrayPool

---

src/Nethermind/Nethermind.Evm.Test/Tracing/ParityLikeTxTracerTests.cs
src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs

#5456 
Not sure that it should work this way. But it matches erigons behavior 
- Do not count precompile calls in subtraces

Do not count precompile calls

---

src/Nethermind/Nethermind.Evm.Test/Eip1052Tests.cs
src/Nethermind/Nethermind.Evm.Test/Eip1108Tests.cs
src/Nethermind/Nethermind.Evm.Test/Eip152Tests.cs
src/Nethermind/Nethermind.Evm.Test/Tracing/ParityLikeTxTracerTests.cs
src/Nethermind/Nethermind.Evm/Precompiles/Blake2FPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1AddPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MulPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MultiExpPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2AddPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MulPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MultiExpPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapToG1Precompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapToG2Precompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Bls/PairingPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/EcRecoverPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/IPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/IdentityPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompilePreEip2565.cs
src/Nethermind/Nethermind.Evm/Precompiles/PointEvaluationPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Ripemd160Precompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Sha256Precompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Snarks/Bn254AddPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Snarks/Bn254MulPrecompile.cs
src/Nethermind/Nethermind.Evm/Precompiles/Snarks/Bn254PairingPrecompile.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- changed Precompile.Address from an instance property to be static

Made precompile address property static

---

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs

Fixed tests assumptions about the size of goerli chain

Fix goerli state db size assumptions

---

src/Nethermind/Nethermind.Evm.Test/BytecodeBuilderExtensionsTests.cs
src/Nethermind/Nethermind.Evm.Test/GasPriceExtractorTests.cs
src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs
src/Nethermind/Nethermind.Evm.Test/Keccak256Tests.cs
src/Nethermind/Nethermind.Evm.Test/Sha3Tests.cs
src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs
src/Nethermind/Nethermind.Evm/Instruction.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

- Align with other clients with regards to opcode 0x20 naming : SHA3 -> KECCAK256

Rename SHA3 opcode to KECCAK256

---

scripts/deployment/debian/control

Fixes #4959 
- Adds "arm64" as architecture in the debian control file, used when building on PPA. 
I've build the package locally using debuild, although I'm not sure if this is the right way to properly test it. I already enabled arm64 support on Launchpad side, but the latest build was only available on amd64. I am assuming it's because of this missing architecture. 
More info is here: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-architecture -> 5.6.8. Architecture

Add arm64 as arch for ppa

---

src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs
src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/BoundedModulePoolTests.cs
src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStorePlugin.cs
src/Nethermind/Nethermind.JsonRpc/Exceptions/LimitExceededException.cs
src/Nethermind/Nethermind.JsonRpc/Exceptions/ModuleRentalTimeoutException.cs
src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
src/Nethermind/Nethermind.JsonRpc/Modules/BoundedModulePool.cs
src/Nethermind/Nethermind.JsonRpc/Modules/IRpcModuleProviderExtensions.cs
src/Nethermind/Nethermind.Mev/MevPlugin.cs
src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs

With spam testing
**Before change:**
Requests per second: 100
Requests sent in total: 100000
Succeeded requests: 4818
Failed requests: **95182**
**After the change:**
Requests per second: 100
Requests sent in total: 100000
Succeeded requests: 57566
Failed requests: **42434**
- [] New feature (a non-breaking change that adds functionality)
We did load testing with eth_call and testing on gateway infra
Auto-updated with a new config parameter. However, would be great to introduce articles Nethermind for RPC Providers
ToDo...

Throttle Eth_ module queue

---

src/Nethermind/Nethermind.Merge.Plugin/IMergeConfig.cs
src/Nethermind/Nethermind.Merge.Plugin/MergeConfig.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs

Solves: #5951
Add option to manipulate timeout for newPayload - needed for Block Processing tests in case of some blocks being processed slower than expected. 
- _Add new flag --Merge.NewPayloadTimeout_
_New parameter which allows to manipulate maximum time to process `engine_newPayload` requests. 
Current default value is 7 seconds.
Usage example: 
`--Merge.NewPayloadTimeout=10` _

Add NewPayload timoeut based on config

---

src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationSimulator.cs
src/Nethermind/Nethermind.Evm.Test/Tracing/GasEstimationTests.cs
src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs

Fixes #5706
- Change Gas estimation algorithm for more consistent results
Some tests were updated to reflect the behavior changes.
The code for Gas estimation is still very complex compared to the competition (see `go-ethereum` implementation: https://github.com/ethereum/go-ethereum/blob/2274a03e339f213361453590b54917bbfd0a0c31/internal/ethapi/api.go#L1137). A refactor would be highly suggested.

Fix gas estimations

---

src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs

- Return "Invalid params" instead of "Internal error" when `object invocationResult = method.Info.Invoke(rpcModule, parameters);`(above) breaks on null root parameter

Return "Invalid params" when root paramter is absent

---

src/Nethermind/Nethermind.Evm.Test/Eip6780Tests.cs
src/Nethermind/Nethermind.Evm/VirtualMachine.cs

context here:
https://github.com/ethereum/EIPs/pull/7308
- disable eth burn on preexisting contract when inheritor equals contract address for cancun

[cancun] [eip6780] apply danno's clarification: disable eth burn on preexisting contract when inheritor equals contract address

---

src/Nethermind/Directory.Packages.props
src/Nethermind/Nethermind.Precompiles.Benchmark/PointEvaluationBenchmark.cs

The Point Evaluation precompile (eip-4844) benchmarks require Ckzg being initialized before run
The performance is good in comparison with other implementations ( https://github.com/imapp-pl/benchmarking/tree/precompiles_benchmark/shanghai#client-comparison )
```markdown
|   Method |            Input |       Mean |   Error |  StdDev | Ratio | Alloc Ratio |
|--------- |----------------- |-----------:|--------:|--------:|------:|------------:|
| Baseline |      fuzzcorp-33 |   109.7 us | 1.23 us | 2.93 us |  1.00 |        1.00 |
|          |                  |            |         |         |       |             |
| Baseline |      fuzzcorp-95 |   109.5 us | 0.77 us | 1.17 us |  1.00 |        1.00 |
|          |                  |            |         |         |       |             |
| …
```

Add initialization; use latest Ckzg version

---

src/Nethermind/Nethermind.TxPool.Test/TxBroadcasterTests.cs
src/Nethermind/Nethermind.TxPool/ITxPoolConfig.cs
src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs

- Right now we are rebroadcasting only one tx per sender per block, which has perfect sense with low `PeerNotificationThreshold` (e.g. default value: 5), but doesn't have sense if someone wants to rebroadcast all persistent transactions. This PR is changing source of persistent transactions from `_persistentTxs.GetFirsts()` (one per sender) to `_persistentTxs.GetSnapshot()` (all) if `PeerNotificationThreshold` is set to 100

Rebroadcast all persistent txs if PeerNotificationThreshold is 100

---

src/Nethermind/Nethermind.Facade/BlockchainBridge.cs

In estimateGas we can use Timestamp opcode. The better estimates we will get once timestamp opcode will give us currentBlock.Timestamp + SecondsPerSlot. 
**Requires unit tests and testing. Draft to open discussion.**
In progress.

SecondsPerSlot in eth_estimateGas

---

Dockerfile
Dockerfile.dev
scripts/deployment/build-runner.sh

Added symlinks for Docker files and macOS to support the old `Nethermind.Runner` name
This is an improvement for the Nethermind executable rename introduced in #5908 and addresses the cases where users use the old entrypoint when deriving from Nethermind Docker file.

Improve Nethermind executable rename handling

---

src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs
src/Nethermind/Nethermind.Synchronization/Synchronizer.cs

- As @kamilchodola found, 5 second wait time is not enough on slower node. So increasing the default to 60 second.
- Also useful for testing where we can wait like 15 minute after sync to check block processing time.
- Also useful for testing where a synced node will automatically shutdown after the wait time. 
- Expose wait time after sync finished.
- Seems to work.

Expose wait duration to config

---

src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/SyncStatusListTests.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs

- OldBodies and OldReceipts seems to download beyond ancient barrier.
- It will stop eventually after the barrier bodies/receipts is saved, but before that other blocks can be saved causing unexpected ethgetlogs and such.
- Add a lower bound to SyncStatusList.
- Confirms old blocks and receipts now missing cleanly beyond ancient barrier.

Fix old blocks downloaded beyond old barrier

---

src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs

- When a header sync batch is deemed invalid, it is retried by adding to a `_pending` queue.
- In another thread, the pending batch may get dequeue and sent out which involve adding it to a `_sent` set.
- However, the processing of the invalid block, may remove back the batch from `_sent` after adding it to `_pending` queue, causing the batch to be unrecognized and missed. 
- Remove batch from `_sent` before processing it.
- Tested by adding a 1% random failure in `InsertHeader`. 
- Unit tests can reliably hang also.

Fix fast header may miss a retried batch

---

src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs
src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
src/Nethermind/Nethermind.Network.Discovery/NettyDiscoveryHandler.cs
src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs
src/Nethermind/Nethermind.Network/PeerManager.cs

Addresses #6014
- ~~On one of the log @kamilchodola gave, the peer loop exited very early without any exception.~~ mistake in task handling causes it to not wait for worker thread exit, but not a problem.
- ~~There is a mistake in the tasks handling which hide the exception probably.~~
- ~~This fixes it and make sure it does not stop trying on exception.~~
- Discovery thread does not seems to start after initial bootnodes connection.
- Seems like task scheduler from dotnetty, maybe hanging.
- Switching to explicitly running default task scheduler.
- Fix connection loop exception accidentally hidden.
- Well, nothing bad happened for sure.

Dont stop peer connection on any exception

---

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
src/Nethermind/Nethermind.Network.Discovery.Test/NodeSourceToDiscV4Feeder.cs
src/Nethermind/Nethermind.Network.Discovery/EnrToDiscv4Feeder.cs
src/Nethermind/Nethermind.Network.Discovery/NodeSourceToDiscV4Feeder.cs
src/Nethermind/Nethermind.Network/Config/INetworkConfig.cs
src/Nethermind/Nethermind.Network/Config/NetworkConfig.cs

- On goerli, all the bootnodes does not response for some reason.
- To compensate for that, this adds a code that feeds nodes from DNS discovery to disv4 to somewhat seed it.
- Unlike with disv4, entry from dns may be offline (disv4 wait for Pong message).
- This seems to cause some noise, so it limit the number of added record to 50. The amount does not strictly matter much, it just need one node that can respond.
- Seed discv4 with dns.

Feature/feed DNS to discv4

---

src/Nethermind/Nethermind.GitBook/RpcAndCliDataProvider.cs

- auto docs generation is broken after recent changes in naming (`Nethermind.Cli` => `nethermind-cli`). This PR is fixing it.

Adjust name of cli assembly in docs generator

---

.github/workflows/run-a-single-node-from-branch.yml

- Do not build master image if default config is used since this one is being built after each commit merged to master branch
Tested on this run when `kch/optimize_oneClick` was also added to the check next to master branch - as expected it skipped two steps for triggering and waiting for docker image to be done
https://github.com/NethermindEth/nethermind/actions/runs/6089715555
Tested on this run where only master branch was checked (final version) - as expected it triggers build since it was triggered from `kch/optimize_oneClick` branch:
https://github.com/NethermindEth/nethermind/actions/runs/6089729660

Skip docker image creation if default master is used

---

src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PivotUpdator.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/ISyncProgressResolver.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncProgressResolver.cs

Fixes #6053
- update barriers in receipt and bodies sync feeds when initialized if pivot has updated.
- update barriers in `SyncProgressResolver`
- [Fix] bug with PivotUpdator not updating barriers

[Fix][PivotUpdator] Update receipts and bodies Barriers

---

src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorFastSyncTests.cs
src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorTests.Scenario.cs
src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs

- Fixes random `Unable to find beacon header at height 18051001. This is unexpected, forcing a new beacon sync.` and `Peer sent orphaned blocks/headers inside the batch`.
- When `BlockTree.AcceptVisitor` take too long (I don't know how @kamilchodola did that), `DbLoad` in MSMS will get activated and pivot updater will get deactivated and disabled. This causes it to not update sync pivot. On restart, the pivot updated will reactivate and set a different sync pivot, but blocktree already initialized various pointers with respect to old pivot causing forward sync to start from before the sync pivot which causes the errors.
- Step to reproduce:
- Make sure CL is synced.
- Add `Thread.Sleep(1000)` in `ReviewBlockTree` around line 67.
- Add `Thread.Sleep(1000)` in `BlockTree.AcceptVisitor` …

Fix sync pivot not set when dbload

---

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs

`Update_known_chain_sizes` is failing on master, which blocks PR merging to master.
- Increase boundary prunning size value for the `Update_known_chain_sizes` test
- (Temporary) Fix for a unit test

Tests: Bump pruning size value for unit test

---

src/Nethermind/Nethermind.Blockchain/BeaconBlockRoot/BeaconBlockRootHandler.cs

- Update address and buffer size 

Eip4788 : Update address and buffer size (Post audit)

---

src/Nethermind/Nethermind.Runner/Logging/NLogConfigurator.cs

Fixes #6017
- Do not change the log levels of `JsonWebAPI*` rules.
Tested on VM using with and without the `--log info` flag.
Passing `--log info` as a argument results in the same logging settings as not passing any argument.

Remove HTTP log spam on default settings

---

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs

- Make tests related to WebSockets explicit
Tests that rely on WebSockets are marked as explicit due to issues running them on CI.

Make flaky tests explicit for `JsonRpc.Test`

---

src/Nethermind/Nethermind.Runner/Logging/NLogConfigurator.cs

Fixes #6017
- Don't override `HealthCheckService` log levels
Similar to #6097. We missed an extra rule related to JSON Web API Health Checks, so we're adding it here.

Don't override `HealthCheckService` log levels

---

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs

Fixes #5805
- Fail with `InvalidParams` when deserializing non-nullable aggregate types (ex. Arrays and Objects).
Tested the provided example in the referenced ticket.

Reject non-nullable aggregate types when deserializing method parameters

---

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs

- awaits the task instead of Task.Result to unpack exception

fix AggregateException being thrown instead of TimeoutException

---

src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs

- Changes default value for TuneDb to HeavyWrite which significantly improves sync speed
No need for new tests
Setting is hidden so no need to post about it in Release Notes.
Will mention it on release that it is now adjusted and sync speed improved significantly.

Change TuneDb default to HeavyWrite

---

scripts/deployment/debian/postinst
scripts/execution.sh

- Fixed the PPA package post-install script to download resources from the latest release branch instead of the main one.
- Replaced `wget` with `curl`
- Optimized `jq` queries
**To be merged right before the release of #5908**
Tested manually as a standalone shell script but not in the context of PPA.

Fix PPA package post-install script

---

src/Nethermind/Directory.Packages.props
src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs

- Fixes native library loading when running the client locally via `dotnet run ` with Cancun fork activated. The fixing change [is in the dependency](https://github.com/ethereum/c-kzg-4844/pull/372/files#diff-493080fc005224379f2b7325c47ddc03489ac459ba67b9d55f7c761edc3eb5c7R33).
Requires Cancun

Load ckzg properly

---

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs

- Expose file size base and file size multiplier, and specify default for statedb and receipts db.
- Adjust blobfile parameter to reduce number of file.
- Reduce number of file from about 16000 to 6000.
- Does not seems to affect write amp much.
- Set multiplier for statedb to 2.
- Set file size base for receipts db to 256MB.
- Increase write buffer size during 
- Verified with `find | wc` and rocksdb's stat.

Perf/Reduce number of files in DB.

---

src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/AuthEip8MessageSerializerTests.cs
src/Nethermind/Nethermind.Network/Rlpx/Handshake/AuthEip8MessageSerializer.cs
src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs

Resolves #6116
- Fix auth message decode throws an exception when attempting to decode auth message with string version.
- Fix sometimes the auth payload is not complete.
- Tested with fuzzer.
- Node, when using fuzzer, the second try that use the same connection will disconnect the connection due to invalid header mac. Which IFAIK is expected.

Fix unable to decode auth message with invalid version

---

src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/NettyHandshakeHandlerTests.cs
src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs

- When the exception handler did not explicitly handle the exception, the exception will pass down to the next handler, which if its the tail, it'll do nothing.
- This add an explicit disconnect on exception.
- Also fix the method itself throwing exception.
- Add explicit disconnect on `ExceptionCaught`
- Wrap trying to get client id string so that on exception, it does nothing.
- Verified with a custom spammer.

Fix on handshake failure not disconnecting connection

---

src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs

- #6143 broke engine RPC as plugin RPC module sometimes does not load.
- Its unclear why its only sometimes.
- Failing engine hive test was added yesterday.

Fix engine hive tests not working

---

src/Nethermind/Chains/chiado.json
src/Nethermind/Chains/gnosis.json
src/Nethermind/Nethermind.Blockchain.Test/TransactionSelectorTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Validators/ShardBlobBlockValidatorTests.cs
src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs
src/Nethermind/Nethermind.Core/Eip4844Constants.cs
src/Nethermind/Nethermind.Evm.Test/BlobGasCalculatorTests.cs
src/Nethermind/Nethermind.Evm.Test/TransactionProcessorEip4844Tests.cs
src/Nethermind/Nethermind.Evm/BlobGasCalculator.cs
src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs
tools/SendBlobs/BlobSender.cs

- Made the following EIP-4844 parameters configurable with chain spec:
- `BLOB_GASPRICE_UPDATE_FRACTION` 
- `MAX_BLOB_GAS_PER_BLOCK`
- `MIN_BLOB_GASPRICE`
- `TARGET_BLOB_GAS_PER_BLOCK`
The default EIP-4844 parameters can be overridden by defining them in a chain spec file (e.g., `gnosis.json`). Otherwise, the hardcoded defaults are used.
- Refactored some parameter names to match the ones in EIP-4844.

Make EIP-4844 parameters configurable

---

src/Nethermind/Nethermind.Runner/NLog.config

- Log logger name in log file.
- Make it way easier to grep the logs. 
Before
```
2023-10-21 12:16:14.8844|INFO|20|Setting state sync state root to 151268 0xf7999ca8b9174056b0a3a03ceba2408935ce6891acc880dae279114576c35576
2023-10-21 12:16:14.8844|INFO|20|Now syncing nodes starting from root of block 151268
```
After
```
2023-10-21 17:23:22.2584|INFO|Network.Discovery.DiscoveryApp|209|Connected to 2 bootnodes, 5 trusted/persisted nodes 
2023-10-21 17:23:26.3520|INFO|Merge.Plugin.MergePlugin|16|Engine Module has been enabled 
```
- Tested manually

Log logger name

---

src/Nethermind/Nethermind.Config/ExitCodes.cs
src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
src/Nethermind/Nethermind.Runner/Program.cs

- Long overdue fix on incorrect exit code on sigterm/sigint.
- On POSIX, when given SIGTERM/SIGINT, the application should exit with a specific exit code instead of 0.
- Without this, a script may not behave as expected. For example, if I have a script something like this, which sync, then remove the directory then sync again, on the first nethermind run, when I ctrl-c, I would expect it to stop the whole script. Instead, it remove the directory and start the second run.
```
nethermind --Sync.ExitOnSynced true
rm -rf thedir
nethermind --Sync.ExitOnSynced true
```
- Return proper exit code.
- Also consolidate the various exit signal.
- On linux SIGTERM: :heavy_check_mark: 
- On linux SIGINT: :heavy_check_mark: 
- On mac SIGTERM: ✔️ 
- On windows: :heavy_check_mark: 
- Exit after sync …

Fix incorrect exitcode in SIGTERM and SIGINT.

---

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs

- It turns out, holesky's state sync hang due to unable to write to DB. Errors at statedb log is:
```
2023/10/24-13:56:58.071176 164930 [WARN] [db/column_family.cc:933] [default] Stopping writes because we have 0 immutable memtables (waiting for flush), max_write_buffer_number is set to 0
```
- It turns out, max write buffer was set to 0. This likely works fine during snap sync as the default heavy write tune temporarily set a high max write buffer number, but during state sync, it would revert back to 0.
- Normally, memoryhintman would set the value. However, holesky does not have memory hint applied so the default value of 0 was used, causing the hang.
- This PR set a default value of 4, and throw errors if it detect that it was configured to 0.
- Set default max write buffer num to 4. …

Fix max write buffer number is 0 on holesky.

---

src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs
src/Nethermind/Nethermind.Core.Test/Builders/BlockTreeBuilder.cs
src/Nethermind/Nethermind.Core/BlockInfo.cs
src/Nethermind/Nethermind.Core/ChainLevelInfo.cs
src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs

Fixes #6183
- Preserve the `processed` status of blocks
- Added test case to reproduce the issue as seen in Holesky
- Tested against real Holesky in a VM.
Very tricky bug, a full breakdown is available as discussion.

Fix Holesky crash on restart

---

src/Nethermind/Nethermind.Blockchain.Test/Blocks/BlockStoreTests.cs
src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Blockchain/Blocks/BlockStore.cs
src/Nethermind/Nethermind.Blockchain/Blocks/IBlockStore.cs
src/Nethermind/Nethermind.Blockchain/IBlockTree.cs
src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs
src/Nethermind/Nethermind.Core.Test/TestMemDb.cs
src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rpc/RpcDb.cs
src/Nethermind/Nethermind.Db/DbExtensions.cs
src/Nethermind/Nethermind.Db/IDbWithSpan.cs
src/Nethermind/Nethermind.Db/MemDb.cs
src/Nethermind/Nethermind.Db/ReadOnlyDb.cs
src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/BodiesSyncFeedTests.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/Synchronizer.cs

- Most of the write IO during old bodies are actually due to WAL (Write Ahead Log) file, which is the mechanism for which rocksdb recover on unclean shutdown.
- This PR disable WAL writes for bodies writes from OldBodies.
- For recovery, the LowestInsertedBlockNumber is not updated on all request, instead it is updated every 100000 blocks, at which point an explicit flush is also triggered to make sure the memtables are written at that point.
- This reduces total writes during OldBodies by about 60-70% or so. This is more than 50% because the WAL file are not compressed and the bodies are compressed to about 60-70% on flush.
- No change in bodies sync time. Unless your SSD can't sustain about 350MB/s of writes before and you have really fast internet.
- Graph is after, before, after, …

Perf/NoWAL during OldBodies

---

src/Nethermind/Nethermind.Core.Test/TestMemDb.cs
src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/BodiesSyncFeedTests.cs
src/Nethermind/Nethermind.Synchronization.Test/ReceiptSyncFeedTests.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs

- I was trying to find a solution to the situation where *netty memory pool grew when block insert slow down which causes high memory pressure which slows down block insert* when I found out that if block insert failed due to OOM even temporarily, old bodies will get stuck.
- This make sure to re-mark all block and receipt for download as pending on failure.
- Make sure to mark block info as pending on failure.
- Tested by randomly throwing exception in blockstore.

Fix old blocks hang on insert failure

---

src/Nethermind/Nethermind.Facade.Test/Eth/EthSyncingInfoTests.cs
src/Nethermind/Nethermind.Facade/Eth/EthSyncingInfo.cs

Fixes #6153
- Fix edge case where `eth_syncing` never returned false given that receipts were never downloaded.
Tested on a VM running Holesky with the current default config (https://github.com/NethermindEth/nethermind/blob/9c40c81de03a3f9d4f4f5e10cf93eef767f71071/src/Nethermind/Nethermind.Runner/configs/holesky.cfg) and with `PivotNumber: 100`
The justification as to why this fixes the issue is complex and more details will be provided as part of the discussion on this PR.

Fix `eth_syncing` in young chains

---

src/Nethermind/Nethermind.Blockchain.Test/TestEip4844Config.cs
src/Nethermind/Nethermind.Blockchain.Test/TransactionSelectorTests.cs
src/Nethermind/Nethermind.Blockchain.Test/TxPoolSourceTests.cs
src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
src/Nethermind/Nethermind.Consensus/Transactions/SinglePendingTxSelector.cs
src/Nethermind/Nethermind.Core/Eip4844Constants.cs
src/Nethermind/Nethermind.Core/IEip4844Config.cs
src/Nethermind/Nethermind.TxPool/LightTransaction.cs

All blob calculations should use blob gas and do not rely on max blob count to be consistent
- Use blob gas instead of count

Use blob gas instead of count

---

src/Nethermind/Nethermind.AuRa.Test/AuRaBlockProducerTests.cs
src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs
src/Nethermind/Nethermind.Blockchain/SpecificBlockReadOnlyStateProvider.cs
src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs
src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
src/Nethermind/Nethermind.Mev/MevRpcModule.cs
src/Nethermind/Nethermind.State/IReadOnlyStateProvider.cs
src/Nethermind/Nethermind.State/IStateReader.cs
src/Nethermind/Nethermind.State/StateReader.cs
src/Nethermind/Nethermind.State/StateReaderExtensions.cs
src/Nethermind/Nethermind.State/WorldState.cs

We use the RootCheckVisitor to check if we have state for a particular state root. But this will not be the case with pathBased layout, we can directly maintain a list of stateRoot that we have at hand.
So moving the underlying logic to the stateReader and worldState would be a better idea.
- add bool HashStateForRoot(Hash256) to IStateReader and IReadOnlyStateProvider 

move the state root checking mechanism to the stateReader/worldState

---

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/DiskFreeSpacePruningTriggerTests.cs
src/Nethermind/Nethermind.Blockchain/FullPruning/DiskFreeSpacePruningTrigger.cs

Fixes #6258, #5738
- Do not use `PathRoot` to find the proper drive.
Tested on a Fedora 38 machine (Linux) using the real filesystem with 3 drives.
Our tests mock the real filesystem (using `IFilesystem` and `NSubstitute`) so we cannot actually be sure that we're picking the appropriate drives.
On my machine, I could verify that the proper drive was being picked up with the following test:
```C#
// It would be great if we could verify that we're picking the correct drives on Windows too:
// [TestCase(@"C:\")]
// [TestCase(@"D:\")]
[TestCase("/home/emlautarom1")]
[TestCase("/run/media/emlautarom1/Toshiba")]
[TestCase("/run/media/emlautarom1/EC8AEBDD8AEBA1F6")]
public void triggers_target_the_proper_drive(string path)
{
IFileSystem fs = new FileSystem();
string driveName = …
```

Select proper drive when using `VolumeFreeSpace` trigger

---

src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadBodiesByHashV1Handler.cs
src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadBodiesByRangeV1Handler.cs

- Use full enumerator rather than building List for block bodies

Reduce memory for GetPayloadBodiesByRangeV1 and GetPayloadBodiesByHashV1

---

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs

- `DbOnTheRocks.GetSize()` takes RocksDB's blob storage into account via [the corresponding metric](https://github.com/facebook/rocksdb/blob/9202db1867e412e51e72fc04062ca3664deb097b/include/rocksdb/db.h#L1248-L1250)
Mainnet blocks database has the correct value in the Grafana dashboard

fix(db, rocks): total table size should include blobs

---

src/Nethermind/Nethermind.AuRa.Test/AuRaBlockProducerTests.cs
src/Nethermind/Nethermind.Synchronization.Test/ExitOnSyncCompleteTests.cs

Fixes #6291
concurrency issue where `processedEvent.Set` happens after `ClearReceivedCalls`
Before the fix I could reproduce the issue within 50 attempts
Screenshot after fix:
`TestWillExit` could reproduce the issue easily as well.
Screenshot After fix:
- delay after `ClearReceivedCalls`
- delay between the event raising in `TestWillExit`

Fix flaky tests `Can_produce_first_block_when_private_chains_allowed` and `TestWillExit`

---

src/Nethermind/Nethermind.Optimism/IOptimismEngineRpcModule.cs
src/Nethermind/Nethermind.Optimism/OptimismEngineRpcModule.cs
src/Nethermind/Nethermind.Runner/configs/base-mainnet.cfg

Latest version of op node calls V2 engine methods instead of V1
- Migrate to V2
- Fix base config

Fix base config & migrate op to V2 methods

---

src/Nethermind/Nethermind.Init/Steps/ReviewBlockTree.cs

Right now because of in-memory pruning, after client restarts there is a gap between the last state root from which we have state in the database and the latest processed block (for which we should have state) according to block tree. This gap is fixed at startup by reviewing the block tree and reprocessing the blocks in the gap, however if networking or synchronization are disabled in config this reprocessing won't happen, causing issues later in the pipeline because of missing state.
- Reprocess blocks in the gap regardless of whether synchronization/networking are enabled or not.

Remove syncing check from ReviewBlockTree step

---

src/Nethermind/Nethermind.Evm/Tracing/GethStyle/JavaScript/Context.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/JavaScript/Engine.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/JavaScript/JavaScriptConverter.cs

Initially Geth had some different types used, they unified them after our feedback here: https://github.com/ethereum/go-ethereum/pull/28488 this makes same changes in Nethermind.
Run some smoke test comparisions

Unify js types, use typed arrays everywhere + long for slice parameters

---

src/Nethermind/Nethermind.Runner/configs/base-goerli.cfg
src/Nethermind/Nethermind.Runner/configs/base-mainnet.cfg
src/Nethermind/Nethermind.Runner/configs/op-goerli.cfg
src/Nethermind/Nethermind.Runner/configs/op-mainnet.cfg

- Disables networking and synchronization in OpStack chains
P2P Networking is now disabled by default in OP Stack configs.

Disable networking on OpStack configs

---

src/Nethermind/Nethermind.Core.Test/RateLimiterTests.cs
src/Nethermind/Nethermind.Core/RateLimiter.cs
src/Nethermind/Nethermind.Network.Discovery.Test/DiscoveryManagerTests.cs

- Fix excessive timer allocation in RateLimiter
Before left (more allocations than `byte[]`) After right

Fix excessive timer allocation in rate limiter

---

src/Nethermind/Nethermind.Crypto/AesEngineX86Intrinsic.cs
src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
src/Nethermind/Nethermind.Db.Rocks/Statistics/DbMetricsUpdater.cs
src/Nethermind/Nethermind.Db.Test/DbMetricsUpdaterTests.cs
src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs

fix some typos in comment && replaced in all doc

fix: typos in comment

---

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
src/Nethermind/Nethermind.Serialization.Json/EthereumJsonSerializer.cs
src/Nethermind/Nethermind.Serialization.Json/IJsonSerializer.cs
src/Nethermind/Nethermind.Serialization.Json/StreamPipeWriter.cs

- Serialize Json direct to Kestrel's Http `PipeWriter` rather than intermediary buffer and then flush
- Switch off `AllowSynchronousIO` as no longer needed

Serialize Json direct to Http PipeWriter

---

src/Nethermind/Nethermind.Cli/Modules/CliModuleLoader.cs
src/Nethermind/Nethermind.Cli/NodeManager.cs
src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs
src/Nethermind/Nethermind.Consensus.Ethash/HintBasedCache.cs
src/Nethermind/Nethermind.Core/Collections/LinkedHashSet.cs
src/Nethermind/Nethermind.Core/Resettables/ResettableDictionary.cs
src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs
src/Nethermind/Nethermind.Network/P2P/Session.cs
src/Nethermind/Nethermind.Overseer.Test/Framework/TestBuilder.cs
src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
src/Nethermind/Nethermind.State/Proofs/AccountProofCollector.cs
src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
src/Nethermind/Nethermind.Wallet/DevKeyStoreWallet.cs
src/Nethermind/Nethermind.Wallet/DevWallet.cs

- Use `TryGetValue` rather than guard with `Contains` and then a lookup of value
- Or `CollectionsMarshal.GetValueRefOrAddDefault` when appropriate

Use TryGetValue to halve Dictionary lookups

---

src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs
src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
src/Nethermind/Nethermind.State/StateProvider.cs

- Use return value from first lookup rather than looking up each time

Reduce ResettableDictionary lookups

---

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs

- Apply max responseBodySize the same way as pre Json changes (check size increases inside the enumerator loop)

Apply max responseBodySize correctly

---

src/Nethermind/Directory.Packages.props
src/Nethermind/Nethermind.Core/Nethermind.Core.csproj
src/Nethermind/Nethermind.Core/Resettables/RecyclableStream.cs
src/Nethermind/Nethermind.JsonRpc.TraceStore/ParityLikeTraceSerializer.cs
src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs
src/Nethermind/Nethermind.KeyStore/AesEncrypter.cs
src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs

- RecyclableMemoryStream for MemoryStreams

Use RecyclableMemoryStream for MemoryStreams

---

src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs

- Follow up to https://github.com/NethermindEth/nethermind/pull/6371 to dispose the Stream on completion of PipeReader and reduce the usings(try/finally) by one

Use leaveOpen: false on StreamPipeReaderOptions

---

src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs

Fixes hive test "Pre-Merge Fork Number > 0 (Shanghai)"
- Prioritize timestamp forks if block timestamp is bigger than the first timestamp-based fork value
- So it fixes corner case when timestamp matches some timestamp fork and block number is exact number of block number only fork

Properly activate timestamp fork

---

src/Nethermind/Nethermind.ReferenceAssemblies/Nethermind.ReferenceAssemblies.csproj

Fixed Nethermind.ReferenceAssemblies package path modified during .NET 8 migration.

Fix reference assemblies package path

---

.github/workflows/sync-testnets.yml

Change from `docker compose up -d` to `sedge run` so image is pulled properly.

Add extra docker compose pull to ensure latest image

---

src/Nethermind/Nethermind.Runner/Program.cs

- Many regexes are used for logging; prometheus etc however the default cache size is only 10 which leads to Regex objects being constantly created as shown in this trace for Gnosis.
- Increase cache size for 10 to 128 to stop this allocation
Before
After this path doesn't show up

Increase regex cache size

---

src/Nethermind/Nethermind.Core.Test/Json/DoubleArrayConverterTests.cs
src/Nethermind/Nethermind.Serialization.Json/DoubleConverter.cs

- Fix unbounded memory growth in DoubleArrayConverter by moving on the reader after reading each element

Fix unbounded memory growth in DoubleArrayConverter

---

src/Nethermind/Nethermind.Core.Test/RateLimiterTests.cs
src/Nethermind/Nethermind.Core/RateLimiter.cs

- Can just return Task from Task.Delay directly rather than awaiting it

RateLimiter: Remove unneeded async statemachine

---

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/CopyTreeVisitorTests.cs
src/Nethermind/Nethermind.Blockchain/FullPruning/CopyTreeVisitor.cs
src/Nethermind/Nethermind.Core/IKeyValueStore.cs
src/Nethermind/Nethermind.Db.Test/FullPruning/FullPruningDbTests.cs
src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs
src/Nethermind/Nethermind.Trie/ITreeVisitor.cs
src/Nethermind/Nethermind.Trie/PatriciaTree.cs

- Not sure when do this happen, but it turns out, during full pruning, and in memory pruning at the same time, all read is duplicated causing duplicated writes.
- This add a flag to skip it if the read come from CopyTreeVisitor.
- Seems to increase maximum throughput 5x.
- Add a flag `SkipDuplicateRead`.
- Pass it.
- Full pruning completed successfully

Fix double write during full pruning

---

src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs

Resolves #6375
- Removes the second call to txPool for `eth_getTransactionByHash` as it has already been checked

Remove Duplicate call to TryGetPendingTransaction in RPC

---

src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
src/Nethermind/Nethermind.Specs.Test/CustomSpecProvider.cs
src/Nethermind/Nethermind.Specs.Test/CustomSpecProviderTests.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/SpecProviderBase.cs
src/Nethermind/Nethermind.Specs/ChainSpecStyle/SpecProviderExtensions.cs

- block and timestamp forks are fully separated
- `ChainSpecBasedProvider` and `CustomSpecProvider` now share transition loading and `GetSpec` logic

Fully separate block forks from timtestamp ones

---

src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
src/Nethermind/Nethermind.Facade/Filters/ILogFinder.cs
src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs
src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs
src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs

Resolves #6410
- Remove duplicate calls to FindHeader in eth_getLogs; as they have previously been found

Remove duplicate calls to FindHeader in eth_getLogs

---

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
src/Nethermind/Nethermind.Blockchain/Headers/HeaderStore.cs
src/Nethermind/Nethermind.Synchronization/FastSync/DetailedProgress.cs
src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
src/Nethermind/Nethermind.Trie/PatriciaTree.cs
src/Nethermind/Nethermind.Trie/Pruning/ITrieNodeResolver.cs
src/Nethermind/Nethermind.Trie/Pruning/NullTrieNodeResolver.cs
src/Nethermind/Nethermind.Trie/Pruning/NullTrieStore.cs
src/Nethermind/Nethermind.Trie/Pruning/ReadOnlyTrieStore.cs
src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
src/Nethermind/Nethermind.Trie/TrieNode.cs
src/Nethermind/Nethermind.Trie/TrieNodeResolverWithReadFlags.cs

- During regular operation we want to throw exceptions for missing trie nodes, however during sync we should use a non throwing path as its just checking for existence (and otherwise just swallows the exceptions). Exceptions are expensive as they need to capture the stack etc
-

Don't use exceptions for flow control during sync

---

src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
src/Nethermind/Nethermind.Monitoring/NethermindKestrelMetricServer.cs

Probably fixes #6424
- Turns out there is quite some issue when not using kestral metric server.
- This time I've copied the metric server class, but only replace what is needed to prevent it from replacing exit code.
- Copied KestralMetricServer
- Replaced the last line.
- Confirmed exit code is 0 when exiting naturally like block number reached.
- Confirmed exit code is 130 on Ctrl-C as expected.

Reimplement KestrelMetricServer

---

src/Nethermind/Nethermind.Core.Test/AddressTests.cs
src/Nethermind/Nethermind.Core/Address.cs
src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/JavaScript/Engine.cs
src/Nethermind/Nethermind.Evm/Tracing/GethStyle/JavaScript/JavaScriptConverter.cs
src/Nethermind/Nethermind.Evm/Tracing/TraceMemory.cs

- Fix size guards in js-memory

fix memory guard and slice

---

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
src/Nethermind/Nethermind.Runner/configs/goerli.cfg
src/Nethermind/Nethermind.Runner/configs/goerli_archive.cfg

- setting flag `BlobsSupport` to `StorageWithReorgs` in `goerli.cfg` and `goerli_archive.cfg`. It means that on goerli network 1) blob transactions will be supported and 2) stored in persistent db and 3) processed blob transactions would be stored and readded to the blob pool after chain reorganization
- add test for correct config values of `BlobsSupport` for various networks

Enable blob txs support in goerli configs

---

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/PoSSwitcherTests.cs
src/Nethermind/Nethermind.Merge.Plugin/PoSSwitcher.cs
src/Nethermind/Nethermind.Runner/configs/holesky.cfg
src/Nethermind/Nethermind.Runner/configs/holesky_archive.cfg

Ready for review, but please don't merge yet. I am going to test it more.
If genesis.Difficulty is greater than or equal to TTD, then we have a merge in the genesis.
This pull request:
- Removes the need for setting FinalTotalDifficulty for holesky.
- It will help with post-merge devnet edge cases and the calculation of total difficulty on them.
- Additionally, I added some missing tests for a similar trick but with a sync pivot.

Fix TotalDifficulty for post-merge networks in genesis

---

src/Nethermind/Nethermind.Monitoring/NethermindKestrelMetricServer.cs

- I was so occupied at checking exit code that I forgot to check that the metric still works.
- That was embarressing.
- The exception that was silenced is server already started.
- Fix metric not being served.
- It serve it now.

Fix metric not working

---

src/Nethermind/Nethermind.Core/Buffers/CappedArray.cs

- change to readonly struct and remove length setter as it is not used

Make CappedArray readonly

---

src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/MergeRewardCalculatorTests.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/PoSSwitcherTests.cs
src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/BeaconHeadersSyncTests.cs
src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
src/Nethermind/Nethermind.Merge.Plugin/PoSSwitcher.cs
src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.Merge.cs
src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs
src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs

Related PR: https://github.com/NethermindEth/nethermind/pull/6407
BlockTree.Genesis can be null if we haven't processed the block, so it is better to use _chainspec.Genesis.Difficulty

Fixed FinalTotalDifficulty based on genesis

---

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
src/Nethermind/Nethermind.Evm/Metrics.cs
src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs

- Gas price in gwei is between ~0.001 and ~4000; in practice between 8 and 300 and given in 2 decimal places. Using a 4 byte float accurately covers this range without needing to resort to the precision of a 16 byte decimal.

Gas price estimation as 4 byte float rather than 16 byte decimal

---

src/Nethermind/Nethermind.Trie/PatriciaTree.cs
src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
src/Nethermind/Nethermind.Trie/TrieNode.cs

While individually low impact these functions are called a huge amount so it does add up. 
- The Jit sees a method as an atomic unit that can't be subdivided, and inlining and optimization choices, variable allocation/reservation are taken at that level, so move infrequent code out to other methods. This also makes the hot code more dense and compact in the cpu caches.
- Move the throws and exception creation out to local functions
- Store the `_logger.IsTrace` and `_logger.IsDebug` in a `bool` field in class so its not always a virtual call to check if is disabled
- Move any tracing or debug logging out to local function.
- Use runtime Span.CommonPrefixLength rather than uninteresting custom implementation
- Don't introduce try/finally just to return ArrayPool.Shared arrays, it will …

Speed up trie node traversal

---

src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs

- Return to NoGCRegion from SustainedLowLatencynow runtime bug https://github.com/dotnet/runtime/issues/84096 is fixed

Return to NoGCRegion now runtime bug is fixed
