NethermindEth/nethermind

src/Nethermind/Nethermind.Core/Address.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Core/NetworkNode.cs, src/Nethermind/Nethermind.Core/Specs/Byzantium.cs, src/Nethermind/Nethermind.Core/Specs/Constantinople.cs, src/Nethermind/Nethermind.Core/Specs/Dao.cs, src/Nethermind/Nethermind.Core/Specs/Frontier.cs, src/Nethermind/Nethermind.Core/Specs/Homestead.cs, src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs, src/Nethermind/Nethermind.Core/Specs/Olympic.cs, src/Nethermind/Nethermind.Core/Specs/RopstenSpecProvider.cs, src/Nethermind/Nethermind.Core/Specs/SpuriousDragon.cs, src/Nethermind/Nethermind.Core/Specs/TangerineWhistle.cs, src/Nethermind/Nethermind.Evm.Test/Eip1052Tests.cs, src/Nethermind/Nethermind.Evm.Test/Eip145Tests.cs, src/Nethermind/Nethermind.Evm.Test/VirtualMachineTests.cs, src/Nethermind/Nethermind.Evm.Test/VirtualMachineTestsBase.cs, src/Nethermind/Nethermind.Evm/ConsoleTransactionTracer.cs, src/Nethermind/Nethermind.Evm/GasCostOf.cs, src/Nethermind/Nethermind.Evm/Instruction.cs, src/Nethermind/Nethermind.Evm/TransactionTraceEntry.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Network.Test/PeerStorageTests.cs
merging these two EIPs as they are easily reversible and I have made some other changes that we can use on master
=> EIP-145 + EIP1052

src/Nethermind/Nethermind.Blockchain.Test/BlockhashProviderTests.cs, src/Nethermind/Nethermind.Blockchain.Test/RewardCalculatorTests.cs, src/Nethermind/Nethermind.Blockchain/BlockhashProvider.cs
and basic reward calculator tests
=> blockhash int256 overflow fix

.vscode/launch.json, .vscode/tasks.json, src/Nethermind/Nethermind.Blockchain/AuraSealEngine.cs
This is a work in progress pull request, more changes coming soon
Fixes #35
=> Implement Aura (Kovan PoA) WIP PR

src/Nethermind/Nethermind.Core/Specs/RinkebySpecProvider.cs
Another little update before validation changes.
=> Add SpecProvider for Rinkeby

src/Nethermind/Nethermind.Runner/configs/spaceneth_posix.config.json, src/Nethermind/Nethermind.Runner/configs/spaceneth_windows.config.json
Include separate spaceneth configs for POSIX and Windows, like already done for the other configs.
=> provide platform-specific spaceneth configs

src/Nethermind/Nethermind.Blockchain.Test/CliqueTests.cs, src/Nethermind/Nethermind.Blockchain.Test/SnapshotTests.cs, src/Nethermind/Nethermind.Blockchain/Snapshot.cs
=> Unit tests for Snapshot

src/Nethermind/Nethermind.Clique/Snapshot.cs
Serialization failed, because Snapshot accessors were not available to the `JsonSerializer`, and it therefore couldn't update the fields.
=> Make Snapshot fields public for serialization

src/Nethermind/Nethermind.Clique.Test/CliqueSealEngineTests.cs, src/Nethermind/Nethermind.Clique/Clique.cs
Fixes for `Clique.Mine()` and unit tests.
=> Implement sealing for Clique

src/Nethermind/Nethermind.Clique/Clique.cs, src/Nethermind/Nethermind.Clique/CliqueSealEngine.cs, src/Nethermind/Nethermind.Clique/Snapshot.cs, src/Nethermind/Nethermind.Mining/SealEngineException.cs
Closes most of the todos in the `Nethermind.Clique`.
=> Fix old TODOs in Clique

src/Nethermind/Nethermind.Clique/Clique.cs, src/Nethermind/Nethermind.Clique/Snapshot.cs
=> Allow to validate unprocessed Clique blocks

src/Nethermind/Nethermind.Clique.Test/CliqueSealEngineTests.cs, src/Nethermind/Nethermind.Clique.Test/CliqueTests.cs, src/Nethermind/Nethermind.Clique/Clique.cs, src/Nethermind/Nethermind.Clique/CliqueSealEngine.cs, src/Nethermind/Nethermind.Clique/Snapshot.cs
=> Clique refactoring

src/Nethermind/Nethermind.Clique.Test/SnapshotTests.cs, src/Nethermind/Nethermind.Clique/Snapshot.cs, src/Nethermind/Nethermind.Core/Address.cs
Logical continuation of #223.
Removing converter is basically revert of the [earlier commit](https://github.com/NethermindEth/nethermind/pull/185/commits/03f34180bbe4be3c00031c9353a6ad1848b0375d).
=> JSON-serialization related code

src/Nethermind/Nethermind.Clique/Clique.cs, src/Nethermind/Nethermind.Clique/CliqueBlockProducer.cs, src/Nethermind/Nethermind.Clique/Snapshot.cs, src/Nethermind/Nethermind.Clique/SnapshotDecoder.cs
=> Various fixes of Clique codebase

src/Nethermind/Nethermind.Clique/CliqueBlockProducer.cs
=> Fix block producing for Clique

src/Nethermind/Nethermind.Clique/CliqueBlockProducer.cs
=> Add sealing to CliqueBlockProducer

arm/README.md, arm/lib/README.md, arm/net2v2-arm32v7
this fix should allow to recreate the working images.
just remember to build the images on non-arm machines, and run the images on arm machines.
=> fix rocksdb error, re #334

Dockerfile_workshop
addresses #471 along with https://github.com/NethermindEth/workshop/pull/4
=> include dockerfile for workshop

scripts/packaging/archive-packages.sh, scripts/packaging/build-packages.sh, scripts/packaging/setup-packages.sh
=> Adding and modifying scripts for package manager

.travis.yml
=> travis setup check

README.md
* add separate sections for Win/Lin/Mac
* add test section
=> rearrage content

.travis.yml
=> testing travis build and git hooks

src/Nethermind/Nethermind.Blockchain/BlockProcessor.cs, src/Nethermind/Nethermind.Core/Bloom.cs, src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthModuleTests.cs
=> #745 master bloom

src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs
This is to significantly reduce allocations in the tests that generate lots of NewBlockMessage (mimicking a real-world well-connected node).
This was responsible for around 20% of all allocations in the test.
This fragment of code is already covered by tests.
=> Reuse AES engine generated for the given MAC secret #777

src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/NewBlockMessageSerializer.cs
For a well-connected node (500+ connections) NewBlockMessage is issued quite often and an optimized serialization decreases slightly GC requirements. Change is minor and simple and covered by tests.
=> new block message serializer using RLP stream #779

src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs
A simple trick to limit MAC related allocations.
=> mac copy + reset #781

src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs, src/Nethermind/Nethermind.Network/Config/INetworkConfig.cs, src/Nethermind/Nethermind.Network/PeerManager.cs
Removed extensive allocations in UpdatePeers
=> Update peers 797

src/Nethermind/Ethereum.Blockchain.Test/ChainIdTests.cs, src/Nethermind/Ethereum.Blockchain.Test/RevertTests.cs, src/Nethermind/Ethereum.Blockchain.Test/SLoadTests.cs, src/Nethermind/Ethereum.Blockchain.Test/SelfBalanceTests.cs, src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs, src/Nethermind/Nethermind.Blockchain.Test.Runner/BugHunter.cs, src/Nethermind/Nethermind.Blockchain.Test.Runner/Program.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Evm.Test/Eip2200Tests.cs, src/Nethermind/Nethermind.Evm/GasCostOf.cs, src/Nethermind/Nethermind.Evm/RefundOf.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Mainly a fix for the late EIP changes (following the updated spec for 2200)
=> Istanbul state tests 890

src/Nethermind/Nethermind.Core/Json/EthereumJsonSerializer.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs
Guid test needs to be done properly and implementation for Guid ids is needed.
Also here I repalce Update params so it can go as one PR.
=> Guid requests

src/Nethermind/Nethermind.BeaconNode.Test/TestSystem.cs, src/Nethermind/Nethermind.BeaconNode/Nethermind.BeaconNode.csproj
Minimal just to get it now working on my Macbook, so across all 3 platforms now. Also increase the logging level in tests as Rider nicely shows the output and I noticed it was missing log debug details.
=> Update package reference with OSX support

src/Nethermind/Nethermind.Blockchain.Test/Synchronization/FastSync/NodeDataDownloaderTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Synchronization/MeasuredProgressTests.cs, src/Nethermind/Nethermind.Blockchain/TxPools/TxPool.cs, src/Nethermind/Nethermind.Blockchain/TxPools/TxPoolConfig.cs
Decreases the amount of time pending txs are kept in memory.
=> Pending limit

Dockerfile_alpine
fix https://github.com/NethermindEth/nethermind/issues/1160
=> make alpine image "portable"

src/Nethermind/Nethermind.BeaconNode.Test/Storage/MemoryStoreProviderTest.cs, src/Nethermind/Nethermind.BeaconNode.Test/ValidatorAssigmentsTest.cs
PR was merged before I had pushed the changes for the feedback
=> Code review feedback

src/Nethermind/Nethermind.BeaconNode.Host/Nethermind.BeaconNode.Host.csproj, src/Nethermind/Nethermind.BeaconNode.Host/Program.cs, src/Nethermind/Nethermind.BeaconNode.Peering/BeaconNodePeeringServiceCollectionExtensions.cs, src/Nethermind/Nethermind.BeaconNode.Peering/Nethermind.BeaconNode.Peering.csproj, src/Nethermind/Nethermind.BeaconNode.Peering/NetworkPeering.cs, src/Nethermind/Nethermind.BeaconNode.Peering/PeeringWorker.cs, src/Nethermind/Nethermind.BeaconNode.Storage/Nethermind.BeaconNode.Storage.csproj, src/Nethermind/Nethermind.BeaconNode.Test/BeaconNodeWorkerTest.cs, src/Nethermind/Nethermind.BeaconNode.Test/TestSystem.cs, src/Nethermind/Nethermind.BeaconNode/BeaconNodeFacade.cs, src/Nethermind/Nethermind.BeaconNode/Log.cs, src/Nethermind/Nethermind.BeaconNode/Services/INetworkPeering.cs, src/Nethermind/Nethermind.sln
Including a peering worker, with interface for publishing blocks
Just the first bit of peering, setting up a project and interface.
(Am planning to extract out common bits of validator & node before implementing peering, but just wanted to set up the structure).
=> Skeleton project for peering

src/Nethermind/Nethermind.Core/Crypto/Keccak512.cs, src/Nethermind/Nethermind.HashLib/Crypto/SHA3/KeccakBase.cs, src/Nethermind/Nethermind.HashLib/Hash.cs, src/Nethermind/Nethermind.HashLib/HashCryptoNotBuildIn.cs, src/Nethermind/Nethermind.HashLib/Nethermind.HashLib.csproj, src/Nethermind/Nethermind.Mining/Ethash.cs, src/Nethermind/Nethermind.Mining/EthashCache.cs, src/Nethermind/Nethermind.Mining/FullDataSet.cs, src/Nethermind/Nethermind.Mining/IEthashDataSet.cs
Reverts NethermindEth/nethermind#1241
=> Revert "Less allocatey ethash"

src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Blockchain/IBlockTree.cs, src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs, src/Nethermind/Nethermind.Cli/Modules/DebugCliModule.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/BlockInfoForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/ChainLevelForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugModule.cs
Allows diagnostic questions via RPC or CLI about any chain level
It also allows a deletion of the chain slices
=> getChainLevel RPC and CLI

src/Nethermind/Nethermind.Blockchain/Synchronization/SyncModeSelector.cs
Reduce "Staying on sync" logs by with logic:
If All BestHeader/BestFullBlock/BestFullState are advancing skip logging. If any of them is not advancing for threshold then log every 3 sec.
Treshold is adjusted to 20s in order to handle mainnet block times.
=> Reduce "Staying on sync" logs

src/Nethermind/Nethermind.AuRa.Test/AuRaBlockProducerTests.cs, src/Nethermind/Nethermind.AuRa/AuRaBlockProducer.cs, src/Nethermind/Nethermind.Blockchain.Test/IntegrationTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Synchronization/SyncThreadTests.cs, src/Nethermind/Nethermind.Blockchain/BaseBlockProducer.cs, src/Nethermind/Nethermind.Blockchain/BaseLoopBlockProducer.cs, src/Nethermind/Nethermind.Blockchain/BlockchainProcessor.cs, src/Nethermind/Nethermind.Blockchain/DevBackgroundBlockProducer.cs, src/Nethermind/Nethermind.Blockchain/DevBlockProducer.cs, src/Nethermind/Nethermind.Blockchain/IBlockProcessingQueue.cs, src/Nethermind/Nethermind.Blockchain/MinedBlockProducer.cs, src/Nethermind/Nethermind.Blockchain/OneTimeProcessor.cs, src/Nethermind/Nethermind.Blockchain/ReadOnlyChainProcessingEnv.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugModuleFactory.cs, src/Nethermind/Nethermind.Runner/Runners/EthereumRunner.cs, src/Nethermind/Nethermind.Runner/Runners/ReadOnlyChain.cs
Delay BaseLoopBlockProducer (including AuRaBlockProducer) producing block until chain is processed
This solves #1252 .
=> Delay producing AuRa blocks until chain synced

Dockerfile_alpine_arm64, scripts/entrypoint2.sh
Should fix https://github.com/NethermindEth/nethermind/issues/1199
=> add arm64 alpine docker image

Dockerfile_alpine, Dockerfile_alpine_arm64, scripts/entrypoint.sh
add snappy support to rocksdb build, better readability, repository pinning, copying chainspec folder is not needed
=> small docker improvements

README.md
=> github actions badges

src/Nethermind/Nethermind.Runner/Ethereum/Steps/EthereumStepsManager.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/FilterBootnodes.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/IEthereumRunnerStep.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitDatabase.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitRlp.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitRlpAuRa.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeFinalizationAuRa.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/LoadGenesisBlock.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModulesClique.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/ReviewBlockTree.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupHive.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupKeyStore.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartBlockProducer.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartEthStatsClient.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartGrpcProducer.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartKafkaProducer.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/UpdateDiscoveryConfig.cs
Allows to prevent node from waiting 6 seconds for ethash start
Parallelizes the startup
=> is required step

docs/source/build.rst, docs/source/cloud.rst, docs/source/contact.rst, docs/source/docker.rst, docs/source/download.rst, docs/source/hardware_requirements.rst, docs/source/networks.rst, docs/source/platforms.rst
* some minor fixes/changes to read the docs
=> updating documentation

src/Nethermind/Nethermind.Blockchain.Test/Synchronization/SynchronizerTests.cs, src/Nethermind/Nethermind.Cli.Test/ProofCliModuleTests.cs, src/Nethermind/Nethermind.Cli/CliEngine.cs, src/Nethermind/Nethermind.Cli/CliLogger.cs, src/Nethermind/Nethermind.Cli/Console/AutoCompletionHandler.cs, src/Nethermind/Nethermind.Cli/Console/CliConsole.cs, src/Nethermind/Nethermind.Cli/Console/ColorScheme.cs, src/Nethermind/Nethermind.Cli/Console/ICliConsole.cs, src/Nethermind/Nethermind.Cli/Console/StatementHistoryManager.cs, src/Nethermind/Nethermind.Cli/Console/Terminal.cs, src/Nethermind/Nethermind.Cli/Modules/CliFunctionAttribute.cs, src/Nethermind/Nethermind.Cli/Modules/CliModuleAttribute.cs, src/Nethermind/Nethermind.Cli/Modules/CliModuleLoader.cs, src/Nethermind/Nethermind.Cli/Modules/CliPropertyAttribute.cs, src/Nethermind/Nethermind.Cli/Modules/NdmCliModule.cs, src/Nethermind/Nethermind.Cli/NodeManager.cs, src/Nethermind/Nethermind.Cli/Program.cs, src/Nethermind/Nethermind.Network.Test/Discovery/DiscoveryManagerTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModules.cs
Moves out some of the code from program - to prepare for tests.
Added help for user to solve connection issues.
=> moved out history manager and a few other tweaks

src/Nethermind/Nethermind.Blockchain/Synchronization/BlockDownloader.cs, src/Nethermind/Nethermind.Blockchain/Validators/HeaderValidator.cs, src/Nethermind/Nethermind.Blockchain/Validators/IBlockTreeExtensions.cs, src/Nethermind/Nethermind.Core.Test/BytesTests.cs, src/Nethermind/Nethermind.Core.Test/HeaderValidatorTests.cs, src/Nethermind/Nethermind.Core/BlockHeader.cs, src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs, src/Nethermind/Nethermind.Core/Extensions/ZeroPaddedSpan.cs, src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs, src/Nethermind/Nethermind.Evm/EvmStack.cs, src/Nethermind/Nethermind.Evm/ExecutionEnvironment.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
small change decreasing allocations on VM
=> added zero padded bytes in VM operations

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Proof/ProofModuleTests.cs, src/Nethermind/Nethermind.Store.Test/Proofs/AccountProofCollectorTests.cs, src/Nethermind/Nethermind.Store/Proofs/AccountProofCollector.cs, src/Nethermind/Nethermind.Store/Proofs/ProofVerifier.cs, src/Nethermind/Nethermind.Store/TreeDumper.cs
Fixes:
https://github.com/NethermindEth/nethermind/issues/1461
=> proofFuzzer WIP

src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/InitConfig.cs, src/Nethermind/Nethermind.Store.Bloom/NullBloomStorage.cs
1. Backward compatibility with UseMemDb.
2. BloomStorage to be compatible with DiagnosticMode
=> DiagnosticMode updates

src/Nethermind/Nethermind.Cli/Modules/DebugCliModule.cs, src/Nethermind/Nethermind.Cli/Modules/NodeCliModule.cs
=> CLI changes to support https and chain level operations

src/Nethermind/Nethermind.Network/Rlpx/RlpxPeer.cs
=> update error message to match current cli args

src/Nethermind/Nethermind.Network/Discovery/DiscoveryManager.cs
=> removed minor memory leak in discovery

src/Nethermind/Nethermind.Blockchain/Synchronization/FastSync/NodeDataFeed.cs, src/Nethermind/Nethermind.Core/ThisNodeInfo.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Rocks/RocksDbProvider.cs, src/Nethermind/Nethermind.Evm/MemoryAllowance.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitDatabase.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Runner/configs/goerli.cfg, src/Nethermind/Nethermind.Trie/MemoryAllowance.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.TxPool/MemoryAllowance.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
includes a console display of more detailed memory estimates
(includes one line change that clears the cache after the fast sync finishes - to clear memory)
=> Memory allowance

src/Nethermind/Nethermind.Abi.Test/AbiEncoderExtensionsTests.cs, src/Nethermind/Nethermind.BeaconNode.Eth1Bridge.Test/MockedStart/QuickStartTests.cs, src/Nethermind/Nethermind.BeaconNode.Peering/Nethermind.BeaconNode.Peering.csproj, src/Nethermind/Nethermind.BeaconNode.Test/BlockProducerTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs, src/Nethermind/Nethermind.Blockchain/Synchronization/SyncReport.cs, src/Nethermind/Nethermind.Core.Test/Encoding/ReceiptDecoderTests.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers.Infrastructure/Rpc/Models/SessionClientForRpc.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers/DataStreams/Services/DataStreamService.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers/Sessions/Domain/ConsumerSession.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers/Sessions/Domain/SessionClient.cs, src/Nethermind/Nethermind.DataMarketplace.Core/Services/EthPriceService.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Persistence/Mongo/AddressSerializer.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Persistence/Mongo/KeccakSerializer.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Persistence/Mongo/PublicKeySerializer.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Persistence/Mongo/SignatureSerializer.cs, src/Nethermind/Nethermind.DataMarketplace.Subprotocols/Messages/NdmMessageCode.cs, src/Nethermind/Nethermind.DataMarketplace.Subprotocols/NdmSubprotocol.cs, src/Nethermind/Nethermind.Db.Rocks/RocksDbProvider.cs, src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/Migrations/BloomMigration.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/Migrations/ReceiptMigration.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartBlockProducer.cs, src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpBehaviors.cs, src/Nethermind/Nethermind.State/Repositories/IChainLevelInfoRepository.cs, src/Nethermind/Nethermind.TxPool/Storages/PersistentTxStorage.cs
This PR follows strict don't ask don't tell policy. ;)
=> Remove warnings

src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Deposits/BlockchainBridgeBuilder.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Modules/NdmModule.cs, src/Nethermind/Nethermind.DataMarketplace.Test/ContractInteractionTest.cs, src/Nethermind/Nethermind.Facade.Test/BlockChainBridgeTests.cs, src/Nethermind/Nethermind.Facade/BlockchainBridge.cs, src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs, src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/BoundedModulePoolTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SingletonModulePoolTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModuleFactory.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModules.cs
more eth tests using the new test classes
=> various json eth tests

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
=> DB dispose improvement #1702

src/Nethermind/Nethermind.Blockchain/KnownAddresses.cs
Just add miners and sort to avoid duplicates
=> sort miners

scripts/syncSettings.py, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner.Test/Nethermind.Runner.Test.csproj, src/Nethermind/Nethermind.Runner/configs/goerli.cfg, src/Nethermind/Nethermind.Runner/configs/goerli_beam.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet_archive.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet_beam.cfg, src/Nethermind/Nethermind.Runner/configs/poacore_beam.cfg, src/Nethermind/Nethermind.Runner/configs/poacore_validator.cfg, src/Nethermind/Nethermind.Runner/configs/rinkeby.cfg, src/Nethermind/Nethermind.Runner/configs/rinkeby_archive.cfg, src/Nethermind/Nethermind.Runner/configs/rinkeby_beam.cfg, src/Nethermind/Nethermind.Runner/configs/ropsten.cfg, src/Nethermind/Nethermind.Runner/configs/ropsten_beam.cfg, src/Nethermind/Nethermind.Runner/configs/sokol_validator.cfg, src/Nethermind/Nethermind.Runner/configs/volta.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_validator.cfg
Added wildcards in config tests.
Added beam configs.
Changed some default values.
=> Beam configs

src/Nethermind/Nethermind.JsonRpc.Test/Modules/AdminModuleTests.cs, src/Nethermind/Nethermind.Network.Test/EnodeTests.cs, src/Nethermind/Nethermind.Network/Enode.cs
=> Support DNS enode

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet_beam.cfg
Removes the accidental default diagnostic mode
=> fixes #1844

src/Nethermind/Cortex.sln, src/Nethermind/Cortex.sln.DotSettings, src/Nethermind/Nethermind.BeaconNode.Peering.Test/MothraPeeringWorkerTests.cs, src/Nethermind/Nethermind.Core2.Abstractions/Types/Bytes32.cs, src/Nethermind/Nethermind.Core2/Crypto/Sha256.cs, src/Nethermind/Nethermind.HashLib/Crypto/SHA256Base.cs, src/Nethermind/Nethermind.HashLib/Crypto/SHA3/KeccakBase.cs, src/Nethermind/Nethermind.HashLib/Extensions/Converters.cs, src/Nethermind/Nethermind.HashLib/Hash.cs, src/Nethermind/Nethermind.HashLib/HashBuffer.cs, src/Nethermind/Nethermind.HashLib/HashCryptoNotBuildIn.cs, src/Nethermind/Nethermind.HashLib/IHash.cs
61MB -> 18MB allocations on beacon node startup
=> Less Sha allocation

src/Nethermind/Ethereum.Blockchain.Block.Test/StateTests.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.State/IStorageProvider.cs, src/Nethermind/Nethermind.State/StorageProvider.cs
partial fix for the block 10094566
=> Create2 fix

src/Nethermind/Nethermind.Core/Transaction.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Deposits/BlockchainBridgeBuilder.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Modules/NdmModule.cs, src/Nethermind/Nethermind.Facade.Test/BlockChainBridgeTests.cs, src/Nethermind/Nethermind.Facade.Test/TxPoolBridgeTests.cs, src/Nethermind/Nethermind.Facade/BlockchainBridge.cs, src/Nethermind/Nethermind.Facade/TxPoolBridge.cs, src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModuleFactory.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
Fixes own transactions broadcasts
=> Broadcasts

src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs, src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Blockchain/Processing/IBlockProcessor.cs, src/Nethermind/Nethermind.Blockchain/Processing/NullBlockProcessor.cs, src/Nethermind/Nethermind.Blockchain/Processing/ProcessingOptions.cs, src/Nethermind/Nethermind.Blockchain/Rewards/RewardCalculator.cs, src/Nethermind/Nethermind.Blockchain/Visitors/DbBlocksLoader.cs, src/Nethermind/Nethermind.Core/BlockHeader.cs, src/Nethermind/Nethermind.Db/ISnapshotableDb.cs, src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/IBlockTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofBlockTracer.cs, src/Nethermind/Nethermind.Network/Discovery/Lifecycle/NodeLifecycleManager.cs, src/Nethermind/Nethermind.Runner/IInitConfig.cs
Genesis processed same way as other blocks.
Block processor readability changes.
Other PR (discovery included but review is kept separate).
Removed repeated head processing when loading blocks from the DB.
Tested on mainnet, Goerli, xDai for initial launch on archive sync and on Goerli on fast sync.
=> Reorganization manager

src/Nethermind/Nethermind.Network/Discovery/Lifecycle/NodeLifecycleManager.cs
Otherwise we do not find non-Nethermind peers
=> bootnodes do not send any pings back

src/Nethermind/Nethermind.Blockchain/Producers/TxPoolTxSource.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockFinalizationManager.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProducer.cs, src/Nethermind/Nethermind.Consensus.AuRa/Transactions/GeneratedTxSourceSealer.cs, src/Nethermind/Nethermind.Consensus.AuRa/Transactions/RandomContractTxSource.cs, src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxFilterTxSource.cs, src/Nethermind/Nethermind.Consensus.AuRa/Validators/ContractBasedValidator.cs, src/Nethermind/Nethermind.Consensus.AuRa/Validators/MultiValidator.cs, src/Nethermind/Nethermind.Consensus.AuRa/Validators/ReportingContractBasedValidator.PersistentReports.cs, src/Nethermind/Nethermind.Consensus/Transactions/CompositeTxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/ITxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/SinglePendingTxSelector.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartBlockProducerAuRa.cs
This changes are temporary - needed to investigate issue in RANDAO that produced multiple transactions with same nonce for same phase in block.
=> RANDAO investigation & workaround

src/Nethermind/EthereumTests.sln, src/Nethermind/Nethermind.Core.Test/Json/AddressConverterTests.cs, src/Nethermind/Nethermind.Core.Test/Json/ByteArray32ConverterTests.cs, src/Nethermind/Nethermind.Core.Test/Json/ByteArrayConverterTests.cs, src/Nethermind/Nethermind.Core.Test/Json/PublicKeyConverterTests.cs, src/Nethermind/Nethermind.Core.Test/Json/UInt256ConverterTests.cs, src/Nethermind/Nethermind.Core.Test/RlpTests.cs, src/Nethermind/Nethermind.Core/Bloom.cs, src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Db/StateDb.cs, src/Nethermind/Nethermind.Evm/TransactionProcessor.cs, src/Nethermind/Nethermind.JsonRpc.Test/Data/IdConverterTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs, src/Nethermind/Nethermind.Serialization.Json/AddressConverter.cs, src/Nethermind/Nethermind.Serialization.Json/BloomConverter.cs, src/Nethermind/Nethermind.Serialization.Json/ByteArray32Converter.cs, src/Nethermind/Nethermind.Serialization.Json/ByteArrayConverter.cs, src/Nethermind/Nethermind.Serialization.Json/EthereumJsonSerializer.cs, src/Nethermind/Nethermind.Serialization.Json/NullableBigIntegerConverter.cs, src/Nethermind/Nethermind.Serialization.Json/UInt256Converter.cs, src/Nethermind/Nethermind.Specs/FrontierSpecProvider.cs, src/Nethermind/Nethermind.Specs/GoerliSpecProvider.cs, src/Nethermind/Nethermind.State.Test/StatsCollectorTests.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/StateTree.cs, src/Nethermind/Nethermind.Trie/NibbleExtensions.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs, src/Nethermind/Nethermind.Trie/TrieStats.cs
this will gradually add more and more test coverage for sync
=> Sync coverage

src/Nethermind/Nethermind.Blockchain/Filters/Topics/AnyTopic.cs, src/Nethermind/Nethermind.Blockchain/Filters/Topics/OrExpression.cs, src/Nethermind/Nethermind.Blockchain/Filters/Topics/SpecificTopic.cs, src/Nethermind/Nethermind.Blockchain/Filters/Topics/TopicExpression.cs, src/Nethermind/Nethermind.Blockchain/Receipts/KeccaksIterator.cs, src/Nethermind/Nethermind.Core.Test/Encoding/LogEntryDecoderTests.cs, src/Nethermind/Nethermind.Core/Address.cs, src/Nethermind/Nethermind.Core/Crypto/Keccak.cs, src/Nethermind/Nethermind.Core/TransactionReceipt.cs, src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
This reverts commit f83d5f11599c38e7e1756db8190dad3c6350855e.
=> Revert "use ValueKeccak instead KeccakStructRef (#2120)"

src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs, src/Nethermind/Nethermind.Blockchain/LogTraceDumper.cs, src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Blockchain/Processing/ProcessingOptions.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/IInitConfig.cs
Without setting diagnostic mode will store failing block traces
=> auto trace blocks on failure

src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs, src/Nethermind/Ethereum.Test.Base/EthereumTestResult.cs, src/Nethermind/Ethereum.Test.Base/Interfaces/IBlockchainTestRunner.cs, src/Nethermind/Nethermind.Blockchain.Test.Runner/BlockchainTestsBugHunter.cs, src/Nethermind/Nethermind.Blockchain.Test.Runner/Program.cs, src/Nethermind/Nethermind.Blockchain.Test.Runner/StateTestsBugHunter.cs
=> blockchain test bug hunter

src/Nethermind/Nethermind.Grpc/IGrpcConfig.cs, src/Nethermind/Nethermind.Network/Config/NetworkConfig.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner.Test/Nethermind.Runner.Test.csproj, src/Nethermind/Nethermind.Seq/Config/ISeqConfig.cs, src/Nethermind/Nethermind.TxPool/ITxPoolConfig.cs
=> default values test

src/Nethermind/Nethermind.Consensus.Clique/ICliqueModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/IAdminModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/JsonRpcMethodAttribute.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Parity/IParityModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Web3/IWeb3Module.cs
=> remove Returns property

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/baseline_ropsten.cfg, src/Nethermind/Nethermind.Runner/configs/ndm_consumer_mainnet_proxy.cfg, src/Nethermind/Nethermind.Runner/configs/ndm_provider_local.cfg, src/Nethermind/Nethermind.Runner/configs/ndm_provider_mainnet_proxy.cfg, src/Nethermind/Nethermind.Runner/configs/spaceneth.cfg, src/Nethermind/Nethermind.Runner/configs/spaceneth_persistent.cfg, src/Nethermind/Nethermind.Runner/configs/volta_archive.cfg
=> test for additional commas in config files

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcModuleProviderTests.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs
Fixes #2314 
Please confirm that it
=> case sensitive method resolution and tests

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs, src/Nethermind/Nethermind.Blockchain.Test/TxPools/ReceiptStorageTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRecovery.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Services/Deposits/BlockchainBridgeBuilder.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceModuleTests.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/ReceiptMigrationTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/Migrations/BloomMigration.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/Migrations/ReceiptMigration.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/ResetDatabaseMigrations.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
=> #2312 ReceiptRecovery to recover Transaction.SenderAddress

src/Nethermind/Nethermind.Baseline/Tree/BaselineTreeMetadata.cs, src/Nethermind/Nethermind.Provide.Vault/Nethermind.Provide.Vault.csproj, src/Nethermind/Nethermind.Provide.Vault/VaultService.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartBlockProducerClique.cs
update Provide version so the bookie is available for sending txs for payment
=> bumped provide lib to 2.2.0

src/Nethermind/Nethermind.DataMarketplace.Consumers.Infrastructure/NdmConsumersModule.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/INdmApi.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/NdmApi.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Updaters/INdmAccountUpdater.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/Updaters/NdmAccountUpdater.cs, src/Nethermind/Nethermind.DataMarketplace.Initializers/NdmInitializer.cs, src/Nethermind/Nethermind.DataMarketplace.Initializers/NdmPlugin.cs
Updating account balance and nonce by web sockets
=> Ndm account updater

src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs, src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Tracing/GethStyleTracerTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Validators/HeaderValidatorTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Visitors/DbBlocksLoaderTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Visitors/StartupTreeFixerTests.cs, src/Nethermind/Nethermind.Blockchain/BlockReplacementEventArgs.cs, src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Blockchain/IBlockTree.cs, src/Nethermind/Nethermind.Blockchain/OnChainTxWatcher.cs, src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs, src/Nethermind/Nethermind.Blockchain/TxFilterAdapter.cs, src/Nethermind/Nethermind.Clique.Test/CliqueBlockProducerTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/Contracts/DataStore/ContractDataStore.cs, src/Nethermind/Nethermind.Consensus.AuRa/Contracts/TxPriorityContract.Destination.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Builders/BlockTreeBuilder.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/BoundedModulePoolTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/ParityModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SingletonModulePoolTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityStyleTracerTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceModuleTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchainAuRa.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncThreadTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs
Decouple TxPool and BlockTree with OnChainTxWatcher
Fix InitializeBlockchainAuRa FilteredTxPool initialization
=> POSDAO test fixes

src/Nethermind/Baseline.sln.DotSettings, src/Nethermind/Nethermind.Baseline.Test/JsonRpc/BaselineModuleTests.cs, src/Nethermind/Nethermind.Baseline/BaselineModule.cs, src/Nethermind/Nethermind.Baseline/IBaselineModule.cs
Updated baseline RPC to the latest spec
export interface IBaselineRPC {
// Retrieve a single leaf from a tree at the given shield contract address
getCommit(address: string, index: number): Promise<MerkleTreeNode>;
// Retrieve multiple leaves from a tree at the given shield contract address
getCommits(address: string, startIndex: number, count: number): Promise<MerkleTreeNode[]>;
// Retrieve the root of a tree at the given shield contract address
getRoot(address: string): Promise<string>;
// Retrieve sibling paths/proof of the given leaf index at the given shield contract address
getSiblings(address: string, leafIndex: number): Promise<MerkleTreeNode[]>;
// Retrieve a list of the shield contract addresses being tracked and persisted
getTracked(): Promise<string[]>;
// Inserts a single …
=> leaf -> commit

src/Nethermind/Nethermind.AuRa.Test/Contract/ContractDataStoreTests.cs, src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Blockchain.Test/TxPools/Collections/DistinctValueSortedPoolTests.cs, src/Nethermind/Nethermind.Blockchain/Contracts/Contract.ConstantContract.cs, src/Nethermind/Nethermind.Blockchain/Data/FileLocalDataSource.cs, src/Nethermind/Nethermind.Blockchain/OnChainTxWatcher.cs, src/Nethermind/Nethermind.Blockchain/Processing/ReadOnlyTransactionProcessorSource.cs, src/Nethermind/Nethermind.Consensus.AuRa/Contracts/DataStore/ContractDataStore.cs, src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxPermissionFilter.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Evm/ReadOnlyTransactionProcessor.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/ParityModuleTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchainAuRa.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/TxFilterBuilders.cs, src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
@matilote  This could use testing on validator before merging
=> Tx permissions fix

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
@matilote can you test on linux, windows and mac before merging?
=> Add TLS 1.3 support

src/Nethermind/Nethermind.HealthChecks/NodeHealthChecks.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
(cherry picked from commit e4eb3e1588dc09744260ea83a45803be97845099)
=> HealthChecks enabled but the plugins directory missing breaks (#2626)

src/Nethermind/Nethermind.DataMarketplace.Consumers.Infrastructure/Rpc/NdmRpcConsumerModule.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers.Test/Infrastructure/NdmRpcConsumerModuleTests.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers/Deposits/Services/DepositManager.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers/Refunds/Services/RefundClaimant.cs, src/Nethermind/Nethermind.DataMarketplace.Consumers/Shared/Services/ConsumerServicesBackgroundProcessor.cs, src/Nethermind/Nethermind.DataMarketplace.Core/Services/GasPriceService.cs, src/Nethermind/Nethermind.DataMarketplace.Core/Services/IGasPriceService.cs, src/Nethermind/Nethermind.DataMarketplace.Test/Services/GasPriceServiceTests.cs
Stumbled on this while debugging some code. I think we should know what methods are returning just from their names not from interface/class name - open for discussion
=> More straight up methods names in GasPriceService

scripts/deployment/archive-packages.sh
=> fix dll in package

.github/workflows/on-issue-alert.yml
Creates an alert to Opsgenie when non Nethermind member opens an issue
=> adding issue alert flow

src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncFeed.cs
=> State sync feed finish lock fix

src/Nethermind/Nethermind.DataMarketplace.Infrastructure/NdmApi.cs, src/Nethermind/Nethermind.Db/IRocksDbFactory.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TransactionForRpcConverterTests.cs, src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Nethermind.JsonRpc.csproj
=> change tx for rpc data to quantity on signature

.github/workflows/posdao-tests.yml
* Upload nethermind node logs after posdao tests failure
=> uploading logs after failure

Dockerfile
This will make it so tooling will know what ports to suggest to users to forward, and potentially automatically forward them to localhost depending on configuration.
=> Adds ports to Dockerfile.

.editorconfig, src/Nethermind/Nethermind.Runner/Program.cs
Fixes a bunch of compiler style warnings.
Let me know if you would rather I disable some of these warnings in `.editorconfig` instead.
=> Removes squigglies.

src/Nethermind/Nethermind.Evm/EvmStack.cs
This PR adds just a comment to the `EvmStack.Word` structure.
=> Better comments for EvmStack.Word 

.github/workflows/hive-docker.yml
Missed this one from my previous pass.
=> Disables hive-docker workflow on forks.

src/Nethermind/Nethermind.Core/Caching/MemCountingCache.cs, src/Nethermind/Nethermind.Crypto/EciesCipher.cs, src/Nethermind/Nethermind.Crypto/Nethermind.Crypto.csproj, src/Nethermind/Nethermind.Crypto/ProtectedData.AspNetWrapper.cs, src/Nethermind/Nethermind.Crypto/ProtectedData.DpapiWrapper.cs, src/Nethermind/Nethermind.Crypto/ProtectedData.T.cs, src/Nethermind/Nethermind.Crypto/ProtectedData.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db/RocksDbSettings.cs, src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs, src/Nethermind/Nethermind.HealthChecks/Nethermind.HealthChecks.csproj, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpBehaviors.cs
Feedback welcome on the various solutions to problems.  Some may be disagreeable.
Previously there were a bunch of build warnings (at least on Windows with only .NET SDK 5), now there are 0!
=> Fixes compiler warnings/errors.

src/Nethermind/Nethermind.Core/Caching/MemCountingCache.cs, src/Nethermind/Nethermind.Crypto/EciesCipher.cs, src/Nethermind/Nethermind.Crypto/Nethermind.Crypto.csproj, src/Nethermind/Nethermind.Crypto/ProtectedData.AspNetWrapper.cs, src/Nethermind/Nethermind.Crypto/ProtectedData.DpapiWrapper.cs, src/Nethermind/Nethermind.Crypto/ProtectedData.T.cs, src/Nethermind/Nethermind.Crypto/ProtectedData.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db/RocksDbSettings.cs, src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs, src/Nethermind/Nethermind.HealthChecks/Nethermind.HealthChecks.csproj, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpBehaviors.cs
This reverts commit fb67f62a2494140a96d189c9f0391cc9af14df4b.
=> Revert "Fixes compiler warnings/errors. (#2808)"

src/Nethermind/Nethermind.Core/Caching/LruCache.cs
This PR reverts #2497 as recent reports #2862 found it to represent flaky behavior. The revert is based on the version before the mentioned PR that was followed by a review of next PRs that touched this file and applying additional fixes.
I spent 2+ hours on trying to find the issue and had no success in providing a limited reproduction scenario. Having in mind that it's better to have this running than not running fast, I propose a revert to an earlier version.
=> Undo lru ache

src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/ISubscriptionManager.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/JsonRpcSubscriptionResult.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SubscribeModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SubscriptionManager.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SyncingSubscription.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/RegisterRpcModules.cs
* changed SyncingSubscription result to boolean "false" if syncing=false. If syncing=true still returns SyncingResult object
* changed order of subscription and result in JsonRpcSubscriptionResult
* fixed typo in SubscriptionManager
* added more tests
=> SyncingSubscription result is bool now if false

src/Nethermind/Nethermind.Blockchain/KnownAddresses.cs
=> Nethermind.Blockchain: Improve known Goerli validators

src/Nethermind/Nethermind.EthStats.Test/EthStatsClientTests.cs, src/Nethermind/Nethermind.EthStats.Test/Nethermind.EthStats.Test.csproj, src/Nethermind/Nethermind.EthStats/Clients/EthStatsClient.cs, src/Nethermind/Nethermind.EthStats/Configs/EthStatsConfig.cs, src/Nethermind/Nethermind.EthStats/IEthStatsConfig.cs, src/Nethermind/Nethermind.EthStats/IMessage.cs, src/Nethermind/Nethermind.EthStats/Integrations/EthStatsIntegration.cs, src/Nethermind/Nethermind.EthStats/Messages/BlockMessage.cs, src/Nethermind/Nethermind.EthStats/Messages/HelloMessage.cs, src/Nethermind/Nethermind.EthStats/Messages/LatencyMessage.cs, src/Nethermind/Nethermind.EthStats/Messages/PendingMessage.cs, src/Nethermind/Nethermind.EthStats/Messages/PingMessage.cs, src/Nethermind/Nethermind.EthStats/Messages/StatsMessage.cs, src/Nethermind/Nethermind.EthStats/Senders/MessageSender.cs, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
Added nulability checks in the ethstats project.
=> nulability checks in ethstats

.github/workflows/cc-build.yml, .github/workflows/no-cc-build.yml, src/Nethermind/Nethermind.Api.Test/CompositePluginLoaderTests.cs, src/Nethermind/Nethermind.Api.Test/Nethermind.Api.Test.csproj, src/Nethermind/Nethermind.Api.Test/SinglePluginLoaderTests.cs, src/Nethermind/Nethermind.Api.Test/TestPlugin.cs, src/Nethermind/Nethermind.Api.Test/TestPlugin2.cs, src/Nethermind/Nethermind.Api/Extensions/CompositePluginLoader.cs, src/Nethermind/Nethermind.Api/Extensions/PluginLoader.cs, src/Nethermind/Nethermind.Api/Extensions/SinglePluginLoader.cs, src/Nethermind/Nethermind.sln
Adds two helper classes for registering plugins easily while building, without having to copy files.
=> added some plugin loader helpers with tests

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Fixes the AuRa Berlin devnet validator callbacks.
=> fixes for the future AuRa chains

src/Nethermind/Nethermind.Benchmark/Core/LruCacheBenchmarks.cs, src/Nethermind/Nethermind.Benchmark/Nethermind.Benchmark.csproj, src/Nethermind/Nethermind.Dirichlet.Benchmark/Nethermind.Dirichlet.Benchmark.csproj, src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs, src/Nethermind/Nethermind.JsonRpc.Benchmark/Nethermind.JsonRpc.Benchmark.csproj, src/Nethermind/Nethermind.JsonRpc.Benchmark/ParamInfoBenchmarks.cs, src/Nethermind/Nethermind.Network.Benchmark/Nethermind.Network.Benchmark.csproj, src/Nethermind/Nethermind.Precompiles.Benchmark/ModExpBenchmark.cs, src/Nethermind/Nethermind.Precompiles.Benchmark/PrecompileBenchmarkBase.cs
Fixes the build of the Benchmarks.sln
=> fixed benchmarks build

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
=> Add compression to http based on caller header

src/Nethermind/Nethermind.Consensus/Transactions/TxFilterBuilders.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/Eth2BlockProducerFactory.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.BlockProducer.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin/Nethermind.Merge.Plugin.csproj, src/Nethermind/Nethermind.Runner/Ethereum/Steps/InitializeBlockchainAuRa.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/TxAuRaFilterBuilders.cs, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
**temporary solution**  --  adding Merge plugin reference
=> Docker merge plugin

src/Nethermind/Nethermind.Merge.Plugin.Test/ConsensusModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/Result.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/FinaliseBlockHandler.cs
=> quick fix for success return value

src/Nethermind/Nethermind.Blockchain/GenesisLoader.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecAllocation.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/AllocationJson.cs, src/Nethermind/Nethermind.State/IStateProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs
=> add nonces to test allocations

src/Nethermind/Nethermind.GitBook/SharedContent.cs
Right now object description are generate for Array instead of actual object - this quick PR fix it.
=> Fix object detail generation in Gitbook

src/Nethermind/Ethereum.Blockchain.Block.Test/Eip1559Tests.cs, src/Nethermind/Ethereum.Blockchain.Block.Test/ExampleTests.cs, src/Nethermind/Ethereum.Test.Base/GeneralStateTest.cs, src/Nethermind/Ethereum.Test.Base/GeneralStateTestEnvJson.cs, src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs, src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs, src/Nethermind/Ethereum.Test.Base/TransactionJson.cs, src/Nethermind/Ethereum.Transition.Test/BerlinToLondon.cs, src/Nethermind/Ethereum.Transition.Test/BerlinToLondonTests.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
I tested it against different branches from Ethereum/tests repo. Now, we're using develop branch, but we should remember to upgrade the submodule when PRs will be merged
=> Add London Etheruem tests

src/Nethermind/Nethermind.Config/Enode.cs, src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs, src/Nethermind/Nethermind.Network/StaticNodes/StaticNodesManager.cs
=> [Bug] Peers managers fails

src/Nethermind/Nethermind.Blockchain.Test/TxPools/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/TxSortedPoolExtensions.cs, src/Nethermind/Nethermind.TxPool/CompareReplacedTxByFee.cs, src/Nethermind/Nethermind.TxPool/CompareSameIdentityTxByFee.cs
Introduces a minimum requirement of a 10 percent fee increase when replacing transaction
=> Tx replacement improvement

src/Nethermind/Nethermind.Baseline.Test/BaselineTreeTrackerTests.cs, src/Nethermind/Nethermind.Baseline.Test/JsonRpc/BaselineModuleTests.cs, src/Nethermind/Nethermind.Blockchain.Test/BlockProcessorTests.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockProducer.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/NUnitLogManager.cs, src/Nethermind/Nethermind.Core.Test/NUnitLogger.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs
1. Remove infinite waits -> tests will fail instead of haning
2. Fix infinite loop
3. Fix disposing TestBlockchain
4. Fix ReadOnlyState
5. Make multiple AddFunds to one block
=> Test fixes

.github/pull_request_template.md
Closes #3134
- Add a PR template
=> Close #3134 - Add PR Template

.github/ISSUE_TEMPLATE/bug_report.md
- Update Bug Report issue template
=> Update Bug Report Issue template

src/Nethermind/Nethermind.Synchronization/SyncServer.cs
=> Better sync server logging

src/Nethermind/Nethermind.TxPool/TxPool.cs
- fix PendingTransactionsEvicted metric (should be inside of the "if" statement checking if tx was evicted from the pool)
=> Fix PendingTransactionsEvicted metric

CODE_OF_CONDUCT.md
Closes #3157 
- Add Code of Conduct to project's root
The **Scope** section needs special review, as well as the **Contributing** section
=> Close #3157 - Create Code of Conduct

src/Nethermind/Nethermind.AuRa.Test/AuraBlockProcessorTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs
- In normal processing we shouldn't check gas remainig.
=> xDai in normal processing we shouldn't check gas remainig

src/Nethermind/Nethermind.Benchmark.Runner/Nethermind.Benchmark.Runner.csproj, src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs, src/Nethermind/Nethermind.Network.Benchmark/Eth62ProtocolHandlerBenchmarks.cs
Uptadets benchmarks to be buildable.
=> make benchmarks build

src/Nethermind/Nethermind.Mev.Test/MetricsTests.cs, src/Nethermind/Nethermind.Mev/Execution/TxBundleSimulator.cs, src/Nethermind/Nethermind.Mev/Metrics.cs, src/Nethermind/Nethermind.Monitoring.Test/MetricsTests.cs, src/Nethermind/Nethermind.Monitoring.Test/Nethermind.Monitoring.Test.csproj, src/Nethermind/Nethermind.Monitoring/Metrics/MetricsUpdater.cs
- We used incorrect type for Metrics. It resulted with node startup error. Fixed and added tests. 
=> Metrics incorrect type fix

src/Nethermind/Nethermind.Network/Timeouts.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/Timeouts.cs
Wait for first timeout before resetting root hash in state sync
=> Wait for first timeout before switch state root in state sync

src/Nethermind/Chains/test.json, src/Nethermind/Nethermind.Blockchain.Test/GenesisLoaderTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Nethermind.Blockchain.Test.csproj, src/Nethermind/Nethermind.Blockchain.Test/Specs/test.json, src/Nethermind/Nethermind.Blockchain/GenesisLoader.cs, src/Nethermind/Nethermind.Core/Account.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/SetupHive.cs, src/Nethermind/Nethermind.Runner/Hive/HiveConfig.cs, src/Nethermind/Nethermind.Runner/Hive/HiveRunner.cs, src/Nethermind/Nethermind.Runner/Hive/IHiveConfig.cs, src/Nethermind/Nethermind.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Runner/configs/hive.cfg, src/Nethermind/Nethermind.State/IStateProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs
- Fixed some of the problems with genesis. We're not loading accounts with balance = 0 and storage != Empty. That resulted in a genesis mismatch on hive tests. It resolves some of the tests, but not all of them.
=> Hive genesis problems

src/Nethermind/Chains/foundation.json, src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs, src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs, src/Nethermind/Nethermind.Specs.Test/MainnetSpecProviderTests.cs, src/Nethermind/Nethermind.Specs/Forks/12_London.cs, src/Nethermind/Nethermind.Specs/MainNetSpecProvider.cs
- The London block for mainnet 
=> Mainnet london

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/Comparison/CompareReplacedTxByFee.cs
- More info: https://github.com/NethermindEth/nethermind/pull/3211
=> Fix 1559 tx replacement

src/Nethermind/Nethermind.DataMarketplace.Core/Services/NdmBlockchainBridge.cs, src/Nethermind/Nethermind.DataMarketplace.Test/ContractInteractionTest.cs, src/Nethermind/Nethermind.DataMarketplace.Test/Services/NdmBlockchainBridgeTests.cs, src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs, src/Nethermind/Nethermind.Facade/BlockchainBridge.cs, src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Proof/ProofRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/BlockForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofRpcModule.cs
- More info: https://github.com/ethereum/eth1.0-specs/pull/251
=> tx.GasPrice should return effectiveGasPrice or feeCap for 1559 txs

src/Nethermind/Nethermind.Runner/configs/spaceneth.cfg, src/Nethermind/Nethermind.Runner/configs/spaceneth_persistent.cfg
Updating spaceneth.cfg and spaceneth_presistent.cfg with list containing all  modules.
Testing has been done manually based on reported issue.
=> Add enabled modules #3219

scripts/systemd-utils/pullandbuild.sh, scripts/systemd-utils/restart.sh, scripts/systemd-utils/shutdown.sh, scripts/systemd-utils/status.sh, scripts/systemd-utils/tail.sh, scripts/systemd-utils/up.sh
New scripts for better management of development nodes with systems service.
=> adding systemd utility scripts

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs, src/Nethermind/Nethermind.TxPool/Filters/TooExpensiveTxFilter.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
Resolves #3173
- discard transaction if cumulative costs of this transaction and pending transactions with lower nonces exceeds account balance
=> Fix adding latent invalid transactions

.github/workflows/run-nethermind-tests-with-code-coverage.yml, .github/workflows/run-nethermind-tests.yml, src/Nethermind/Nethermind.Evm.Test/EvmStateTests.cs, src/Nethermind/Nethermind.Evm/EvmState.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Mev.Test/BundlePoolTests.cs, src/Nethermind/Nethermind.Mev.Test/MetricsTests.cs, src/Nethermind/Nethermind.Mev.Test/MevRpcModuleTests.cs, src/Nethermind/Nethermind.Mev.Test/TestBundlePool.cs, src/Nethermind/Nethermind.Mev/Data/MevBundle.cs, src/Nethermind/Nethermind.State/StateProvider.cs
- fixing a bug that occasionally raises an exception when producing blocks, when an out of gas transaction is followed by a reverting transaction
=> block production bugfix

src/Nethermind/Nethermind.Blockchain.Test/TransactionsExecutorTests.cs, src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.BlockProductionTransactionPicker.cs
-This could affect nodes when we're signer
=> One more balance fix

scripts/syncSettings.py, src/Nethermind/Nethermind.Runner/configs/goerli_mev.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet_mev.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_mev.cfg
Configs for `mainnet`, `goerli` and `xdai` networks with MEV enabled by default.
Should be covered by the default configs tests.s
=> adding mev default configs for xdai, goerli and mainnet + auto update

src/Nethermind/Nethermind.HealthChecks.Test/HealthChecksWebhookInfoTests.cs, src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs, src/Nethermind/Nethermind.HealthChecks/HealthChecksWebhookInfo.cs
Modified health checks notifications, so that they give more information (description if node is unhealthy, node name, hostname, ip).
=> changed healthchecks notifications

src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs, src/Nethermind/Nethermind.HealthChecks/NodeHealthService.cs
=> HealthChecks message change

src/Nethermind/Nethermind.Blockchain/Find/BlockParameter.cs, src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs, src/Nethermind/Nethermind.JsonRpc/Data/BlockParameterConverter.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/Filter.cs
Closes #3265 PR
Remove obsolete (and buggy) deserialization.
=> Fix BlockParameter parsing for filters

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs
- I hope we will fix it later. Lower priority for now.
- [] Yes
=> Ignore flaky tests

src/Nethermind/Nethermind.Sockets.Test/Nethermind.Sockets.Test.csproj
Remove references to non existing WebSockets folder.
=> Remove reference to WebSockets folder

scripts/syncSettings.py, src/Nethermind/Nethermind.Runner/configs/goerli_pruned_mev.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet_pruned_mev.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_pruned_mev.cfg
Adding pruned mev configs for `goerli`, `xdai` and `mainnet`.
=> adding pruned mev configs

src/Nethermind/Nethermind.Blockchain.Test/TransactionGasPriceComparisonTests.cs, src/Nethermind/Nethermind.Blockchain/Comparers/GasPriceTxComparer.cs, src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs, src/Nethermind/Nethermind.Core/Transaction.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
Just move it to master too: https://github.com/NethermindEth/nethermind/pull/3294
=> Tx pool fix (#3294)

scripts/packaging/archive-packages.sh, scripts/packaging/azure-upload.sh
=> Building linux package with latest tag

src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs
- fix test NewHeadSubscription_should_send_notifications_when_adding_multiple_blocks_at_once_and_after_reorgs()
Thread.Sleep is replaced by ManualResetEvent now
=> Fix flaky test in SubscribeModuleTests

src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
=> fix benchamrks

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/xdai.cfg, src/Nethermind/Nethermind.Runner/configs/xdai1559.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_archive.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_archive_pruned.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_mev.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_pruned.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_pruned_mev.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_validator.cfg
Increase xdai tx pool size from 1k -> 2k
=> Increase xdai tx pool size from 1k -> 2k

src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.TestAccountAbstractionRpcBlockchain.cs, src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationPoolTests.cs, src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs, src/Nethermind/Nethermind.AccountAbstraction/Broadcaster/IUserOperationPoolPeer.cs, src/Nethermind/Nethermind.AccountAbstraction/Broadcaster/MemoryAllowance.cs, src/Nethermind/Nethermind.AccountAbstraction/Broadcaster/PeerInfo.cs, src/Nethermind/Nethermind.AccountAbstraction/Broadcaster/UserOperationBroadcaster.cs, src/Nethermind/Nethermind.AccountAbstraction/Broadcaster/UserOperationExtensions.cs, src/Nethermind/Nethermind.AccountAbstraction/Data/UserOperation.Rlp.cs, src/Nethermind/Nethermind.AccountAbstraction/Data/UserOperation.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs, src/Nethermind/Nethermind.Network/P2P/Protocol.cs
-
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Yes
- [ x ] No
Will add the test cases once @kristofgazso approves the approach
If this is a relatively large or complex change, kick off the discussion by explaining why you chose …
=> Getting capabilities using nethermindAPI functionality

.github/workflows/alert-on-issue-open-event.yml, .github/workflows/build-nethermind-docker-images.yml, .github/workflows/build-nethtest-hive-docker-images.yml, .github/workflows/release-nethermind.yml, .github/workflows/run-benchmarks-tests.yml, .github/workflows/run-nethermind-tests-with-code-coverage.yml, .github/workflows/run-truffle-smoke-tests.yml, .github/workflows/update-config-files.yml, .github/workflows/update-dappnode-package.yml, .github/workflows/update-gitbook-docs.yml
=> GHA Vault removal

src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/BoundedModulePoolTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/GasPriceOracleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SingletonModulePoolTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModuleFactory.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/GasPrice/EthGasPriceConstants.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/GasPrice/GasPriceOracle.cs
Use IMinerConfig.MinGasPrice as default gas price in empty block, instead of some arbitrary number
=> Use IMinerConfig.MinGasPrice as default gas price in empty block

src/Nethermind/Nethermind.Consensus.AuRa/Contracts/VersionedContract.cs
=> Change V1 permission contract warning to debug

src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
=> Fix benchmark solution

src/Nethermind/Ethereum.Blockchain.Legacy.Test/SpecialTests.cs, src/Nethermind/Ethereum.Blockchain.Test/CreateTests.cs, src/Nethermind/Ethereum.Blockchain.Test/VmPerformanceTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs
=> add retries for flaky tests

src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
=> Fix build Benchmarks.sln

src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs, src/Nethermind/Nethermind.sln
Remove obsolete config value, fix docs
=> Remove find log block depth limit

src/Nethermind/Nethermind.Api/IInitConfig.cs, src/Nethermind/Nethermind.Api/InitConfig.cs, src/Nethermind/Nethermind.Logging.NLog/NLogLogger.cs, src/Nethermind/Nethermind.Logging.NLog/NLogManager.cs, src/Nethermind/Nethermind.Runner.Test/EthereumRunnerTests.cs, src/Nethermind/Nethermind.Runner/Program.cs
- Added support for configuration options as an argument for Nethermind.Runner.
**In case you checked yes, did you write test(s)??**
=> Logging changes

src/Nethermind/Ethereum.Blockchain.Block.Test/GasPricerTests.cs, src/Nethermind/Ethereum.Blockchain.Block.Test/StateTests.cs, src/Nethermind/Ethereum.Blockchain.Block.Test/VmPerformanceTests.cs, src/Nethermind/Ethereum.Blockchain.Block.Test/WalletTests.cs, src/Nethermind/Ethereum.Blockchain.Test/SpecialTests.cs, src/Nethermind/Nethermind.AuRa.Test/AuRaBlockProducerTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Producers/BuildBlockRegularlyTests.cs, src/Nethermind/Nethermind.DataMarketplace.Test/Services/PriceServiceTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/SessionTests.cs
- Add retries to frequently failing tests
flaky tests
=> Add retries to more flaky tests

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/energyweb.cfg, src/Nethermind/Nethermind.Runner/configs/energyweb_pruned.cfg, src/Nethermind/Nethermind.Runner/configs/volta.cfg, src/Nethermind/Nethermind.Runner/configs/volta_archive.cfg, src/Nethermind/Nethermind.Runner/configs/volta_archive_pruned.cfg, src/Nethermind/Nethermind.Runner/configs/volta_pruned.cfg
=> Update memory hints in EWC and Volta configs

src/Nethermind/Nethermind.TxPool.Test/Collections/SortedPoolTests.cs, src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
- we should remove empty buckets in SortedPool, now we have unnecessary trash in memory
=> Remove empty buckets

src/Nethermind/Nethermind.AuRa.Test/BuildBlocksOnAuRaStepsTests.cs, src/Nethermind/Nethermind.Blockchain/Producers/BuildBlocksInALoop.cs, src/Nethermind/Nethermind.Blockchain/Producers/BuildBlocksOnlyWhenNotProcessing.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Core/DisposableStack.cs
Make BuildBlocksInALoop async disposable, make tests more reliable.
=> Improve BuildBlocksInALoop dispose + tests

src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutePayloadResult.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/SyncStatus.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/VerificationStatus.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
Added methods declarations from https://hackmd.io/@n0ble/consensus_api_design_space# to IEngineRpcModule class.
=> Engine api methods

src/Nethermind/Nethermind.AuRa.Test/AuRaBlockProducerTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/GasPriceOracleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/GasPrice/GasPriceOracle.cs
- For eth_gasPrice we need the default value to be at least 110% of MinGasPrice. Otherwise, it will be filtered by MinGasPriceTxFilter in xDAI
=> Default gasPrice change

src/Nethermind/Nethermind.Consensus.Ethash/Ethash.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
=> Force validation in block downloader

src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs, src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs, src/Nethermind/Nethermind.Specs/Forks/00_Olympic.cs, src/Nethermind/Nethermind.Specs/Forks/01_Frontier.cs, src/Nethermind/Nethermind.Specs/Forks/02_Homestead.cs, src/Nethermind/Nethermind.Specs/Forks/03_Dao.cs, src/Nethermind/Nethermind.Specs/Forks/04_TangerineWhistle.cs, src/Nethermind/Nethermind.Specs/Forks/05_SpuriousDragon.cs, src/Nethermind/Nethermind.Specs/Forks/06_Byzantium.cs, src/Nethermind/Nethermind.Specs/Forks/07_Constantinople.cs, src/Nethermind/Nethermind.Specs/Forks/08_ConstantinopleFix.cs, src/Nethermind/Nethermind.Specs/Forks/09_Istanbul.cs, src/Nethermind/Nethermind.Specs/Forks/10_MuirGlacier.cs, src/Nethermind/Nethermind.Specs/Forks/11_Berlin.cs, src/Nethermind/Nethermind.Specs/Forks/12_London.cs, src/Nethermind/Nethermind.Specs/ReleaseSpec.cs, src/Nethermind/Nethermind.Specs/SystemTransactionReleaseSpec.cs
Added EIP3675 to IReleaseSpec and ChainSpecBasedSpecProviderTests.
=> EIP-3675 preparation

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EstimateGas.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EthCall.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthModule.TransactionExecutor.cs
Standarizes all excecution error codes.
=> Standarize excecution errors

src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.DataMarketplace.Infrastructure/NdmApi.cs, src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/TxFloodControllerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/ProtocolsManagerTests.cs, src/Nethermind/Nethermind.Network/Discovery/DiscoveryApp.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V64/Eth64ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs, src/Nethermind/Nethermind.Network/ProtocolsManager.cs, src/Nethermind/Nethermind.Synchronization/ISyncServer.cs, src/Nethermind/Nethermind.Synchronization/SyncServer.cs
Changes in network for the merge - to discuss
=> Network for the merge

src/Nethermind/Nethermind.Analytics/RewardsVerifier.cs, src/Nethermind/Nethermind.AuRa.Test/Contract/AuRaContractGasLimitOverrideTests.cs, src/Nethermind/Nethermind.AuRa.Test/Transactions/TxCertifierFilterTests.cs, src/Nethermind/Nethermind.AuRa.Test/Transactions/TxPermissionFilterTest.cs, src/Nethermind/Nethermind.Blockchain.Test/BlockProcessorTests.cs, src/Nethermind/Nethermind.Blockchain.Test/ReorgTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Rewards/RewardCalculatorTests.cs, src/Nethermind/Nethermind.Consensus.Ethash/EthashPlugin.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin/MergeRewardCalculator.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncThreadTests.cs
- Changing post-merge rewards calculator.
=> Block rewards

src/Nethermind/Ethereum.VM.Test/VMTestBase.cs, src/Nethermind/Nethermind.Evm.Test/EvmPooledMemoryTests.cs, src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Inspect instead of Load in Virtual Machine tracer
=> Inspect in VM with tracer

src/Nethermind/Nethermind.Merge.Plugin.Test/MergeRewardCalculatorTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/PoSSwitcherTests.cs
- Added tests for MergeRewardCalculator and PoSSwitcher.
=> Test merge rewards

src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs, src/Nethermind/Nethermind.Runner/JsonRpc/JsonRpcIpcRunner.cs, src/Nethermind/Nethermind.Sockets.Test/WebSocketExtensionsTests.cs, src/Nethermind/Nethermind.Sockets/IpcSocketsHandler.cs, src/Nethermind/Nethermind.Sockets/WebSocketHandler.cs
Improve handling of edge cases on sockets
=> Improve sockets handling

src/Nethermind/Nethermind.Blockchain.Test/Nethermind.Blockchain.Test.csproj, src/Nethermind/Nethermind.Blockchain.Test/Validators/HeaderValidatorTests.cs, src/Nethermind/Nethermind.Blockchain/Validators/HeaderValidator.cs
- Added tests for HeaderValidator behaviour after The Merge.
=> Header validity tests

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/BlockRequestResult.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/PayloadStorage.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/PreparePayloadHandler.cs
- Added random field to BlockRequestResult and set it in engine_getPayload to the value supplied in corresponding engine_preparePayload call.
=> Add random field

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/PreparePayloadHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/MergeErrorCodes.cs
=> tests for prepare and get payload

src/Nethermind/Nethermind.Sockets/WebSocketHandler.cs
Fixes #3464
Whenever a client disconnects without a handshake we get Socket Error = 10054. We should handle it gracefully.
The web socket connection will be closed without logging an error whenever we get Socket Error = 10054
=> Handle WS client disconnection without a handshake

src/Nethermind/Nethermind.TxPool/Metrics.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
=> Improve tx pool metrics

src/Nethermind/Nethermind.Runner/configs/xdai.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_archive.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_archive_pruned.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_mev.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_pruned.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_pruned_mev.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_validator.cfg
Increase xdai mem pool default size to 8192
=> Increase xdai tx pool size to 8192

src/Nethermind/Nethermind.Analytics/AnalyticsWebSocketsModule.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcUrlCollectionTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcUrlTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcModuleProviderTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcUrlCollection.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcContext.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcUrl.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs, src/Nethermind/Nethermind.JsonRpc/Modules/IRpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/Modules/NullModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/RegisterRpcModulesTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/JsonRpcRunner.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs, src/Nethermind/Nethermind.Runner/JsonRpc/JsonRpcIpcRunner.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Sockets.Test/WebSocketExtensionsTests.cs, src/Nethermind/Nethermind.Sockets/Extensions.cs, src/Nethermind/Nethermind.Sockets/IWebSocketsModule.cs
Merge from an external repository for code review and testing.
=> Merge to Feature/3535_MultipleJsonrpcUrls

src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs
Fix trace dumps on invalid block
=> fix trace dumps

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.TestVectorsV1.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.cs
=> The Merge - Kintsugi Test Vectors

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutePayloadV1Result.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/ExecutePayloadV1Handler.cs, src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
- Implements `engine_executePayloadV1` response as per Kintsugi specs
=> Add execute_PayloadV1 rpc endpoint

src/Nethermind/Nethermind.Core/NetworkDiagTracer.cs, src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
Push NetworkDiagTracer logs to standard log to help with user issues
=> Push NetworkDiagTracer logs to standard log

src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/PaymasterThrottler.cs
- Enables Account Abstraction RPCModule independently of whether mining is enabled or not
- Adds constructor parameter to PaymasterThrottler to allow the use of different constants depending on the _mining mode_
=> [WIP] Account abstraction while not mining

src/Nethermind/Nethermind.Core/Transaction.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs
Resolves https://github.com/NethermindEth/nethermind/issues/3276.
Added yParity field for EIP-2930 and 1559 transactions.
=> Added yParity for eip-2930 and 1559 transactions.

src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
Fixes #3089
Properly handles single feed dispatched requests
Will test on POA nodes as they experience the issue daily.
=> Fix sync dispatcher in single feed mode by adding continuation

src/Nethermind/Nethermind.Sockets/WebSocketHandler.cs
=> Silence premature web socket disconnections.

src/Nethermind/Nethermind.AuRa.Test/AuRaBlockProducerTests.cs, src/Nethermind/Nethermind.AuRa.Test/BuildBlocksOnAuRaStepsTests.cs, src/Nethermind/Nethermind.Blockchain/Producers/BuildBlocksInALoop.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuraBlockProductionTrigger.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs
Fix race condition in BuildBlocksOnAuRaSteps, between loop in background thread and constructor.
=> Fix AuRa validator startup race condition

src/Nethermind/Nethermind.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Runner/configs/themerge_kintsugi_m2.cfg, src/Nethermind/Nethermind.Runner/configs/themerge_kintsugi_mev.cfg, src/Nethermind/Nethermind.Runner/configs/themerge_kintsugi_testvectors.cfg, src/Nethermind/Nethermind.sln
- Added MEV config, also added some fixes to the merge configs
=> Add Mev config

.github/workflows/run-nethermind-tests-with-code-coverage.yml
=> Move code coverage run to linux only

src/Nethermind/Nethermind.Cli/Modules/EthCliModule.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.FeeHistory.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModuleProxy.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/FeeHistory/FeeHistoryOracle.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/FeeHistory/IFeeHistoryOracle.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
Resolves https://github.com/NethermindEth/nethermind/issues/3639.
Changed type of blockCount parameter in eth_feeHistory from int to long.
=> Changed type of blockCount parameter in eth_feeHistory.

.github/workflows/build-baseline.yml, .github/workflows/build-solution.yml, src/Nethermind/Baseline.sln, src/Nethermind/Cortex.sln
Fixes #2878 
- Adds a GHA Job to build `baseline.sln` on CI
- Fixes file path on `baseline.sln` 
=> CI: Build solution files on GHA

src/Nethermind/Nethermind.Blockchain/KnownChainSizes.cs, src/Nethermind/Nethermind.Core/ChainId.cs
Resolves #2442
Manual update of known chain sizes for different chains based on Grafana data.
=> updating chain sizes

src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/Filter.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/NewHeadSubscription.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/NewPendingTransactionsSubscription.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SubscriptionFactory.cs
Resolves https://github.com/NethermindEth/nethermind/issues/3455.
Added includeTransactions option to eth_subscribe for new headers and pending transactions.
=> Add more subscription options

src/Nethermind/Nethermind.Blockchain/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs, src/Nethermind/Nethermind.Blockchain/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.Blockchain/Tracing/IGethStyleTracer.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ChangeableTransactionProcessorAdapter.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugModuleFactory.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugRpcModule.cs, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
=> Add debug_traceCall

src/Nethermind/Nethermind.Network.Enr/EnrContentEntry.cs, src/Nethermind/Nethermind.Network.Enr/EnrContentKey.cs, src/Nethermind/Nethermind.Network.Enr/ForkId.cs, src/Nethermind/Nethermind.Network.Enr/IdEntry.cs, src/Nethermind/Nethermind.Network.Enr/IpEntry.cs, src/Nethermind/Nethermind.Network.Enr/NodeRecord.cs, src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs, src/Nethermind/Nethermind.Network.Enr/Secp256K1Entry.cs, src/Nethermind/Nethermind.Network.Enr/TcpEntry.cs, src/Nethermind/Nethermind.Network.Enr/UdpEntry.cs
Addresses some of #3709
Added comments to the ENR code
=> added comments

src/Nethermind/Nethermind.Blockchain.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Db/Blooms/FixedSizeFileStore.cs
Update bloom storage before updating main chain. Its ok to do that before updating main chain.
=> Save blooms before blocks

src/Nethermind/Nethermind.AuRa.Test/Transactions/TxCertifierFilterTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxCertifierFilter.cs, src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs
-
Came up in a desynchronized (due to clock) validator on restart.
=> Fix null sender address handling in TxCertifierFilter

src/Nethermind/Nethermind.Core/NetworkDiagTracer.cs
Clear events in NetworkDiagTracer
=> Clear events in NetworkDiagTracer

src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs, src/Nethermind/Nethermind.HealthChecks/HealthRpcModule.cs, src/Nethermind/Nethermind.HealthChecks/NodeHealthChecks.cs
- Unfortunately, it doesn't fix the root cause of the last problem with healtchecks (99%),
- [] No
I performed manual testing
=> Health Checks, removed unnecessary Task.Run

src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs, src/Nethermind/Nethermind.HealthChecks/HealthRpcModule.cs, src/Nethermind/Nethermind.HealthChecks/NodeHealthChecks.cs
=> Healthchecks extra logs

src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Merge.Plugin/MergeFinalizationManager.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin/Nethermind.Merge.Plugin.csproj
=> Add FinalizationManager to AuRa

src/Nethermind/Nethermind.Core/Crypto/Keccak.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/ZeroNettyP2PHandler.cs, src/Nethermind/Nethermind.State/StateTree.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
Simple files refactorizations.
=> Minor files refactorizations

src/Nethermind/Nethermind.Cli/Modules/EthCliModule.cs, src/Nethermind/Nethermind.Core/TransactionExtensions.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/GasPriceOracleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModuleProxy.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/GasPrice/EthGasPriceConstants.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/GasPrice/GasPriceOracle.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/GasPrice/IGasPriceOracle.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
Added eth_maxPriorityFeePerGas implementation.
=> Eth max priority fee per gas implementation

.github/workflows/build-nethermind-docker-images.yml, Dockerfile.dev
`Dockerfile.dev` with dotmemory and dottrace tools preinstalled. 
Adding Dockerfile input to the github workflow for building docker images.
=> adding dockerfile input to github workflow docker image builder

.github/workflows/release-nethermind.yml, .github/workflows/update-config-files.yml, .github/workflows/update-poa-bootnodes.yml
Add permissions to the GITHUB_TOKEN scope in GHA workflows.
=> adding gha permissions

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
=> Fix payload body tests

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs, src/Nethermind/Nethermind.Db/MetadataDbKeys.cs, src/Nethermind/Nethermind.Db/Metrics.cs, src/Nethermind/Nethermind.Db/StandardDbInitializer.cs
=> Add metadata db

src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/Extensions.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorTests.Scenario.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorTests.cs
Make MultiSyncModeSelectorTests more readable.
=> Refactorize MultiSyncModeSelectorTests

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/PayloadService.cs, src/Nethermind/Nethermind.Merge.Plugin/IMergeConfig.cs, src/Nethermind/Nethermind.Merge.Plugin/MergeConfig.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
- SuggestedFeeRecipient assigned from MergeConfig
=> Get SuggestedFeeRecipient from config

src/Nethermind/Nethermind.Hive/HiveRunner.cs
- catch RlpException when decoding block in HiveRunner. It is fixing 3 hive consensus tests - BerlinToLondon.
It is tested in hive tests
=> Catch RlpException when decoding block in HiveRunner

src/Nethermind/Nethermind.Network.Dns/EnrTreeCrawler.cs, src/Nethermind/Nethermind.Network.Dns/IDnsClient.cs
Closes #3801
Ignore DNS call when servers unavailable.
Make it allocate less.
=> Refactor DNS crawling to allocate less

README.md
Added sepolia to networks list
=> Added sepolia to networks list

src/Nethermind/Nethermind.Mev/Source/BundlePool.cs
=> Remove simulations more agresivly in MEV

.github/workflows/release-nethermind.yml
=> updated GH Action permissions

src/Nethermind/Nethermind.Core/Authentication/MicrosoftJwtAuthentication.cs, src/Nethermind/Nethermind.Core/Nethermind.Core.csproj, src/Nethermind/Nethermind.Merge.Plugin.Test/JwtTest.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Jwt auth implementation using microsoft library
=> Jwt auth implementation using microsoft library

src/Nethermind/Nethermind.Merge.Plugin/Data/V1/ForkchoiceStateV1.cs
-     Add toString for ForkchoiceStateV1.cs
- [ x] No
- [ x] No
=> Kiln logging

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
=> fix debug_resetHead to also reset best state

src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionPeerManagerTests.cs, src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.TestAccountAbstractionRpcBlockchain.cs, src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationPoolTests.cs, src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs, src/Nethermind/Nethermind.AccountAbstraction/Network/AccountAbstractionPeerManager.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/IUserOperationBroadcaster.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationBroadcaster.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs
- Fix issue that Nethermind was not able to transmit ops even though it was able to receive them
=> [AA] Fix p2p broadcasting

src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs, src/Nethermind/Nethermind.Logging/TestErrorLogManager.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.Wallet.Test/WalletTests.cs
ConcurrentBag doesn't work well with multi-thread access
=> Remove ConcurrentBag, replace with ConcurrentQueue

src/Nethermind/Nethermind.Core/Collections/JournalSet.cs
This PR simplifies the `JournalSet<T>` by replacing `Dictionary<int,T>`` that was index based anyway with a list `List<T>`. This is a small change based on reviewing `EvmState` & `VirtualMachine` implementations. Not having a dictionary and using a list instead should be lighter.
- `JournalSet<T>` uses a list instead of a `Dictionary<int,T>` now
=> JournalSet trimmed

src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationTracerTests.cs, src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationTracer.cs, src/Nethermind/Nethermind.Evm.Test/InstructionTests.cs, src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs, src/Nethermind/Nethermind.Evm.Test/TestAllTracerWithOutput.cs, src/Nethermind/Nethermind.Evm/Instruction.cs, src/Nethermind/Nethermind.Evm/Tracing/AccessTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/AlwaysCancelTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/CallOutputTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/CompositeTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/EstimateGasTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofTxTracer.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Mev/BeneficiaryTracer.cs, src/Nethermind/Nethermind.Mev/Execution/TxBundleSimulator.cs, src/Nethermind/Nethermind.State.Test.Runner/StateTestTxTracer.cs
- Rename DIFFICULTY opcode to PREVRANDAO
=> Change DIFFICULTY to PREVRANDAO

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
Removing Count that was using System.Collections.Concurrent.ConcurrentDictionary`2.AcquireLocks(Int32, Int32, ref Int32)
=> Speed up node caching

src/Nethermind/Nethermind.EthStats/Integrations/EthStatsIntegration.cs
Send blocks max 4x per s, rather than 40x times
=> Reduce rate of sending blocks when batch bloks are being processed

src/Nethermind/Nethermind.EthStats.Test/EthStatsPluginTests.cs, src/Nethermind/Nethermind.EthStats.Test/Nethermind.EthStats.Test.csproj, src/Nethermind/Nethermind.EthStats/EthStatsPlugin.cs
=> Dispose fix - EthStatsPlugin

README.md
* Added README instructions for Apple Silicon users to symlink Snappy homebrew dependency
Resolves #3745
- Edited README with instructions for Apple Silicon users to create a symlink for Snappy homebrew dependency
=> fix: add instructions for Apple Silicon users for symlink brew dependencies

src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
This  gives better chance to catch up with the chain during state sync
Was tested on VM, reduced the last part of state sync and made it more reliable
=> Increase fast sync lag to 32

src/Nethermind/Nethermind.Blockchain/KnownChainSizes.cs
Latest size and growth estimates
=> Update mainnet chain size and growth estimate

src/Nethermind/Nethermind.Blockchain/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Blockchain/Processing/ProcessingStats.cs
Statistical logging of processing time now shows actual time spent on processing blocks and total time passed since last logs.
Tested by running the app and checking logs
=> Measure processing time in accurate way

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs
- Latest block after re-org test
- [ x ] Other (please describe): test
=> Latest block after reorg test

src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerType.cs
- Add Eth2MergeFullWithoutTTD
-  fix failing tests
- [x ] Yes
- [x ] Yes
=> Add Eth2MergeFullWithoutTTD and fix failing tests

src/Nethermind/Nethermind.Merge.Plugin.Test/MergeBetterPeerStrategyTests.cs, src/Nethermind/Nethermind.Synchronization.Test/TotalDifficultyBasedBetterPeerStrategyTests.cs
- MergeBetterPeerStrategyTests
=> Merge sync - merge better peer strategy tests

README.md
Makes the `README.md` badges more compact and clean.
=> Updating README.md with badges

src/Nethermind/Nethermind.State/StateProvider.cs
- fix state provider in order to pass hive consensus tests
Hive consensus tests are passing now
=> Fix state provider

src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs
- fix MarkChainAsProcessed_does_not_change_main_chain test
=> fix MarkChainAsProcessed_does_not_change_main_chain test

src/Nethermind/Nethermind.Init/MemoryHintMan.cs, src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs, src/Nethermind/Nethermind.Network/Config/INetworkConfig.cs, src/Nethermind/Nethermind.Network/Config/NetworkConfig.cs, src/Nethermind/Nethermind.Network/PeerManager.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
MaxActivePeers are now configurable, closes #4026
=> Fix MaxActivePeers config

.github/workflows/run-merge-hive-tests.yml
Adds a workflow that builds a docker image and tests that image with the merge hive tests each time someone pushes to the kiln branch.
=> Create Merge Hive Test Workflow

src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs, src/Nethermind/Nethermind.Merge.Plugin/PoSSwitcher.cs
- remove pos switcher fcu
- [] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation Update
- [] Code style update (formatting, renaming)
- [] Other (please describe): 
- [] No
=> remove IPoSSwitcher.cs fcu

src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationSimulator.cs, src/Nethermind/Nethermind.Blockchain/Processing/ReadOnlyTxProcessingEnv.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ReadOnlyTransactionProcessor.cs, src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
Fixes #4002
State was not properly reset on rpc context after gas estimation
=> Fix state reset after estimate gas

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloaderFactory.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeSynchronizer.cs, src/Nethermind/Nethermind.Synchronization.Test/OldStyleFullSynchronizerTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncThreadTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs, src/Nethermind/Nethermind.Synchronization/Blocks/IBlockDownloaderFactory.cs, src/Nethermind/Nethermind.Synchronization/Synchronizer.cs
=> Fix duplicated SyncReport

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs, src/Nethermind/Nethermind.sln.DotSettings
Improve messages logging when gossiping is disabled
=> Better gossip logs

.github/workflows/run-merge-hive-tests.yml
Fixes Merge Hive Test
- Uploads entire Workspace directory
=> Fix Merge Hive Tests

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
- Fix CLI startup failure when Nethermind.Merge.Plugin presents
=> Add Nethermind.Merge.Plugin dependencies

src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs, src/Nethermind/Nethermind.Runner/NLog.config, src/Nethermind/Nethermind.Runner/configs/kiln_fastsync.cfg
=> +5 green hive tests (inconsistency checks)

src/Nethermind/Nethermind.TxPool/Filters/FeeTooLowFilter.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
=> Optimize FeeTooLowFilter and add additional tracing to check for issues

src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncMode.cs
=> Fix sync modes after merging

src/Nethermind/Nethermind.Runner/configs/kiln_relay.cfg
- Add config for boost-builder integration
=> Add Kiln Builder Relay Config

.github/workflows/run-merge-hive-tests.yml, scripts/testing/hiveTestResultPrinter.py, src/Nethermind/Nethermind.AuRa.Test/BuildBlocksOnAuRaStepsTests.cs
- Changed Docker image name
- Changed Hive repo to a fork with the same docker image name
Funny enough my previous set-up was meant to save to me and not break things
=> Update Merge Hive Workflow

scripts/testing/hiveTestResultPrinter.py
Edited it so it prints the number of passed and failed tests with each run.
- Remove extra code
- Added Total number of tests passed and failed to outputs.
It just needs to be ran once
=> Updated HiveTestResultPrintter

src/Nethermind/Nethermind.Blockchain.Test/Find/LogFinderTests.cs, src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs, src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs
Fix receipt not found when block does not have a transaction.
- Check for tx root of block if it is empty.
- [X x] Bugfix (non-breaking change which fixes an issue)
Testing...
=> Fix receipt not found when block does not have transaction

src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
Resolves #4131 
- Enable FastSync on config level if SnapSync is enabled
=> SnapSync enables FastSync

src/Nethermind/Chains/sepolia.json, src/Nethermind/Nethermind.Runner/configs/sepolia.cfg, src/Nethermind/Nethermind.Runner/configs/sepolia_archive.cfg
- add merge configs for sepolia
=> Sepolia TheMerge configs

.github/workflows/run-posdao-tests.yml
=> Always upload logs from posdao-tests

src/Nethermind/Nethermind.Blockchain/Metrics.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core/ChainId.cs, src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
=> Add TotalDifficulty and LastDifficulty metrics

src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.TestAccountAbstractionRpcBlockchain.cs, src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.cs, src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationTracerTests.cs, src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs, src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationSimulator.cs, src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationTracer.cs, src/Nethermind/Nethermind.AccountAbstraction/Executor/UserOperationTxBuilder.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationTxSource.cs, src/Nethermind/Nethermind.Consensus/Processing/ReadOnlyTxProcessingEnvFactory.cs, src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.State/IReadOnlyStateProvider.cs
- Remove usages of StateProvider within the AA plugin
=> Fix AA state provider

.github/workflows/run-nethermind-tests.yml
=> Rebalance test workflow + add pull_request

src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
Fixes | Closes | Resolves #3958
- Allow GetChild to run in parallel
=> Add separate stream for every child loading

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/ropsten.cfg, src/Nethermind/Nethermind.Runner/configs/ropsten_archive.cfg
- enable SnapSync as default for ropsten
- replace stale EthStats
- add test for SnapSync enabled
default config change
=> Ropsten: SnapSync as default

.github/workflows/run-nethermind-tests.yml
=> More rebalancing

src/Nethermind/Chains/sepolia.json, src/Nethermind/Nethermind.Runner/configs/sepolia.cfg, src/Nethermind/Nethermind.Runner/configs/sepolia_archive.cfg, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs, src/Nethermind/Nethermind.Specs/SepoliaSpecProvider.cs
- update Sepolia TTD to 17_000_000_000_000_000 (3C6568F12E8000)
TTD update
=> Sepolia TTD update

src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncDispatcher.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/HeadersSyncDispatcher.cs
- Wrap timeout exception and log on debug level what it happen
=> Reduce sync timeout error level to debug

src/Nethermind/Nethermind.Runner/configs/mainnet_shadowfork.cfg
- update mainnet_shadowfork pivot
- add SnapSync as default
update pivot
=> Update mainnet_shadowfork pivot and add SnapSync as default

src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
- Throw an exception if receipt not available when merge is enabled.
=> Throw an exception if receipt not available with merge

src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
- Change `PayloadPreparationService` to not remove payloads after serving them
- [] No
=> Don't remove payload right after serving them

src/Nethermind/Nethermind.Core/Authentication/MicrosoftJwtAuthentication.cs
- Auth log messages have been improved
- [ x ] Refactoring (no functional changes, no api changes)
- [ x ] No
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
=> Auth log messages

.github/workflows/run-posdao-tests.yml
- Adds cl logs in posdao tests setup
=> Add cl logs collection to posdao tests ci workflow

.github/workflows/run-posdao-tests.yml
- Upload posdao logs even if cancelled workflow
=> Add `if: always()` to upload posdao logs even if cancelled

src/Nethermind/Nethermind.Hive/HiveRunner.cs
- revert timeout change - we had regression in engine tests
=> HiveRunner: timeout is back

src/Nethermind/Chains/sepolia.json, src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs, src/Nethermind/Nethermind.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Specs/KnownHashes.cs, src/Nethermind/Nethermind.Specs/SepoliaSpecProvider.cs
https://github.com/ethereum/execution-specs/pull/564
https://discord.com/channels/595666850260713488/745077610685661265/999980766291316796
**ForkId**: 0xb96cbd13
=> Sepolia Merge Transition Fork Id

src/Nethermind/Nethermind.Core/Authentication/MicrosoftJwtAuthentication.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/JwtTest.cs
- Jwt token TTL increased to 60 seconds due to proposal
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] No
=> Jwt token TTL increased to 60 seconds

src/Nethermind/Nethermind.Core/TxTypeExtensions.cs, src/Nethermind/Nethermind.JsonRpc.Test/Data/Eip2930Tests.cs, src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs
Fix in TransacitonForRpc, AccessList should work with TxType = 1 (AccessList) and TxType = 2 (EIP1559)
=> Access List 1559 fix

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj, src/Nethermind/Nethermind.Runner/Program.cs
=> Patch further versions if 1.13.5 touched the dbs

.github/workflows/run-merge-hive-tests.yml
Fix hive test workflow
- added option for ethereum/rpc-compat tests
- added option for ethereum/sync tests
I ran both of the new tests and they are working as expected.
=> Hive workflow - add more test suites

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ExchangeTransitionConfigurationV1Handler.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs, src/Nethermind/Nethermind.Synchronization/SyncServer.cs
Context for TTD placeholder: https://discord.com/channels/595666850260713488/892088344438255616/1002142052575887410
=> More gossip transition tests + TTD placeholder for CL

src/Nethermind/Nethermind.Wallet/ProtectedKeyStoreWallet.cs
Replace `MemoryCache` with `LruCache` in `ProtectedKeyStoreWallet`
=> replace with lru cache

src/Nethermind/Nethermind.Blockchain/BlockchainException.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockHashEventArgs.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/NewPayloadV1Handler.cs
=> Enhance exception handling

src/Nethermind/Nethermind.Trie.Test/PruningScenariosTests.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
Probably fix trie exception.
- Same modification to `CanPruneCacheFurther` as before, but on `Dispose`.
=> Fix probably cause of trie exception on restart

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs
I expected that I would find the issue, but it is working fine, so I've just added one more unit test.
=> One more unit test for Engine API

src/Nethermind/Nethermind.Runner/configs/goerli_shadowfork.cfg
- Update goerli_shadowfork pivot
=> Update goerli_shadowfork pivot

.github/workflows/run-nethermind-tests.yml
Resolves #4363
- Try cancel previous run
=> Try bringing test cancellation back

LICENSE-GPL, LICENSE-LGPL, README.md
- The first paragraph of the README is revised to fix English issues and typos. `.NET Core` is replaced with `.NET`
- The LICENSE is split into two separate files for each license to allow GitHub [correctly handle](https://github.blog/changelog/2022-05-26-easily-discover-and-navigate-to-multiple-licenses-in-repositories/) them
=> Revise README and separate LICENSE files

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
Remove a log that I forgot to remove.
- Remove a log line.
=> Remove missed debug log

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/ChainLevelHelper.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs
- Fix post merge sync hangs.
- Ropsten can sync.
=> Fix post merge sync

src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
=> Add default value for EngineHost

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
Resolves #4385
Added Header to Peer Report
=> Add PeerReport Header

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
Only show header when there are peers to list
=> Fix peer header when no peers to show

src/Nethermind/Nethermind.Runner/configs/mainnet_shadowfork.cfg
- Update mainnet_shadowfork pivot
=> Update mainnet_shadowfork pivot

src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
remove one extra loop for transaction calls
=> remove extra loop

src/Nethermind/Nethermind.Runner/configs/chiado.cfg, src/Nethermind/Nethermind.Runner/configs/denver.cfg
- Adds pivot block for fast sync to denver/chiado
=> Add pivot block for gnosis testnets

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
=> FixPeerReportHeader

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- fix hive tests edge case scenario
=> Fix hive tests

src/Nethermind/Ethereum.Blockchain.Test/Ethereum.Blockchain.Test.csproj, src/Nethermind/Nethermind.Crypto/Nethermind.Crypto.csproj, src/Nethermind/Nethermind.DataMarketplace.Test/Nethermind.DataMarketplace.Test.csproj, src/Nethermind/Nethermind.Network.Test/Nethermind.Network.Test.csproj, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
Closes #4408, #4407, #4406, #4405, #4404
Update package for security reasons
=> Upgrade Microsoft.AspNetCore.DataProtection to 6.0.8

.github/workflows/develop-rebase.yml
Auto rebase develop without using third party action
=> Rebase develop

src/Nethermind/Nethermind.Network.Dns/EnrDiscovery.cs
Fixes #4283
Add warning message and do not throw the exception.
=> Produce proper warning message when failing to Search tree of ENR

scripts/deployment/publish-downloads.sh
Exit on error response from server when publishing packages to Downloads page.
-
=> Exit if response code is >=400

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
ReleaseResources before setting disposed flag.
Only touch managed objects when disposing
=> Fix disposing DB with open batch

src/Nethermind/Nethermind.Evm.Test/SModTests.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
=> int256 improvements

scripts/syncSettings.py
- Fixes config files (fast sync settings) script
=> fix syncSettings.py

src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs, src/Nethermind/Nethermind.Specs/RopstenSpecProvider.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.Merge.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
Fix "Incremental Sync" hive test on archive mode only. Fast sync seems to have other issue.
- Do not download PoS blocks with PoW downloader.
- Goerli can sync to head.
- One less failing hive test.
- Require https://github.com/NethermindEth/nethermind/pull/4496 in order to not introduce hive regression.
=> Fix incremental sync hive test on archive mode

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Send 403 Forbidden error code on authentication error
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] No
=> 403 error code on authentication error

.github/workflows/release-nethermind.yml, scripts/deployment/publish-downloads.sh, src/Nethermind/Nethermind.Core/ChainLevelInfo.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
=> Mainnet terminal block hotfix

src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs, src/Nethermind/Nethermind.Synchronization/SyncServer.cs
BlockTreeSuggestOptions.None started setting setAsMain as true. I removed it from SyncServer for now.
=> ForceDoNotSetAsMain in SyncServer

src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
Resolves #4343
Better logging message
=> Produce meaningFull error message for PushGatewayUrl not reachable

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/RocksDbTests.cs, src/Nethermind/Nethermind.Runner/Program.cs
=> write rocksDb version info into the log file

src/Nethermind/testenvironments.json
- Enable WSL for tests, specifically for Ubuntu-22.04. Works in MS VS, was not tested in Rider
=> Enable WSL for tests, specifically for Ubuntu-22.04

src/Nethermind/Nethermind.Runner/Program.cs
- Update docs by excluding redundant linking to libdl and libsnappy
- Remove unused code
Needs manual testing of successful startup of clean setup on different architectures
=> Remove libdl; libsnappy workarounds

src/Nethermind/Nethermind.Network.Stats/Model/Node.cs, src/Nethermind/Nethermind.Synchronization.Test/PeerInfoAllocationTests.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerExtensions.cs
Nethermind cannot be assigned as peer to snap sync
=> Don't connect to Nethermind peers for snap sync until it is implemented

src/Nethermind/Nethermind.JsonRpc.Test/Modules/ParityRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Parity/IParityRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Parity/ParityRpcModule.cs, src/Nethermind/Nethermind.TxPool/ITxPool.cs, src/Nethermind/Nethermind.TxPool/NullTxPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
=> Add optional argument Address in parity_pendingTransactions (#4413)

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
In DropUselessPeers, peer with lowest head number is dropped. With FCU peer refreshing, all peer that is not dropped, have the same head number. This causes the peer that get dropped to be random as the backing store is a concurrent dictionary.
- Use latency as last comparison.
Running smoke
=> Fix peer dropped randomly

src/Nethermind/Nethermind.Db.Test/DbMetricsUpdaterTests.cs
=> Fix db metric uploader test

.gitmodules, src/Nethermind/Nethermind.Evm/Nethermind.Evm.csproj
Rollback a package config.
- Rollback a package config
Seems to work... locally at least.
=> Fix invalid block on mainnet

.gitmodules
the url for the Math.Gmp.Native submodule is git url
=> change the url

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs
Just changed logging level https://github.com/NethermindEth/nethermind/issues/4718
=> Change unhandled to trace

src/Nethermind/Nethermind.Monitoring/Config/IMetricsConfig.cs, src/Nethermind/Nethermind.Monitoring/Config/MetricsConfig.cs, src/Nethermind/Nethermind.Monitoring/MonitoringService.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/energyweb_archive.cfg
- Remove default gateway url and allow prometheus pull mode only.
Metrics still work with expose port.
=> Remove default gateway url and allow pull mode only

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs
- Minor format adjustment in sync peer report
=> Minor formatting adjustment

src/Nethermind/Nethermind.sln
Fixes solution build error.
- Removes the reference to the non-existing `Math.Gmp.Native` project from the solution file.
=> Remove Math.Gmp.Native project

src/Nethermind/Nethermind.Evm.Test/BytecodeBuilderExtensionsTests.cs, src/Nethermind/Nethermind.Evm.Test/FluentByteCodeBuildeTests.cs, src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs
- Added Extension Methods to simplify Preparing bytecode tests using Prepare API
=> Refactor/preparep api/function like opcodes

scripts/syncSettings.py, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs, src/Nethermind/Nethermind.Runner/configs/chiado.cfg, src/Nethermind/Nethermind.Synchronization/Blocks/SyncBatchSize.cs
- Adds chiado (using rpc) to the python script that updates the sync pivot information
=> Add chiado to sync settings python script

src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/GetPayloadV1Handler.cs, src/Nethermind/Nethermind.Merge.Plugin/Metrics.cs
Closes #4720
-Add metrics to Engine API as specified in the issue.
=> EngineAPI metrics

src/Nethermind/Nethermind.UPnP.Plugin/UPnPPlugin.cs
- Dispose cancellation token source.
- Use periodic timer.
- confirmed add mapping happened periodically.
=> Cleanup UPnP code

src/Nethermind/Nethermind.Blockchain/Metrics.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Add metrics to track block gas usage
Tested on live network using grafana
=> Add metrics to track gas usage

src/Nethermind/Chains/chiado.json, src/Nethermind/Nethermind.Runner/configs/chiado.cfg
- Add Chiado TTD, scheduled for (block: `680928`, time:  `2022-11-04T15:00:00.000Z`)
- Add base db path to chiado config
=> Chiado TTD

src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs
- Added json conversion rule for Shanghai, and compatibility conversion rule to match EthereumTests in [PR#847](https://github.com/ethereum/tests/pull/847)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose …
=> Added Spec conversion rule for EthereumTests

src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.ChainLevelHelper.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/V1/ForkchoiceUpdatedV1Handler.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconPivot.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/ChainLevelHelper.cs
- Add a codepath to restart beacon sync if beacon chain is disconnected during forward sync.
- Add a flag in beacon pivot to specify force new beacon sync.
=> Autorecover when disconnected chain is found

src/Nethermind/Nethermind.Hive/HiveRunner.cs, src/Nethermind/Nethermind.Runner/NLog.config
- Refactor `HiveRunner` to wait for processing only if block was suggested
=> Refactor HiveRunner

src/Nethermind/Nethermind.Cli.Test/ProofCliModuleTests.cs, src/Nethermind/Nethermind.Cli/Modules/EthCliModule.cs, src/Nethermind/Nethermind.Cli/NodeManager.cs
- Fix eth_syncing cli bug. When result is false standard ToString method returns "False"(with capital F) which is not suitable for JsValue parser.
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] Yes
- [ x ] Yes
If this is a relatively large …
=> 4537 cli eth syncing if false broken

.github/workflows/release-nethermind.yml
Fixes release workflow environment variable definition.
Moved environment variable definition from the step to the job
=> Fix release workflow environment variable definition

src/Nethermind/Directory.Build.props
Upgrade Build version info to 14.5.
- Only version info.
=> Bump build version to 14.5

src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManager.cs, src/Nethermind/Nethermind.Network/ProtocolsManager.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
- Wanted to use debug log level by default for debugging.
- Needed to change some thing to make it a bit more tolerable.
- Change log level for ping response from trace to debug.
- Change log level for missing satellite protocol from trace to debug.
- Add `FastHeader LogStateOnPrepare` to fast header log.
- Not sure onn the satellite protocol thing. But its quite noisy.
=> Make debug level slightly more tolerable

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Core/Specs/ForkActivation.cs, src/Nethermind/Nethermind.Core/Specs/ISpecProvider.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs
- When blocknumber is the only activation it was creating ForkActivation with timestamp 0, but it should be null.
=> fix transition creation after timestamp

.editorconfig, CONTRIBUTING.md
As agreed with our legal department, the file header has been replaced with a more concise and appropriate one.
It is highly recommended to replace the current one with the new one whenever possible. That will lead to less clutter in the files and an overall reduction in repo size.
=> Revise the file header notice

src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs, src/Nethermind/Nethermind.Baseline/BaselineModule.cs, src/Nethermind/Nethermind.Blockchain.Test/Producers/BlockProducerBaseTests.BaseFee.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Data/TransactionForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.Mev/Execution/TxBundleSimulator.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/AcceptTxResult.cs, src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Filters/GapNonceFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/ReusedOwnNonceTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/TooExpensiveTxFilter.cs, src/Nethermind/Nethermind.TxPool/ITxPool.cs, src/Nethermind/Nethermind.TxPool/ITxSender.cs, src/Nethermind/Nethermind.TxPool/Nethermind.TxPool.csproj, src/Nethermind/Nethermind.TxPool/NullTxSender.cs, src/Nethermind/Nethermind.TxPool/PeerInfo.cs, src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs, src/Nethermind/Nethermind.TxPool/TxNonceTxPoolReserveSealer.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs, src/Nethermind/Nethermind.TxPool/TxPoolSender.cs
This reverts commit adf46100230262a3d664dbfa2536721566256920.
=> Revert "enable nullable on TxPool project (#4874)"

src/Nethermind/Chains/xdai.json, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/ndm_consumer_xdai.cfg, src/Nethermind/Nethermind.Runner/configs/ndm_consumer_xdai_proxy.cfg, src/Nethermind/Nethermind.Runner/configs/xdai.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_aa.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_archive.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_mev.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_nethermind_testnet.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_testnet.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_themerge.cfg, src/Nethermind/Nethermind.Runner/configs/xdai_validator.cfg, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecLoaderTests.cs
Scheduled for `Dec 5 2022` assuming 5s block times: `8626000000000000000000058750000000000000000000`
- Adds gnosischain TTD value
=> Add gnosischain TTD value

src/Nethermind/Nethermind.Evm.Test/Tracing/ParityLikeTxTracerTests.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
This reverts commit 4c7344384ed421a8248043f804d6e706fee1d6b3 due to regression
=> Revert "update the precompile tracing (#4472)"

.github/workflows/build-nethermind-docker-images.yml, .github/workflows/release-nethermind.yml
Fixes the Docker push action by changing the password to a token. This is for both the main release workflow and dev docker workflow. 
- Change secrets.DOCKER_PASSWORD to secrets.DOCKER_ACCESS_TOKEN
=> Changes the docker password to a token

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Network.Test/Rlpx/RlpxPeerTests.cs, src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs
This reverts commit 26a00ee0eaf3894bb53a4b17dc0a4b4fa6ab0858.
=> Revert "Set local IP explicitly for P2P. (#4854)"

src/Nethermind/Directory.Build.props
=> Bump build version to 14.6

.github/workflows/build-nethermind-docker-images.yml, .github/workflows/build-nethtest-hive-docker-images.yml, .github/workflows/release-nethermind.yml, .github/workflows/run-truffle-smoke-tests.yml
Fixes the Docker push action by changing the password to a token. 
- Change secrets.DOCKER_PASSWORD to secrets.DOCKER_ACCESS_TOKEN
=> Changes the docker password variable to token

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/Filters/TooExpensiveTxFilter.cs
- Fixes #4829
- That is basically typo
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] No
- [ x ] Yes
=> TooExpensiveTxFilter cumulative cost fix

src/Nethermind/Nethermind.Blockchain/FullPruning/FullPruner.cs, src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
=> Typo in FullPruning logs

src/Nethermind/Nethermind.Evm.Test/EvmPooledMemoryTests.cs, src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
- Fixes edge case when memory tracing is enabled
=> Fix GetTrace crash when memory is not yet resized

src/Nethermind/Nethermind.Network/PeerManager.cs
- Rearrange `PeerManager` code into three sections.
- Peer update loop.
- Outgoing connection handling.
- Incoming connection handling.
- Rearrange `PeerManager` code into `#section`(s)
Unit test passed.
=> Rearrange peer manager code.

src/Nethermind/Nethermind.Trie/Nethermind.Trie.csproj, src/Nethermind/Nethermind.Trie/VerkleUtils.cs, src/Nethermind/nuget.config
=> add verkle utils in nugettest

src/Nethermind/Nethermind.JsonRpc.TraceStore/ITraceStoreConfig.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStoreConfig.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStoreModuleFactory.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStorePlugin.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStoreRpcModule.cs
- Add parallelization limit to trace_filter
=> Add TraceStoreConfig.DeserializationParallelization

src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs, src/Nethermind/Nethermind.Facade/BlockchainBridge.cs
=> fix for eth_call?

src/Nethermind/Nethermind.Provide.Vault/VaultTxSender.cs
- Added missing `await` to async method call
May have been intentionally skipped?
=> Add await in VaultTxSender.SendTransaction

src/Nethermind/Ethereum.Blockchain.Block.Legacy.Test/Ethereum.Blockchain.Block.Legacy.Test.csproj, src/Nethermind/Ethereum.Blockchain.Legacy.Test/Ethereum.Blockchain.Legacy.Test.csproj, src/Nethermind/Nethermind.Abi.Test/Nethermind.Abi.Test.csproj, src/Nethermind/Nethermind.BeaconNode.OApiClient.Test/Nethermind.BeaconNode.OApiClient.Test.csproj, src/Nethermind/Nethermind.BeaconNode.OApiClient/Nethermind.BeaconNode.OApiClient.csproj, src/Nethermind/Nethermind.BeaconNode.Test/Nethermind.BeaconNode.Test.csproj, src/Nethermind/Nethermind.Config.Test/Nethermind.Config.Test.csproj, src/Nethermind/Nethermind.Config/Nethermind.Config.csproj, src/Nethermind/Nethermind.Consensus.Test/Nethermind.Consensus.Test.csproj, src/Nethermind/Nethermind.Core2.Configuration.Test/Nethermind.Core2.Configuration.Test.csproj, src/Nethermind/Nethermind.Cryptography.Bls.Test/Nethermind.Cryptography.Bls.Test.csproj, src/Nethermind/Nethermind.EthStats/Nethermind.EthStats.csproj, src/Nethermind/Nethermind.EvmPlayground/Nethermind.EvmPlayground.csproj, src/Nethermind/Nethermind.HonestValidator.Test/Nethermind.HonestValidator.Test.csproj, src/Nethermind/Nethermind.JsonRpc.Test/Nethermind.JsonRpc.Test.csproj, src/Nethermind/Nethermind.JsonRpc/Nethermind.JsonRpc.csproj, src/Nethermind/Nethermind.Mev.Test/Nethermind.Mev.Test.csproj, src/Nethermind/Nethermind.Serialization.Json/Nethermind.Serialization.Json.csproj, src/Nethermind/Nethermind.State.Test.Runner/Nethermind.State.Test.Runner.csproj, src/Nethermind/Nethermind.Vault.Test/Nethermind.Vault.Test.csproj, src/Nethermind/Nethermind.WriteTheDocs/Nethermind.WriteTheDocs.csproj
- Update Newtonsoft.Json to 13.0.2
=> Update Newtonsoft.Json to 13.0.2

src/Nethermind/Nethermind.Init/Nethermind.Init.csproj, src/Nethermind/Nethermind.Init/Steps/LogHardwareInfo.cs
- Logs cpu info on start. 
- Makes debugging easier.
- Using another MIT licensed library as it claims to works on all platform. 
- Looks like this:
- Logs cpu info on start
=> Logs cpu info on start

src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
=> Remove transition fix 1.14.2

src/Nethermind/Directory.Build.props
- Just bump Nethermind to 1.15.0 before releasing it
=> Bump Client Version to 1.15.0

.gitmodules, src/Nethermind/Ethereum.Blockchain.Block.Test/Eip3651Tests.cs, src/Nethermind/Ethereum.Blockchain.Block.Test/Eip3855Tests.cs, src/Nethermind/Ethereum.Blockchain.Block.Test/Eip3860Tests.cs, src/Nethermind/Ethereum.Blockchain.Block.Test/Ethereum.Blockchain.Block.Test.csproj, src/Nethermind/Ethereum.Blockchain.Block.Test/WithdrawalsTests.cs, src/Nethermind/Ethereum.Test.Base/AccountStateJson.cs, src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs, src/Nethermind/Ethereum.Test.Base/LoadLocalTestsStrategy.cs
New tests from this repo: https://github.com/ethereum/execution-spec-tests/
=> Shanghai eth tests

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerAllocation.cs
- Fire SyncPeerAllocation.Replaced outside lock to avoid deadlocks
=> Fire SyncPeerAllocation.Replaced outside lock

.github/pull_request_template.md
Revised and cleaned up the PR template. No structural changes, mostly linguistic ones.
This PR actually uses the updated template.
=> Revise PR template

.github/workflows/release-nethermind.yml
Fixed Homebrew release workflow.
=> Fix Homebrew release workflow

src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs, src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidBlockInterceptor.cs
- Fix node may hang when given invalid block body.
- Do not track block as invalid if block body does not match block header hash.
=> Fix possible hang when receiving invalid body

README.md
Added the Discourse shield to README.
=> Add Discourse shield

src/Nethermind/Directory.Build.props
Bump version on release branch to 1.16.0-unstable
=> Bump Version to 1.16.0-unstable

scripts/syncSettings.py
Fix script for configs pivot bump.
=> Fix Config Pivots Bump

.github/workflows/release-nethermind.yml
Fixed output variable handling in the release workflow.
=> Fix the release workflow

scripts/syncSettings.py, src/Nethermind/Nethermind.Runner/configs/gnosis_archive.cfg
- Add config for gnosis archive node
- Add `gnosis` to `syncSettings.py` script
=> Add gnosis archive config

src/Nethermind/Nethermind.Network/ForkInfo.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs, src/Nethermind/Nethermind.Specs/MainNetSpecProvider.cs
- Ignore impossible block numbers and timestamps
Tested with devp2p hive tests and passing
https://github.com/NethermindEth/nethermind/actions/runs/3887919285/jobs/6634708147
=> Fix hive tests peering issue

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ForkchoiceStateV1.cs
=> Revert FCU ToString change, because of SEQ bug

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Wrong serialization. 
- fix serialization
- Tested manually with a python script.
- Tested CL can call now.
=> Fix single jsonrpc request not working

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcBatchResult.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcBatchResult.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcResult.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/RpcReport.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs, src/Nethermind/Nethermind.Runner/JsonRpc/JsonRpcIpcRunner.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Sockets.Test/WebSocketExtensionsTests.cs
- Limits response size when batches are active
=> Introduce MaxBatchResponseBodySize

src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationSubscribeTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcResult.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- refactor to reduce confusion
=> Add back Response and Report to JsonRpcResult

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Fix posdao test failure.
- Tested to pass posdao test.
=> Fix missed dispose in single json rpc call

src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
- Tests and sets value, then overwrites with same value. Missing `else`
=> Reduce unnecessary work in DecodeKeccakStructRef

src/Nethermind/Nethermind.Blockchain/Contracts/Json/AbiParameterConverter.cs, src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs, src/Nethermind/Nethermind.Db.Rocks/Statistics/DbMetricsUpdater.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerExtensions.cs
With .NET 7 comes source generated Regex which is much faster than regular regex
See: [regular-expression-improvements-in-dotnet-7/#source-generation](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#source-generation)
=> Use source generated regex

src/Nethermind/Nethermind.AccountAbstraction/Source/PaymasterThrottler.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs, src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationTxSource.cs, src/Nethermind/Nethermind.AuRa.Test/Validators/ContractBasedValidatorTests.cs, src/Nethermind/Nethermind.Blockchain/KnownAddresses.cs, src/Nethermind/Nethermind.Config.Test/ConfigFileTestsBase.cs, src/Nethermind/Nethermind.Config/ConfigProvider.cs, src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs, src/Nethermind/Nethermind.Db/MemDb.cs, src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs, src/Nethermind/Nethermind.KeyStore/MemKeyStore.cs, src/Nethermind/Nethermind.Network.Enr/NodeRecord.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.State/Proofs/AccountProofCollector.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/ReceiptsSyncFeedTests.cs, src/Nethermind/Nethermind.Synchronization/FastSync/DetailedProgress.cs, src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs, src/Nethermind/Nethermind.Synchronization/SyncServer.cs
- Prefer TryGetValue rather than ContainsKey+Lookup, as the latter does a double lookup in the Dictionary, and the former only one
=> Prefer TryGetValue rather than ContainsKey+Lookup

src/Nethermind/Nethermind.Consensus/IMiningConfig.cs, src/Nethermind/Nethermind.Merge.Plugin/IMergeConfig.cs
Resolves #5040
- description of deprecated configs updated to avoid confusion
=> fix description of deprecated configs

src/Nethermind/Nethermind.Runner/Program.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
Resolves #4989
- handle some OperationCanceledException differently than general exceptions.
=> catch OperationCanceledException in some cases

src/Nethermind/Directory.Build.props
Just bumping Version to 1.16.0
=> Bump Client version to 1.16.0

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
- Increase RPC batch limit to 1000
=> Increase batch limit to 1000

src/Nethermind/Nethermind.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.sln
Fixes #5199
Removed catalyst references
Search for 'catalyst' references on solution. There should be none.
All existing tests should be passing / no solution opening / loading issues should appear.
Mentioned above - manual testing on solution required, testing by developers should be enough.
=> removed catalyst configs / specs

src/Nethermind/Directory.Build.props
Bump version to 1.16.1 for Hotfix purpose
=> Bump version of Nethermind to 1.16.1

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcContext.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Disable limiting batches if endpoint is authenticated
=> Do not limit batches on authenticated endpoints

src/Nethermind/Ethereum.HexPrefix.Test/HexPrefixTests.cs, src/Nethermind/Nethermind.Benchmark/Store/HexPrefixFromBytesBenchmarks.cs, src/Nethermind/Nethermind.State.Test/SnapSync/Storage/SnapStorageTests.cs, src/Nethermind/Nethermind.State/Proofs/AccountProofCollector.cs, src/Nethermind/Nethermind.State/Proofs/ProofCollector.cs, src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs, src/Nethermind/Nethermind.Trie.Test/HexPrefixTests.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie.Test/TrieNodeTests.cs, src/Nethermind/Nethermind.Trie/HexPrefix.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/TreeDumper.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs, src/Nethermind/Nethermind.Trie/TrieNodeFactory.cs
Reverts NethermindEth/nethermind#4623 - will merge #5194
=> Revert "HexPrefix object no longer needed"

src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
Remove old networks from launchsettings.json
=> cleanup launchsettings.json

src/Nethermind/Nethermind.Synchronization/SnapSync/Pivot.cs
Fix typo in `SnapSync/Pivot.cs`
Spelling correction
- [ X ] Other: Spelling correction
- [ X ] No
=> Fix typo in SnapSync/Pivot.cs

src/Nethermind/Directory.Build.props
- Bump version to 1.17.0-unstable
=> Bump version to 1.17.0-unstable

src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Add warnings for exceeding BatchSize
=> Batch size exceeded warnings

src/Nethermind/Nethermind.Evm/Precompiles/Sha256Precompile.cs
- Use Span based overload for TryComputeHash
=> Use input buffer directly for Sha256Precompile

src/Nethermind/Nethermind.Crypto/EciesCipher.cs
- Minor change, avoids double array allocation (MemorySteam -> .ToArray())
=> Skip intermediate MemoryStream in EciesCipher.Encrypt

src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
Adjust our batch size to prysm 
Reference issue: https://github.com/prysmaticlabs/prysm/pull/11982
I did manual testing. It works well with prysm
=> Adjust to prysm batch size

src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
- Reuse previous snapshots if nothing has changed to reduce allocations
Greatly reduces the snapshot allocations from flattening the txns collection for a given amount of notification allocations
=> Only re-snapshot SortedPool on changes

README.md
Fixed the broken tests workflow badge in the README.
=> Fix the test workflow badge

src/Nethermind/Nethermind.Db/DbExtensions.cs, src/Nethermind/Nethermind.Serialization.Rlp/BlockDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/BlockInfoDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/ChainLevelDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/Eip2930/AccessListDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/HeaderDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/ReceiptMessageDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpBehaviors.cs, src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
Renamed RlpBehaviors.AllowExtraData -> RlpBehavious.AllowExtraBytes. Just to avoid confusion in the future with the block.ExtraData. The confusion happened to our team a few times.
=> AllowExtraData -> AllowExtraBytes

src/Nethermind/Nethermind.Core.Test/KeccakTests.cs, src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs, src/Nethermind/Nethermind.Crypto/Keccak512.cs, src/Nethermind/Nethermind.Crypto/KeccakRlpStream.cs, src/Nethermind/Nethermind.Network.Test/NetTestVectors.cs, src/Nethermind/Nethermind.Network.Test/Rlpx/FrameMacProcessorTests.cs, src/Nethermind/Nethermind.Network.Test/Rlpx/Handshake/EncryptionHandshakeServiceTests.cs, src/Nethermind/Nethermind.Network/Rlpx/EncryptionSecrets.cs, src/Nethermind/Nethermind.Network/Rlpx/FrameMacProcessor.cs, src/Nethermind/Nethermind.Network/Rlpx/Handshake/HandshakeService.cs, src/Nethermind/Nethermind.Network/Rlpx/IFrameMacProcessor.cs, src/Nethermind/Nethermind.Network/Rlpx/NettyHandshakeHandler.cs
Closes #388 | Resolves #5207 (partially)
Resolves the TODO in code
```
[Todo(Improve.Performance, "Ideally we would use our own implementation of Keccak here")]
```
- Replace BouncyCastle `KeccakDigest` for Nethermind `KeccakHash`
- Improvements to `KeccakHash`
=> BouncyCastle.KeccakDigest => Nethermind.KeccakHash

.gitignore
=> add githooks to gitignore

.github/ISSUE_TEMPLATE/bug_report.md
- Adjusted bug report template
=> Adjusted issue report to sound more professional and retrieve more info

src/Nethermind/Nethermind.Serialization.Rlp/BlockInfoDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/IRlpDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs
- change interface IRlpValueDecoder<T> : IRlpDecoder<T>
=> fix decoder

src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs
Disable capabilities warning for `engine_getPayloadBodiesBy*` methods.
=> Mark `engine_getPayloadBodiesBy*` methods as optional capabilities

src/Nethermind/Nethermind.Synchronization.Test/SyncPeersReportTests.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs, src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
- Makes peer reports less confusing
=> Fix Allocated report

src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
- removes "Parent wasn't processed" from logs to avoid confusion
=> Remove "Parent wasn't processed" from logs

src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs
=> Remove obsolete ToArrays

src/Nethermind/Nethermind.JsonRpc.TraceStore/DbPersistingBlockTracer.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/ParityLikeTraceSerializer.cs
- Checks graph depth before serialization
=> TraceStore - Check depth when serializing

src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs
- Keep last in field
- Remove lock
=> Non-blocking SortedPool.TryGetLast and IsFull

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core/Block.cs, src/Nethermind/Nethermind.Core/BlockHeader.cs, src/Nethermind/Nethermind.Core/Crypto/Keccak.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs, src/Nethermind/Nethermind.State/IStateProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs
- Partial bad block processing fix
=> Adjust trace fix 1.17.1

src/Nethermind/Nethermind.Synchronization.Test/FastSync/DetailedProgressSerializerTest.cs, src/Nethermind/Nethermind.Synchronization/FastSync/DetailedProgress.cs, src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
Fixes  #5383 
- make a array of variables before serialization in DetailedProgress
=> copy variables for serialization

src/Nethermind/Nethermind.Core/Resettables/ResettableDictionary.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs
- Change from `IDictionary` to `Dictionary` for faster direct calls rather than interface calls
=> Use concrete dictionary rather than interface

src/Nethermind/Nethermind.Evm/ZeroPaddedSpan.cs
- Minor: change `ZeroPaddedSpan` to `readonly ref` as works better when passed `in`
=> ZeroPaddedSpan to readonly ref

src/Nethermind/Nethermind.Core/Caching/SpanLruCache.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
- Fix overlapping defining same methods
=> Fix merge conflict build break

src/Nethermind/Nethermind.Core/Address.cs
- Use the full 20 bytes of `Address` to create the hashcode rather just the last 4; to reduce potential dictionary collisions
=> Better address GetHashCode

src/Nethermind/Chains/foundation.json, src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs, src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecLoaderTests.cs, src/Nethermind/Nethermind.Specs/MainNetSpecProvider.cs
- Updated chainspec for Shapella hardfork. 
- Execution-spec: https://github.com/ethereum/execution-specs/pull/727/files#diff-5241ef75472fc48d6d58dc19151b8ae5526097e2ad0a58d098c83ba1a035a300
- ForkId Hash confirmed with other EL devs.
=> Mainnet Shapella Configs

src/Nethermind/Nethermind.Runner/Program.cs
Sometimes it's very useful to see Nethermind version in logs. Especially if some crash happened during startup
- Prints version of Nethermind
=> Print version on strartup

src/Nethermind/Nethermind.Consensus.Ethash/EthashCache.cs, src/Nethermind/Nethermind.Core/FakeBatch.cs, src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs, src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs
- Remove Finalizer from EthHash
- Remove GC.SuppressFinalize from classes with no finalizers
=> Remove unnecessary GC finalization

.github/workflows/run-a-single-node-from-branch.yml
-Fix to node creation workflow
This workflow successfully triggered smoke-tests workflow
https://github.com/NethermindEth/nethermind/actions/runs/4493286705/jobs/7904303805
And VM with node is spawned properly.
=> Fix node creation workflow

.github/workflows/run-a-single-node-from-branch.yml
=> Workflow Typo fix

src/Nethermind/Nethermind.Blockchain/KnownChainSizes.cs, src/Nethermind/Nethermind.Core/BlockchainIds.cs
Applied discord suggestion about BlockchainIds
- renamed xDai -> Gnosis
- removed Stureby
- removed some old comments
I ran xdai/gnosis configs to check if there is no unexpected crash on startup
=> xdai-> Gnosis in BlockchainIds and small cleanup

.github/workflows/hive-tests.yml
Fixed the jq error because of the extra .json file added to the result set.
=> Fix the jq error in Hive tests results

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
Fixes #5506
- Changes error code on error
=> Eth_get_filter_changes_missing

src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
Fixes #5076
- Follow AAA
Thank you @LukaszRozmej  for the guidance.
=> refactor ChainspecbasedSpecProviderTests to follow AAA

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs, src/Nethermind/Nethermind.Merge.Plugin/GC/IGCStrategy.cs, src/Nethermind/Nethermind.Merge.Plugin/GC/NoGCStrategy.cs, src/Nethermind/Nethermind.Merge.Plugin/GC/NoSyncGcRegionStrategy.cs, src/Nethermind/Nethermind.Merge.Plugin/IMergeConfig.cs, src/Nethermind/Nethermind.Merge.Plugin/MergeConfig.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
- Switch to SustainedLowLatency during NewPayload
Interim version of https://github.com/NethermindEth/nethermind/pull/5381
=> New payload sustained low latency

src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidBlockInterceptor.cs
- Gives nullable compile errors in VS UI (is fine at cli and build)
=> nullable compile error

src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecLoaderTests.cs, src/Nethermind/Nethermind.Specs/GoerliSpecProvider.cs, src/Nethermind/Nethermind.Specs/KnownHashes.cs
- Cleanup in GoerliSpecProvider & KnownHashes
- Added basic test for TimestampFork
=> Cleanup in test spec loader classes and KnownHashes

src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/StatusMessageSerializer.cs, src/Nethermind/Nethermind.Serialization.Rlp/BasicStreamDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
- Remove unused code.
- Remove unused code.
- Unit test passed.
=> Remove unused Rlp code

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Init/Cpu/ConsoleExitHandler.cs, src/Nethermind/Nethermind.Init/Cpu/CpuInfo.cs, src/Nethermind/Nethermind.Init/Cpu/DefaultCultureInfo.cs, src/Nethermind/Nethermind.Init/Cpu/Frequency.cs, src/Nethermind/Nethermind.Init/Cpu/FrequencyUnit.cs, src/Nethermind/Nethermind.Init/Cpu/ProcCpuInfoKeyNames.cs, src/Nethermind/Nethermind.Init/Cpu/ProcCpuInfoParser.cs, src/Nethermind/Nethermind.Init/Cpu/ProcCpuInfoProvider.cs, src/Nethermind/Nethermind.Init/Cpu/ProcessExtensions.cs, src/Nethermind/Nethermind.Init/Cpu/ProcessHelper.cs, src/Nethermind/Nethermind.Init/Cpu/RuntimeInformation.cs, src/Nethermind/Nethermind.Init/Cpu/SectionsHelper.cs, src/Nethermind/Nethermind.Init/Cpu/SysctlCpuInfoParser.cs, src/Nethermind/Nethermind.Init/Cpu/SysctlCpuInfoProvider.cs, src/Nethermind/Nethermind.Init/Cpu/TimeInterval.cs, src/Nethermind/Nethermind.Init/Cpu/TimeUnit.cs, src/Nethermind/Nethermind.Init/Cpu/UnitPresentation.cs, src/Nethermind/Nethermind.Init/Cpu/WmicCpuInfoKeyNames.cs, src/Nethermind/Nethermind.Init/Cpu/WmicCpuInfoParser.cs, src/Nethermind/Nethermind.Init/Cpu/WmicCpuInfoProvider.cs, src/Nethermind/Nethermind.Init/Nethermind.Init.csproj, src/Nethermind/Nethermind.Init/Steps/LogHardwareInfo.cs
Resolves #5528
- Lighter query just to check CPU type
- Previously would iterate all hardware on the machine and jam if it conflicted with some other hardware access
Requires testing on Mac (don't have access to one)
=> Less invasive CPU logging

scripts/syncSettings.py
AA and MEV configs were removed recently https://github.com/NethermindEth/nethermind/pull/5524. Updated Config workflow
I will run workflow
=> Remove AA and MEV from update config workflow

src/Nethermind/Nethermind.Core.Test/Collections/ArrayPoolListTests.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
- Fix arraypoollist hangs when capacity is 0
=> Fix arraypool hangs when capacity is 0

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Db.Rocks/Nethermind.Db.Rocks.csproj, src/Nethermind/Nethermind.Db.Test/RocksDbTests.cs
Closes #5343
- Updated to RocksDB v8
- Removed ARM libraries as no longer needed (now included in the package)
Smoke tests are in progress.
See the RocksDB v8 [release notes](https://github.com/facebook/rocksdb/releases/tag/v8.0.0)
=> Upgrade to RocksDB v8

src/Nethermind/Nethermind.Init/Steps/InitDatabase.cs
Revised the RocksDB loading error message causing confusion among the users
=> Revise RocksDB loading failure message

src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs
- add Cancun instance in network switch in `JsonToEthereumTest`
=> Update ethereum tests, add Cancun

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs
- adjust failing tests to rollbacked changes
=> Adjust receipts tests

src/Nethermind/Nethermind.Core/TxType.cs
- Change blob tx  number according to https://github.com/ethereum/EIPs/pull/6832
Requires Dencun
=> Change blob transaction type value to 3

src/Nethermind/Nethermind.Blockchain.Test/Bloom/BloomStorageTests.cs, src/Nethermind/Nethermind.Core/Platform.cs, src/Nethermind/Nethermind.Evm.Test/CmpTests.cs, src/Nethermind/Nethermind.Evm.Test/Eip145Tests.cs, src/Nethermind/Nethermind.Evm.Test/SimdTests.cs, src/Nethermind/Nethermind.Facade/Filters/FilterManager.cs, src/Nethermind/Nethermind.Facade/Filters/LogFinder.cs, src/Nethermind/Nethermind.Merkleization/MerkleTree.cs, src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs, src/Nethermind/Nethermind.Synchronization/LesSync/CanonicalHashTrie.cs
- Removed never called private methods
=> Removed never called private methods

src/Nethermind/Nethermind.Consensus.AuRa/AuRaSealValidator.cs, src/Nethermind/Nethermind.Core/Bloom.cs, src/Nethermind/Nethermind.Facade/Filters/AddressFilter.cs, src/Nethermind/Nethermind.Facade/Filters/Topics/SpecificTopic.cs, src/Nethermind/Nethermind.Init/Cpu/Frequency.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SubscriptionFactory.cs, src/Nethermind/Nethermind.Network/PeerManager.cs, src/Nethermind/Nethermind.Network/Rlpx/FrameHeaderReader.cs, src/Nethermind/Nethermind.Network/Rlpx/ZeroFrameMerger.cs, src/Nethermind/Nethermind.Trie/BatchedTrieVisitor.cs
- Make some structs `readonly`
=> Make some structs readonly

src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockFinalizationManager.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcUrl.cs, src/Nethermind/Nethermind.Network/PeerManager.cs, src/Nethermind/Nethermind.Runner/Program.cs, src/Nethermind/Nethermind.Synchronization/Peers/AllocationStrategies/BySpeedStrategy.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs
- Use direct `.Count`, `.Length` properties rather than Linq
=> Use direct properties rather than Linq

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Blockchain/Nethermind.Blockchain.csproj, src/Nethermind/Nethermind.Db/Nethermind.Db.csproj, src/Nethermind/Nethermind.Hive/Nethermind.Hive.csproj, src/Nethermind/Nethermind.JsonRpc/Nethermind.JsonRpc.csproj, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj, src/Nethermind/Nethermind.TxPool/Nethermind.TxPool.csproj, src/Nethermind/Nethermind.Wallet/Nethermind.Wallet.csproj
Replaced `System.IO.Abstractions` with `TestableIO.System.IO.Abstractions.Wrappers` package as recommended by the package author. No functionality changes.
=> Replace `System.IO.Abstractions` with `TestableIO.System.IO.Abstractions.Wrappers` package

README.md, SECURITY.md
- Updates the security policy and readme to reflect the new changes.
=> Update security policy

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptConfig.cs, src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs, src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptConfig.cs
It turns out that this commit https://github.com/NethermindEth/nethermind/commit/e5777a8cf98e4f1d1816c1aa243a6a80093f8585 makes it work. Reverting all changes was painful: https://github.com/NethermindEth/nethermind/pull/5620 because I had to revert 5 commits with lots of conflicts so I did it in another way and I hid all receipts optimization params from docs. As @asdacap will be back he can investigate and fix it further.
Manual testing - no invalid blocks
=> Rollback receipt fix

src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManager.cs
It doesn't resolve this issue: https://github.com/NethermindEth/nethermind/issues/5559 but it will help with smoke tests analysis
=> Enr log Warn -> Debug

src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Rpc/RpcDb.cs, src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs, src/Nethermind/Nethermind.Db/IDb.cs, src/Nethermind/Nethermind.Db/MemDb.cs, src/Nethermind/Nethermind.Db/Metrics.cs, src/Nethermind/Nethermind.Db/NullDb.cs, src/Nethermind/Nethermind.Db/ReadOnlyDb.cs, src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs, src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs
- Surfaces the memory the DB is using to metrics
=> Report metrics for DB memory size

.github/workflows/hive-tests.yml
- adjust our workflow to recent changes in root repo: https://github.com/ethereum/hive/pull/762/files
Tested manually - workflow is testing expected branch after this fix
=> Adjust hive tests workflow

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPruningDiskTest.cs
- added retry on 2 flaky tests
=> temp fix flaky tests

src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptConfig.cs
=> Hide from doc

.github/CODEOWNERS
Removed `core-general` ownership.
=> Revise CODEOWNERS

src/Nethermind/Nethermind.Abi/AbiSignature.cs, src/Nethermind/Nethermind.AuRa.Test/Validators/ReportingContractBasedValidatorTests.cs, src/Nethermind/Nethermind.Consensus.Ethash/EthashCache.cs, src/Nethermind/Nethermind.Core/Bloom.cs, src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Crypto/Keccak512.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/INodeDistanceCalculator.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeDistanceCalculator.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.State/Proofs/AccountProofCollector.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromAccountRangesTests.cs, src/Nethermind/Nethermind.Trie/NibbleExtensions.cs
- If it can swap byte[] to Span<byte> with little to no change, swap with Span.
- Was hoping for a lot more... but ok.
- Swap with span
=> One that touches keccak.bytes

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
- Reenable state db compression by default.
=> Reenable state db compression by default

src/Nethermind/Directory.Build.props
- _Change master version to 1.20.0-unstable_
- [X No
=> Bump master branch to 1.20.0-unstable

.github/workflows/nethermind-tests.yml
Fixed the misbehavior on failed job re-run when the final status remains failed regardless of all jobs' success.
=> Fix tests workflow jobs re-run handling

src/Nethermind/Nethermind.Serialization.Ssz.Test/MerkleTreeTests.cs, src/Nethermind/Nethermind.Serialization.Ssz.Test/Nethermind.Serialization.Ssz.Test.csproj
One less project with warning.
=> No warnings in Nethermind.Serialization.Ssz.Test.csproj

.github/workflows/publish-nuget.yml, .github/workflows/publish-packages.yml
Fixed the workflows to run publishing on the latest stable release only skipping pre-releases and the ones not marked as latest.
=> Fix to publish the latest stable release only

.github/workflows/build-nethermind-packages.yml, .github/workflows/release.yml, scripts/deployment/build-cli.sh, scripts/deployment/build-launcher.sh, scripts/deployment/build-runner.sh, scripts/deployment/publish-downloads.sh, scripts/deployment/publish-github.sh
- Fixed the issue with workflow triggering on release publish
- Replaced caching with artifacts for more stability
- Refactored and optimized package build
- Remove version requirement for package build workflow
=> Fix workflows triggering on release publish

.github/workflows/sync-testnets.yml
=> Increase timeout for testnets slightly and always display docker logs

README.md, SECURITY.md
- Updated and revised installation instructions
- Moved prerequisite requirements to the "Download and run" section to make it more visible
- Added Visual C++ Redistributable requirement
- Revised the security policy wording
The Linux requirements have been tested with recent distros.
=> Revise README

src/Nethermind/Directory.Packages.props
Updated the `Nethermind.Crypto.SecP256k1` package that contains the correct binary for Linux arm64.
Tested manually on Linux arm64.
=> Update `Nethermind.Crypto.SecP256k1` package

src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
- Fix if node is offline too long it ceases to be able to sync properly if pivots move
=> Fix stuck state from period offline

src/Nethermind/Directory.Packages.props
Updated `Nethermind.Crypto.Pairings` package with lowered version requirements for `glibc`
=> Update `Nethermind.Crypto.Pairings` package

.github/workflows/sync-testnets.yml
Move timeout to task and ensure that logs will be displayed
=> Move timeout to task and fix logs steps

src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
Allows block processing to compete with OldReceipts and OldBodies
- Block Processor thread priority to `Highest`
- Block Recovery thread priority to `AboveNormal`
- Clique Signal Processor thread priority to `AboveNormal`
=> Boost Block Processor thread priority

src/Nethermind/Nethermind.Core.Test/TestMemDb.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/CompressingStoreTests.cs, src/Nethermind/Nethermind.Db/CompressingDb.cs
- Fix compressed db does not apply tune.
- Update tune stats after rocksdb update and receipts update.
Can sync
=> Fix compressed db does not apply tune

src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.Runner/NLog.config
PR to open discussion. Do we really need to log JSON RPC calls by default? I think we don't. CL is spamming us with tons of logs and this PR will keep it simple.
=> JSON-RPC logs from Info to Debug

src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/GetByteCodesMessageSerializer.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs, src/Nethermind/Nethermind.Synchronization/Nethermind.Synchronization.csproj, src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncFeed.cs, src/Nethermind/Nethermind.Trie/NibbleExtensions.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Optimize some snap sync code
- Sort Db Batch data before creating the batch with it
Needs performance testing on someone with a faster CPU
=> Optimize Snap sync + Sort DB Batches

src/Nethermind/Nethermind.Api/IInitConfig.cs, src/Nethermind/Nethermind.Api/InitConfig.cs, src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs, src/Nethermind/Nethermind.Init/Steps/InitializePrecompiles.cs
- Adds new field to InitConfig.
=> Add path to kzg setup file

src/Nethermind/Nethermind.Evm.Test/TransactionProcessorTests.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
#4197 
- Do not subtract value if tx is system tx and validation is disabled.
=> Fix estimate gas

src/Nethermind/Ethereum.Blockchain.Test/Eip3651WarmCoinbaseTests.cs, src/Nethermind/Ethereum.Blockchain.Test/Eip3855Push0Tests.cs, src/Nethermind/Ethereum.Blockchain.Test/Eip3860LimitmeterInitCodeTests.cs, src/Nethermind/Ethereum.Blockchain.Test/Ethereum.Blockchain.Test.csproj, src/Nethermind/Ethereum.Blockchain.Test/MetaTests.cs
- standard update of docs ref
- adjust paths to the changes in base repo
- adjust tests names
- adjust `MetaTest`
=> Update ethereum tests, adjust paths and naming, update docs ref

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.RelayBuilder.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs
=> Rename BlockChain -> Blockchain in Merge tests

.github/workflows/sync-testnets.yml
- Adjust action to run with new logs
=> Adjust sync testnets to new logs.

.github/workflows/sync-testnets.yml
-Add color to synctestnet action
=> Add color to sync testnets

.github/workflows/sync-testnets.yml
- One more fix for sync testnets
=> Adjust required count for logs in sync testnet

.github/workflows/hive-consensus-tests.yml, .github/workflows/hive-tests.yml, src/Nethermind/Nethermind.Runner/NLog.config
=> Revert colors in Hive tests

src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
- Only output Changing state if state actually changes, even in Debug mode; as otherwise is just log spam
=> Only output Changing state if state actually changes

src/Nethermind/Nethermind.Evm.Test/BnMulPrecompileTests.cs, src/Nethermind/Nethermind.Evm.Test/Tracing/DebugTracerTests.cs
=> Fix debug build

src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.State/StateProvider.cs
- Prefer code from code cache for Create rather than creating a new `CodeInfo` and allocating array
- Prime the code cache if new code
- Filter out writes to codedb for code that's already been written
=> Prefer code from code cache for Create

src/Nethermind/Directory.Build.props
=> Bump master to 1.21.0-unstable

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
=> Increase Goerli size prediction

.github/pull_request_template.md
=> Revise docs instructions

.github/pull_request_template.md
_Adding extended PR template to give devs a chance to put more info about PR and remind about docs._
- _New fields added to PR template._
=> Add docs and Release notes info

src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
- Remove the tx index in batch (just use existing function)
- ~Move PreviousBlock tx  remove into same background task~
=> Receipt clean up in batch
