NethermindEth/nethermind

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
- Start with optimized code (may make exe size a lot larger)
=> Use ready to run

.github/workflows/hive-tests.yml
=> Engine hive tests on every commit to master

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Include block count when processing multiple blocks
=> Include block count when processing multiple blocks

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockProductionTransactionPicker.cs, src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs, src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs, src/Nethermind/Nethermind.Evm/DataGasCalculator.cs, src/Nethermind/Nethermind.Evm/TransactionExtensions.cs
- Clean up the code related to data gas calculations
=> Optimize, clean up data gas calculations

src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ITraceRpcModule.cs
=> Added example value of TraceTypes in TraceModule

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
- Include Pyroscope so is easy to switch on via env vars in docker container
=> Add Pyroscope

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs, src/Nethermind/Nethermind.Blockchain/KnownChainSizes.cs
Update state size approximation for mainnet and goerli.
=> Update KnownChainSizes - Goerli/Mainnet

src/Nethermind/Nethermind.Blockchain/FullPruning/FullPruner.cs
I forgot to divide required value by 100 when it printed to logs
- Fix
=> Fix required number in logs

scripts/execution.sh
Restored Nethermind old executable name for the PPA package.
=> Restore old executable name for PPA

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
=> Add unit test for edge-case TxPool scenario

src/Nethermind/Directory.Packages.props, src/Nethermind/nuget.config
Changed DotNetty feed back to production
=> Restore DotNetty feed

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/Filters/BalanceTooLowFilter.cs, src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs, src/Nethermind/nuget.config
There were some fixes in 1.20.1 which may not be yet included in master branch so we need to merge them back.
=> Merge 1.20.1 into master branch

.github/workflows/run-a-single-node-from-branch.yml
- Fix OneClick with new action name
=> Fix oneClick for new docker file

src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs
- Changed this line "No incoming messages from Consensus Client. Consensus Client is required to sync the node. Please make sure that it's working properly." to "No incoming messages from the Consensus Client. A Consensus Client is required to sync the node. Please make sure that it's working properly.".
This has been annoying me for 3 months.
=> Fix the grammar in one line

src/Nethermind/Nethermind.AuRa.Test/AuraBlockProcessorTests.cs, src/Nethermind/Nethermind.AuRa.Test/Contract/AuRaContractGasLimitOverrideTests.cs, src/Nethermind/Nethermind.AuRa.Test/Transactions/TxCertifierFilterTests.cs, src/Nethermind/Nethermind.AuRa.Test/Transactions/TxPermissionFilterTest.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProcessor.cs, src/Nethermind/Nethermind.Consensus.AuRa/BeaconBlockRoot/NullBeaconBlockRootHandler.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/InitializeBlockchainAuRa.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Consensus/BeaconBlockRoot/BeaconBlockRootHandler.cs, src/Nethermind/Nethermind.Consensus/BeaconBlockRoot/IBeaconBlockRootHandler.cs, src/Nethermind/Nethermind.Consensus/EgineApiVersions.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Producers/PayloadAttributes.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergeBlockProcessor.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergeBlockProducerEnvFactory.cs, src/Nethermind/Nethermind.Merge.AuRa/InitializationSteps/InitializeBlockchainAuRaMerge.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Cancun.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Shanghai.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs, src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.Cancun.cs
=> Add engine_forkChoiceUpdatedV3

src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs, src/Nethermind/Nethermind.AuRa.Test/Contract/ContractDataStoreTests.cs, src/Nethermind/Nethermind.Config.Test/ConfigFileTestsBase.cs, src/Nethermind/Nethermind.Config/ConfigProvider.cs, src/Nethermind/Nethermind.Core.Test/RateLimiterTests.cs, src/Nethermind/Nethermind.Core/Extensions/TypeExtensions.cs, src/Nethermind/Nethermind.Core/TypeDiscovery.cs, src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/BoundedModulePoolTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStorePlugin.cs, src/Nethermind/Nethermind.JsonRpc/Modules/BoundedModulePool.cs, src/Nethermind/Nethermind.JsonRpc/Modules/IRpcModuleProviderExtensions.cs, src/Nethermind/Nethermind.Mev/MevPlugin.cs, src/Nethermind/Nethermind.Monitoring.Test/MetricsTests.cs, src/Nethermind/Nethermind.Runner/Program.cs
- Consider plugins when searching for Nethermind types, 
- remove logs from BoundedModule to not break plugin registrations
Tested using @MicahZoltu  plugin:  https://github.com/Zoltu/nethermind-plugin-multicall/
=> Fix loading plugins with configs

src/Nethermind/Nethermind.JsonRpc.Test/Modules/ParityRpcModuleTests.cs
- refactor to remove unnecessary code duplications
It was made as a part of requested changes in blob pool PR, moved it to separate one as it is not directly related with blob pool and it will make blob pool PR easier to review
=> Refactor `ParityRpcModuleTests`

src/Nethermind/Nethermind.TxPool/Comparison/ByHashTxComparer.cs, src/Nethermind/Nethermind.TxPool/Comparison/CompareReplacedTxByFee.cs, src/Nethermind/Nethermind.TxPool/Comparison/CompareTxByGasLimit.cs, src/Nethermind/Nethermind.TxPool/Comparison/CompareTxByNonce.cs, src/Nethermind/Nethermind.TxPool/Comparison/CompareTxByPoolIndex.cs, src/Nethermind/Nethermind.TxPool/Comparison/CompareTxByTimestamp.cs, src/Nethermind/Nethermind.TxPool/Comparison/CompetingTransactionEqualityComparer.cs, src/Nethermind/Nethermind.TxPool/Comparison/TxComparisonResult.cs
- improve readability of tx comparers
It was made as a part of requested changes in blob pool PR, moved it to separate one as it is not directly related with blob pool and it will make blob pool PR easier to review
=> Improve readability of tx comparers

src/Nethermind/Nethermind.Consensus/Producers/PayloadAttributes.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs
Covers corner cases revealed by the Hive
- Return UnsupportedFork error for fcuvN if N < 3, but timestamp is Cancun or if N >=3 but timestamp belongs to any other (!=N) fork
=> Improve return codes (UnsupportedFork)

scripts/deployment/debian/postinst, scripts/execution.sh
_Squash merge to intermediate branch to pick for 1.20.2_
- _PPA fix for 1.20.2_
=> Squash merge to intermediate branch to pick for 1.20.2

scripts/deployment/debian/postinst, scripts/execution.sh
=> Fix PPA package post-install script

src/Nethermind/Nethermind.Runner/configs/holesky.cfg
Add SnapSync and FastBlocks to Holesky config
=> Add SnapSync and FastBlocks to Holesky

src/Nethermind/Nethermind.Runner/configs/holesky.cfg, src/Nethermind/Nethermind.Runner/configs/holesky_archive.cfg
Fix EnabledEngineModules - change from ; to , in as separator.
Fixed a separator from semicolon to comma in holesky.cfg and holesky_archive.cfg
=> Change EngineEnabledModules to be comma separated

src/Nethermind/Nethermind.Synchronization/Synchronizer.cs
- Turns out blob files was not enabled by default is no sync tune is set.
- Turn it on by default.
=> Fix blob files not enabled by default

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
We fail test because estimation is over current limit.
=> Increase sepolia pruning state estimation limit

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj, src/Nethermind/Nethermind.Runner/Properties/launchSettings.json
In the `launchSettings.json`, replaced the `%NETHERMIND_DATA_DIR%` environment variable with the `.data` directory located in the project output directory. Thus, removed the hassle of configuring the environment variable or forgetting to do so.
Tested manually with Visual Studio. Would be nice to try with Rider as well.
=> Update data dir in launch settings

src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ITraceRpcModule.cs
- fix double bracket in `trace_transaction` docs, reported by user on discord
=> Fix typo in docs

.github/workflows/run-a-single-node-from-branch.yml
Add Run details for OneClick machines (IP, SEQ link, Grafana Link, machine details (CPU, RAM, FIO for disk etc)
- Add machine spec and details for oneClicks
=> Add summary of oneClick run to output

scripts/deployment/publish-github.sh
Updated the release workflow to publish a drafted release on GitHub as the latest if it's not a pre-release.
Needs manual testing.
=> Publish draft releases as the latest

src/Nethermind/Nethermind.Merge.Plugin.Test/BlockTreeTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidChainTrackerTest.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidHeaderInterceptorTest.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/MergeHeaderValidatorTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/Nethermind.Merge.Plugin.Test.csproj, src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/BeaconHeadersSyncTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/BeaconPivotTests.cs
Removed all warnings from Merge.Plugin.Tests.csproj
=> Remove warnings from Merge.Plugin.Tests.csproj

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
Resolves #5949
- Remove mining methods
=> Remove mining methods

scripts/deployment/archive-packages.sh
Fixed symlinks for macOS package archives.
=> Fix symlinks for macOS packages

src/Nethermind/Nethermind.Core.Test/Builders/ReceiptBuilder.cs, src/Nethermind/Nethermind.Core.Test/Encoding/BlockInfoDecoderTests.cs, src/Nethermind/Nethermind.Core.Test/Encoding/TxDecoderTests.cs, src/Nethermind/Nethermind.Core.Test/Nethermind.Core.Test.csproj, src/Nethermind/Nethermind.Core.Test/RequestSizer/AdaptiveRequestSizerTests.cs, src/Nethermind/Nethermind.Core.Test/RlpTests.cs
- Remove warnings for the test suite
Full test suite passes.
=> Remove warnings from `Nethermind.Core.Test`

src/Nethermind/Nethermind.Blockchain/BeaconBlockRoot/BeaconBlockRootHandler.cs
=> Devnet-9 : Eip4788 Address change

src/Nethermind/Chains/holesky.json, src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs, src/Nethermind/Nethermind.Runner/configs/holesky.cfg, src/Nethermind/Nethermind.Runner/configs/holesky_archive.cfg, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs, src/Nethermind/Nethermind.Specs/HoleskySpecProvider.cs, src/Nethermind/Nethermind.Specs/KnownHashes.cs
- following new holesky timestamps and genesis :
https://github.com/eth-clients/holesky/pull/73
=> [Fix][Holesky] timestamps and genesis updates

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
CI is broken. A quick fix, but I am going to talk about final solution with @deffrian.
=> Update tests assumption for Goerli pruning

src/Nethermind/Nethermind.Blockchain.Test/ReadOnlyBlockTreeTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Receipts/ReceiptsRecoveryTests.cs, src/Nethermind/Nethermind.Blockchain.Test/ReorgTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Validators/HeaderValidatorTests.cs, src/Nethermind/Nethermind.Core.Test/AddressTests.cs, src/Nethermind/Nethermind.Init/Cpu/TimeUnit.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Proof/ProofRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcModuleProviderTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidChainTrackerTest.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidHeaderInterceptorTest.cs
- Remove warnings that only show up in Rider
Full test suite passes.
=> Remove Rider/Resharper specific warnings

src/Nethermind/Nethermind.Blockchain/KnownChainSizes.cs
Actual fix for issue #6087
- Updated state size for mainnet
=> Update pruning estimations for mainnet

src/Nethermind/Nethermind.EthStats/Configs/EthStatsConfig.cs, src/Nethermind/Nethermind.EthStats/EthStatsPlugin.cs, src/Nethermind/Nethermind.EthStats/IEthStatsConfig.cs, src/Nethermind/Nethermind.EthStats/Integrations/EthStatsIntegration.cs
Fixes #6139
- Support configurable ethstats update interval
- Make the default interval 15 seconds to avoid spam
Config should reflect automatically the new option `--EthStats.SendInterval`
=> Support configurable `ethstats` update interval

src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs
- Improve error reporting when Genesis block is not loaded after certain timeout.
The issue showed up when running 13 instances of Nethermind in 9 machines simultaneously. 2 of those nodes showed up the following exception during initialization:
```
03 Oct 15:52:19 | Step LoadGenesisBlock         failed after 40056ms Nethermind.Blockchain.BlockchainException: Genesis block processing failure
at Nethermind.Init.Steps.LoadGenesisBlock.Load() in /src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 87
at Nethermind.Init.Steps.LoadGenesisBlock.Execute(CancellationToken _) in /src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs:line 42
at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken) in …
```
=> Use `TimeoutException` on `LoadGenesisBlock`

src/Nethermind/Nethermind.Init/Steps/RegisterPluginRpcModules.cs, src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs
- Activates JsonRPC endpoint (except engineAPI) before Block Reprocessing on restart
- Reorder Init Steps
=> Activate (most) JsonRPC endpoints before BlockReprocessing 

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
Fix #6182 
- I made a mistake. Was under the impression that the tx was later re-added. It was not.
- Fix tx index removed after reorg.
- Added a log to confirm the ordering. It was inserted before the added to main event.
=> Fix tx index was removed during reorg

src/Nethermind/Nethermind.Runner/configs/holesky.cfg, src/Nethermind/Nethermind.Runner/configs/holesky_archive.cfg
Holesky FinalTotalDifficulty to be equal to genesis block's one.
- Correct FinalTotalDifficulty
=> Holesky FinalTotalDifficulty to be equal to genesis block's one

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EthCall.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.TransactionExecutor.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModuleProxy.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
- Fix Antithesis NullException 
=> Fix Antithesis NullPointerException in Evm

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
Fixes a failing unit test, which is blocking merges to master
=> [Unit tests] Update pruning estimations for sepolia

.github/workflows/publish-docker.yml
- Allows publishing docker images for `release/*` branches
- Make sure the code make sense
- I did a test run of the action for this PR: https://github.com/NethermindEth/nethermind/actions/runs/6550656364/job/17790215673?pr=6200#step:6:15
=> Publish to docker on push to release branches

.github/workflows/publish-docker.yml
Fixed the Docker image name handling for the `push` triggers.
=> Fix Docker image name handling

src/Nethermind/Chains/chiado.json, src/Nethermind/Chains/gnosis.json, src/Nethermind/Nethermind.Core/Eip4844Constants.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs
Prefixed EIP-4844 chain spec parameters with `eip4844` to keep them more discoverable and sorted together.
=> Rename EIP-4844 chain spec parameters

src/Nethermind/Nethermind.Init/Steps/StartBlockProducer.cs
=> Remove unused code in StartBlockProducer

src/Nethermind/Nethermind.AccountAbstraction/Bundler/MevBundler.cs, src/Nethermind/Nethermind.Config/JsonConfigSource.cs, src/Nethermind/Nethermind.HealthChecks/IHealthChecksConfig.cs, src/Nethermind/Nethermind.JsonRpc/Metrics.cs, src/Nethermind/Nethermind.KeyStore/FileKeyStore.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
Fix some typos in logs and comments
=> Fix typos in logs and comments

src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
I want to understand which clients (Nethermind?) send incorrect requests.
=> BlockDownloader - client type in logs

.github/workflows/sync-testnets.yml
Added Holesky to testnet syncs verification.
Adjusted configuration and added way to switch to different agent in future.
=> Change agents for testnets syncs and add holesky

.github/workflows/sync-testnets.yml
- Adjust SyncTestnets to clean the self-hosted always and use selfhosted for Sepolia
=> Adjust SyncTestnets to clean the self-hosted always and use selfhosted for Sepolia

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/chiado.cfg, src/Nethermind/Nethermind.Runner/configs/chiado_archive.cfg, src/Nethermind/Nethermind.Runner/configs/gnosis.cfg, src/Nethermind/Nethermind.Runner/configs/gnosis_archive.cfg
Lowered the Gnosis gas limit to `17000000`.
=> Lower the Gnosis gas limit

.gitmodules
Removed the `docs` submodule as no longer needed because of #6252.
=> Remove `docs` submodule

src/Nethermind/Directory.Build.props
Just bump to 1.23.0-unstable which was forgotten before.
=> Bump master version to 1.23.0

.github/workflows/run-a-single-node-from-branch.yml
Fix OneClick action where because of lack of ' chars timeout and ips/ssh weren't passed properly.
Action started with custom timeout and value passed properly to oneClick.
=> Fix timeout not being passed properly

.github/workflows/run-a-single-node-from-branch.yml
Add Holesky Support to OneClick
Synced Holesky using test branch on other side
=> Add Holesky support to oneClick

.github/workflows/sync-testnets.yml
=> Fix Sync Testnet images used

Dockerfile.dev
Updated JetBrains tools for dockerfile.dev
Manual testing todo
=> Update JetBrains tools for dockerfile.dev

src/Nethermind/Nethermind.Blockchain.Test/ReadOnlyBlockTreeTests.cs, src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Blockchain/IBlockTree.cs, src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugRpcModule.cs
- Adds additional parameter to allow deleting non-corrupted blocks
=> Add force to debug_deleteChainSlice

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityStyleTracerTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceModuleFactory.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
DO NOT MERGE UNTILL : https://github.com/NethermindEth/nethermind/pull/6237 is merged
- Adds state checks of availability for blocks in tracing rpc endpoints
=> Add state check for blocks when using trace_module

src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.Init.Snapshot/ISnapshotConfig.cs, src/Nethermind/Nethermind.Init.Snapshot/InitDatabaseSnapshot.cs, src/Nethermind/Nethermind.Init.Snapshot/SnapshotConfig.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs, src/Nethermind/Nethermind.Runner/Program.cs, src/Nethermind/Nethermind.Runner/configs/op-mainnet.cfg
- Op-mainnet genesis snapshot
- Now snapshot will continue downloading after restart
- Fixes op-plugin startup issue
=> Restore snapshot download & op-mainnet snapshot

.github/workflows/run-posdao-tests.yml
Make POSDAO tests to run more frequently rather than only on tag
=> Make POSDAO tests to run on each master and release commits

.github/workflows/posdao-tests.yml
Fixed POSDAO tests setup messed up because of the merge issue.
=> Fix POSDAO tests

src/Nethermind/Nethermind.Core/IKeyValueStore.cs
- Release the span after testing if key exists
=> Fix KeyExists leak

src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs
- Skip signature only for TxType.DepositTx
=> Skip signature only for TxType.DepositTx

src/Nethermind/Nethermind.Network/Metrics.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroNettyP2PHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Les/LesProtocolHandler.cs, src/Nethermind/Nethermind.Network/PeerManager.cs
Minor typo fix. Two of them are error messages, rest are comments.
=> chore(src/Nethermind): typo fix

src/Nethermind/Nethermind.Core/BlockchainIds.cs
- BlockchainIds.GetBlockchainName returns the name of holesky when passing it's networkid.
=> holesky networkId -> name

Dockerfile.diag
Revised, improved, and cleaned up the Dockerfile for diagnostics.
=> Revise and improve diagnostics Dockerfile

.github/workflows/posdao-tests.yml
Ensured artifact name is unique for each job to fix the failing POSDAO tests workflow.
=> Fix POSDAO tests workflow

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
- Time passes; size need occasional updates
=> Update Chain size test

src/Nethermind/Nethermind.Config.Test/ConfigFileTestsBase.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/holesky.cfg
- remove kovan and duplicates from configs tests
- add holesky to configs tests
- add FastSyncCatchUpHeightDelta = 10_000_000_000 to holesky.cfg
=> Update configs tests, add FastSyncCatchUpHeightDelta for holesky

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
- Remove db throttling introduced by https://github.com/NethermindEth/nethermind/pull/6417 as needs more study; as may risk reducing concurrency allowed by db
=> Remove db throttling

.editorconfig, CONTRIBUTING.md
Updated the copyright year in file header templates.
=> Update file header

.github/workflows/release.yml
Adjust path for release action (remove extra nethermind dir in path)
=> Fix Release Action

.github/workflows/release.yml
One more fix for checkout paths
=> Fix checkout paths for release action

src/Nethermind/Directory.Build.props
Just bump version to 1.25.0-unstable
=> Bump version to 1.26.0-unstable

.github/workflows/build-solutions.yml
Resolves #6454
- Added debug build configuration
- Parallelized build jobs to fix storage issues and speed them up
@LukaszRozmej Required merge checks need to be updated
=> Fix solution builds and add debug build configuration

src/Nethermind/Nethermind.TxPool/BlobTxStorage.cs
- Write out `IByteBuffer` prior to it being released back to pool by `using`
=> Write out IByteBuffer before it is released

src/Nethermind/Nethermind.Consensus/Processing/RecoverSignature.cs
Making block processing more robust. If something goes wrong in TxPool, block processing will work
We will test it with prysm node on devnet-12
=> Handling exceptions during signatures recovery

src/Nethermind/Nethermind.Core/Collections/EnumerableExtensions.cs, src/Nethermind/Nethermind.Network/PeerManager.cs
- Fixes snapshoting: https://stackoverflow.com/questions/41038514/calling-tolist-on-concurrentdictionarytkey-tvalue-while-adding-items
=> Fix ConcurrentDictionary.ToList->ToArray

src/Nethermind/Nethermind.State/StateProvider.cs
- Output codehash changes at Debug
=> Change logging of codehash changes to Debug

src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SubscriptionFactory.cs
=> Json rpc more flexible string parameter parsing

src/Nethermind/Directory.Packages.props
- Upgrade `System.IdentityModel.Tokens.Jwt` from 7.0.3 => 7.1.2 (security patch)
Breaking build
=> Upgrade System.IdentityModel.Tokens.Jwt

.github/workflows/publish-nuget.yml
Fixed the NuGet package path that has been changed by switching to simplified outputs.
=> Fix NuGet package path

src/Nethermind/Nethermind.Test.Runner/Nethermind.Test.Runner.csproj
- TestRunner should use `PublishReadyToRun` and `ServerGarbageCollection`
=> Testrunner should use same build settings as Nethermind

src/Nethermind/Nethermind.Api/IInitConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs, src/Nethermind/Nethermind.Db/Metrics.cs, src/Nethermind/Nethermind.Network/Metrics.cs
Fixed few typos, one is a comment, rest are descriptions. 
Doesn't require testing or changelog entry.
Have a nice evening.
=> Fixing few typos in src/Nethermind

src/Nethermind/Nethermind.Evm/CodeAnalysis/JumpDestinationAnalyzer.cs
- CPU doesn't like operating at single byte size, so move to `int`s
- Also reduces number of instructions needed to set and check
=> Optimize JumpDestinationAnalyzer further

src/Nethermind/Nethermind.Sockets/Extensions.cs
- Dispose websocket, shouldn't make much difference as should get disposed in RemoveClient, but shouldn't hurt either
=> Dispose websocket

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Monitoring/Nethermind.Monitoring.csproj, src/Nethermind/Nethermind.Sockets/Extensions.cs, src/Nethermind/Nethermind.Sockets/Nethermind.Sockets.csproj, src/Nethermind/Nethermind.sln
- use Sdk.Web where needed instead of having the deprecated nuget package references
All existing tests passing
=> [Cleanup] Remove deprecated aspnet core nugets

.github/workflows/hive-consensus-tests.yml
- Add a section to GitHub action for running consensus hive test results to reporter
=> Send consensus hive test results to reporter

.github/workflows/hive-consensus-tests.yml
Fix Hive tests branch selection on release commit
=> Fix branch selection when triggered by workflow_run

src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs
Micro-optimized and fixed GMP data import weirdness.
=> Optimize GMP data import

.github/workflows/sync-testnets.yml
Sepolia is getting bigger - it does not fit 80GB machine now on NonValidator (it does when sync is very fast but barely).
=> Upgrade machine to use 160 GB instead of 80 for sepolia

src/Nethermind/Nethermind.Core/Crypto/Signature.cs
- Mark `Span<T>` types as `JsonIgnore`
=> Ignore Span wrapping properties for Json serialization

.github/workflows/nethermind-tests.yml, src/Nethermind/Nethermind.AccountAbstraction.Test/Nethermind.AccountAbstraction.Test.csproj, src/Nethermind/Nethermind.Api.Test/Nethermind.Api.Test.csproj, src/Nethermind/Nethermind.Hive.Test/Nethermind.Hive.Test.csproj, src/Nethermind/Nethermind.Merge.AuRa.Test/Nethermind.Merge.AuRa.Test.csproj, src/Nethermind/Nethermind.Mev.Test/Nethermind.Mev.Test.csproj, src/Nethermind/Nethermind.Monitoring.Test/Nethermind.Monitoring.Test.csproj, src/Nethermind/Nethermind.Overseer.Test/Nethermind.Overseer.Test.csproj, src/Nethermind/Nethermind.Specs.Test/Nethermind.Specs.Test.csproj, src/Nethermind/Nethermind.State.Test.Runner.Test/Nethermind.State.Test.Runner.Test.csproj, src/Nethermind/Nethermind.TxPool.Test/Nethermind.TxPool.Test.csproj
Fixed code coverage collection and added missing package references.
=> Fix code coverage collection

src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Synchronization.Test/MallocTrimmerTests.cs, src/Nethermind/Nethermind.Synchronization/Synchronizer.cs
- Root `MallocTrimmer` and `SyncDbTuner`; they are rooted via timer (so not GC collected). Mostly it bothers me
=> Root MallocTrimmer and SyncDbTuner

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
=> Increase chainsize

src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
Contributes to #6557
Creates false log alerts
- VerifyCapacity under lock
=> VerifyCapacity under lock

src/Nethermind/Nethermind.Evm.Test/EvmPooledMemoryTests.cs, src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
Fix bug with trace memory introduced by https://github.com/NethermindEth/nethermind/pull/6640
- Only update trace memory clear by amount cleared
=> Only update trace memory clear by amount cleared

src/Nethermind/Nethermind.Trie/TrieNode.cs
- Atomically set the data array + value if being set when loading trie from db
=> Robustify Parallel Trie Reads

src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs, src/Nethermind/Nethermind.Synchronization/Peers/ISyncPeerPool.cs, src/Nethermind/Nethermind.Synchronization/Timeouts.cs
- Fix null pointer exception on FCU when no peer and block not found.
=> Fix null pointer exception

src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Rename and refactor as feedback from https://github.com/NethermindEth/nethermind/pull/6653#pullrequestreview-1864893045
=> TrieNode Feedback refactor

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
- "Attempted to process a blockchain without having starting state" is unhelpful
=> Clearer error message for missing starting block state

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- simple fix for proper error response on kestral exceptions
Return proper error message on JsonRPC server exceptions like exceeding the body size and others.
=> Push proper error message on kestral exceptions

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- As per SSTORE, makes easier for Jit to optimize, clearer what's happening when dottracing. Though shouldn't really have significant perf impact
=> Move SLOAD to own method as per SSTORE

CONTRIBUTING.md
Fixes
This simple PR fixes broken/outdated link.
- Simple update of broken link in contribution guide.
=> Fix broken link to docs

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
- Functionally the same but avoids creating an array
=> Use RocksDb HasKey

src/Nethermind/Nethermind.Blockchain/Blocks/BlockStore.cs, src/Nethermind/Nethermind.Blockchain/FullPruning/CopyTreeVisitor.cs, src/Nethermind/Nethermind.Core/Bloom.cs, src/Nethermind/Nethermind.Crypto/Keccak512.cs, src/Nethermind/Nethermind.Db/IDb.cs, src/Nethermind/Nethermind.Evm.Test/EvmPooledMemoryTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Data/AccessListItemForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Data/AccountForRpc.cs, src/Nethermind/Nethermind.Optimism/Create2DeployerContractRewriter.cs, src/Nethermind/Nethermind.Optimism/OptimismBlockProcessor.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs, src/Nethermind/Nethermind.Sockets/WebSocketMessageStream.cs, src/Nethermind/Nethermind.Trie.Test/VisitingTests.cs, src/Nethermind/Nethermind.Trie/BatchedTrieVisitor.cs, src/Nethermind/Nethermind.Trie/VisitContext.cs
- Make what can be `readonly` readonly
=> ReadOnly all the things

src/Nethermind/Nethermind.Benchmark.Runner/Program.cs
=> Update Benchmarks to .NET8

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
=> Consistent severity in bad blocks logging

.github/workflows/sync-testnets.yml
=> Adjust Sync Testnet action 

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs, src/Nethermind/Nethermind.Network.Test/MessageDictionaryTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs
Flaky test to explicit Will_fill_up_over_and_over_again_on_disconnects_and_when_ids_keep_changing
=> Flaky tests to explicit or retries of flaky tests

.github/workflows/hive-consensus-tests.yml
=> Make sure reporting does not affect the Hive results

.github/workflows/posdao-tests.yml
Change runner to LargeRunner for POSDAO tests
EDIT:
Added extra option to change Nethermind branch (Needed by Jorge for troubleshooting)
=> Change POSDAO VM to Large Runner + add option to select custom Neth branch

src/Nethermind/Nethermind.Db.Test/ColumnsDbTests.cs, src/Nethermind/Nethermind.TxPool.Test/NonceManagerTests.cs
Issues with flaky test to fix:
https://github.com/NethermindEth/nethermind/issues/6737
https://github.com/NethermindEth/nethermind/issues/6736
=> Less flaky tests

src/Nethermind/Nethermind.Db.Test/ColumnsDbTests.cs
- Add retry wait for memtable size.
=> Probably fix flaky memtable size test

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs, src/Nethermind/Nethermind.Synchronization/Peers/ISyncPeerPool.cs
Fix #6725
- Catch timeout exception in get header.
=> Fix timeout exception

src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
- No functional change, just some doc change.
- Remove clearly no longer experimental flag.
=> Remove experimental flag

src/Nethermind/Nethermind.Evm.Test/TransactionProcessorTests.cs, src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
Fixes #6651
- Estimate when balance matches tx value too
[Some test cases](https://gist.github.com/flcl42/5875fa855eb814e5f2ae255d76349456)
=> Estimate when balance matches tx value too

src/Nethermind/Nethermind.Api/IInitConfig.cs, src/Nethermind/Nethermind.Api/InitConfig.cs, src/Nethermind/Nethermind.Blockchain/BlockHashInState/BlockHashInStateHandler.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/IBlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/StatelessBlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Withdrawals/WithdrawalProcessor.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/BasicTestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/BasicTestVerkleBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestVerkleBlockchain.cs, src/Nethermind/Nethermind.Evm/Tracing/BlockExecutionTracer.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.JsonRpc/Modules/ModuleType.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs, src/Nethermind/Nethermind.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Verkle.Tree/VerkleTree.Prover.cs
=> [Verkle] Feature/stateless processing

src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Network/P2P/Messages/HelloMessage.cs
- Dispose HelloMessage
Missed one more
=> Dispose HelloMessage

src/Nethermind/Nethermind.Init/Steps/Migrations/ReceiptFixMigration.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PeerRefresher.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/SnapProtocolTests/StateSyncDispatcherTests.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
- More ArrayPoolList dispose fixes
=> More missed disposes

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
- Make things easier to integrate with hive.
=> Allow serving snap without having snap sync enabled

src/Nethermind/Nethermind.Consensus/Producers/BuildBlocksOnlyWhenNotProcessing.cs, src/Nethermind/Nethermind.Consensus/Producers/CompositeBlockProductionTrigger.cs, src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Core/Extensions/DisposableExtensions.cs, src/Nethermind/Nethermind.Core/Resettables/DisposableResettableList.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcResponse.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs, src/Nethermind/Nethermind.Network/P2P/MessageDictionary.cs, src/Nethermind/Nethermind.Network/P2P/MessageQueue.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/Request.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs
- Cleanup response if it comes after timeout
=> Cleanup timeout responses

src/Nethermind/Nethermind.JsonRpc.Test/Data/DictionaryConverterTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Data/SerializationTestBase.cs, src/Nethermind/Nethermind.Serialization.Json/DictionaryAddressKey.cs
- Sometimes one of the `AddressAsKey` dictionaries is serialized
=> Support AddressAsKey Json Serialization

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
=> Remove cold costs

src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedHealingTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs
- Backport from halfpath.
- Use snap server for state sync test.
=> Use snap server for state sync tests

src/Nethermind/Nethermind.Runner/Program.cs
Closes #6823 
- Running dotnet format command to resolve formatting errors.
=> Adding dotnet formatting

src/Nethermind/Nethermind.Config/ExitCodes.cs, src/Nethermind/Nethermind.Core/Collections/MemoryContentsComparer.cs, src/Nethermind/Nethermind.Runner/Program.cs
Replaces #6829
Resolves #6823
- Adding a new method to create a dictionary of the passed arguments. 
- If a certain key is passed twice, then the program will stop execution. 
1. Need to add test cases by trying to run with duplicate arguments and expecting an exception to be thrown. 
- [] Yes
- [] Yes
=> Check for multiple cli arguments

src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
Accidentally, rolled back in https://github.com/NethermindEth/nethermind/pull/6804 Adjusted bad blocks severity to Warn
=> Fix logging for bad blocks

.github/workflows/update-config-files.yml, scripts/syncSettings.py
Remove goerli from pivot bump action as it crashes now.
=> Remove goerli from pivot updates

src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs, src/Nethermind/Nethermind.Benchmark/Verkle/VerkleWorldStateBenchmark.cs, src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs, src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs, src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs, src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs
- Add some benchmark for verkle world state and compare it to MPT.
- Fix build.
- Current result:
| Method                         | TreeType | Configuration | Mean         | Error      | StdDev     |
|------------------------------- |--------- |-------------- |-------------:|-----------:|-----------:|
| InsertAndCommitRepeatedlyTimes | MPT      | Balance       |     70.34 ms |   1.383 ms |   1.593 ms |
| InsertAndCommitRepeatedlyTimes | MPT      | WriteHeavy    |     60.47 ms |   1.151 ms |   1.130 ms |
| InsertAndCommitRepeatedlyTimes | MPT      | ReadHeavy     |     12.46 ms |   0.236 ms |   0.231 ms |
| InsertAndCommitRepeatedlyTimes | MPT      | AddressOnly   |     75.62 ms |   1.441 ms |   1.479 ms |
| InsertAndCommitRepeatedlyTimes | Verkle   | Balance       |  7,191.14 ms | …
=> Add benchmark

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/CopyTreeVisitorTests.cs, src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs, src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs, src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs, src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs, src/Nethermind/Nethermind.Consensus.Test/Scheduler/BackgroundTaskSchedulerTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
- Make some tests more reliable.
- Make sync test run faster.
- Unfortunately, locally, still does not always pass all tests in one go. At least it does not hang.
=> Make test run faster

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
Stop building if branch contains upper case letters
=> Check branch name for uppercase

scripts/deployment/ppa/debian/control
Fixes #6764 
Added the missing PPA `unzip` dependency.
=> Fix PPA dependencies

scripts/private-networking/clique-validators.sh
Fixed the script so it works, and made validator number and docker image as args.
=> clique script for private network

src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
=> Increase Will_Trigger_ReorgBoundaryEvent_On_Prune delay to fix CI

.github/workflows/publish-docker.yml, .github/workflows/rpc-comparison.yml, .github/workflows/run-a-single-node-from-branch.yml
Adds option to convert automatically selected node to Paprika on oneClick and in JsonRPC testing action
=> Add Paprika Conversion to OneClick and RPC Tests

src/Nethermind/Nethermind.Consensus.Test/Scheduler/BackgroundTaskSchedulerTests.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
=> Increase delay on CI

.github/workflows/update-docs.yml
Fixed the shell script in the docs workflow.
=> Fix the docs workflow

src/Nethermind/Nethermind.Core/ByteArrayConverter.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
- Use runtime's IndexOfAnyExcept
=> Optimize CountLeadingZeros

.github/workflows/publish-packages.yml
Added PPA package support on Ubuntu 24.04 (Noble Numbat) and made it the default.
=> Support PPA package on Ubuntu 24.04

src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs, src/Nethermind/Nethermind.Api/Extensions/IConsensusPlugin.cs, src/Nethermind/Nethermind.Api/Extensions/IConsensusWrapperPlugin.cs, src/Nethermind/Nethermind.Api/Extensions/IPlugin.cs, src/Nethermind/Nethermind.Api/PluginPriorities.cs, src/Nethermind/Nethermind.Consensus/IBlockProducerFactory.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockProducer.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.BlockProducer.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Mev.Test/MevPluginTests.cs, src/Nethermind/Nethermind.Mev/MevPlugin.cs
- Make block production chain slightly understandable.
- Make `IBlockProducerFactory` which `IConsensusWrapper` wraps.
- Add a priority to plugins to determine wrapping priority.
=> Make block production chain slightly clearer

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.State/VerkleWorldState.cs, src/Nethermind/Nethermind.Verkle.Tree/VerkleTree.Prover.cs
Completed generation of ExecutionWitness by adding post state NewValue
https://github.com/NethermindEth/nethermind/issues/6690
=> Add post state values for ExecutionWitness

src/Nethermind/Nethermind.Core/ConsensusRequests/ConsensusRequest.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V4.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/Boost/BoostBlockImprovementContext.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayloadV3.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayloadV4.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/GetPayloadV2Result.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/GetPayloadV3Result.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/GetPayloadV4Result.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/IExecutionPayloadParams.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadV1Handler.cs
Additional refactor for #6905
- Refactor for more strict versioning. Avoid creating multiple ExecutionPayload for each versions due to type hierarhy.
- Optimize Creating ExecutionPayload.
=> Refactor Engine API with even more strict ExecutionPayload versioning

src/Nethermind/Nethermind.Blockchain.Test/BlockhashProviderTests.cs, src/Nethermind/Nethermind.Blockchain/Blocks/BlockhashStore.cs, src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs, src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs, src/Nethermind/Nethermind.Specs/ReleaseSpec.cs, src/Nethermind/Nethermind.Specs/SystemTransactionReleaseSpec.cs
=> remove transition timestamp and use spec instead

.github/workflows/rpc-comparison.yml
Fixed invalid machine type selected for tests.
Changed log level to INFO to remove overload on node during perf testing.
Removed Pruning=None as tool will use only last 64 blocks
=> Improve RPC tests action

src/Nethermind/Ethereum.Blockchain.Pyspec.Test/CancunStateTests.cs, src/Nethermind/Ethereum.Test.Base/GeneralStateTest.cs, src/Nethermind/Ethereum.Test.Base/GeneralStateTestEnvJson.cs, src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs, src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs
Fixes #6978
Fix pyspec tests for Cancun state tests
1. Added missing (CurrentExcessBlobGas) field
2. initialize KzgPolynomialCommitments
=> Fix pyspec tests for Cancun state tests

.github/workflows/run-a-single-node-from-branch.yml
Add possibility to trigger nimbus node with oneClick
=> Add Nimbus support to oneClick

src/Nethermind/Directory.Build.props
A bit late bump on master to 1.27.0
=> Late bump to 1.27.0-unstable

.github/workflows/rpc-comparison.yml
Small typo in workflow which was missed on last PR
=> Fix small typo in workflow

.github/workflows/rpc-comparison.yml
Improve RPC action node to always use most recent flood version
=> Make sure flood is reinstalled on VPS

.github/workflows/rpc-comparison.yml
=> Fix simple typo in workflow file

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Add memory size before and after to prune message
=> Add Memory sizes to Pruning message

src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs
Related to #7042
- Details in logs
=> Add more logs on discovery binding issue

src/Nethermind/Nethermind.JsonRpc/Modules/Eth/FeeHistory/FeeHistoryOracle.cs
- Runs the cleanup on caching blocks, useful when there are no eth_getHistory calls.
=> Fee history - run cleanup also on updating main chain

src/Nethermind/Nethermind.Core/IKeyValueStore.cs
Fixes KeyExists function in KeyValueStore
=> fixed KeyExists function in KeyValueStore

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Don't change MgasPerSec on empty blocks
=> Don't change MgasPerSec on empty blocks

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
- Skip prewarm if tx count < 3
=> Skip prewarm if tx count < 3

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Add 🔥 next to > 1Ggas/s in logs
=> Highlight gigagas in logs

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Reduces contention as speeds go higher
=> Use NonBlocking ConcurrentDictionary in a couple places

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- use AccountChanges only in main processing thread
=> use AccountChanges only in main processing thread

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
- We force GC at particular points anyway; so keep the behviour boring and consistent (until throuput is stable)
=> Turn off GarbageCollectionAdaptationMode

src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/PersistentBlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.Events.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
Resolves #6843?
- Change access to `value` on removal.
- RemoveLast will try until it succeeds.
=> Persistently remove worst item until actually removed

src/Nethermind/Nethermind.Core/Account.cs, src/Nethermind/Nethermind.Core/Verkle/AccountHeader.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Evm/Witness/IExecutionWitness.cs, src/Nethermind/Nethermind.Evm/Witness/NoExecWitness.cs, src/Nethermind/Nethermind.Evm/Witness/VerkleExecWitness.cs, src/Nethermind/Nethermind.State.Test/VerkleTreeTests.cs, src/Nethermind/Nethermind.State.Test/VerkleWitnessAccessCostTest.cs, src/Nethermind/Nethermind.State/VerkleStateReader.cs, src/Nethermind/Nethermind.State/VerkleStateTree.cs, src/Nethermind/Nethermind.State/VerkleWorldState.cs, src/Nethermind/Nethermind.Verkle.Tree/Utils/AccountExtension.cs
=> account header compression

src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
Fixes #7064 
buffer until all logs are available: eth_getLogs
=> buffer until all logs are available: eth_getLogs

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Serialization.Json/StreamPipeWriter.cs
- fix not completing the writing
=> fix not completing the writing of the JsonRPC response

tools/docgen/JsonRpcGenerator.cs
Fixed DocGen tool by removing `IWitnessRpcModule` as a result of the changes in #7020
=> Fix DocGen and remove `IWitnessRpcModule`

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Handle parallel withdrawals in pre-warmer
- Also don't let exception escapt to main loop
=> Handle parallel withdrawals in pre-warmer

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Fix pre-warm withdrawals (set state root)
=> Fix pre-warm withdrawals

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/Simulate/EthSimulateTestsBlocksAndTransactions.cs
https://github.com/NethermindEth/nethermind/pull/5530 Introduced an obvious typo
=> Fix typo in  EthSimulateTestsBlocksAndTransactions

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs
=> Updated comment in MergeBlockDownloader, fixed typos

src/Nethermind/Nethermind.Logging/ILogger.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
=> Fix comments

src/Nethermind/Nethermind.Core.Test/Caching/LruCacheLowObjectTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheLowObjectTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheNonConcurrentTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/SpanLruCacheTests.cs
- Check the full layout in Beyond_capacity
=> Further increase Lru tests

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Reset (`using`) prior to returning (`finally`) to pool
=> WarmupWithdrawals reset env prior to returning to pool

src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
- Output the invalid request at debug in jsonrpc; we currently only output the response
=> Output the invalid request at debug in jsonrpc

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs
- Provide some additional detail in debuig logs
=> Increase logging detail in debug

src/Nethermind/Nethermind.AccountAbstraction.Test/AccountAbstractionRpcModuleTests.cs, src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MulPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MultiExpPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2AddPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MulPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MultiExpPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapToG1Precompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapToG2Precompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/PairingPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/ModExpPrecompilePreEip2565.cs, src/Nethermind/Nethermind.Evm/Precompiles/Snarks/Bn254PairingPrecompile.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthSimulateTestsPrecompilesWithRedirection.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/Simulate/EthSimulateTestsSimplePrecompiles.cs
Revert parts of changes #7106
- Reverts SkipLocalsInit and parts of ModExp optimizations - they might cause consensus issues
=> Revert parts of changes #7106

src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
- Fix by setting the cache to empty items
=> Fix by setting the cache to empty items

src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Fixed the misleading _"Message authentication error: The token cannot be found."_ flood of warnings caused by the changes introduced in #7177 
Manually tested
=> Revise JWT authentication check

src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/NoBlockImprovementContext.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/NoBlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/NoBlockProductionContext.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PostMergeBlockProducer.cs, src/Nethermind/Nethermind.Optimism/OptimismPostMergeBlockProducer.cs, src/Nethermind/Nethermind.Taiko/BlockMetadata.cs, src/Nethermind/Nethermind.Taiko/ITaikoEngineRpcModule.cs, src/Nethermind/Nethermind.Taiko/TaikoEngineRpcModule.cs, src/Nethermind/Nethermind.Taiko/TaikoPayloadAttributes.cs, src/Nethermind/Nethermind.Taiko/TaikoPayloadPreparationService.cs, src/Nethermind/Nethermind.Taiko/TaikoPayloadTxSource.cs, src/Nethermind/Nethermind.Taiko/TaikoPostMergeBlockProducer.cs, src/Nethermind/Nethermind.Taiko/TaikoSimplePayloadPreparationService.cs
Engine api modifications without the logic for skipping invalid txs during block execution
=> Gigachain engine api

src/Nethermind/Nethermind.Logging/Progress.cs
- Inputs aren't guarenteed to be in range of each other
=> Clamp progress bar inputs

src/Nethermind/Nethermind.JsonRpc/ResultWrapper.cs, src/Nethermind/Nethermind.Optimism/OptimismBlockProducerEnvFactory.cs, src/Nethermind/Nethermind.Optimism/Rpc/IOptimismEngineRpcModule.cs, src/Nethermind/Nethermind.Optimism/Rpc/OptimismEngineRpcModule.cs, src/Nethermind/Nethermind.Optimism/Rpc/OptimismGetPayloadV3Result.cs
Fixes OP CL driven block production
- Add pbbr to GetPayloadV3Result
- Use OptimismTransactionsExecutorFactory again
- [x No
=> Fixes OP CL driven block production

src/Nethermind/Nethermind.Core.Test/Caching/ClockCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/ClockKeyCacheNonConcurrentTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/ClockKeyCacheTests.cs, src/Nethermind/Nethermind.Core/Caching/ClockCache.cs, src/Nethermind/Nethermind.Core/Caching/ClockCacheBase.cs, src/Nethermind/Nethermind.Core/Caching/ClockKeyCache.cs, src/Nethermind/Nethermind.Core/Caching/ClockKeyCacheNonConcurrent.cs
Resolves #7256 
- Allow zero sized caches
=> Allow zero sized caches

.github/workflows/sync-testnets.yml
- Update golang version for Sedge
=> Update golang version for sedge

.github/workflows/sync-testnets.yml
Switching to prysm as there are issues with sepolia on any other CL
=> Switch quick sync test to prysm

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Cli/Nethermind.Cli.csproj, src/Nethermind/Nethermind.Cli/Program.cs, src/Nethermind/Nethermind.Runner/Logging/NLogConfigurator.cs, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj, src/Nethermind/Nethermind.Runner/Program.cs, tools/HiveCompare/HiveCompare/HiveCompare.csproj, tools/HiveCompare/HiveCompare/Program.cs, tools/SendBlobs/Program.cs, tools/SendBlobs/SetupCli.cs
- Replaced abandoned `Microsoft.Extensions.Configuration.CommandLine` with newer but also no longer evolving [`McMaster.Extensions.CommandLineUtils`](https://github.com/natemcmaster/CommandLineUtils?tab=readme-ov-file#project-origin-and-status) package which is an _almost_ drop-in replacement. This brings bug fixes and new features and eliminates the NuGet warning on deprecated packages. I consider this a temporary solution until switching to System.CommandLine, which is asymptotically getting closer to its release. _Sigh._
- Also updated projects in tools. Maintainers may take a closer look.
Needs manual testing.
=> Switch to McMaster.Extensions.CommandLineUtils package

tools/Nethermind.Tools.Kute/JsonRpcMethodFilter/ComposedJsonRpcMethodFilter.cs
Replaced the missing method, causing a compile error introduced in #7269.
=> Replace missing method in Kute

src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcModuleProviderTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/Modules/IRpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/Modules/NullModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs
- Add module name to module disabled message
=> Add module name to module disabled message

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs, src/Nethermind/Nethermind.Blockchain/KnownChainSizes.cs
@kamilchodola could you update pruned estimates for those chains?
Added some estimations for mainnet and sepolia, but I don't trust them.
=> update known chain sizes

.github/workflows/hive-consensus-tests.yml
Increase a wait time for publish action as it is longer now
=> Wait for longer on docker creation and trigger

src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
Fixes Closes Resolves #7284
fix gas estimation issue when from address defaults to system user address. 
=> fix eth_gasEstimate issue

src/Nethermind/Nethermind.Core/ILogEntry.cs, src/Nethermind/Nethermind.Core/LogEntry.cs, src/Nethermind/Nethermind.Facade/Filters/FilterLog.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergePlugin.cs, src/Nethermind/Nethermind.Merge.AuRa/Shutter/Contracts/SequencerContract.cs, src/Nethermind/Nethermind.Merge.AuRa/Shutter/IShutterBlockHandler.cs, src/Nethermind/Nethermind.Merge.AuRa/Shutter/ShutterBlockHandler.cs, src/Nethermind/Nethermind.Merge.AuRa/Shutter/ShutterTxLoader.cs
=> Shutter: collect events on new block

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Benchmark.Runner/Program.cs, src/Nethermind/Nethermind.Benchmark/Verkle/VerkleWorldStateBenchmark.cs, src/Nethermind/Nethermind.Verkle.Tree.Test/NodeSerializerTests.cs, src/Nethermind/Nethermind.Verkle.Tree/Serializers/InternalNodeSerializer.cs, src/Nethermind/Nethermind.Verkle.Tree/TreeNodes/InternalNodes.cs
=> use uncompressed internal nodes for verkle

.github/workflows/sync-supported-chains.yml
I've used invalid event to distinguish if job should be triggered or not. Fixed
=> Fix trigger of tests

src/Nethermind/Nethermind.Core/Caching/ClockCache.cs, src/Nethermind/Nethermind.Core/Caching/ClockCacheBase.cs, src/Nethermind/Nethermind.Core/Caching/ClockKeyCache.cs, src/Nethermind/Nethermind.Core/Caching/ClockKeyCacheNonConcurrent.cs
- Feedback from https://github.com/NethermindEth/nethermind/pull/7338
=> Clock cache additional improvements

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
- Move prewarm wait to just before state reset; in case it takes a little while to cancel
=> Move prewarm wait to end of all block activity

.github/workflows/sync-supported-chains.yml
Simple issue - missed this step to be added to properly trigger other action
- [ X] No
=> Add missing token generation

src/Nethermind/Nethermind.Blockchain.Test/Consensus/ClefSignerTests.cs, src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs, src/Nethermind/Nethermind.ExternalSigner.Plugin/ClefSigner.cs, src/Nethermind/Nethermind.ExternalSigner.Plugin/ClefSignerPlugin.cs
=> Some basic refactors of Nethermind.ExternalSigner.Plugin

src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorFastSyncTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncReportTest.cs
Fixed compile errors caused by #6529
=> Fix compile errors

src/Nethermind/Nethermind.Runner/configs/energyweb.cfg, src/Nethermind/Nethermind.Runner/configs/exosama.cfg, src/Nethermind/Nethermind.Runner/configs/gnosis.cfg, src/Nethermind/Nethermind.Runner/configs/holesky.cfg, src/Nethermind/Nethermind.Runner/configs/joc-mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/poacore.cfg
Resolves #7166 
- removes obsolete flag `FastBlocks` from configs
=> Remove obsolete flag `FastBlocks` from configs

.github/workflows/test-assertoor.yml
Fix assertor docker image creation trigger
=> Fix assertor docker image creation trigger

.github/workflows/build-solutions.yml
Add merge_group trigger for Build action - preparation for enabling merge queues on repo.
=> Add merge_group trigger condition to build

src/Nethermind/Nethermind.Core/Extensions/SizeExtensions.cs, src/Nethermind/Nethermind.Init/InitializeStateDb.cs
Resolves #7368 
- Display full pruning info in convinient way
=> Display parameters of full pruning

.github/workflows/sync-supported-chains.yml
When on release docker image creation, sync supported chains action triggered not for release but for master.
This hopefully address the issue
=> Fix invalid image used when trigger for new release docker publish action

funding.json
=> OP funding

funding.json
=> Funding OP RPGF, project nr 2

funding.json
=> Funding OP RPGF

funding.json
=> OP RPGF funding.json

src/Nethermind/Nethermind.Init/InitializeStateDb.cs
=> change PruningBoundry setting log to Info

README.md
Updated supported networks page.
=> Update Supported Networks in Readme

src/Nethermind/Nethermind.Core/Address.cs
- Address is always 20 bytes so can do direct Vector128 + uint compare rather than calling SequenceEqual
=> Fast address equals

src/Nethermind/Directory.Build.props
Bump version to 1.29.0_unstable (should be done some time ago).
=> Bump unstable to 1.29.0

src/Nethermind/Nethermind.Blockchain/Blocks/BlockStore.cs, src/Nethermind/Nethermind.Blockchain/Headers/HeaderStore.cs, src/Nethermind/Nethermind.Evm/Tracing/NullBlockTracer.cs, src/Nethermind/Nethermind.Serialization.Rlp/KeyValueStoreRlpExtensions.cs, src/Nethermind/Nethermind.State/Repositories/ChainLevelInfoRepository.cs
- Use ClockCache rather than LurCache for blocks and headers
=> Use ClockCache rather than LurCache for blocks and headers

README.md
=> Remove Goerli

src/Nethermind/Nethermind.Core/Collections/SpanConcurrentDictionary.cs
=> Fix argument null checks

src/Nethermind/Directory.Build.props
=> Bump unstable to 1.30.0

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Unnecessary noise; still logs in main entry
=> Skip logging cancellations in each arm of prewarmer

src/Nethermind/Nethermind.Optimism/InitializeBlockchainOptimism.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs, src/Nethermind/Nethermind.Optimism/Rpc/IOptimismEthRpcModule.cs
=> Fix OP initialization order

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Prague.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadBodiesByRangeV2Handler.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
Some merge led to [compilation issues](https://github.com/NethermindEth/nethermind/actions/runs/11035788842/job/30653100263#step:6:401), needs a clean up from a specific namespace
=> Fix namespaces

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Don't let any errors escape the prewarmer; treat EvmErrors as normal txn flow
=> Streamline prewarming error handling

src/Nethermind/Nethermind.Runner/configs/base-mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/base-sepolia.cfg, src/Nethermind/Nethermind.Runner/configs/op-mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/op-sepolia.cfg
Resolves #7463
- Use new DiscoveryVersion option in OP configs
=> Use new DiscoveryVersion option in OP configs

src/Nethermind/Chains/op-mainnet.json, src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs, src/Nethermind/Nethermind.Core/Specs/ReleaseSpecDecorator.cs, src/Nethermind/Nethermind.Evm/Precompiles/Snarks/Bn254PairingPrecompile.cs, src/Nethermind/Nethermind.Network/ProtocolValidator.cs, src/Nethermind/Nethermind.Optimism/IOptimismSpecHelper.cs, src/Nethermind/Nethermind.Optimism/OPConfigHelper.cs, src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainParameters.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecJson.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecParamsJson.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/OptimismParameters.cs, src/Nethermind/Nethermind.Specs/ReleaseSpec.cs
=> Add OP Granite fork

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- More are used than the current cache size (addition of parallel address warmer + add buffer)
=> Increase object pool sizes in prewarmer

src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/TransactionForRpc.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs
=> Json Type parsing

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcUrlTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/TxTraceFilterTests.cs
- Tend to Jam; might have issues with Test runner sync context
=> Reduce Parallelism in JsonRpc tests

src/Nethermind/Nethermind.Evm/Metrics.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1AddPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MulPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MultiMulPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2AddPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MulPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MultiMulPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapToG1Precompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapToG2Precompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/PairingPrecompile.cs
=> Add bls precompile metrics

src/Nethermind/Nethermind.Blockchain/FullPruning/CopyTreeVisitor.cs, src/Nethermind/Nethermind.Merge.Plugin/PoSSwitcher.cs
Full pruning started shouldn't be a warning, just info. 
Removed all logs from PoS transition that are incorrectly printed on nodes now.
=> Small log improvements

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
Based on #7541
- Avoid some allocations
- non-allocating Stopwatch 
- code simplification/shortening
=> Micro optimizations: avoid allocations + stopwatch

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Runner/NLog.config
tps is commonly used so I propose changing t/s to tps. Wdyt?
=> t/s to tps in logs?

src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs
This reverts commit 50d74867484da2088f14ca7abd82ad8ee3de5874.
- Needs more testing
=> Revert "Avx512 Keccak (#7561)"

src/Nethermind/Nethermind.TxPool/Collections/BlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/PersistentBlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
Alternative to #7568
- Run TryGetBlobAndProof under lock, simplify to Dictionary
=> Fix Blob index locking v2

src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Consensus.Test/TargetAdjustedGasLimitCalculatorTests.cs
I wanted to check something related to the gas limit, so I added a unit test. It's just one more test, nothing else important in this PR.
=> One more test in TargetAdjustedGasLimitCalculator

.github/workflows/build-tools.yml
Added build status checks for the projects in the `tools` directory.
=> Add status checks for tools

src/Nethermind/Nethermind.Consensus/GC/GCScheduler.cs, src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs
- Add back MallocTrim, was lost in a refactoring
- Shorten pause after NewPayload to GC to 125ms
=> Re Add Malloc Trim

.github/workflows/publish-packages.yml
Added the `build-essential` package to fix PPA publishing
=> Update PPA publish prerequisites

.github/workflows/publish-packages.yml, .github/workflows/update-fast-sync.yml
- Fixed Python issues because of PEP 668 adoption in GitHub Action runners on Ubuntu 24.04:  Replaced the default Python installation
- Reverted the changes in #7613 
=> Fix Python issues in workflows

src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
- Fix opstack start.
- Tested manually.
=> Fix opstack cant start

.github/workflows/sync-supported-chains.yml, scripts/workflow_config/sync_testnets_matrix.json
Add Linea mainnet and sepolia to supported chains
=> Add linea to sync supported chains

src/Nethermind/Nethermind.Wallet/NodeKeyManager.cs
- Add error details to log when account unlock fails, helps in diagnosing issues on AuRa validators
=> Add error details to log when account unlock fails

src/Nethermind/Nethermind.Shutter/Contracts/ValidatorRegistryContract.cs
- Check length of update messages in validator registration contract
=> Shutter fix: check registration update message length

src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaEofTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaStateTests.cs, src/Nethermind/Ethereum.Blockchain.Test/EofTests.cs, src/Nethermind/Ethereum.Test.Base/EofTestBase.cs, src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs, src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs, src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs, src/Nethermind/Nethermind.Evm/EvmObjectFormat/EofCodeInfo.cs, src/Nethermind/Nethermind.Evm/ICodeInfo.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/JavaScript/GethLikeJavaScriptTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Specs.Test/MainnetSpecProviderTests.cs, src/Nethermind/Nethermind.Specs/Forks/18_Prague.cs, src/Nethermind/Nethermind.Specs/Forks/19_Osaka.cs, src/Nethermind/Nethermind.Specs/MainnetSpecProvider.cs, src/Nethermind/Nethermind.Test.Runner/EofTestsRunner.cs, src/Nethermind/Nethermind.Test.Runner/StateTestTxTracer.cs
* Deploy on Osaka (all EEST tests are moving to Osaka only)
* fix bug with EXTDELEGATECALL calling precompiles (should fail)
* Correctly handle value costs in EXTDELEGATECALL
* remove println to fix testing integration issues
Tests are from EEST published reference tests
=> Adaot to EEST Osaka Activation

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockProductionTransactionPicker.cs, src/Nethermind/Nethermind.Evm.Test/Eip3860Tests.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Optimism/OptimismTransactionProcessor.cs, src/Nethermind/Nethermind.Taiko/Rpc/TaikoEngineRpcModule.cs
- Just add constants for failures
=> Replace failure messages with kinda constants in tx processor

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
=> Better increase nonce on prewarming

.github/workflows/sync-supported-chains.yml
=> Handle tests when runner creation fails

src/Nethermind/Nethermind.Merge.Plugin/Synchronization/UnsafePivotUpdator.cs
- fix potential null ref in `UnsafePivotUpdator`
=> Fix `UnsafePivotUpdator`

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Reduce log level on persist node in archive node.
- Tested to not show up when pruning is disabled.
=> Reduce log in archive node

src/Nethermind/Nethermind.Shutter.Test/ShutterApiSimulator.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterCryptoTests.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterTestsCommon.cs, src/Nethermind/Nethermind.Shutter/Config/ShutterValidatorsInfo.cs, src/Nethermind/Nethermind.Shutter/Config/ValidatorsInfo.cs, src/Nethermind/Nethermind.Shutter/Contracts/IValidatorRegistryContract.cs, src/Nethermind/Nethermind.Shutter/Contracts/ValidatorRegistryContract.cs, src/Nethermind/Nethermind.Shutter/ShutterApi.cs, src/Nethermind/Nethermind.Shutter/ShutterBlockHandler.cs, src/Nethermind/Nethermind.Shutter/ShutterCrypto.cs, src/Nethermind/Nethermind.Shutter/ShutterPlugin.cs
- Decode pubkeys in validator info file at startup - prevents crashing later if invalid
- Refactor validator info into own class
=> Shutter: Fix validator info file validation

.github/workflows/sync-supported-chains.yml
Adjusted logs captured during VerifyTrie after state sync
=> Fix Verify trie on tests

.github/workflows/sync-supported-chains.yml
=> make sure VM is removed regardless of previous statuses

src/Nethermind/Nethermind.Evm/Instruction.cs
=> Fix TStore, TLoad gas

src/Nethermind/Nethermind.Consensus.AuRa/Config/AuRaChainSpecEngineParameters.cs
I was not decoding ValidatorsJson properly
- Fix
=> Fix bug in Aura chainspec decoding

src/Nethermind/Nethermind.Runner/configs/gnosis.json
- Fix typo in sequencer contract address in gnosis configs
=> Shutter: fix gnosis config

src/Nethermind/Nethermind.Optimism/OptimismChainSpecEngineParameters.cs
Peers disconnect us if we add op transitions
- Remove transitions from op chainspec
=> Hot fix for op sync

src/Nethermind/Nethermind.Trie/Pruning/OverlayTrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
Fixes issue introduced by #7362
=> Fix RPC "No state available" when using latest block

.github/workflows/sync-supported-chains.yml
Improve peering in base-mainnet test sync
=> [TESTS] Improve peering in base-mainnet test sync

src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs
Currently, when we want to update a vote in a proposal, we need to:
1. Discard the old vote
2. Add the new vote
https://github.com/user-attachments/assets/0c28908f-9983-4593-a9af-ec23862c5287
- Allow override vote when calling clique proposal
https://github.com/user-attachments/assets/c27bee59-5060-4923-aff7-7f8bd355e794
=> Allow override vote in clique proposal

.github/workflows/build-solutions.yml
Switch to 8.0.403 dotnet version temporarily for building purpose
=> Temporarily switch to 8.0.403 dotnet version for build

src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedHealingTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs
=> fix flaky test by increasing dispatcher allocate timeout

README.md
Added Taiko to README and shortened the list for better readability as it gets longer and longer.
=> Add Taiko and revise the list

src/Nethermind/Nethermind.Abi/AbiParameterConverter.cs, src/Nethermind/Nethermind.Abi/AbiType.TypeMapping.cs, src/Nethermind/Nethermind.Blockchain/Spec/ChainHeadSpecProvider.cs, src/Nethermind/Nethermind.Consensus.AuRa/Contracts/DataStore/ContractDataStore.cs, src/Nethermind/Nethermind.Consensus.AuRa/Contracts/DataStore/ThreadSafeContractDataStoreCollectionDecorator.cs, src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs, src/Nethermind/Nethermind.Consensus/Processing/OneTimeProcessor.cs, src/Nethermind/Nethermind.Core/TypeDiscovery.cs, src/Nethermind/Nethermind.Facade/Filters/FilterStore.cs, src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/Recorder.cs, src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucket.cs, src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs, src/Nethermind/Nethermind.Network/NetworkStorage.cs, src/Nethermind/Nethermind.Network/P2P/MessageQueue.cs, src/Nethermind/Nethermind.Network/P2P/Session.cs, src/Nethermind/Nethermind.Network/PeerManager.cs, src/Nethermind/Nethermind.Serialization.Json/StreamPipeWriter.cs, src/Nethermind/Nethermind.Shutter/ShutterBlockHandler.cs, src/Nethermind/Nethermind.Shutter/ShutterKeyValidator.cs, src/Nethermind/Nethermind.Shutter/ShutterTxSource.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerAllocation.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncFeed.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs
- Use the new `System.Threading.Lock` rather than `object`
=> Use new System.Threading.Lock

.github/workflows/nethermind-tests.yml
- Add missing Nethermind and Ethereum tests
In #7763 we found that certain tests were not being run in CI. Since that PR is no longer required the tests changes are presented in this PR.
=> Add missing tests to CI

src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
=> fix for unstable test after introduction of DI

global.json, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerModuleTests.cs, src/Nethermind/Nethermind.Synchronization/FastSync/VerifyStateOnStateSyncFinished.cs
- Not sure why network without CL run verify trie multiple time forever, but this should fix it.
=> Run verifytrie only once on state sync finished

src/Nethermind/Directory.Packages.props
Updated Nethermind.Crypto.SecP256k1 package with small performance optimizations.
=> Update Nethermind.Crypto.SecP256k1 package

scripts/workflow_config/sync_testnets_matrix.json
- Changes the size of machines used for taiko to small tiers
=> fix: taiko machine size

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Perform full flush on shutdown
=> Full flush on shutdown

src/Nethermind/Nethermind.Config/IProcessExitSource.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcProcessor.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Reject incoming requests during shutdown; been bugging me for a while :)
=> Stop accepting JsonRpc requests during shutdown

src/Nethermind/Nethermind.Runner/configs/op-mainnet.json
Reverted removed Barriers as those point to regenesis
=> Revert Barriers Removal

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Incorrect bracketing for fast path
=> Fix dodgy bracket precedent

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeSynchronizer.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs, src/Nethermind/Nethermind.Taiko/TaikoPlugin.cs
- Fix missed dispose due to `Append` is not `Push`. 
- Tested with manual log to make sure synchronizer is disposed.
=> Fix missed dispose

src/Nethermind/Nethermind.Runner/Program.cs
- Remove warning of deprecated value, it is unlikely to ever be removed and message will just cause support headaches and worry
=> Remove for deprecation message for --datadir

src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs, src/Nethermind/Nethermind.Evm/Precompiles/Sha256Precompile.cs, src/Nethermind/Nethermind.Merkleization/ShaMerkleTree.cs
- Use static SHA256`.TryHashData` rather than thread local instance and `.TryComputeHash`
=> Use static SHA256.TryHashData rather than thread local instance

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Withdrawals/WithdrawalProcessor.cs, src/Nethermind/Nethermind.Evm/StateOverridesExtensions.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.State/IWorldState.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs
- Decrease message severity for non-existing account `Error` -> `Debug` (throws exception so if issue will be picked up elsewhere)
- Move if checks on update vs create to use combined method for this purpose
=> Decrease message severity for non-existing account

.github/workflows/hive-consensus-tests.yml
Fixed the hive consensus tests workflow. Configured the required .NET setup.
Although GitHub Actions runner comes with bundled .NET runtime, we must ensure the required version is installed according to the `global.json` in the repo root.
=> Fix hive consensus tests workflow

src/Nethermind/Nethermind.Api/IInitConfig.cs, src/Nethermind/Nethermind.Api/InitConfig.cs, src/Nethermind/Nethermind.Runner/Ethereum/Api/ApiBuilder.cs
Removed redundant `IInitConfig.HiveChainSpecPath` as discussed with @MarekM25 and @dmitriy-b.
=> Remove `HiveChainSpecPath`

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Stats shouldn't effect processing
=> Don't fail when stats can't retrieve beneficiary

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/NodeData/NodeDataProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncFeed.cs
- Clear events in Dispose and more consistently call dispose in disconnect
=> Improve event clean up on disconnected peers

src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs
- The state's stateroot can change by something causing wrong nonce and invalid block.
=> Fix randomly hanging state override test

src/Nethermind/Nethermind.Benchmark.Runner/Program.cs
- Update Core runtime library for BenchmarkDotNet benchmarks
=> Update Benchmark runner .NET version

src/Nethermind/Nethermind.JsonRpc.Test/Modules/AdminModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/IAdminRpcModule.cs
=> Implement admin_dataDir for admin module

src/Nethermind/Nethermind.Shutter.Test/ShutterBlockHandlerTests.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterTestsCommon.cs, src/Nethermind/Nethermind.Shutter/Config/IShutterConfig.cs, src/Nethermind/Nethermind.Shutter/Config/ShutterConfig.cs, src/Nethermind/Nethermind.Shutter/ShutterApi.cs
- Change `BlockUpToDateCutoff` from 5 seconds to 20 seconds
- Make this option configurable
=> Shutter: increase BlockUpToDateCutoff

.editorconfig
- Error is a bit strong; also means templated files are immediately in error
=> Change extra using directive from error to suggestion

tools/SendBlobs/Dockerfile
Update docker image from : https://github.com/dotnet/dotnet-docker/blob/main/README.sdk.md#full-tag-listing
=> update dotnet version in docker image

.github/workflows/sync-supported-chains.yml, scripts/workflow_config/sync_testnets_matrix.json
Adding a DEBUG logs to output of an action whenever it fails.
Helpful when investigating syncing problems, json parsing errors etc.
Additionally adjusted machines types as some of them were too big for their purpose (sync only to tip) - may make action a bit smaller but surely less costly.
=> Add DEBUG logs to output when sync fails

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Network.Dns/EnrDiscovery.cs, src/Nethermind/Nethermind.Network/IP/WebIPSource.cs, src/Nethermind/Nethermind.Network/PeerManager.cs, src/Nethermind/Nethermind.Network/SessionMonitor.cs, src/Nethermind/Nethermind.Shutter/ShutterKeyValidator.cs, src/Nethermind/Nethermind.Shutter/ShutterP2P.cs, src/Nethermind/Nethermind.Shutter/ShutterTxLoader.cs, src/Nethermind/Nethermind.Shutter/ShutterTxSource.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
- Add `DEBUG/ERROR` to errors output during Debug logging
=> Annotate debug errors

src/Nethermind/Nethermind.Blockchain/Metrics.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Core/AccountStateProviderExtensions.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/WorldStateMetricsDecorator.cs
- Add metrics on CommitTrees
Manual on grafana.
=> Add StateMerkleizationTime Metrics

src/Nethermind/Ethereum.Trie.Test/TrieTests.cs, src/Nethermind/Nethermind.State.Test/NodeTests.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Not used by Ethereum MPT and adds additional complexity to the code
Removed some upstream tests that didn't use 32 byte keys
=> Remove branch values

src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs
Remove stdout line after request here:
https://github.com/holiman/goevmlab/pull/178
=> remove problematic stdout

src/Nethermind/Directory.Build.props
=> Bump to 1.31.0_unstable

.github/workflows/publish-packages.yml
Increased the PPA copy waiting time to 2h to avoid random deployment failures.
=> Increase PPA copy waiting time

src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
- Fix ci error
- Can't reproduce.
- I don't know why. This might fix it.
=> Fix ci error

src/Nethermind/Nethermind.Config.Test/SampleJson/SampleJsonConfig.json, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs
- FIxes issue where empty rpc modules are in config
=> filter out empty modules

src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs
- Fix state test runner not handling invalid tx properly
=> Fix state test runner not handling invalid tx properly

.github/workflows/run-a-single-node-from-branch.yml
Adjustments to match recent changes on the test repo
=> Adjust naming of params for oneClick

src/Nethermind/Nethermind.Evm/Metrics.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
- Add gas prices to grafana as `nethermind_gas_price_min`,  `nethermind_gas_price_median`,  `nethermind_gas_price_ave`,  `nethermind_gas_price_max` as requested in https://x.com/ethereanbull/status/1868743404928352569
=> Add gas prices to grafana

src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
- Not sure what real way to trigger this. Could just be a rare race condition.
- Unit test can throw, but need to manually delete level info.
=> Fix error on fetching header without total difficulty

src/Nethermind/Nethermind.Trie/PatriciaTree.cs
- Reuse single set of single byte keys
=> Allocate single byte keys once

src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs
- The `CancelOnDispose` thing does not work as the dispose order is not very clear. So hooked up a linked cancellation token.
- The `TaskCompletionSource` running continuation synchronously causes deadlock. Not the first case of this strange behaviour.
- Runs much faster again.
=> Fix really slow statesync tests

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
- Add block gas limit to NewPayload logs (it has become an interesting metric)
- Enough logging room for 9.99 GigaGas per block
=> Add GasLimit to NewPayoad log

src/Nethermind/Directory.Packages.props
Updated Nethermind.Numerics.Int256 package with the latest changes and performance updates
=> Update Nethermind.Numerics.Int256 package

src/Nethermind/Nethermind.Clique.Test/CliqueBlockProducerTests.cs
- Make clique test a bit more resilient.
=> Make clique test a bit more resilient

src/Nethermind/Nethermind.Synchronization.Test/SnapSync/StateSyncPivotTest.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncPivot.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
- Did not realize `CanSync` have some log in it. 
- Tested manually.
=> Fix spammy log during snap sync

src/Nethermind/Nethermind.Core/Eip7002Constants.cs, src/Nethermind/Nethermind.Core/Eip7251Constants.cs
new addresses for 7002 and 7251
https://github.com/ethereum/execution-specs/pull/1058
https://github.com/ethereum/execution-specs/pull/1056
=> Updated addresses for devnet 5

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Fix ChargeAccountAccessGas logic for delegated accounts
@ak88 to add tests for all conditions
=> Fix ChargeAccountAccessGas logic

.github/workflows/hive-tests.yml
=> Add eest to hive simulators

src/Nethermind/Nethermind.Runner/configs/base-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/base-sepolia_archive.json, src/Nethermind/Nethermind.Runner/configs/energyweb_archive.json, src/Nethermind/Nethermind.Runner/configs/joc-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/joc-testnet_archive.json, src/Nethermind/Nethermind.Runner/configs/linea-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/linea-sepolia_archive.json, src/Nethermind/Nethermind.Runner/configs/op-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/op-sepolia_archive.json, src/Nethermind/Nethermind.Runner/configs/poacore_archive.json
Add TxLookupRange 0 for all missing archive nodes configs
=> Add TxLookupLimit 0 for all missing archive nodes configs

src/Nethermind/Nethermind.Evm.Test/TransactionProcessorEip7702Tests.cs
Tests for 7702 for testing gas accounting, when an account is delegated using different op codes.
=> Account access gas 7702 tests 

scripts/deployment/ppa/debian/control
Fixes #6805 
- Added `curl` as an explicit dependency to PPA configuration
- Updated the description as per README
=> Add `curl` as an explicit dependency

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
ref: https://github.com/ethereum/EIPs/pull/9227
- first substract the refunds and then account for floor gas
=> EIP7623 - account for floor gas after substracting refunds

src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.Taiko/Rpc/RegisterTaikoRpcModules.cs
- Always override scope, applying block header
- Use readonly block tree in taiko?
=> Override empty state scope with the state of the current block

src/Nethermind/Directory.Packages.props
Pinned FluentAssertions version as fixed as other packages to prevent implicit updates
=> Pin FluentAssertions versions

src/Nethermind/Nethermind.Api/IApiWithBlockchain.cs, src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.Init/InitializeStateDb.cs, src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs, src/Nethermind/Nethermind.Synchronization/FastSync/VerifyStateOnStateSyncFinished.cs
- It was set in `WorldStateModule` in tests, so it work it tests.
- But it was missed in step initializations.
=> Fix verify trie starter not set

src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs
=> Remove array allocation when waiting for visiting tree node children

.github/workflows/sync-supported-chains.yml
Further fix as issue can be only spotted when triggered on master branch.
Adjusted branch selection so when it gets triggered from action completion event it will pick release branch and further a proper docker image for tests.
=> Fix branch selection for Sync Supported Chains action

.github/workflows/sync-supported-chains.yml
Adjust condition for Release branch verification in SyncSupportedChains action
=> Adjust condition for Release branch verification in SyncSupportedChains action

src/Nethermind/Directory.Build.props
Bump version post release branch cut
=> Bump version to 1.32.0-unstable

src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1AddPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2AddPrecompile.cs
- Allocate new memory when adding to zero in G1Add and G2Add
=> BLS precompile allocate memory for add

src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1AddPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2AddPrecompile.cs
- Allocate new memory when adding to zero in G1Add and G2Add
- Delete empty file
=> BLS fix add to zero

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
- Traces for invalid block will output memory now
=> Enable memory in Geth bad blocks dumps

src/Nethermind/Nethermind.Core/Eip2935Constants.cs, src/Nethermind/Nethermind.Core/Eip7002Constants.cs, src/Nethermind/Nethermind.Core/Eip7251Constants.cs
Updated devnet-6 addresses:
https://github.com/ethereum/EIPs/pull/9289
https://github.com/ethereum/EIPs/pull/9288
https://github.com/ethereum/EIPs/pull/9287
- [] No
- [] Yes
=> Update Pectra Addresses

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
=> Update sepolia chain size

scripts/syncSettings.py, src/Nethermind/Nethermind.Runner/configs/base-mainnet.json, src/Nethermind/Nethermind.Runner/configs/base-sepolia.json, src/Nethermind/Nethermind.Runner/configs/chiado.json, src/Nethermind/Nethermind.Runner/configs/energyweb.json, src/Nethermind/Nethermind.Runner/configs/exosama.json, src/Nethermind/Nethermind.Runner/configs/gnosis.json, src/Nethermind/Nethermind.Runner/configs/joc-mainnet.json, src/Nethermind/Nethermind.Runner/configs/joc-testnet.json, src/Nethermind/Nethermind.Runner/configs/linea-mainnet.json, src/Nethermind/Nethermind.Runner/configs/linea-sepolia.json, src/Nethermind/Nethermind.Runner/configs/mainnet.json, src/Nethermind/Nethermind.Runner/configs/op-mainnet.json, src/Nethermind/Nethermind.Runner/configs/op-sepolia.json, src/Nethermind/Nethermind.Runner/configs/sepolia.json, src/Nethermind/Nethermind.Runner/configs/volta.json
TD was removed probably from RPC endpoints and defaults to 0 which is wrong.
Made change so PoS chains will not get affected in future.
=> Fix PivotTotalDifficulty in update configs action

src/Nethermind/Nethermind.Blockchain/Blocks/BlockhashStore.cs
EIP-2935 Contract deployment fix
it fixes hive tests: Test id: tests/prague/eip2935_historical_block_hashes_from_state/test_contract_deployment.py::test_system_contract_deployment[fork_CancunToPragueAtTime15k-blockchain_test_engine-deploy_after_fork-nonzero_balance]
Covered in hive tests. Edge case which is not possible on production network.
=> EIP-2935 Contract deployment fix

README.md
=> Added Additional Terms section in Readme.md

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs
- Make unit test run more reliably. 
- Probably.
=> Make test more reliable

README.md
Added World Chain to README and revised
=> Add World Chain to README

src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugRpcModule.cs
- DebugRpcModule `IsShared` configuration was set to true causing concurrent processing env access.
- Tested to no longer throws with the provided script.
=> Fix debug module wrong configuration

src/Nethermind/Nethermind.Network.Stats/Model/Node.cs, src/Nethermind/Nethermind.Network.Stats/Model/NodeClientType.cs, src/Nethermind/Nethermind.Runner/NLog.config
- Add the Nimbus-eth1 EL client to client types
- Add EthereumJS to client types 
Shows less Unknown in peers
=> Add Nimbus-eth1 & EthereumJS to client types

.github/workflows/codeql.yml
- Added [github actions scanning](https://github.blog/security/application-security/how-to-secure-your-github-actions-workflows-with-codeql/) to CodeQL workflow
=> Add github actions scanning to CodeQL workflow

.github/workflows/sync-supported-chains.yml
Adjust few things which were failing recently on sync tests
=> Various fixes to sync tests

src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
- Early return if file is not found rather than trying to read it
=> Fix trusted nodes

src/Nethermind/Nethermind.EthStats/Senders/MessageSender.cs
- Ethstats is expecting numbers but we are using the hex serializer
=> Fix eth stats

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
- Optimize BlockchainProcessor Channel use
- Single reader (lighter synchronisation)
- Continue on same thread (don't requeue to threadpool, carry priority)
=> Blockchainprocessor channel use

src/Nethermind/Nethermind.Core/SlotTime.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterApiSimulator.cs, src/Nethermind/Nethermind.Shutter/ShutterApi.cs, src/Nethermind/Nethermind.Shutter/ShutterBlockHandler.cs, src/Nethermind/Nethermind.Shutter/ShutterBlockImprovementContext.cs, src/Nethermind/Nethermind.Shutter/ShutterTxLoader.cs, src/Nethermind/Nethermind.Shutter/ShutterTxSource.cs
- Renamed `ShutterTime` to `SlotTime` and moved to `Nethermind.Core`. Since this class is not specific to Shutter functionality this could better facilitate code reuse
=> Refactor ShutterTime to SlotTime

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
Resolves #8234
- Accept local tx even when syncing
=> Accept local tx even when syncing

src/Nethermind/Nethermind.Core/SlotTime.cs
- Change to class to prevent copying struct. Couldn't pass with `in` to constructors
=> Optimise: make SlotTime a class

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
- `_queueCount` is decremented after processing, and `blockQueueCount` at start of processing so end up with an off by one error in the metric (as correctly predicted by @LukaszRozmej in https://github.com/NethermindEth/nethermind/pull/8218#discussion_r1959228198)
=> Fix RecoveryQueueSize Metric (off by 1)

src/Nethermind/Chains/holesky.json, src/Nethermind/Chains/sepolia.json, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs
=> Fix deposit contract address

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
- Improve messages when blocks aren't in chain
=> Improve BlockchainProcessor exception messages

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.Paris.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs
- Better error; less wall of text log data
=> Handle orphaned blocks better

src/Nethermind/Chains/chiado.json, src/Nethermind/Chains/gnosis.json, src/Nethermind/Nethermind.Network.Test/ForkInfoTests.cs, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs, src/Nethermind/Nethermind.Specs/ChiadoSpecProvider.cs, src/Nethermind/Nethermind.Specs/GnosisForks/18_PragueGnosis.cs
=> Chiado Pectra

README.md
- Added the GitHub Discussions badge
- Revised some minor things
=> Add GitHub Discussions badge

src/Nethermind/Nethermind.Shutter.Test/ShutterTxFilterTests.cs, src/Nethermind/Nethermind.Shutter/ShutterTxFilter.cs, src/Nethermind/Nethermind.Shutter/ShutterTxLoader.cs
- Adds a check that gas limit = encrypted gas limit. https://github.com/gnosischain/specs/blob/master/shutter/low-level.md#validator
=> Shutter: add gas limit check

src/Nethermind/Nethermind.Serialization.Json/EthereumJsonSerializer.cs
- Normalize line endings in formatted Json to `\n` as a bit annoying
=> Fix Json tracer tests on Windows

src/Nethermind/Nethermind.Consensus.Test/ExecutionRequestProcessorTests.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Core/ExecutionRequest/ExecutionRequestExtensions.cs, src/Nethermind/Nethermind.Core/Resettables/RecyclableStream.cs
- Fixes bad optimization with even better one
hive
=> Fix request hash calculations

src/Nethermind/Nethermind.Consensus/ExecutionRequests/ExecutionRequestProcessor.cs
=> Deposit log match

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Add status codes when rejecting and output error on lack of ContentType
=> Add status codes when rejecting and output error on lack of ContentType

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.Blobs.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
=> Fix should_bring_back_reorganized_blob_txs test

src/Nethermind/Nethermind.Evm/Precompiles/Bls/BlsExtensions.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1AddPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MSMPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2AddPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MSMPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapFp2ToG2Precompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/MapFpToG1Precompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/PairingCheckPrecompile.cs
- Minor refactoring and adding comments
- No functionality changes
=> BLS precompile: refactor, add comments

src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs
Fixes #8286
- Don't dump by default, only on Trace
=> Decrease the tree dump Warn->Trace on Load genesis issue

src/Nethermind/Nethermind.Shutter/ShutterPlugin.cs
- Remove unused code in Shutter Plugin
=> Refactor: Remove unused code in Shutter Plugin

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Evm/Nethermind.Evm.csproj, src/Nethermind/Nethermind.Evm/Precompiles/Secp256r1Precompile.cs
Reverts #8284 until crash is fixed.
=> Revert secp256r1 optimization

src/Nethermind/Nethermind.JsonRpc.Test/Modules/FeeHistoryOracleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/FeeHistory/FeeHistoryOracle.cs
- Add limit to query. Geth has one: https://github.com/ethereum/go-ethereum/blob/4cdd7c86314e5f5a98fa68e928deaa99c026f40d/eth/gasprice/feehistory.go#L247-L249
=> Add percentiles 100 limit

src/Nethermind/Nethermind.TxPool/Metrics.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
7702 metrcis wasn't set correctly.
=> Fix 7702 metrics

src/Nethermind/Nethermind.Core.Test/TxTypeExtensionsTests.cs, src/Nethermind/Nethermind.Core/TxTypeExtensions.cs, src/Nethermind/Nethermind.Optimism/Rpc/DepositTransactionForRpc.cs
Made the class explicitly handle TxTypes. I think usage of >= might create unexpected bugs in the future.
Added a test that fails if a new type is introduced, ensuring developers update the class accordingly.
=> TxTypeExtensions refactoring

src/Nethermind/Nethermind.Core.Test/ProductInfoTest.cs, src/Nethermind/Nethermind.Core/ProductInfo.cs, src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Web3/Web3RpcModule.cs, src/Nethermind/Nethermind.Network.Contract/Config/INetworkConfig.cs, src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/Config/NetworkConfig.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs, src/Nethermind/Nethermind.Network/ProtocolsManager.cs
Resolves #4566
-  Add --network.PublicClientIdFormat
- Update sending HelloMessage with anonymized client id if enabled
- Update web3_clientVersion rpc method to return anonymized client id if enabled
Are there other places where the public client id should be used ? (Shutter ?)
=> Add client id privacy option

src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingScope.cs, src/Nethermind/Nethermind.Consensus/Processing/ReadOnlyTxProcessingScope.cs, src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.Consensus/Tracing/Tracer.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/IOverridableTxProcessingScope.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/IReadOnlyTxProcessingScope.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityStyleTracerTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofModuleFactory.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceModuleFactory.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
=> fix Trace leak

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Just makes it clearer that the failure condition is only possible for contract creation.
=> More explicit jump name

src/Nethermind/Nethermind.Sockets/Extensions.cs
- When websocket closed on other side, responding json rpc message throws due to invalid state.
- The log causes sync github action to fail.
=> Change loglevel on invalid websocket state

src/Nethermind/Nethermind.Consensus/Producers/BlockProducerEnvFactory.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- Output Block Gaslimit on startup; since is an interesting setting these day; as per user request
=> Output Blockgas limit at startup

scripts/workflow_config/sync_testnets_matrix.json
Base mainnet grows significantly so we need more space for it.
=> Give bigger machine for base-mainnet as seems not to fit anymore

src/Nethermind/Nethermind.Consensus.Test/ExecutionRequestProcessorTests.cs, src/Nethermind/Nethermind.Consensus/ExecutionRequests/ExecutionRequestProcessor.cs
Resolves #8223
Skipping execution requests processor in genesis
TBD with other client teams
Tested by running genesis file
=> Skipping execution requests processor in genesis

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs, src/Nethermind/Nethermind.Mining.Test/HintBasedCacheTests.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/JsonRpcRunner.cs, src/Nethermind/Nethermind.Runner/configs/holesky.json, src/Nethermind/Nethermind.Runner/configs/holesky_archive.json, src/Nethermind/Nethermind.Taiko.Test/TxPoolContentListsTests.cs
=> Increase Holesky gas to 60M

src/Nethermind/Nethermind.Runner/configs/hoodi_archive.json
in https://github.com/NethermindEth/nethermind/pull/8377 we added archive config with incorrect flags. This PR removes these flags
=> Fix Hoodi archive config

src/Nethermind/Nethermind.Consensus.AuRa/Transactions/GeneratedTxSourceSealer.cs, src/Nethermind/Nethermind.Consensus.AuRa/Transactions/RandomContractTxSource.cs, src/Nethermind/Nethermind.Consensus.AuRa/Validators/ContractBasedValidator.Posdao.cs, src/Nethermind/Nethermind.Consensus.AuRa/Validators/MultiValidator.cs, src/Nethermind/Nethermind.Consensus.AuRa/Validators/ReportingContractBasedValidator.PersistentReports.cs, src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs, src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/CompositeTxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/EmptyTxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/FilteredTxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/ITxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/OneByOneTxSource.cs, src/Nethermind/Nethermind.Consensus/Transactions/SinglePendingTxSelector.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PostMergeBlockProducer.cs, src/Nethermind/Nethermind.Optimism/OptimismPayloadTxSource.cs, src/Nethermind/Nethermind.Optimism/OptimismTxPoolTxSource.cs, src/Nethermind/Nethermind.Shutter/ShutterTxSource.cs, src/Nethermind/Nethermind.TxPool/ITxPool.cs, src/Nethermind/Nethermind.TxPool/NullTxPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- Include blob count in block production logs
=> Include blob count in block production logs

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
Disabled the generation of `nethermind.staticwebassets.endpoints.json` that ends up in the release distribution:
=> Disable static web assets

src/Nethermind/Nethermind.Core/Cpu/RuntimeInformation.cs, src/Nethermind/Nethermind.Core/Cpu/SectionsHelper.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
- Fixes aliasing bug on parameter name and field name (Physical cores detection was broken)
=> Fix cpu detection on Windows

src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
- Return txs from pool in form with network wrapper in special case
=> Return txs from pool in form with network wrapper in special case

src/Nethermind/Nethermind.Consensus/AlwaysPoS.cs
- Fix AlwaysPoS did no set final total difficulty.
- Testing
=> AlwaysPoS did not set final total difficulty

src/Nethermind/Nethermind.Api/IApiWithBlockchain.cs, src/Nethermind/Nethermind.Api/IBasicApi.cs, src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.AuRa.Test/AuRaPluginTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/AuRaNethermindApi.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Consensus.Clique/CliquePlugin.cs, src/Nethermind/Nethermind.Core/Container/FallbackToFieldFromApi.cs, src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs, src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs, src/Nethermind/Nethermind.Optimism/OptimismNethermindApi.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/EthereumStepsManagerTests.cs, src/Nethermind/Nethermind.Runner.Test/EthereumRunnerTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/Modules/NethermindRunnerModule.cs, src/Nethermind/Nethermind.Taiko/TaikoNethermindApi.cs
- Fix failed hive test due to double `ISpecProvider` initialization.
- `ISpecProvider` and other dependencied for `INethermindApi` now passed in constructor.
- Created a unit tests to prevent same case.
- Hive now runs.
=> Fix hive test.

src/Nethermind/Nethermind.Blockchain.Test/BeaconBlockRootHandlerTests.cs, src/Nethermind/Nethermind.Blockchain/BeaconBlockRoot/BeaconBlockRootHandler.cs
More mild version of https://github.com/NethermindEth/nethermind/pull/7958
- Warm up both beacon contract slots rather than just one
=> Warm up both beacon root slots

src/Nethermind/Nethermind.Shutter/ShutterP2P.cs
Fixes error on shutdown
```
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
Object name: 'System.Threading.CancellationTokenSource'.
at Nethermind.Shutter.ShutterP2P.DisposeAsync() in /src/Nethermind/Nethermind.Shutter/ShutterP2P.cs:line 158
at Nethermind.Shutter.ShutterApi.DisposeAsync() in /src/Nethermind/Nethermind.Shutter/ShutterApi.cs:line 129
at Nethermind.Shutter.ShutterPlugin.DisposeAsync() in /src/Nethermind/Nethermind.Shutter/ShutterPlugin.cs:line 118
at Nethermind.Runner.Ethereum.EthereumRunner.<>c__DisplayClass10_0.<<StopAsync>b__9>d.MoveNext() in /src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs:line 48
--- End of stack trace from previous location ---
at Nethermind.Runner.Ethereum.EthereumRunner.StopAsync() in …
```
=> Shutter: fix shutdown dispose

scripts/private-networking/clique-validators.sh
Permanent download link for the goerli chain spec .
This is still a usefull script for testing JOC etc.
=> Just fixing the clique test script

src/Nethermind/Nethermind.Config/Enode.cs
Adds a check in `Enode`  for correct Enode format. This gives better error messages, than typically `IndexOutOfBoundsException` since the format assumed to contain certain characters.
=> Check enode format in constructor

src/Nethermind/Nethermind.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Runner/configs/spaceneth.json
Fixes #8449
Spaceneth had an incorrect configuration
I run spaceneth
=> Fix spaceneth

src/Nethermind/Nethermind.AuRa.Test/Contract/TxPriorityContractTests.cs, src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPruningDiskTest.cs, src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs, src/Nethermind/Nethermind.Consensus/Messages/BlockErrorMessages.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Producers/BlockProducerEnvFactory.cs, src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSourceFactory.cs, src/Nethermind/Nethermind.Consensus/Validators/HeaderValidator.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/BasicTestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchainUtil.cs, src/Nethermind/Nethermind.Core.Test/Modules/MergeModule.cs, src/Nethermind/Nethermind.Core/IKeyValueStore.cs, src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Rocks/RocksDbExtensions.cs, src/Nethermind/Nethermind.Db/CompressingDb.cs, src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs, src/Nethermind/Nethermind.Facade/Simulate/SimulateDictionaryBlockStore.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs, src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/BaseEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs, src/Nethermind/Nethermind.State/Proofs/PatriciaTrieT.cs, src/Nethermind/Nethermind.State/Proofs/ReceiptTrie.cs, src/Nethermind/Nethermind.State/Proofs/TxTrie.cs, src/Nethermind/Nethermind.State/Proofs/WithdrawalTrie.cs
Extracted some minor refactoring and optimisations from #8003 #8040, to make easier to review
- Allow arbitrary slot times in TestBlockchain
- Use spans in tries
- Fix error messages
- Refactor txpooltxsource to have a factory class, useful for FOCIL
- Use scoped spans in db
- Improve error messages
- General code quality improvements, delete unused code
=> Minor refactoring and optimisations

src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
- Differentiate between Persisted and Transient nodes in metrics
=> Differentiate Pruning metrics

src/Nethermind/Nethermind.Trie/Pruning/Metrics.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
- Feedback from https://github.com/NethermindEth/nethermind/pull/8456#discussion_r2024322187
=> Remove branch from Purning Metrics

src/Nethermind/Nethermind.Runner/configs/hoodi.json, src/Nethermind/Nethermind.Runner/configs/hoodi_archive.json
Should be merged _AFTER_ Pectra activation on Hoodi
=> [Hoodi] Increase gas limit to 60M

src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs
- Fix some of the patricia benchmark is broken as it is missing writes.
- Add another benchmark `LargeInsertAndCommit` for large insert and commit.
Looks like this.
```
| Method                          | Mean         | Error       | StdDev       | Median       | Gen0       | Gen1       | Gen2      | Allocated    |
|-------------------------------- |-------------:|------------:|-------------:|-------------:|-----------:|-----------:|----------:|-------------:|
| Scenarios                       |     161.7 us |     1.76 us |      1.65 us |     161.6 us |     7.3242 |          - |         - |    121.52 KB |
| InsertAndHash                   |   1,706.5 us |    33.79 us |     42.73 us |   1,702.7 us |   210.9375 |   130.8594 |         - |   3449.28 KB |
| InsertAndCommit                 | …
```
=> Fix benchmark missing any writes

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
- Is failing again; not really sure what this test is testing
=> Update chain sizes test

src/Nethermind/Nethermind.Config/BlocksConfig.cs, src/Nethermind/Nethermind.Init/Steps/MigrateConfigs.cs, src/Nethermind/Nethermind.Runner/Program.cs
- Version can be too big in custom builds
=> Don't include too much version in extradata

src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs
- Current commit benchmark also include `Get` and `Set` in its timing.
- This PR create additional benchmark that isolate just `Hash` and `Commit`.
- Looks like this:
Method | Mean | Error | StdDev | Median | Gen0 | Gen1 | Gen2 | Allocated
-- | -- | -- | -- | -- | -- | -- | -- | --
Scenarios | 160.5 us | 3.08 us | 2.88 us | 159.8 us | 7.3242 | - | - | 121.52 KB
InsertAndHash | 1,657.0 us | 33.01 us | 68.91 us | 1,674.4 us | 210.9375 | 130.8594 | - | 3449.28 KB
InsertAndCommit | 7,254.0 us | 139.05 us | 175.85 us | 7,245.2 us | 406.2500 | 250.0000 | 54.6875 | 5931.03 KB
InsertAndCommitRepeatedlyTimes | 394,764.8 us | 7,876.70 us | 20,472.61 us | 395,150.8 us | 12000.0000 | 11000.0000 | 1000.0000 | 184522.23 KB
LargeInsertAndCommit | 104,666.4 us | 2,073.19 us | 4,327.52 us | 103,402.2 us | …
=> Isolated commit and hash benchmark

src/Nethermind/Nethermind.Flashbots/Data/BuilderBlockValidationRequest.cs, src/Nethermind/Nethermind.Flashbots/Handlers/ValidateBuilderSubmissionHandler.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/BaseEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V4.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayloadV3.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/IExecutionPayloadParams.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs, src/Nethermind/Nethermind.Optimism/CL/P2P/P2PBlockValidator.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterIntegrationTests.cs, src/Nethermind/Nethermind.Taiko/TaikoExecutionPayload.cs
Resolves #8479
Resolves #8384
- Don't catch exceptions
- Pass errors explicitly
=> Don't catch all exceptions on ExecutionPayload.TryGetBlock

src/Nethermind/Nethermind.Config/BlocksConfig.cs, src/Nethermind/Nethermind.Config/IBlocksConfig.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
- We can improve blocks until asked for the payload, however no single block should consume the whole slot to run, as it then needs to be propagated, validated, attested to etc
=> Limit time any single block can be produced for

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
- Commit additionally between the applications of two different specs
=> Commit state according to the regular spec, before system tx spec usage

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs, src/Nethermind/Nethermind.Core.Test/Builders/TransactionBuilder.cs, src/Nethermind/Nethermind.Crypto/BlobProofsManagerV0.cs, src/Nethermind/Nethermind.Crypto/BlobProofsManagerV1.cs, src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs, src/Nethermind/Nethermind.Evm/Precompiles/PointEvaluationPrecompile.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V5.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/BlobsBundleV2.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.Blobs.cs, src/Nethermind/Nethermind.TxPool/Collections/BlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs, tools/SendBlobs/BlobSender.cs
=> Ckzg.Ckzg -> Ckzg.

src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
- Don't resolve to full blob in candidate phase but delay until blob is being added to block
=> Delay resolving to full blob when picking

src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs, src/Nethermind/Nethermind.Init/PruningTrieStateFactory.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs, src/Nethermind/Nethermind.Serialization.Json/StreamPipeWriter.cs, src/Nethermind/Nethermind.Trie.Test/TrieTests.cs, src/Nethermind/Nethermind.Trie/Pruning/Persist.cs
- Fix trie tests failing as previously `TrackPastKeys` was not enabled in test.
- Rename `IfBlockOlderThan` to `EveryNBlock`.
- Reproducable with `Repeat(10)`.
=> Fix trie tests

.editorconfig
- Fix dotnet rules applied to py file.
- Set rules level from suggestion to errors. Indeed it previously does not err in intellij.
=> Fix editorconfig not applied to C# file.

.dockerignore, src/Nethermind/Nethermind.Test.Runner/Dockerfile, src/Nethermind/Nethermind.Test.Runner/Nethermind.Test.Runner.csproj
Added a simple Docker image for `Nethermind.Test.Runner` as requested by the EF testing team
=> Add Nethermind.Test.Runner Docker image

src/Nethermind/Nethermind.Blockchain.Test/Filters/FilterManagerTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Filters/FilterStoreTests.cs, src/Nethermind/Nethermind.Core/Timers/TimerFactory.cs, src/Nethermind/Nethermind.Facade.Test/BlockchainBridgeTests.cs, src/Nethermind/Nethermind.Facade/BlockchainBridge.cs, src/Nethermind/Nethermind.Facade/Filters/BlockFilter.cs, src/Nethermind/Nethermind.Facade/Filters/FilterBase.cs, src/Nethermind/Nethermind.Facade/Filters/FilterManager.cs, src/Nethermind/Nethermind.Facade/Filters/FilterStore.cs, src/Nethermind/Nethermind.Facade/Filters/IFilterManager.cs, src/Nethermind/Nethermind.Facade/Filters/IFilterStore.cs, src/Nethermind/Nethermind.Facade/Filters/LogFilter.cs, src/Nethermind/Nethermind.Facade/Filters/NullFilterStore.cs, src/Nethermind/Nethermind.Facade/Filters/PendingTransactionFilter.cs, src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcLocalStats.cs
- Ensures filters are removed if not touched in 15 mins.
Check if filters expire
=> Fix filter timeouts, set to 15m

scripts/workflow_config/sync_testnets_matrix.json
Switch checkpoint sync for Holesky
=> Fix Holesky Sync

src/Nethermind/Directory.Packages.props
Updated RocksDB to v9.10.
⚠️ This is the latest version available to us, while the actual latest version of RocksDB is 10.
Tested for forward-compatibility. Needs later manual testing as usual.
=> Update RocksDB package

tools/Nethermind.Tools.Kute/MessageProvider/FileMessageProvider.cs
- Write time is random when copying a directory and then using the files
=> Kute: order by filename

src/Nethermind/Nethermind.Optimism/CL/Derivation/DepositTransactionBuilder.cs, src/Nethermind/Nethermind.Optimism/CL/Derivation/ISystemConfigDeriver.cs, src/Nethermind/Nethermind.Optimism/CL/P2P/PayloadByNumberProtocol.cs, src/Nethermind/Nethermind.Trie.Test/TreePathTests.cs
- Use span when slicing arrays rather than creating a new array
=> Use span when slicing arrays

tools/TxParser/Program.cs
- TxParser: Add signature validation, keep errors in 1 line
=> TxParser: Add signature validation, keep errors in 1 line

src/Nethermind/Nethermind.Test.Runner/Dockerfile
Fixed the Dockerfile of Nethermind.Test.Runner, broken in #8659 
=> Fix Nethermind.Test.Runner Dockerfile

.github/workflows/test-assertoor.yml
Fixed file names in the workflow.
=> Fix Assertoor workflow

src/Nethermind/Nethermind.Runner/Dockerfile, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
- Optimized debugging container and removed release-related code from Dockerfile as redundant
- Regrouped project settings
=> Optimize debugging container

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs
=> Update known_chain_sizes test

src/Nethermind/Nethermind.Evm/ExecutionEnvironment.cs
- ExecutionEnvironment pass Uint256 as in
=> ExecutionEnvironment pass Uint256 as in

src/Nethermind/Nethermind.Evm.Test/Eip7918Tests.cs
- Add regression test for https://github.com/NethermindEth/nethermind/pull/8743
=> Add boundary tests for EIP-7918

src/Nethermind/Nethermind.Core/Extensions/Bytes.Vector.cs, src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Math1Param.cs, src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.cs
- Tries to avoid going to Uint256 and uses avx2
=> eip 7939 count leading zeros optimization

src/Nethermind/Nethermind.Evm/VirtualMachine.Warmup.cs
- Dispose any EvmStates created during opcode warmup
=> Dispose EvmState on warmup

src/Nethermind/Nethermind.Evm/VirtualMachine.Warmup.cs
=> Dispose EvmState on warmup (#8771)

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Base prewarming on logical cores rather than physical (max at 16); regression which switches prewarming off
=> Base prewarming on logical cores

src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
- Skip `UInt256` intermediary
- Move uncommon padding clear to non-inlined method
=> Lighter Memory.Save

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionSubstate.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Taiko/TaikoTransactionProcessor.cs
- Change `TransactionSubstate ` from `class` to `readonly ref struct`
=> TransactionSubstate to readonly ref struct

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
- Only log started `BlockchainProcessor` shutdown
=> Only notify about main BlockchainProcessor shutdown

src/Nethermind/Nethermind.Config/BlocksConfig.cs
Adjusted CL Block size - EIP 7934 https://eips.ethereum.org/EIPS/eip-7934
=> Adjusted CL Block size - EIP 7934

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.FeeHistory.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.Serialization.Json/DoubleConverter.cs
=> Json serializing doubles - decimal part optional for round numbers

Directory.Packages.props
Updated Nethermind.GmpBindings package to support Linux distros with glibc v2.35+.
=> Update Nethermind.GmpBindings package

src/Nethermind/Nethermind.Evm/CodeAnalysis/IL/EvmToIlEmitter.cs
=> fix blob base fee

src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs
- Update single node directly; rather than creating array and then updating via IEnumerable
=> Update single node directly rather than creating array

src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
- Ensure exception in blockdownloader is caught
=> Ensure exception in block downloader is caught

src/Nethermind/Nethermind.Core/Eip7918Constants.cs
Implements https://github.com/ethereum/EIPs/pull/9979/files
- Change constant to 2^13
=> EIP-7918 Blob Base cost constant change

src/Nethermind/Nethermind.Core/Eip7594Constants.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/BlobScheduleSettings.cs, src/Nethermind/Nethermind.Specs/ReleaseSpec.cs, src/Nethermind/Nethermind.Specs/TestSpecProvider.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.Blobs.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
- Use constant maxBlobsPerTx when PeerDAS is activated
=> EIP-7594: Constant maxBlobsPerTx 

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- fix naming changed by mistake in https://github.com/NethermindEth/nethermind/pull/5967
=> Fix naming of data cost in ExecutePrecompile

src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs
- The aura block processor factory here uses the last orphan tx processing scope, that is tx processing scope that is not closed.
=> Remove last orphan readonly tx processing scope.

src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaEofTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/OsakaStateTests.cs, src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs, src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs, src/Nethermind/Nethermind.Evm.Test/InvalidOpcodeTests.cs, src/Nethermind/Nethermind.Logging/TestLogManager.cs
- Atm are too heavy for github to display, so hard to find issues when error. Dial down the output
=> Make Ethereum.Blockchain test logs more readable

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Make gas price and premium gas calculation overridable in classed derived from transaction processor.
Make the following calculations as virtual methods of `TransactionProcessor` for ease of overriding:
- TryCalculatePremiumPerGas
- CalculateEffectiveGasPrice
=> Make gas price and premium gas calculation overridable

scripts/config/testnet-matrix.json
Increase the machine size for op-mainnet
=> Increase the machine size for op-mainnet

Directory.Packages.props
=> Rollback discv5 update

src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
- Improved peer logging, include counts in all output
=> Include peer count in both peer reports

src/Nethermind/Nethermind.Network.Discovery.Test/NodeDistanceCalculatorTests.cs, src/Nethermind/Nethermind.Network.Discovery/DiscoveryConfig.cs, src/Nethermind/Nethermind.Network.Discovery/IDiscoveryConfig.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/INodeDistanceCalculator.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeDistanceCalculator.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeTable.cs, src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs
- Vectorize Node distance calculation
=> Vectorize Node distance

src/Nethermind/Nethermind.Network.Test/PeerManagerTests.cs, src/Nethermind/Nethermind.Network/PeerManager.cs, src/Nethermind/Nethermind.Network/Rlpx/IRlpxHost.cs, src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs, src/Nethermind/Nethermind.Synchronization.Test/E2ESyncTests.cs
- Just return `true`/`false` rather than throwing exception catching it and returning `false`
=> Throw less exceptions during peer connection

src/Nethermind/Nethermind.Blockchain/IBlockTree.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs
Fixes #9065
- Support named blocks as arguments to `debug_getRawBlock`
Tested using the setup provided in the corresponding issue.
=> Use proper block params

src/Nethermind/Nethermind.Network.Discovery/Discv5/NethermindLoggerFactory.cs, src/Nethermind/Nethermind.Runner/Ethereum/JsonRpcRunner.cs, src/Nethermind/Nethermind.Runner/Program.cs, src/Nethermind/Nethermind.Runner/runtimeconfig.template.json
- Disables system-level diagnostics and activity propagation through runtime configuration
- Optimizes logging performance by adding level checks before expensive log message formatting
- Improves DotNetty integration with proper logger factory configuration
=> Optimize unused logging from Diagnostics, Activity and Metrics

src/Nethermind/Nethermind.Merge.Plugin/Data/IExecutionPayloadParams.cs
- Compare tx `blobVersionedHashes` and payload `blobVersionedHashes` without linq
=> Compare Flattened hashes without Linq

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Output processing logs for non-consecutive block commits
=> Report processing log for reorg'd blocks

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Evm/IVirtualMachine.cs, src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.CodeCopy.cs, src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Stack.cs, src/Nethermind/Nethermind.Evm/Metrics.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Facade/Simulate/SimulateVirtualMachine.cs
- Add opCode count executed per block to logs
=> Add opcode count per block in logs

src/Nethermind/Nethermind.History.Test/HistoryPrunerTests.cs, src/Nethermind/Nethermind.History/HistoryConfig.cs, src/Nethermind/Nethermind.History/IHistoryConfig.cs
- Disable history pruner by default
- Move config
Explain that this is experimental feature, so disabled by default
=> Disable history pruner by default

src/Nethermind/Nethermind.Core.Test/TestRawTrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/ITrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/ReadOnlyTrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Usage was replaced with overridable trie store.
- Waiting for sync...
=> Remove readonly trie store read with custom node storage.

src/Nethermind/Nethermind.Monitoring/NethermindKestrelMetricServer.cs
- Limit rate of metrics update
=> Add OutputCache to metrics endpoint

src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
- Correctly wrap PrepareRequest exception in task
=> Correctly Wrap PrepareRequest exeception

src/Nethermind/Nethermind.Core/Collections/CollectionExtensions.cs, src/Nethermind/Nethermind.Core/Extensions/MemberInfoExtensions.cs, src/Nethermind/Nethermind.Core/Threading/ZeroContentionCounter.cs, src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs, src/Nethermind/Nethermind.Monitoring/Metrics/MetricsController.cs, src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
- Only start metrics updating if prior has completed
- Fast reflection accessor
- Get Db metrics out of flow of regular metrics so they don't block metric updates
=> Only update metrics if not already updating metrics

src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
- Don't report cancellation as error
=> Handle peers shutdown more gracefully

src/Nethermind/Nethermind.Hive/HiveRunner.cs
=> Use genesis as the parent for the first block

src/Nethermind/Nethermind.AuRa.Test/AuRaPluginTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaPlugin.cs, src/Nethermind/Nethermind.Core/Specs/AuRaSpecProvider.cs, src/Nethermind/Nethermind.Core/Specs/AuraSpecProvider.cs, src/Nethermind/Nethermind.Core/Specs/ISpecProvider.cs, src/Nethermind/Nethermind.Core/Specs/SpecProviderDecorator.cs
- Move hardcoded AuRa release spec decorator to plugin.
- Gnosis running normally.
=> Remove hardcoded AuRa release spec decorator to plugin module

src/Nethermind/Nethermind.Network/ForkInfo.cs
- Ensure ForkInfo is initialized
=> Ensure ForkInfo is initialized

src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
=> feat(block-validator): add debug logging message for MaxRlpBlockSize

src/Nethermind/Nethermind.Xdc.Test/XdcHeaderDecoderTests.cs, src/Nethermind/Nethermind.Xdc/XdcHeaderDecoder.cs
Correction for sealing encoding and a couple of test taking RLP from XDC and tests compatibility
=> Corrected sealing encoding XDC

src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
=> Change implementation

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Data/AccountInfoForRpc.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
- implement `eth_getAccountInfo` referenced here: https://github.com/paradigmxyz/reth/issues/16027 for DevUX and foundry support
Added supported for `eth_getAccountInfo` RPC method for foundry support
=> implement eth_getAccountInfo

src/Nethermind/Nethermind.Api/IBasicApi.cs, src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.Core.Test/FunctionalTimerFactory.cs, src/Nethermind/Nethermind.Core.Test/Modules/PseudoNethermindModule.cs, src/Nethermind/Nethermind.Init/Modules/NethermindModule.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs, src/Nethermind/Nethermind.Runner.Test/EthereumRunnerTests.cs
- Make some test more consistent
- Wait for CI...
=> fix inconsistent merge plugin test

.github/workflows/sync-supported-chains.yml
- Enable passing args to Nethermind when using sync chains pipeline
=> Enable passing args to Nethermind when using sync chains pipeline

src/Nethermind/Nethermind.Xdc/DifficultyCalculator.cs, src/Nethermind/Nethermind.Xdc/Errors/CertificateValidationException.cs, src/Nethermind/Nethermind.Xdc/IEpochSwitchManager.cs, src/Nethermind/Nethermind.Xdc/IForensicsProcessor.cs, src/Nethermind/Nethermind.Xdc/IMasternodesManager.cs, src/Nethermind/Nethermind.Xdc/IQuorumCertificateManager.cs, src/Nethermind/Nethermind.Xdc/ISnapshotManager.cs, src/Nethermind/Nethermind.Xdc/ISyncInfoManager.cs, src/Nethermind/Nethermind.Xdc/ITimeoutCertificateManager.cs, src/Nethermind/Nethermind.Xdc/IVotesManager.cs, src/Nethermind/Nethermind.Xdc/IXdcConfigs.cs, src/Nethermind/Nethermind.Xdc/IXdcSealer.cs, src/Nethermind/Nethermind.Xdc/XdcConstants.cs
- adds a set of interfaces we may need 
=> XDC : Interfaces and Dependencies (To Discuss)

.github/workflows/nethermind-tests.yml
Added XDC tests to tests workflow
=> Add XDC tests

Directory.Packages.props
Updated the MCL library to the version that addresses the memory leak on Windows. The stable version will be released once the fix lands in the stable version of MCL.
=> Fix MCL memory leak

src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs, src/Nethermind/Nethermind.Consensus/Messages/TxErrorMessages.cs, src/Nethermind/Nethermind.Consensus/Validators/TxValidator.cs
Replaces #9345 Resolves #9344
- Nonce cap validation
=> Implement EIP 2681 validation

src/Nethermind/Nethermind.Facade/Proxy/Models/Simulate/SimulateBlockResult.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugRpcModuleTests.TraceCallMany.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/TransactionBundle.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs, tools/Evm/T8n/JsonTypes/InputData.cs, tools/Evm/T8n/JsonTypes/T8nExecutionResult.cs, tools/SchemaGenerator/update.ps1
Fixes #6662 Replaces PR #9179
* Implement batch transaction tracing with smart path bifurcation
* Add TransactionBundle data structure with block/state override support
* Handle transaction failures gracefully with proper trace generation
* Support advanced simulation scenarios via existing infrastructure
* Add comprehensive test coverage for new functionality
=> Add debug_traceCallMany RPC method with Geth compatibility

src/Nethermind/Nethermind.Blockchain/LogTraceDumper.cs, src/Nethermind/Nethermind.Core/Either.cs
Fixes a bug revealed by devnet-3. 
Either it's time for some monads?
- Fix input type
=> Safer types for a one of case
