NethermindEth/nethermind

src/Nethermind/Nethermind.State/StateProvider.cs
- Reads of existing accounts are cached; however reads of non-exiting accounts always check the db. Cache these also (we already pretty much have a cache for them, though is used for tracing, so just need to use it for regular things)
Cache empty non-existent account reads rather than always rechecking the db for them
=> Use the empty account cache as cache

src/Nethermind/Nethermind.AccountAbstraction/Executor/AABlockProducerTransactionsExecutor.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockProductionTransactionsExecutor.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs, src/Nethermind/Nethermind.Consensus/Processing/TransactionProcessorAdapterExtensions.cs, src/Nethermind/Nethermind.Evm/ExecutionEnvironment.cs, src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/BuildUpTransactionProcessorAdapter.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/CallAndRestoreTransactionProcessorAdapter.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ChangeableTransactionProcessorAdapter.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ExecuteTransactionProcessorAdapter.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ITransactionProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ITransactionProcessorAdapter.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ReadOnlyTransactionProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TraceTransactionProcessorAdapter.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/TxExecutionContext.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Mev/MevBlockProductionTransactionsExecutor.cs, src/Nethermind/Nethermind.Optimism/OptimismTransactionProcessor.cs
- Pass `readonly struct` `BlockExecutionContext` via `in` as is chonky and often just pass-through; co no need for struct copy at each level.
=> Pass `readonly struct` `BlockExecutionContext` via `in`

src/Nethermind/Nethermind.Blockchain/Find/BlockParameter.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.EthCall.cs
- Should parse `blockHash` when `requireCanonical` is not present
=> Parse BlockParameter correctly for eth_call

src/Nethermind/Nethermind.Core.Test/RlpTests.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
There was a mistake in Rlp.LengthOf(byte value) && RlpStream.DecodeByte().
For values > 128, encoded length is 2.
- Rlp.LengthOf(byte value)
- RlpStream.DecodeByte()
=> fix byte length calculation

.github/workflows/sync-testnets.yml
Add more time for sepolia to finish since it has a bit less peers discovered for sync nowadays.
=> Increase timeout on sync tests since Sepolia peering is weak

src/Nethermind/Nethermind.Trie/NibbleExtensions.cs
- Vectorize `BytesToNibbleBytes` to work in 16 byte chunks rather than 1 byte at a time
Originally did it for path storage, then realised it was in master https://github.com/NethermindEth/nethermind/pull/6490
=> Vectorize BytesToNibbleBytes

src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
- Only allocate the closure once
=> Reduce allocations of Gossip filter closures

src/Nethermind/Ethereum.Test.Base/EthereumTestResult.cs, src/Nethermind/Ethereum.Test.Base/GeneralStateTestInfoJson.cs, src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs, src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs, src/Nethermind/Nethermind.Blockchain.Test.Runner/Program.cs, src/Nethermind/Nethermind.Test.Runner/StateTestRunner.cs, src/Nethermind/Nethermind.Test.Runner/StateTestTxTraceResult.cs
- Previously were more flexible in handling of `_info` restore that flexibility
- Include the `timeInMs` in the Json output for successful tests not just failed trace time
- Pre-warm Jit to determine that time
e.g.
```
❯ .\nethtest.exe -n -i E:\slow.json
[
{
"name": "jd_attack_london_10MGas_JUMPDEST_250M_d0g0v0_",
"pass": false,
"fork": "Shanghai",
"timeInMs": 140.2537,
"stateRoot": "0xb477153913f9f4214202f0eda1fa4afe153f937dee736e6284bd188e71a63ae6"
}
]
```
=> Fix nethtest handing of `_info`

src/Nethermind/Nethermind.Monitoring/Config/IMetricsConfig.cs, src/Nethermind/Nethermind.Monitoring/Config/MetricsConfig.cs, src/Nethermind/Nethermind.Monitoring/MonitoringService.cs
- Add `--Metrics.ExposeHost` option and pass that to NethermindKestrelMetricServer so a hostname other than localhost can be exposed. Defaults to `127.0.0.1` since this is the current default behavior without an option.
_I have only compiled this on my dev laptop and not run this on my production node yet. Therefore I am looking for early feedback to my commits until that can be completed. It would be good to verify the passed address matches what is printed in the logs (instead of 127.0.0.1, as it currently shows). as well as, ensuring that the hostname:port can be accessed, i.e. from dev laptop curl_
_Built Nethermind.Runner, correcting all errors and verified the new CLI option was available (when spelled correctly)_
_Metrics documentation is already marked for needing update_
_Add …
=> Feature: Exposing Prometheus metrics to user-defined interface

src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/StorageRangesMessageSerializer.cs, src/Nethermind/Nethermind.State/Snap/PathWithStorageSlot.cs
- Capture closures once per class rather than once per invocation
- Change `PathWithStorageSlot` from class to `readonly struct`
=> Reduce allocations in StorageRangesMessageSerializer

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Skip adding Mvc controllers on start-up as they are not used and searching for them adds to startup time
=> Skip adding Mvc controllers on start-up

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Init/InitializeStateDb.cs, src/Nethermind/Nethermind.Init/MemoryHintMan.cs, src/Nethermind/Nethermind.Runner.Test/MemoryHintManTests.cs, src/Nethermind/Nethermind.State.Test/CachingStoreTests.cs, src/Nethermind/Nethermind.State.Test/Witnesses/WitnessingStoreTests.cs, src/Nethermind/Nethermind.Trie/CachingStore.cs, src/Nethermind/Nethermind.Trie/MemoryAllowance.cs
This reverts commit 9d1b4f66ee9abe131e1f32555f4bfd7235291c69.
- Full pruning with in memory pruning does not work reliably without caching store.
- Also means we are kinda running on luck here.
- Rerun an old database, turn on pruning, restart and run verify trie.
- Still trying to find solutions, but still can't find a reliable one.
=> Revert "Replace caching store with row cache (#6405)"

src/Nethermind/Nethermind.Trie/PatriciaTree.cs
- Delay allocation of the two `ConcurrentQueue<T>` and one `Stack<StackedNode>` until a change is written to the `PatriciaTree`.
- This means smart contracts that either only proxy, forward or just read values (no `sstore`s) to return don't need to perform these allocations.
```
Type layout for 'ConcurrentQueue`1'
Size: 24 bytes. Paddings: 0 bytes (%0 of empty space)
|=================================================|
| Object Header (8 bytes)                         |
|-------------------------------------------------|
| Method Table Ptr (8 bytes)                      |
|=================================================|
|   0-7: Object _crossSegmentLock (8 bytes)       |
|-------------------------------------------------|
|  8-15: ConcurrentQueueSegment`1 _tail (8 bytes) | …
```
=> Reduce readonly CALL allocations by 64 bytes

src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs
- Use `ThreadStatic`s for the pooled buffers rather than a `ConcurrentQueue` as their is lots of contention in very high multi thtreaded Keccaking
Before Left, After Right
During sync, before it spends more time contended on getting the buffer than it does hashing; after all the time is on the Keccak
=> Remove contention from KeccakHash during Sync

src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/BodiesSyncFeedTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/ReceiptsSyncFeedTests.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/BarrierSyncFeed.cs
- put a more lenient number for the amount of blocks the node can continue to sync below the barrier and still be within range of the old default.
Will test on 1.19.3
=> [Fix]{Config] old default barrier being ignoreed in clients upgraded to new versions but were initailly synced with older versions (1.19.3 and below))

src/Nethermind/Nethermind.AccountAbstraction.Test/UserOperationSubscribeTests.cs, src/Nethermind/Nethermind.Facade.Test/Eth/EthSyncingInfoTests.cs, src/Nethermind/Nethermind.Facade/Eth/EthSyncingInfo.cs, src/Nethermind/Nethermind.HealthChecks.Test/NodeHealthServiceTests.cs, src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/SubscribeModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcBlockchain.cs, src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
Fixes #6512
- changed to follow same logic utilizing SyncProgressResolver 
Fixed a bug with `eth_syncing` returning true when node is fully synced to old bodies and receipt barrier.
=> [Fix]  EthSyncing showing Syncing even when node is fully synced up to old default barrier

src/Nethermind/Nethermind.Core.Test/Events/WaitForEventTests.cs, src/Nethermind/Nethermind.Core/Events/WaitForEvent.cs, src/Nethermind/Nethermind.Init/Steps/DatabaseMigrations.cs, src/Nethermind/Nethermind.Init/Steps/Migrations/BloomMigration.cs, src/Nethermind/Nethermind.Init/Steps/Migrations/IDatabaseMigration.cs, src/Nethermind/Nethermind.Init/Steps/Migrations/ReceiptFixMigration.cs, src/Nethermind/Nethermind.Init/Steps/Migrations/ReceiptMigration.cs, src/Nethermind/Nethermind.Init/Steps/Migrations/TotalDifficultyFixMigration.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/ReceiptMigrationTests.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/TotalDifficultyFixMigrationTest.cs
- "Why!?... just... even if..." ***takes a deep breath*** 
- Refactor database migration to run async and takes the cancellation token from step's run.
- Use `Task Run(CancellationToken)` instead. The cancellation token is same as application wide.
- No need to manually make one and pass oneself to dispose stack.
- IReceipt migration can run and continue
=> Use async run for migration

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Converts trimmed Span to Array to assingn back to Span. The intermediate Array conversion is unneeded
=> Remove unnecessary .ToArray() from SStore

src/Nethermind/Nethermind.Db/Metrics.cs, src/Nethermind/Nethermind.Evm/MemoryAllowance.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Move statics to non-generic VM so not instantiated per variant
- Initialize Precompiles as static FrozenDictionary
- Make some more things readonly static
=> Initialize Precompiles as static FrozenDictionary

src/Nethermind/Nethermind.Blockchain.Test/Validators/TxValidatorTests.cs, src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs, src/Nethermind/Nethermind.Core/Eip2930/AccessList.cs, src/Nethermind/Nethermind.Evm/EvmState.cs, src/Nethermind/Nethermind.Evm/IntrinsicGasCalculator.cs, src/Nethermind/Nethermind.Evm/Tracing/Proofs/ProofTxTracer.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
- Maintain two strongly typed `List<T>` to avoid boxing the `UInt256` keys to `object` (some txs have 6k+)
- Clean up some `UInt256 == 0` to `.IsZero`
- Also long comparision to 0 rather than convert to UInt256 and then compare zero
- Use Span when calcuating DataCost
=> Avoid boxing in AccessLists

src/Nethermind/Nethermind.Consensus/Producers/PayloadAttributes.cs, src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs, src/Nethermind/Nethermind.Optimism/OptimismPayloadAttributes.cs, src/Nethermind/Nethermind.State/Proofs/PatriciaTrieT.cs, src/Nethermind/Nethermind.State/Proofs/ProofVerifier.cs, src/Nethermind/Nethermind.State/Proofs/ReceiptTrie.cs, src/Nethermind/Nethermind.State/Proofs/TxTrie.cs, src/Nethermind/Nethermind.State/Proofs/WithdrawalTrie.cs
- Change parameters for `Withdrawl`, `TxReceipt` and `Transaction` tries to be arrays rather than IEnumerator. They start as arrays to pass them through as arrays meaning no allocation for the enumerator and faster enumeration.
=> Optimize Tries to Array rather than IEnumerator

src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Use `RlpStream` as the backing for `FullRlp` removing one field, but also having atomic writes vs the struct
- Take all fields to method locals when operating on them, so any check (like null check) remains valid for the method.
- Always **(_and this is the important one_)** take a clone of the `RlpStream` when operating on it; as otherwise multiple readers with adjust each others positions in the stream.
- Use an atomic barrier to prevent concurrent writers; rather than just checking params
- Move some things (like the barrier) that only apply to writes into the `Set` rather than having in shared `Run`
- Atomically set `IsDirty` and use same flag for `IsDirty` and `IsSealed`
- Atomically set the `_data` backing array
Common symptoms of this are Rlp error with invalid encoding …
=> Increase Trie robustness for multi-readers

src/Nethermind/Nethermind.Serialization.Rlp/ByteArrayExtensions.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpFactory.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs, src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Performance follow up to https://github.com/NethermindEth/nethermind/pull/6580 to change the RlpStream copies to structs
=> Trie RlpStreams as structs

src/Nethermind/Nethermind.Blockchain/Metrics.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Adds colors for MGas for block (from cold blue if far below `block.GasLimit`; green on target through to hot red if near it)
- Add colors for MGas/s also based on `block.GasLimit`
- Changes to fields to `long`s and `doubles` as they don't need to be decimals which are much more expensive to process
Can't do anything with tx/s as that's very much "it depends"; and can't do much with Blk/s as that depends on the chain's block times.
=> Add colors to logging for MGas

src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs
Resolves #6465 
- If connect timesout; cancel/close the connecting socket
=> Disconnect timed out connects

src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityAction.cs, src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityTraceActionConverter.cs, src/Nethermind/Nethermind.JsonRpc.Test/Data/SerializationTestBase.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityTraceActionSerializationTests.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore.Test/DbPersistingBlockTracerTests.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/ITraceStoreConfig.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/ParityLikeTraceSerializer.cs, src/Nethermind/Nethermind.JsonRpc.TraceStore/TraceStoreConfig.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ParityTxTraceFromReplay.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ParityTxTraceFromStore.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs, src/Nethermind/Nethermind.Serialization.Json/EthereumJsonSerializer.cs, src/Nethermind/Nethermind.Serialization.Json/ForcedNumberConversion.cs
Fixes #6600
- Fix serialization in TraceStore plugin
- increases max depth to have bigger headroom for recursive actions
Needs TraceStore plugin
=> Fix TraceStore plugin

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcLocalStats.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcLocalStats.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ForkchoiceStateV1.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs, src/Nethermind/Nethermind.Runner/ConsoleHelpers.cs, src/Nethermind/Nethermind.Runner/NLog.config, src/Nethermind/Nethermind.Runner/Program.cs
- [Enable Ansi colors as per](https://superuser.com/a/1300251)
- Make peers report fit
- Tidy ups
=> Enable Ansi color sequences for Cmd

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncedTxGossipPolicyTests.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncedTxGossipPolicy.cs, src/Nethermind/Nethermind.TxPool/ITxGossipPolicy.cs
- Use for loop rather than Linq to avoid the allocation from capturing `Transaction` in a closure
=> Don't capture tx in ShouldGossipTransaction closure

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
Fix #6629 
- Increase `level0_stopwrites_trigger` so that db does not stop writes immediately after old receipts until it finish compacting. 
- Seems to work.
=> Fix block processing hang after OldReceipts

.github/workflows/sync-testnets.yml
=> Quick upper case fix for synctestnet

src/Nethermind/Nethermind.Evm.Test/EvmPooledMemoryTests.cs, src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Correctly output memory traces; rather than dumping uninitalized memory
=> Clean unitialized memory when passing it to tracer

src/Nethermind/Nethermind.Evm/Tracing/TraceMemory.cs
Adds a `bool` parameter to `TraceMemory Slice()`, which is `true` by default.
If `true`, an exception is thrown if the `ReadOnlySpan<byte>` to be returned from the function exceeds `MemoryPadLimit`.
If `false`, no size constraint is imposed on the return value. This is useful for retrieving the *verbatim* memory contents.
=> Allow retrieving memory traces that are unconstrained in size

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Synchronization.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs, src/Nethermind/Nethermind.Synchronization/Peers/AllocationStrategies/BySpeedStrategy.cs, src/Nethermind/Nethermind.Synchronization/Peers/ISyncPeerPool.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
Address #6596 
- At least with lighthouse, after a long shutdown, it does not send new payload until it finishes catching up to head. It does send FCU however. 
- This means that Nethermind does not start catching up until lighthouse send new payload message.
- This changes that so that nethermind will attempt to get header from p2p if the block is not known allowing it to sart catching up.
```
======================== Nethermind initialization completed ========================
This node    : enode://290dabe192600a6a939ef463258325e58e577291542684eb96cc0cde4d4dc4470e90c9433693bd2727936bfbaa0aa2bf216478f92e0bcf90cd25c61893dabdd7@45.133.181.46:30303
RPC modules  : Admin
Node address : 0x6f1e3c3464737eec2a548476a755f6cad5023d4e (do not use as an account)
Mem est tx   :    82 MB
Mem est DB …
```
=> Perf/fetch blockheader from peer on FCU if block so that it start beacon header sync.

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/mainnet_archive.cfg
- Set default mainnet peers to 50 rather than 100; this matches docs and geth's defaults
=> Set mainnet peers to 50

src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs
Resolves #5660
- Lodestar makes request via non-auth for non engineapi request and sometimes goes a little above the 30M limit, so increase to 32MB to allow them to suceed.
=> Set MaxBatchResponseBodySize to 32MB (for Lodestar)

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
- Fix dbstats not working on column db as it seems that only the main option can have it.
- Attempting to fetch from the default column db will throw.
- This only happen with flatdb layout.
- Seems to work with flatdb layout.
=> Fix dbstats not working for column db and not working for column db without an explicit Default column.

src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
- if TxPool/BlobPool capacity is exceeded, remove 2 worst txs instead of 1 (when inserting new tx)
It will not be used in normal workflow - only if TxPool/BlobPool capacity will be exceeded, which is not expected, but rarely observed on devnet nodes
=> Self-recovery of TxPool max capacity

src/Nethermind/Nethermind.Evm/EvmState.cs
- The StackPool is stored in a `ThreadLocal<StackPool>` so doesn't need concurrent collections
=> StackPool's don't need to be concurrent

src/Nethermind/Nethermind.Merkleization/ShaMerkleTree.cs
Resolves #6684
- Use different HashAlgorithm instance per thread
=> Fix ShaMerkleTree for multithreaded access

src/Nethermind/Nethermind.Network/SessionMonitor.cs
- I get the message `100 % of nodes did not respond to a Ping message - 1/1` frequently which seems a bit alarmist. We already don't alert when its less that 33% of the batch contacted, so also have a lower absolute limit on this.
e.g. 100% of nodes, followed by 49 connected
=> Failures > 4 for ping message alerts

src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
Resolves #6557
- If txPool fails to remove txn due to an out of date worst value; update then remove again
=> Update txPool worst value if removal unsuccessful

src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs
- No functional change, just add more benchmarks for PatriciaTree.
- Here are my result:
| Method                      | Mean       | Error     | StdDev    | Median     | Gen0     | Gen1     | Gen2    | Allocated  |
|---------------------------- |-----------:|----------:|----------:|-----------:|---------:|---------:|--------:|-----------:|
| Scenarios                   |   111.0 us |   2.21 us |   3.81 us |   109.3 us |   8.7891 |   2.1973 |       - |  144.77 KB |
| InsertAndHash               | 3,062.2 us |  60.02 us | 115.64 us | 3,025.6 us | 218.7500 | 128.9063 |       - | 3593.14 KB |
| InsertAndCommit             | 5,734.0 us | 114.43 us | 315.16 us | 5,769.8 us | 437.5000 | 382.8125 | 93.7500 | 5879.76 KB |
| ReadWithFullTree            | 2,734.2 us |  34.77 us |  29.03 us | …
=> More patricia tree benchmarks

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
- Remove the Task.Dispose (the cancellation token handles shutting them down)
Saw following errors in CI
```
TearDown failed for test fixture Nethermind.Blockchain.Test.ReorgTests
TearDown : System.InvalidOperationException : A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
StackTrace: --TearDown
at System.Threading.Tasks.Task.Dispose(Boolean disposing)
at System.Threading.Tasks.Task.Dispose()
at Nethermind.Consensus.Processing.BlockchainProcessor.Dispose() in /_/src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs:line 752
at Nethermind.Blockchain.Test.ReorgTests.TearDown() in /_/src/Nethermind/Nethermind.Blockchain.Test/ReorgTests.cs:line 92
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, …
```
=> Don't dispose Tasks (unless its waithandle is used)

src/Nethermind/Nethermind.Core/Buffers/CappedArray.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs, src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs
- Use preallocated Span for bytes 0-127 and preallocated arrays for bytes 0-127 (and the conversion between them)
=> Improved single byte Rlp.DecodeByteArray

src/Nethermind/Nethermind.Benchmark/Store/PatriciaTreeBenchmarks.cs
- No functional change, just add benchmark for when the trie load nodes from in memory trie store.
- Here are current readings:
| Method                          | Mean       | Error     | StdDev    | Gen0     | Gen1     | Gen2    | Allocated  |
|-------------------------------- |-----------:|----------:|----------:|---------:|---------:|--------:|-----------:|
| Scenarios                       |   116.6 us |   2.05 us |   2.36 us |   8.7891 |   2.1973 |       - |  146.77 KB |
| InsertAndHash                   | 3,090.4 us |  58.86 us |  89.88 us | 218.7500 | 128.9063 |       - | 3593.14 KB |
| InsertAndCommit                 | 5,959.6 us | 118.68 us | 312.66 us | 437.5000 | 375.0000 | 93.7500 |  5859.5 KB |
| ReadWithFullTree                | 2,868.6 us |  41.60 us |  32.48 us | 320.3125 …
=> Add benchmark for reading from memory trie store

src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs, src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs
- Also apply #6711 to ValueDecoderContext
- Move ByteSpanToArray to single place since its now used 3 times (Is what it is 🤷‍♂️)
=> Apply improved DecodeByteArray to ValueDecoderContext

src/Nethermind/Nethermind.Monitoring/Config/IMetricsConfig.cs, src/Nethermind/Nethermind.Monitoring/Config/MetricsConfig.cs
Revert the default for ExposeHost for metrics
=> Change the default of ExposeHost to + due to backward compatibility

src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
* [Make Rlp.LengthOfLength branchless](https://github.com/NethermindEth/nethermind/commit/befbda17376d37d3e7df3c0e6c12785bf0c9935d)
* This is just calculating the amount of bytes required the represent the value, we can CLZ it. This makes the method inlineable for the JIT thanks to much tighter IL (and codegen).
* [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgDkBXfGKASzFwG4BYAKGIDMlAEzkAwuQDefcrMpDqScqwB2GcgBkYKgOYYAFgHkAZlt0GAFKvUA3bABsGMAJQy503nK/K15YKwxccgBecgFROHIAIQDDAAcWbAxWCBVcGi1sABNVHQAtFggxCAY1CwsGa2c7RxhyQnIqZx5Pb1liAHZyC39A8gBqcg7ncgB6cgAOFq8AXz4ZoA)
* [Make Rlp.LengthOf almost branchless](https://github.com/NethermindEth/nethermind/commit/ef66b02310e5a01893871330ad325f5e93dc78f1)
* We can use similar bit tricks here. Wasn't able to get rid …
=> Optimize RLP length calculation

src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
- Forward Rpl.LengthOf(int) to LengthOf(long)  from https://github.com/NethermindEth/nethermind/pull/6729#discussion_r1491325971 by @PaulusParssinen
- Use quick checks for UInt256 and forward to LengthOf(long); drop stackalloc, span, coversion to bigendien etc
=> Further optimize Rpl.LengthOf(...)

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- If calcuating Keccak as part of pruning cache, should save it to the node
=> Save Keccak when calculated

src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
Resolves #6663 though would need resync
Resolves #6670
- Perform the full Rlp hash if fast path not available
=> Calculate Tx Hash if fast path not available

src/Nethermind/Nethermind.Blockchain/FullPruning/PruningTriggerPersistenceStrategy.cs, src/Nethermind/Nethermind.Db/IPruningConfig.cs, src/Nethermind/Nethermind.Db/MemDb.cs, src/Nethermind/Nethermind.Db/PruningConfig.cs, src/Nethermind/Nethermind.Init/InitializeStateDb.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TestPruningStrategy.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie.Test/PruningScenariosTests.cs, src/Nethermind/Nethermind.Trie.Test/TinyTreePathTests.cs, src/Nethermind/Nethermind.Trie/INodeStorage.cs, src/Nethermind/Nethermind.Trie/NodeStorage.cs, src/Nethermind/Nethermind.Trie/Pruning/Archive.cs, src/Nethermind/Nethermind.Trie/Pruning/CompositePersistenceStrategy.cs, src/Nethermind/Nethermind.Trie/Pruning/IPersistenceStrategy.cs, src/Nethermind/Nethermind.Trie/Pruning/ISnapshotStrategy.cs, src/Nethermind/Nethermind.Trie/Pruning/IntervalSnapshotting.cs, src/Nethermind/Nethermind.Trie/Pruning/MemoryLimit.cs, src/Nethermind/Nethermind.Trie/Pruning/NoPersistence.cs, src/Nethermind/Nethermind.Trie/Pruning/NoPruning.cs, src/Nethermind/Nethermind.Trie/Pruning/Prune.cs, src/Nethermind/Nethermind.Trie/Pruning/TinyTreePath.cs, src/Nethermind/Nethermind.Trie/Pruning/TrackedPastKeyCountStrategy.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs, src/Nethermind/Nethermind.Trie/Utils/WriteBatcher.cs
- We have seen #6331 reduces database growth by about 50% likely due to improved compression. Branch that change only one child that sits next to previously unchanged branch probably get compressed really well.
- BUT WAIT THERE'S MORE!
- Since different path no longer share hashes we can approximately keep track of what is currently in the database, and on persist of a canonical block, we remove the old value.
- This work suprisingly well, where 90% (95% for state, 82% for storage) of the about to be persisted key have a match in the LRU for tracking persisted node.
- This does require additional memory with an LRU of 2 million nodes. This should take about 2Mil * 48 byte of memory at best case, with an additional 0.5Mil * 48 byte to keep track of recommitted nodes to prevent them from …
=> Perf/Live Pruning

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Blockchain/Receipts/InMemoryReceiptStorage.cs, src/Nethermind/Nethermind.Config/ConfigProvider.cs, src/Nethermind/Nethermind.Config/Nethermind.Config.csproj, src/Nethermind/Nethermind.Facade/Filters/FilterManager.cs, src/Nethermind/Nethermind.Facade/Filters/FilterStore.cs, src/Nethermind/Nethermind.Facade/Nethermind.Facade.csproj, src/Nethermind/Nethermind.JsonRpc/Modules/RpcMethodFilter.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs, src/Nethermind/Nethermind.Synchronization/Peers/PeerInfo.cs, src/Nethermind/Nethermind.Trie/Nethermind.Trie.csproj, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs, src/Nethermind/Nethermind.TxPool/Nethermind.TxPool.csproj, src/Nethermind/Nethermind.TxPool/NonceManager.cs, src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
- Use [`NonBlocking.ConcurrentDictionary`](https://github.com/VSadov/NonBlocking) from @VSadov where appropriate. Can't changes `AllNodes` in `TrieStore` as we also grab all the internal locks at one point.
=> Use NonBlocking.ConcurrentDictionary

src/Nethermind/Nethermind.Blockchain.Test/Utils/LastNStateRootTrackerTests.cs, src/Nethermind/Nethermind.Blockchain/Utils/ILastNStateRootTracker.cs, src/Nethermind/Nethermind.Blockchain/Utils/LastNStateRootTracker.cs, src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Snap/Messages/AccountRangeMessageSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Snap/Messages/TrieNodesMessageSerializerTests.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/AccountRangeMessageSerializer.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/TrieNodesMessageSerializer.cs, src/Nethermind/Nethermind.Synchronization.Test/RangeQueryVisitorTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/SnapServerTest.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapServer.cs, src/Nethermind/Nethermind.Trie.Test/TreePathTests.cs, src/Nethermind/Nethermind.Trie/Pruning/TreePath.cs, src/Nethermind/Nethermind.Trie/RangeQueryVisitor.cs
- Fix snap server hive tests.
- Need to change the default config to turn on snap serving and snap sync, but otherwise should pass all snap tests.
- Slight performance improvement. Halfpath peaks at 250k nodes per sec now.
- Have not test sync yet.
=> Fix Snap Server Hive Tests

src/Nethermind/Nethermind.AuRa.Test/AuRaHealthHintServiceTests.cs, src/Nethermind/Nethermind.AuRa.Test/AuRaStepCalculatorTests.cs, src/Nethermind/Nethermind.Blockchain/Data/FileLocalDataSource.cs, src/Nethermind/Nethermind.Blockchain/FullPruning/FullPruner.cs, src/Nethermind/Nethermind.Consensus.AuRa/TaskExt.cs, src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PeerRefresher.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucket.cs, src/Nethermind/Nethermind.Network/PeerManager.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncPeersReportTests.cs, src/Nethermind/Nethermind.Synchronization/IProcessExitSourceExtensions.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapServer.cs, src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
Almost always use `DateTime.UtcNow` except in a couple places, which can cause inconsitences with timezones and daily savings changes.
- Change any use of `DateTime.Now` to `DateTime.UtcNow` other than in logging output
=> Consistently use DateTime.UtcNow over DateTime.Now

src/Nethermind/Nethermind.Consensus/Scheduler/BackgroundTaskScheduler.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Network.Stats/Model/DisconnectReason.cs, src/Nethermind/Nethermind.Network.Test/P2P/PacketSenderTests.cs, src/Nethermind/Nethermind.Network/P2P/Messages/P2PMessage.cs, src/Nethermind/Nethermind.Network/P2P/PacketSender.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/HashesMessage.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/PooledTxsRequestor.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/TransactionsMessage.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Messages/Eth66Message.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Messages/NewPooledTransactionHashesMessage68.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Les/LesProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/NodeData/NodeDataProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Utils/BackgroundTaskSchedulerWrapper.cs
- Fix silent background task failure causing transaction to not be able to sent out due to ArrayPoolList being disposed before serialization.
- Log error on unhandled exception at BackgroundTaskScheduler level.
- Disconnect and log debug on unhandled exception at p2p handler level.
- Add IDisposable to P2PMessage and dispose after serialization in PacketSender.
=> Fix silent backgrount task failure.

src/Nethermind/Nethermind.Blockchain/SpecificBlockReadOnlyStateProvider.cs, src/Nethermind/Nethermind.Core/Account.cs
- Make `SpecificBlockReadOnlyStateProvider` return `Account.TotallyEmpty` instead of `default` for non-existing accounts.
This issue broke posdao-tests, they now pass
=> Fix an issue where the default constructor for `AccountStruct` was used when account was not found

.github/workflows/sync-testnets.yml
Small change to make sure if there was any previous error on a run, sedge is not leaving any leftovers and won't affect next runs.
=> Make sure sedge is always cleared after sync

src/Nethermind/Nethermind.Init/InitializeStateDb.cs, src/Nethermind/Nethermind.State.Test/StateProviderTests.cs, src/Nethermind/Nethermind.State.Test/StateReaderTests.cs, src/Nethermind/Nethermind.State/IWorldStateExtensions.cs, src/Nethermind/Nethermind.State/StateReaderExtensions.cs
- Use StateReader for VerifyTrie instead of WorldState.
- Its faster as it does not modify dirty cache.. Probably a mistake before when it use WorldState.
- I've literally always change this.
=> Use state reader for trie visitor

src/Nethermind/Nethermind.Consensus.Clique/CliquePlugin.cs
Bug:
`CliqueBlockProducer` will throw `ObjectDisposedException` during shutdown. 
Fix:
Put `CliqueBlockProducer` on the dispose stack.
=> Put clique block producer on dispose stack

src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/RocksDbTests.cs
Fixes #6544 
- Update RocksDB with https://github.com/curiosity-ai/rocksdb-sharp/pull/51
Significant db version change 8.3 -> 8.10
When building from source or using ppa, the client does not use system-installed version of rocksdb anymore
=> Update rocksdb with the loading order fix

src/Nethermind/Nethermind.Blockchain.Test/KnownChainSizesTests.cs, src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/mainnet_archive.cfg, src/Nethermind/Nethermind.TxPool.Test/Collections/DistinctValueSortedPoolTests.cs, src/Nethermind/Nethermind.TxPool/Collections/BlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/PersistentBlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs
TxPool autorecover - experiments
For now I am experimenting
=> TxPool autorecover

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/P2PProtocolInfoProviderTests.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs
- remove eth67 and eth68 conditional enabling, now set both as default capabilities
More context:
We were disabling eth67 and eth68 if node were not synced and didn't support snap sync. This is because `GetNodeData` and `NodeData` messages are not supported in mentioned versions and we needed these messages to be able to fast sync on some networks, e.g. gnosis.
In 1.25.0 we released `NodeDataProtocol` - satellite protocol designed for support of `NodeData` messages. Since then nethermind can serve/receive `NodeData` using sattelite protocol and doesn't need eth66 anymore.
For cooperation with old client versions on some networks (e.g. OE), we keep eth66 as default capability. Nodes will use highest common version (eth66).
=> Set eth67 and eth68 as default capabilities

src/Nethermind/Nethermind.Network.Test/MessageDictionaryTests.cs, src/Nethermind/Nethermind.Network.Test/SnapProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/P2P/MessageDictionary.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Messages/Eth66Message.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/SnapMessageBase.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs
- The MessageDictionary class is the successor to MessageQueue which allow handling of P2P message out of order.
- For some reason, snap protocol handler does not use it, even when it have request id. Wonder why it does not implement it, who missed it when creating the MessageDictionary.. oh wait its me. That makes complete sense.
- This means it can't handle snap request out of order, which will probably just cause peer disconnection.
- Also finally explain why just increasing number of concurrent call does not work improve snap server throughput.
- Make it implement it.
=> Migrate snap message to use MessageDictionary

src/Nethermind/Nethermind.Core/Collections/IOwnedReadOnlyList.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Snap/Messages/StorageRangesMessageSerializerTests.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/StorageRangeMessage.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/Messages/StorageRangesMessageSerializer.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs, src/Nethermind/Nethermind.Serialization.Rlp/AccountDecoder.cs, src/Nethermind/Nethermind.State.Test/SnapSync/RecreateStateFromAccountRangesTests.cs, src/Nethermind/Nethermind.State.Test/SnapSync/RecreateStateFromStorageRangesTests.cs, src/Nethermind/Nethermind.State/Snap/SlotsAndProofs.cs, src/Nethermind/Nethermind.Synchronization.Test/RangeQueryVisitorTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromAccountRangesTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromStorageRangesTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/SnapServerTest.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/AccountCollector.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/ISnapServer.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/PathWithStorageCollector.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapServer.cs, src/Nethermind/Nethermind.Synchronization/Synchronizer.cs, src/Nethermind/Nethermind.Trie/RangeQueryVisitor.cs
- Collect leaf value to an arraypoollist of the desired types for snap server instead of encoding accounts to bytes first.
- Increase snap server throughput by about 10-20%.
- Total throughput right now + some optimization in halfpath is about 450k nodes writes per sec.
=> Leaf value collector

src/Nethermind/Nethermind.Core/ProductInfo.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ClientVersionV1.cs, src/Nethermind/Nethermind.Merge.Plugin/EngineRpcModule.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs, src/Nethermind/Nethermind.Merge.Plugin/IEngineRpcModule.cs
=> add engine_getClientVersionV1 API support

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db/DbNames.cs, src/Nethermind/Nethermind.Db/IDbProvider.cs, src/Nethermind/Nethermind.Db/MemColumnsDb.cs, src/Nethermind/Nethermind.Db/MemDb.cs, src/Nethermind/Nethermind.Db/MemDbFactory.cs, src/Nethermind/Nethermind.Db/StandardDbInitializer.cs, src/Nethermind/Nethermind.Db/VerkleDbColumns.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V2.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Verkle/VerkleProtocolHandler.cs, src/Nethermind/Nethermind.State/VerkleStateTree.cs, src/Nethermind/Nethermind.Synchronization.Test/VerkleSync/VerkleProgressTrackerTest.cs, src/Nethermind/Nethermind.Synchronization/VerkleSync/VerkleProgressTracker.cs, src/Nethermind/Nethermind.Synchronization/VerkleSync/VerkleSyncProvider.cs, src/Nethermind/Nethermind.Synchronization/VerkleSync/VerkleSyncServer.cs, src/Nethermind/Nethermind.Verkle.Tree.Test/GenesisTestBench.cs, src/Nethermind/Nethermind.Verkle.Tree.Test/Nethermind.Verkle.Tree.Test.csproj, src/Nethermind/Nethermind.Verkle.Tree.Test/TestSyncRangesInAHugeVerkleTree.cs, src/Nethermind/Nethermind.Verkle.Tree/TreeStore/VerkleTreeStore.cs, src/Nethermind/Nethermind.Verkle.Tree/VerkleDb/VerkleKeyValueDb.cs
Resolves #6700 
- Leaf and internal nodes now in the same column db and saved atomically.
- Not sure about `StateRootToBlock` or other db. So I just leave it.
=> Use column db for verkle kv db

src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
Fixes
- Use `providedParametersLength` which has already taken into account `null` parameters rather than rechecking `.GetArrayLength()`
=> Fix arraylength check on null parameters

src/Nethermind/Nethermind.Synchronization.Test/Trie/RecoveryTests.cs, src/Nethermind/Nethermind.Synchronization/Trie/SnapTrieNodeRecovery.cs, src/Nethermind/Nethermind.Synchronization/Trie/TrieNodeRecovery.cs
- Fix ObjectDisposedException on trie node recovery due to the same arraypoollist used for multiple peer.
- Copy list for each peer.
- Reproducable by randomly throwing trienodeexception in LoadRlp.
- Error no longer show up.
=> Fix object disposed exception on trie recovery

src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeTxMemoryTracerTests.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs
Fixes #6669, #6810
- Adds a check to ensure that the GasCost trace entry is not overwritten after the `STOP` or `RETURN` opcodes are executed and the gas cost is properly recorded in the trace entry
- This approach is based on the way that [ParityLikeTxTracer](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs#L278-L297) handles this situation
=> Fix negative gas cost in debug_traceTransaction traces

src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
Fixes #6390
In our eth_estimateGas we use a `EstimateGasTracer`, call the EVM and pass it to `GasEstimator`.
Problem is that internally `GasEstimator` uses another tracer that does not fail under certain conditions, like running out of gas on code deploy. 
This means you can pass a tx without gas limit which `EstimateGasTracer` will succeed, and then the internal tracer will incorrectly adjust the gas below out of gas. 
This fix will make the internal tracer also fail correctly. 
Another issue to consider is if the internal tracer should also fail on explicits revert ops?
`OutOfGasTracer` checks out of gas revert correctly.
=> Fix/estimate gas #6390

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs
- On `eth_getLogs` which is a special case, when it throws of any arbitrary error, the module is not returned.
- Not sure what is the actual error that causes this problem for user.
- Also fix response not disposed on websocket.
- Fix
- Reproducable by randomly throwing error in eth_getLogs.
- Websocket is reproducable by turning on websocket with nimbus.
=> Fix rpc module not returned on arbitrary error

src/Nethermind/Nethermind.Verkle.Tree/Utils/VerkleWitness.cs
remove codeKeccak key access when charging gas from contract creation initialization
ref: https://eips.ethereum.org/EIPS/eip-4762
- remove access event `(contract_address, 0, CODE_KECCAK_LEAF_KEY)` when a contract creation is initialized
=> fix the contract creation init gas cost

src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
- Fix logging to have expected items instead of e.g. `Failed to remove the last item from the pool, the current state is 8366/2048. System.Func1[System.String]`
Tested on local node - after changes logging as expected
=> Fix logging in SortedPool

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.Serialization.Json/DoubleConverter.cs
Fixes many tests currently being skipped in `Nethermind.JsonRpc.Test`
Depending on #6859 since it will fix currently broken tests.
Sets `Invariant` culture on Json converter to avoid `,` in json output
=> Dont skip tests Nethermind.JsonRpc.Test 

src/Nethermind/Nethermind.AccountAbstraction/Subscribe/NewPendingUserOpsSubscription.cs, src/Nethermind/Nethermind.AccountAbstraction/Subscribe/NewReceivedUserOpsSubscription.cs, src/Nethermind/Nethermind.Core/Extensions/DisposableExtensions.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcProcessorTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcBatchResult.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcBatchResult.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcResponse.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcResult.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/DroppedPendingTransactionsSubscription.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/LogsSubscription.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/NewHeadSubscription.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/NewPendingTransactionsSubscription.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Subscribe/SyncingSubscription.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Better disposable of JSON RPC batches
- Make dispose of `JsonRpcResult` at the caller
=> Better disposable of JSON RPC batches

src/Nethermind/Nethermind.Trie/Pruning/TinyTreePath.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Using a non IEquatable/ValueTuple as Dictionary key causes huge allocations. Define some structs for these keys with implicit conversions from the ValueTuple
=> Use IEquatable+GetHashCode keys for Dictionary

scripts/wait-for-workflow-completed.sh
Time filter seems like not the best idea especially for Hive Consensus tests which are not triggering a docker creation but seeking for already triggered docker creation action - usually it happens almost at the same time for actions like OneClick but in  case of hive consensus it can start searching for image after few seconds which already violates this check.
Because sorting is applied and workflow_id filter is on place just simple status check for inprogress runs seems to be enough.
Tested on OneClick and will test after merge to release branch if it triggers properly now.
=> Change from time to status trigger - adjustment for Hive Consensus tests

src/Nethermind/Nethermind.Core/Threading/McsLock.cs, src/Nethermind/Nethermind.Core/Threading/McsPriorityLock.cs
Spend less time on lock management, so less likely to encounter contention.
- Use `ThreadNode` rather than `Thread.CurrentThread` to check for reenterncy
- Change spin `State` size from `bool` to `nuint` so is natural machine word size
- Move `SpinWait` stack reservations out of the uncontended path
- Move `Monitor`/`lock` signalling out of the fast-path (reducing fast path size and associated `try`/`finally`s)
- After aquiring lock to signal, check if waiting thread has already picked up the signal before Monitor singalling
- Fast-paths with mild contention will not use `lock` at all
=> McsLock fast-paths

src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandler.cs, src/Nethermind/Nethermind.TxPool/Collections/BlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/TxDistinctSortedPool.cs
Fixes hive test Blob Transaction Ordering, Multiple Clients
- Fix sharing of a new single blob tx over p2p
=> Fix sending new single tx p2p update

src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Fix trie exception when killed after memory pruning but before next block.
- This is because last persisted state is not saved after memory pruning.
=> Fix trie exception when killed after memory pruning before next block

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs, src/Nethermind/Nethermind.Core.Test/Collections/ArrayPoolListTests.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Removes unnecessary arraypoollist dispose
maybe Add a property on ArrayPoolList call `isDiposed` to check if object has been disposed.
useful for nested arrayPoolLists. 
Since we usually want to dispose the entire collection from the top
and sometimes we dispose inner collection from somewhere else when they are passed as references.
=> Fix JsonRPc Double dispose

src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs
Resolves #4642
- Lock around `_blockStore.Get` in `BlockTree` to move the contention outside of the RocksDB allocator (which then heavily hits other RocksDB processing like block processing) and into the calling code (OldReceipts/OldBodies)
- A better soltion would be to change the allocator to tcmalloc or Jemalloc however that is much more complicated especially factoring cross platform (will need to be building RocksDB from source and compiling in the allocator) https://github.com/NethermindEth/nethermind/issues/6107
Before
After
Significantly reduces block processing times
On Windows was seeing block processing times of up to 24seconds, this brings it down to mostly in range with the occasional spike to 2secs
=> Reduce contention inside RocksDB during OldReceipts

src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeNativeTracerFactoryTests.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/GethLikeNativeTracerFactory.cs
=> fix tracer name empty exception

src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/P2PProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ProtocolHandlerBase.cs
Network.DiagTracerEnabled throws `ObjectDisposedException`
Write to log before the dispose happens.
=> Fix Network.DiagTracerEnabled object disposed 

src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeJavaScriptTracerTests.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/JavaScript/GethLikeBlockJavaScriptTracer.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs
- Ensure that tracer resources (ArrayPoolList) are disposed
=> Javascript Tracer resource leak

src/Nethermind/Nethermind.State/StorageTree.cs
- Use FrozenDictionary for StorageTree 1024 key hash lookup
- Skip `.CopyTo` when lookup hit and use value directly from lookup
=> Use FrozenDictionary for StorageTree key cache

src/Nethermind/Nethermind.Evm/EvmStack.cs
- Use Avx512Vbmi for endianness swapping, is 1 instruction rather than 2
=> Use Avx512Vbmi for endianness swapping

src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Evm/IntrinsicGasCalculator.cs
- Cacluate data costs 32 bytes at a time rather than 1
=> Vectorize DataCost

src/Nethermind/Nethermind.Blockchain.Test/Validators/TestBlockValidator.cs, src/Nethermind/Nethermind.Consensus/Validators/AlwaysValid.cs, src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs, src/Nethermind/Nethermind.Consensus/Validators/IBlockValidator.cs, src/Nethermind/Nethermind.Consensus/Validators/NeverValidBlockValidator.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/InvalidChainTracker/InvalidBlockInterceptorTest.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/InvalidChainTracker/InvalidBlockInterceptor.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs
- If block comes from NewPayload, we calculated those hashes in `TryGetBlock`, no need to calculate them again.
=> Skip hash validations when block comes from NewPayload 

src/Nethermind/Nethermind.Consensus.AuRa/Validators/PendingValidators.cs, src/Nethermind/Nethermind.Consensus.AuRa/Validators/ValidatorInfo.cs, src/Nethermind/Nethermind.Network/NetworkNodeDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/BlockInfoDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/ReceiptMessageDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/ReceiptStorageDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Use FrozenDictionary for encoder lookup
- Use struct wrapper for `Type` for dicitionary devirtualization
- Use `Instance` decoder for `BlockInfo`, `Account`, `LogInfo` rather than type lookup
- Use `Instance` decoder for `Transaction` rather than instatiating new one each time.
- Use 256bit assignment rather than Span copy for Hash256 encoding
- Seal `TxDecoder` and `TrieNode`
- Split Rlp and Non-Rlp key generation into seperate methods rather than checking on each loop iteration.
=> Optimize Rlp Encoding

src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikePrestateTracerTests.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Prestate/NativePrestateTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Prestate/NativePrestateTracerAccount.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Prestate/NativePrestateTracerAccountConverter.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Prestate/NativePrestateTracerConfig.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Prestate/NativePrestateTracerDiffMode.cs
- Adds a `diffMode` tracer config option to enable diff mode for the prestate tracer. In diff mode the result object will contain a pre and a post object showing any modified account fields or created/deleted accounts that occurred during the transaction execution.
=> Add diff mode for prestate tracer

src/Nethermind/Nethermind.Blockchain/Metrics.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Evm/Metrics.cs
With vibes around MGas/s as metric, should be reporting it to grafana
- Add `MgasPerSec` to metrics reported to grafana
- Add some very fine grained opcodes to reporting
- EmptyCalls (sends between EOAs)
- Creates
- Remove some very fine grained opcodes from being reported
- SelfDestructs (not as interesting as before deprciation)
- TloadOpcode
- TstoreOpcode
- MCopyOpcode
- ModExpOpcode
- BlockhashOpcode
- Bn254MulPrecompile
- Bn254AddPrecompile
- Bn254PairingPrecompile
- EcRecoverPrecompile
- ModExpPrecompile
- Ripemd160Precompile
- Sha256Precompile
=> Add mgaspersec to metrics reported to grafana

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeersReport.cs, src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
- Maintain peers summary within rest of logs rather than word wrapping
Before
After
=> Logs: Line wrap peers summary

src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManager.cs, src/Nethermind/Nethermind.Network.Discovery/NodesLocator.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/INodeTable.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucket.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeTable.cs
- Introduce struct enumerators rather than using Linq
Addresses the following allocations
=> Less allocations for node processing

src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManager.cs, src/Nethermind/Nethermind.Network.Enr/EnrContentKey.cs, src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs, src/Nethermind/Nethermind.Network.Stats/Model/Node.cs
- Use `IPAddress` comparision rather than string comparision
- Use ReadOnlySpan<byte> Utf8 comparision rather than materializing string
- Lazy create `Host`, `Port` strings in `Node`
- Pre-calucate common `Port` strings
Bunch of unnessary strings being created
=> Reduce string allocs by networking

src/Nethermind/Nethermind.Consensus/TxFilterAdapter.cs, src/Nethermind/Nethermind.TxPool/Filters/AlreadyKnownTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/BalanceTooLowFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/BalanceZeroFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/DeployedCodeFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/FeeTooLowFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/FutureNonceFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/GapNonceFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/GasLimitTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/IIncomingTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/LowNonceFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/MalformedTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/NotSupportedTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/NullHashTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/NullIncomingTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/PriorityFeeTooLowFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/TxTypeTxFilter.cs, src/Nethermind/Nethermind.TxPool/Filters/UnknownSenderFilter.cs, src/Nethermind/Nethermind.TxPool/TxFilteringState.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- TxFilteringState as stack ref struct rather than allocation object per tx added to pool
Number 22 on allocations
=> TxFilteringState as stack ref struct

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Only lookup from dirty nodes once, rather than looking up if exists, then relooking up value (i.e. twice)
=> Only lookup from dirty nodes once

src/Nethermind/Nethermind.Core/Crypto/Hash256.cs, src/Nethermind/Nethermind.Trie/Pruning/ITrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/ReadOnlyTrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/TreePath.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- seal `Hash256`
- Introduce `ValueHash256.GetChainedHashCode(uint previousHash)`; if previous hash is randomised seeded can just use that as input for next hash, rather than starting with randomised seed and then combining at end (saving 2 hash combines)
- `TreePath.Equals` check `Length` first rather than last as simpler compare
- `AddOrUpdate` on ConcurrentDictionary rather than `Contains` + set
- `ref CollectionsMarshal.GetValueRefOrAddDefault` on Dictionary rather than `ContainsKey` + set 
- Reduce some struct copying
=> Improve TrieStore Dictionary use and Hashing

src/Nethermind/Nethermind.Synchronization/Trie/HealingTrieStore.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/Pruning/ScopedTrieStore.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Shrink TraverseBranch(es) method (for smaller loop body) and change to a loop as branches can go quite deep, so branches are all traversed in one method call
- Less stack spaces setup, returned through, etc
- seal `HealingTrieStore` and `ScopedTrieStore`
- Also makes perf traces easier to evaluate as is less branching at lots of different points
Before
After
Also Before (showing how deep it goes)
=> Traverse trie branches in same stack frame

src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/TracerExtensions.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Tracing is used to allow for cancellation, however to also introduces overheads from actually capturing all the trace data, even if it just throws it away.
- Instead introduce a IsCancelled property that can be checked once per loop
=> Don't use tracing for non-traced rpc calls

src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/JavaScript/GethLikeBlockJavaScriptTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/JavaScript/GethLikeJavaScriptTxTracer.cs
- Makes engine dispose lazy on serialization, fixing the issue it was disposed too eagerly introduced in #6929
- Disposes engines on exception
- Removes ArrayPool as it is hard to dispose it just in the right time
@natebeauregard can you test it?
=> Fix too eager dispose in js block tracing

scripts/deployment/ppa/debian/postinst
It seems `uname` changed what it returns doing `uname -m`. 
I'm getting `aarch64` running `uname -m` which results in wrong binary being installed when using nethermind ppa on arm64 machine.
- use dpkg instead uname in ppa postinst debian script
=> fix: Use dpkg instead uname to get unified arch in postinst debian script

src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
Resolves https://github.com/NethermindEth/nethermind/issues/6996
- Subtract new count from old count to get length to clear
=> ArrayPoolList.ReduceCount clear only remaining length

src/Nethermind/Nethermind.Trie/PatriciaTree.cs
- Don't need to pass count as a parameter as Span is already correctly sized
- Don't need to use count parameter to slice Span as is already correcrly sized
- Use `in CappedArray<byte>.Empty` rather than `Array.Empty<byte>()` which then is coverted to `CappedArray<byte>`
- Shuffle params so pointer sized ones are before Span
=> Perf PatriciaTree.Run

src/Nethermind/Nethermind.Evm/Precompiles/IdentityPrecompile.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Use existing array for precompile result, when Memory array backed and size same
=> Use existing array for precompile result

src/Nethermind/Nethermind.Benchmark/Evm/JumpDestinationsBenchmark.cs, src/Nethermind/Nethermind.Core/Specs/IReleaseSpec.cs, src/Nethermind/Nethermind.Evm.Test/CodeAnalysis/CodeInfoTests.cs, src/Nethermind/Nethermind.Evm.Test/InstructionTests.cs, src/Nethermind/Nethermind.Evm/ByteCodeBuilderExtensions.cs, src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs, src/Nethermind/Nethermind.Evm/CodeAnalysis/JumpDestinationAnalyzer.cs, src/Nethermind/Nethermind.Evm/Instruction.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Specs.Test/ChainSpecStyle/ChainSpecBasedSpecProviderTests.cs, src/Nethermind/Nethermind.Specs.Test/GoerliSpecProviderTests.cs, src/Nethermind/Nethermind.Specs.Test/MainnetSpecProviderTests.cs, src/Nethermind/Nethermind.Specs.Test/OverridableReleaseSpec.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecBasedSpecProvider.cs, src/Nethermind/Nethermind.Specs/ReleaseSpec.cs, src/Nethermind/Nethermind.Specs/SystemTransactionReleaseSpec.cs
- "[EIP-2315](https://eips.ethereum.org/EIPS/eip-2315): Simple Subroutines for the EVM" was withdrawn; is dead code now.
=> Remove subroutines (eip2315 withdrawn)

src/Nethermind/Nethermind.Core/ProductInfo.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ClientVersionV1.cs
Following spec here: https://github.com/ethereum/execution-apis/blob/main/src/engine/identification.md
=> Fix commit in ClientVersionV1 to have only 4 bytes of info following the spec

src/Nethermind/Nethermind.Crypto/KzgPolynomialCommitments.cs
- Use `ArrayPool<byte>.Shared` rather than allocating new arrays for `AreProofsValid`
Is a mild allocator
=> Use ArrayPool for Kzg.AreProofsValid

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs, src/Nethermind/Nethermind.Evm/CodeAnalysis/JumpDestinationAnalyzer.cs, src/Nethermind/Nethermind.Evm/Metrics.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
- If its already started processing it will likely finish before starting the processing from start will
- Also replaced queued/received section in logs which are always 0, with from cache + analysed which is more interesting data
=> Wait for background JumpDestinationAnalysis if in progress

src/Nethermind/Ethereum.Blockchain.Pyspec.Test/BerlinBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/BerlinStateTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/ByzantiumBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/ByzantiumStateTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/FrontierBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/FrontierStateTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/HomesteadBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/HomesteadStateTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/IstanbulBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/IstanbulStateTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/ParisBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/ShanghaiBlockChainTests.cs, src/Nethermind/Ethereum.Blockchain.Pyspec.Test/ShanghaiStateTests.cs
Resolves #6978
Added pyspec tests for other forks
=> Add more pyspec tests for other forks

.github/workflows/sync-testnets.yml
Improve Sync Testnets action to make sure it will be failure when nethermind process is stopped unexpectedly.
=> Add more checks on sync testnet to avoid critical issues marked as success

src/Nethermind/Nethermind.AuRa.Test/AuRaPluginTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaPlugin.cs
=> Fix NPE on aura plugin

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs
- Seems to be that the block cache size fluctuate.
- Seems to map with the blob transactions index.
- This set a dedicated block cache for blob transactions so that it does not effect the shared block cache which is used by state.
- The effect of the shared block cache on the block processing is was shown to be not much at all before as the file get os-cached in the first place. There could be a minor difference though.
- Set dedicated block cache for blob transaction.
- Manual log shows dedicated cache is used.
=> Set dedicated block cache for blob transactions

src/Nethermind/Nethermind.AccountAbstraction/AccountAbstractionPlugin.cs, src/Nethermind/Nethermind.Api/Extensions/IConsensusWrapperPlugin.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaPlugin.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Consensus.Clique/CliquePlugin.cs, src/Nethermind/Nethermind.Consensus.Ethash/EthashPlugin.cs, src/Nethermind/Nethermind.Consensus.Ethash/NethDevPlugin.cs, src/Nethermind/Nethermind.Consensus/IBlockProducerFactory.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockProducer.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.BlockProducer.cs, src/Nethermind/Nethermind.Mev.Test/MevPluginTests.cs, src/Nethermind/Nethermind.Mev/MevPlugin.cs, src/Nethermind/Nethermind.Optimism/InitializeBlockProducerOptimism.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
- Remove unnecessary async in block producter setup.
=> Remove unnecessary async

.github/workflows/sync-testnets.yml
Simplified approach which handles well unexpected shutdowns of an containers and exits properly on spcified conditions.
=> Different way of handling sync_testnets failure

src/Nethermind/Nethermind.Core/Bloom.cs
- Take the `.Topics` array to a local array rather than operating through the property so the Jit can confirm it's `.Length` cannot change per iteration and eliminate the bounds check.
Before the asm contains the `RNGCHKFAIL` exception
```asm
G_M000_IG09:                ;; offset=0x00D7
xor      rdx, rdx
xor      r8d, r8d
jmp      G_M000_IG05
G_M000_IG10:                ;; offset=0x00E1
call     CORINFO_HELP_RNGCHKFAIL
int3     
; Total bytes of code 231
```
After it doesn't (and asm is slightly smaller)
```asm
G_M000_IG09:                ;; offset=0x00CF
xor      rdx, rdx
xor      r8d, r8d
jmp      G_M000_IG05
; Total bytes of code 217
```
=> Eliminate bounds checks in Bloom

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.State/IWorldState.cs, src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs
Resolves https://github.com/NethermindEth/nethermind/issues/2324
- Only recalculate root hashes for storages once per block than for each tx; if multiple tx use the same contract it is wasteful to recalcuate them multiple times.
- Also means can recalucate all the storage roots in parallel at the end.
- Addresses some long standing TODOs and issue https://github.com/NethermindEth/nethermind/issues/2324
Now 1.5% of block processing when running in Parallel
=> Only recalculate storage roots once per block

src/Nethermind/Nethermind.Core/Caching/LruCacheNonConcurrent.cs, src/Nethermind/Nethermind.Core/Caching/LruKeyCacheNonConcurrent.cs, src/Nethermind/Nethermind.Db/Metrics.cs, src/Nethermind/Nethermind.Evm/MemoryAllowance.cs, src/Nethermind/Nethermind.State/IWorldState.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/StateReader.cs, src/Nethermind/Nethermind.State/StorageTree.cs, src/Nethermind/Nethermind.State/TransientStorageProvider.cs
Resolves #179
I'd solved this a long time ago; however always had issues doing the more ambitious step of sharing the cache between blocks; and parallel pre-caching.
Recognising the perfect can be the enemy of the good; and that we can make a journey with many steps; this introduces just the part of sharing state and storage between tx in the same block; rather than always starting afresh for each tx.
- Maintain state and storage cache between the txs in a block
Even though it clears every block in this iteration
*  \> 50% of state reads are cache hits
*  ~ 21% of storage reads are cache hits
=> Intra-block cache

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
- As the state is being read, the database will be cached in the OS cache, therefore the block processing improve over time. It takes about 30 minutes of constant block processing (assuming catching up) or about 2 weeks in real time for this effect to continue making consistent testing hard to achieve. Plus if I just want it to run as fast as it could to test for memory issue for example, it take some time.
- This PR introduce a flag that will read the files from DB on start so that the OS cache is filled up early on.
- On a system with 192GB of RAM (max RAM possible on a consumer level hardware at the moment) this can cache the whole state db resulting in a close to 0 iops at ssd level.
- On a system with lower available memory than the size of the db, it will attempt to priority lower …
=> Feature DB File warmer

src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- For the root of the Trie calculate all the branches keys in parallel (which occurs in the GetLength path)
Before 7+% of block processing
After 1.5% of block processing
=> Parallel Trie Branch KeyGeneration

tools/Nethermind.Tools.Kute/Auth/JwtAuth.cs
- Use the proper `Claim` type when building a JWT token in Kute.
Tested against a running Reth (TODO: document which version is being used)
=> Use proper claim types in JSON-RPC replay tool

src/Nethermind/Nethermind.Init/InitializeStateDb.cs
- Warn when using pruning cache larger than 2GB as the pruning hang can take large amount of time which effect attestation.
- Large pruning cache was mainly used to reduce database growth, but since Ahmad's node running 1GB pruning cache for the past 3 month only grow by 25GB, its probably fine to keep the default for most user.
- One scenario where it still make sense is for RPC provider as more cache does improve block processing performance or when setting much longer pruning boundary where large prune cache is unavoidable. For reference, on mainnet minimum prune cache size is about 450MB for past 128 state to support snap serving.
- Tested with setting and not setting te config.
=> Log when using larger than default pruning cache

src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeBucket.cs, src/Nethermind/Nethermind.Network.Discovery/RoutingTable/NodeTable.cs
Resolves #6995
- Use more explict locking for the Node list enumerators
=> Use tighter locking for Node list enumerator

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/ReadOnlyTxProcessingEnv.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.State/IWorldState.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs
- Load load the data for access lists. Now we can pre-warm/cache the data in a tx, it makes sense to actually use the access lists to prepopulate those caches.
=> Pre-cache AccessLists

src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
Fixes #6960
`InsertHeaders` now properly handles null when a dependent batch arrives. 
The added unit test also showcases different header batches that is allowed and not. 
Among them are a bit of strange behavior, since we allow a batch to start with null, but not empty.
This is not allowed
**batch 1-3**
header2, header3 
This is allowed
**batch 1-3**
null,header2, header3 
Also this will fix several instances of `ArrayPoolList` not being disposed in `HeaderSyncFeed`.
=> Fix for #6960 and new unit tests for testing dependent batches

src/Nethermind/Nethermind.Evm/CodeAnalysis/CodeInfo.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- If a call is to a non-contract address; just transfer the value rather than constructing a full call frame 
- between 1% to 10% of calls per block are to non-contract (i.e. effectively only ETH transfers)
=> Fast Call to Non contract addresses

src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/PreBlockCaches.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.Trie/PreCachedTrieStore.cs
- Use larger System.Collections.Concurrent.ConcurrentDictionary
=> Use System.Collections.Concurrent

src/Nethermind/Nethermind.Blockchain/BlockHashInState/BlockHashInStateHandler.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Withdrawals/WithdrawalProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/Witness/VerkleExecWitness.cs, src/Nethermind/Nethermind.State.Test/Nethermind.State.Test.csproj, src/Nethermind/Nethermind.State.Test/VerkleWitnessAccessCostTest.cs, src/Nethermind/Nethermind.State/VerkleWorldState.cs, src/Nethermind/Nethermind.Verkle.Tree.Test/VerkleTreeTests.cs, src/Nethermind/Nethermind.Verkle.Tree/Cache/BlockBranchCache.cs, src/Nethermind/Nethermind.Verkle.Tree/IVerkleTree.cs, src/Nethermind/Nethermind.Verkle.Tree/TreeStore/IVerkleTreeStore.cs, src/Nethermind/Nethermind.Verkle.Tree/TreeStore/NullVerkleTreeStore.cs, src/Nethermind/Nethermind.Verkle.Tree/TreeStore/ReadOnlyVerkleStateStore.cs, src/Nethermind/Nethermind.Verkle.Tree/TreeStore/VerkleTreeStore.cs, src/Nethermind/Nethermind.Verkle.Tree/VerkleDb/IVerkleDb.cs, src/Nethermind/Nethermind.Verkle.Tree/VerkleDb/VerkleKeyValueDb.cs, src/Nethermind/Nethermind.Verkle.Tree/VerkleDb/VerkleMemoryDb.cs, src/Nethermind/Nethermind.Verkle.Tree/VerkleTree.cs
Closes #6961 
- CHUNK_FILL_COST in VerkleExecutionWitness
=> Added CHUNK_FILL_COST

src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
- It still regress by about 20% when prewarm is disabled. When enable net increase is about 20%. This is with db file warmer on a 196GB ram machine.
- Before, After
- Fix
=> Fix forward sync regression, block processing slows down over time

src/Nethermind/Nethermind.Config/IBlocksConfig.cs
- Fix migration config throw error when setting a value because it check the default value via `ToString()` which does not match the string value of the `DefaultValue`.
=> Fix cannot disable prewarm

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- The genesis block has a null `parentStateRoot`; so skip the prewarmer for that block
=> Skip prewarmer for genesis block

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Db/Metrics.cs, src/Nethermind/Nethermind.Evm/Metrics.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- Use `ThreadLocal<long>` for contended metrics (cpu cache contention)
- Report using the processing thread's local for block metric in logs (so is only block, and not all threads work)
=> Fix block metrics + reduce metric contention

src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
Resolves #6843
- If a worst value is removed for the group, but wasn't in the group, readd a new worst value for the group
=> If worsevalue removed but not found, reinsert new worst item

src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs
- If account doesn't exist warm up Accesslist value to empty
=> Warm up empty trees for accesslists

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Don't know why, can't figure it out, but it is reproducable.
- Normally the remove ratio (`rate(nethermind_removed_node_count[$__rate_interval])/rate(nethermind_persisted_node_count[$__rate_interval])`) is around 87%. For some reason, it drops to 20% after around 4000 blocks. This would increase database growth by about 6x.
- Before, after.
=> Fix pruning regression

src/Nethermind/Nethermind.Evm/Metrics.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Fixed a small mistake in EVM metrics
Renamed one metric ModExpOpcode -> ExpOpcode
=> Fixed EVM Metrics with a small modexp->exp bug

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs
- Turns out, you can use string to access options that is not available from the C (and therefore c#) binding.
- Notable options are `compaction_pri=kByCompensatedSize` which prioritize removing items.
- No significant impact on state db though. 
- Still, easy flag for experimentation.
=> Use string for additional rocksdb config

Dockerfile, Dockerfile.chiseled, Dockerfile.diag, src/Nethermind/Directory.Build.props, src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Core/ProductInfo.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/ClientVersionV1.cs, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj
- Removed dependency on Git executable in project files
- Added `Microsoft.Build.Tasks.Git` package to incorporate the commit hash into the version string
- Stopped copying the `.git` directory to Docker containers, which significantly increases local Docker image build times
- Revised `ClientVersionV1` tests
- Removed the branch name check from the project file so as not to fail the build because of an undesired branch name. This logic is completely unrelated to the build process and must be handled at the GitHub level
=> Revise Git commit hash handling

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Core/Cpu/ConsoleExitHandler.cs, src/Nethermind/Nethermind.Core/Cpu/CpuInfo.cs, src/Nethermind/Nethermind.Core/Cpu/DefaultCultureInfo.cs, src/Nethermind/Nethermind.Core/Cpu/Frequency.cs, src/Nethermind/Nethermind.Core/Cpu/FrequencyUnit.cs, src/Nethermind/Nethermind.Core/Cpu/ProcCpuInfoKeyNames.cs, src/Nethermind/Nethermind.Core/Cpu/ProcCpuInfoParser.cs, src/Nethermind/Nethermind.Core/Cpu/ProcCpuInfoProvider.cs, src/Nethermind/Nethermind.Core/Cpu/ProcessExtensions.cs, src/Nethermind/Nethermind.Core/Cpu/ProcessHelper.cs, src/Nethermind/Nethermind.Core/Cpu/RuntimeInformation.cs, src/Nethermind/Nethermind.Core/Cpu/SectionsHelper.cs, src/Nethermind/Nethermind.Core/Cpu/SysctlCpuInfoParser.cs, src/Nethermind/Nethermind.Core/Cpu/SysctlCpuInfoProvider.cs, src/Nethermind/Nethermind.Core/Cpu/TimeInterval.cs, src/Nethermind/Nethermind.Core/Cpu/TimeUnit.cs, src/Nethermind/Nethermind.Core/Cpu/UnitPresentation.cs, src/Nethermind/Nethermind.Core/Cpu/WmicCpuInfoKeyNames.cs, src/Nethermind/Nethermind.Core/Cpu/WmicCpuInfoParser.cs, src/Nethermind/Nethermind.Core/Cpu/WmicCpuInfoProvider.cs, src/Nethermind/Nethermind.Init/Steps/LogHardwareInfo.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs
- Use physical cores rather than logical cores as the degree of parallisation to reduce contention
=> Limit contended paths to physical cores not logical cores

src/Nethermind/Nethermind.Network/Rlpx/RlpxHost.cs
- Cap DotNetty threads at 16; it was made multithreaded in 2019 https://github.com/NethermindEth/nethermind/pull/836 when common core count was 4 or less.
Unbounded as there are 2 loops and the default is logical cores x 2; that can easily be 128 threads for consumer regular hardware or 512 threads for a top end Thread Ripper (2x2x128)
Steam hardware report from 2019
=> Cap DotNetty Threads

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockValidationTransactionsExecutor.cs, src/Nethermind/Nethermind.Core/Block.cs
- Skip transactions for prewarming where main processing has processed or is being processed
=> Skip prewarming tx if main processing has caught up

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Remove parallel from withdrawal warmup (started failing hive tests with this change)
=> Remove parallel from withdrawal warmup

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcModuleProviderTests.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcContext.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- Don't limit eth_getLogs on authenticated context
Test CL's
Can be controversial on AsyncLocal implementation?
=> Don't limit eth_getLogs on authenticated context

src/Nethermind/Nethermind.Core/Threading/ThreadExtensions.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
- Don't boost priority of forkchoice if syncing.
- Apart from being no advantage
- If syncing may go async and switch threads
=> Don't boost priority of forkchoice if syncing

src/Nethermind/Nethermind.Core.Test/Caching/LruCacheLowObjectTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheLowObjectTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheNonConcurrentTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/SpanLruCacheTests.cs, src/Nethermind/Nethermind.Core/Caching/LinkedListNode.cs, src/Nethermind/Nethermind.Core/Caching/LruCacheLowObject.cs, src/Nethermind/Nethermind.Core/Caching/LruKeyCacheLowObject.cs, src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
- Replace was overriting `.Next` and `.Prev` after item had been moved. Carry those values through to new node
=> Fix low object LruCaches

src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
- Very large sized fixed sized `LruKeyCacheLowObject` is causing OOM on some CI tests and hive
=> Fix test CI machines oom

src/Nethermind/Nethermind.Optimism/OPL1CostHelper.cs
- Rented buffer was not zeros, a leg was shot by SkipLocalsInit
=> Fix allocation

Dockerfile.chiseled, src/Nethermind/Nethermind.AccountAbstraction.Test/Network/CalculateRequestIdTest.cs, src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs, src/Nethermind/Nethermind.Cli/Modules/CliModuleLoader.cs, src/Nethermind/Nethermind.Consensus/MiningConfig.cs, src/Nethermind/Nethermind.Consensus/Processing/RecoverSignature.cs, src/Nethermind/Nethermind.Consensus/TargetAdjustedGasLimitCalculator.cs
- fixed spelling errors
- corrected grammar in comments
=> Minor spelling fixes

src/Nethermind/Nethermind.Core.Test/Caching/LruCacheLowObjectTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheLowObjectTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheNonConcurrentTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/SpanLruCacheTests.cs, src/Nethermind/Nethermind.Core/Caching/ICache.cs, src/Nethermind/Nethermind.Core/Caching/ISpanCache.cs, src/Nethermind/Nethermind.Core/Caching/LruCache.cs, src/Nethermind/Nethermind.Core/Caching/LruCacheLowObject.cs, src/Nethermind/Nethermind.Core/Caching/LruKeyCache.cs, src/Nethermind/Nethermind.Core/Caching/LruKeyCacheLowObject.cs, src/Nethermind/Nethermind.Core/Caching/LruKeyCacheNonConcurrent.cs, src/Nethermind/Nethermind.Core/Caching/MemCountingCache.cs, src/Nethermind/Nethermind.Core/Caching/SpanLruCache.cs
Fix in https://github.com/NethermindEth/nethermind/pull/7160 broke hive tests; still haven't been able to track down the issue. However more tests is always good.
Break is state root mismatch
```
Processed block 8 (0x51bd5f...3159f4) is invalid: 
- hash: expected 0x63396b16dea8377d79ee68c1c1029a88315138025941d4815c0cfc033dbd5fc7, 
got 0x51bd5f2998f8e2a5bdba8a15e5a8e8536ccadfd3bb4d776d94c1416b193159f4 
- state root: expected 0x9e0a7957b87f211e0aa26e6f0e4837c6fd23954ed76cce0e0e02c1f15590e157
got 0xd942379f8376919d331a93825182e628c9ac4ab216cabb1ec495ae36084a833d 
- block extra data : 4e65746865726d696e64, UTF8: Nethermind 
Processed block is not valid 8 (0x63396b16dea8377d79ee68c1c1029a88315138025941d4815c0cfc033dbd5fc7) 
InvalidStateRoot: State root in header does not match. 
```
- Increase …
=> Increase Lru tests

src/Nethermind/Nethermind.Analytics/AnalyticsWebSocketsModule.cs, src/Nethermind/Nethermind.Core/Authentication/IRpcAuthentication.cs, src/Nethermind/Nethermind.Core/Authentication/JwtAuthentication.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcWebSocketsModule.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/JwtTest.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Sockets/Extensions.cs, src/Nethermind/Nethermind.Sockets/IWebSocketsModule.cs
- Replaced `JwtSecurityToken` with the new `JsonWebToken` that's up to 30% faster, as Microsoft [claims](https://github.com/dotnet/aspnetcore/issues/49469)
- Made the `JwtAuthentication.Authenticate()` method async because of the underlying handler async API, which in turn caused chained async changes in several places
=> Replace `JwtSecurityToken` with `JsonWebToken`

src/Nethermind/Nethermind.Blockchain/ValidatorExit/WithdrawRequestsContract.cs, src/Nethermind/Nethermind.Consensus/Requests/WithdrawalRequestsProcessor.cs, src/Nethermind/Nethermind.Core.Test/Builders/TestItem.cs, src/Nethermind/Nethermind.Core.Test/Builders/WithdrawalRequestBuilder.cs, src/Nethermind/Nethermind.Core.Test/Encoding/BlockDecoderTests.cs, src/Nethermind/Nethermind.Core.Test/Encoding/ConsensusRequestDecoderTests.cs, src/Nethermind/Nethermind.Core/ConsensusRequests/WithdrawalRequest.cs, src/Nethermind/Nethermind.Serialization.Rlp/WithdrawalRequestDecoder.cs
Align WithdrawalRequestV1 with EIP-7002: https://github.com/ethereum/execution-apis/pull/549
=> Rename: `ValidatorPublicKey` -> `ValidatorPubKey`

src/Nethermind/Nethermind.State/PreBlockCaches.cs
- Use fast-path with early exit; rather than having to lock to get exact number
=> Use .IsEmpty rather than .Count for ConcurrentDictionary

src/Nethermind/Nethermind.Network.Dns/EnrTreeCrawler.cs
- Use OrdinalIgnoreCase to not create intermediate string
=> Use OrdinalIgnoreCase rather than .ToLower()+Op for string

src/Nethermind/Nethermind.Core/Threading/ZeroContentionCounter.cs, src/Nethermind/Nethermind.Db/Metrics.cs, src/Nethermind/Nethermind.Evm/Metrics.cs
While the ThreadLocal removes all contention; it does allocate a new List<T> every time the values are totalled.
- Use reflection to iterate the values to total in same why that runtime constructs the `List<T>`; so no allocations to total
- Introduce new class `ZeroContentionCounter` to hide this complexity
- Runtime issue raised https://github.com/dotnet/runtime/issues/103684
=> Reduce allocations in metrics backed by Zero Contention Counter

src/Nethermind/Nethermind.Core.Test/MCSLockTests.cs, src/Nethermind/Nethermind.Core.Test/McsPriorityLock.cs, src/Nethermind/Nethermind.Core/Threading/McsLock.cs, src/Nethermind/Nethermind.Core/Threading/McsPriorityLock.cs
Contributes to  #7171
- Reduce the number of ThreadLocals in use (seems to be issue on Windows over time and lots end up on finalization queue)
- Also add cache padding to the nodes
=> Mcslock reduce threadlocals

src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
- Use `BitOperations.LeadingZeroCount` rather than a bunch of `if`s
=> Use intrinsic for GetHighestSetBitIndex

src/Nethermind/Nethermind.Benchmark.Runner/Program.cs, src/Nethermind/Nethermind.Benchmark/Core/FromHexBenchmarks.cs, src/Nethermind/Nethermind.Core.Test/BytesTests.cs, src/Nethermind/Nethermind.Core.Test/Json/ByteArrayConverterTests.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Core/Extensions/HexConverter.cs
- We already have a 128bit simd path; add 256bit and 512bit simd paths
=> Add 256bit and 512bit vectorized hex decode

src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs, src/Nethermind/Nethermind.Network.Discovery/Lifecycle/INodeLifecycleManager.cs, src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManager.cs
Fixes #7222
- Does not mark unreachable if secondary ping succeed 
- Retries to connect to unreachable peers when goes online
=> Discovery when offline on start

src/Nethermind/Nethermind.Trie/TrieNode.cs
- Use the standard `i < data.Length` for pattern
- Take local reference to array
- Only access array element once
- Change to switch expression pattern matching (and don't fall through type checking if type already found)
=> Clean up TrieNode.GetMemorySize

src/Nethermind/Nethermind.Synchronization/FastSync/DetailedProgress.cs, src/Nethermind/Nethermind.Synchronization/Reporting/SyncReport.cs
- Log state sync process every 10 secs rather than every 1 sec; as is very verbose and log hungry
=> Log state sync process every 10 secs rather than every 1 sec

src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
- Proper handling of self-destruct for previously non-touched slots
=> Handle un-accessed storage slots in self-destruct

src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/MemoryMessageStream.cs, src/Nethermind/Nethermind.JsonRpc/WebSockets/JsonRpcSocketsClient.cs
Fixes #7253 introduced in #6658
- Fix
=> Fix batch collection massages through sockets

src/Nethermind/Nethermind.Consensus/IMiningConfig.cs, src/Nethermind/Nethermind.Consensus/MiningConfig.cs, src/Nethermind/Nethermind.Init/Steps/SetupKeyStore.cs
Fixes #7258 introduced in #6780
- Make sure to load key
=> Load local key if MiningConfig.Enabled is true

src/Nethermind/Nethermind.Facade/BlockchainBridge.cs, src/Nethermind/Nethermind.Facade/IBlockchainBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.Optimism/Rpc/OptimismEthRpcModule.cs
Mitigates #7251
This resolves the issue, but doesn't fix the root cause of #7251
- Changes order of tx lookup to look first into canonical chain before looking in tx pool
=> RPC Tx lookup changes

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/chiado.cfg, src/Nethermind/Nethermind.Runner/configs/gnosis.cfg
Enable SnapSync on Gnosis and Chiado - we have already quite a lot of resynced/new nodes with SnapServing enabled on these chains and it makes it muuuch faster to sync those chains with this setting set to true.
=> Enable SnapSync on Gnosis by default

.github/workflows/publish-packages.yml
Removed Ubuntu 23.10 (Mantic Minotaur) from PPA distros.
=> Remove Mantic from PPA

src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Related to #6824
- Handle missing params correctly.
Now it handles correctly
```
{"method":"admin_peers","id":1,"jsonrpc":"2.0"}
```
=> JSON RPC: fix missing params when all are optional

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
Contributes to https://github.com/NethermindEth/nethermind/issues/7171
- Process transactions in order (the order that they will be required by main thread), rather than the partitioning scheme from Parallel.For
Partially resolves slow down on Windows
Before
After
=> Prewarm txns in order (of processing)

src/Nethermind/Nethermind.Core/Caching/ClockCache.cs, src/Nethermind/Nethermind.Core/Caching/ClockCacheBase.cs, src/Nethermind/Nethermind.Core/Caching/ClockKeyCache.cs
- Reduce ClockCache contention
- Calling ConcurrentDictionary.Count takes locks and causes contention on read side
- Use local count that is only changed when have write lock anyway
=> Reduce contention in ClockCache

src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
- Set `_loadFromTree` `Func<StorageCell, byte[]>` to method rather than lambda so it shows up in tracing as `LoadFromTreeStorage(StorageCell)` rather than `<.ctor>b__11_0(StorageCell)`
Before
After
=> LoadFromTree improve tracing closure name

src/Nethermind/Nethermind.Consensus/Processing/RecoverSignature.cs
- Originally started to address an observed performance stall with `Parallel.ForEach` resolved by switching to `Parallel.For` (per element dispatch vs integer range). However on comparing again the stall wasn't observed; so will call this more a refactoring 😅
=> Improve parallel signature recover

src/Nethermind/Nethermind.AuRa.Test/Contract/AuRaContractGasLimitOverrideTests.cs, src/Nethermind/Nethermind.AuRa.Test/Transactions/TxCertifierFilterTests.cs, src/Nethermind/Nethermind.AuRa.Test/Transactions/TxPermissionFilterTest.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs
- add prewarmer tests to existing blockchain tests
=> add prewarmer to existing tests

src/Nethermind/Nethermind.Config/ExitCodes.cs, src/Nethermind/Nethermind.Runner/Program.cs
Resolves https://github.com/NethermindEth/nethermind/issues/6942
Changes made into `src/Nethermind/Nethermind.Runner/Program.cs`
- Add a function to load all possible flags/params/arguments to be used and put them on a hash
- The hash is initialized with the default flags allowed in the app and not related to flags in config files
- Add a function to validate current args against the hash generated
- Call the validation function into `Run` so that we initialize the app and validate before start running most of the logic.
I did not see any test file for Program.cs files
I recorded a video showing how it works and the error log is displayed when the argument/option/flag used is not valid and when it is valid.
Also, the cases where no flag is provided and when a default app flag (like …
=> Validate and log when an unrecognized parameter/flag is used

src/Nethermind/Nethermind.Core.Test/CollectionExtensions.cs, src/Nethermind/Nethermind.Network.Test/MessageDictionaryTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/PacketSenderTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/NodeDataMessageSeralizerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V65/PooledTxsRequestorTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/GetBlockBodiesMessageSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/GetBlockHeadersMessageSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/GetNodeDataMessageSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/GetPooledTransactionsSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/GetReceiptsMessageSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/NodeDataMessageSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V66/PooledTransactionsMessageSerializerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V67/Eth67ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V68/Eth68ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/P2P/MessageDictionary.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/PooledTxsRequestor.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V65/Eth65ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V66/Eth66ProtocolHandler.cs
Fixes some of the missing `ArrayPoolList` cleanups in client code and tests.
Fixed:
- eth/66 and SNAP protocols not disposing some messages in case of a `SubprotocolException`.
- eth/65 not disposing `NewPooledTransactionHashesMessage`.
- `PooledTxsRequestor` not disposing some of the allocated `ArrayPoolList`s
- Tests under `Nethermind.Network.Test.P2P.Subprotocols.Eth` failing randomly due to some `ArrayPoolList`s not being disposed. Should be reproducible by either running or debugging tests for multiple protocol versions in a single run.
Also, optimized `ArrayPool` copying in `PooledTxsRequestor.RequestTransactionsEth66`, when multiple batches are sent.
=> Fix resources cleanup in eth/* protocols

src/Nethermind/Nethermind.Config/ExitCodes.cs, src/Nethermind/Nethermind.Runner/Program.cs
- Removes custom validation and uses library one
- Ammends error messages and exit codes
- Fix parsing argument names introduced in #7331
=> Removes custom args validation and uses library one

src/Nethermind/Nethermind.Evm/EvmState.cs
- Only need a single Stack for stacks as they are always done in pairs so use single one
- Using struct for Stack (that has both arrays) avoids calls to StelemRef to type check from having and Array as the generic param
- Halves the number of operations on Stack and depth book keeping
=> Only need single stack for stacks

src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
- Add dual array overload vs `params byte[][]` where it uses two for loops. Is used by 17 call sites
=> Add dual array concat overload

src/Nethermind/Nethermind.Merge.Plugin/Handlers/EngineRpcCapabilitiesProvider.cs
Fixes  #7322
- disable warning if CL doesn't have `engine_getBlobsV1` as it is optional on CL side ([link](https://github.com/ethereum/execution-apis/pull/559/files#diff-556d0544d517a1fe1242173c7d23c7cb5f3153bad5eeec9293865df9eefd349aR182-R184))
=> Disable warning in engine_getBlobsV1

src/Nethermind/Ethereum.Test.Base/Interfaces/IEofTestRunner.cs, src/Nethermind/Ethereum.Test.Base/LoadEofTestsFileStrategy.cs, src/Nethermind/EthereumTests.sln, src/Nethermind/Nethermind.EOFParse.Runner/Nethermind.EOFParse.Runner.csproj, src/Nethermind/Nethermind.EOFParse.Runner/Program.cs, src/Nethermind/Nethermind.EOFParse.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Test.Runner/EofTestsRunner.cs, src/Nethermind/Nethermind.Test.Runner/Nethermind.Test.Runner.csproj, src/Nethermind/Nethermind.Test.Runner/Program.cs, src/Nethermind/Nethermind.Test.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Test.Runner/eoftest1.json
EEST would very much benefit from a CLI launchable EOF fixtures test.
Here are two CLIs on top of @Demuirgos's EOF test work
(1) adds a -e option to `nethtest` to test a EOFTest
(2) adds a new standalone `netheofparse` CLI to participate in [eofparse](https://github.com/holiman/txparse?tab=readme-ov-file#eof-parser-eofparse) fuzzing.
=> Add EOFTest CLI Support

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Initialize last seen to -1 since 0 is a used value by tests
=> Fix last seen asserts

src/Nethermind/Nethermind.Network.Discovery/NettyDiscoveryBaseHandler.cs, src/Nethermind/Nethermind.Network.Discovery/NettyDiscoveryHandler.cs
Fixes frequent warning on invalid Discovery packet size in some cases.
- Reduced "invalid incoming packet size" log level to Debug.
- Fixed typo.
=> Fix frequent warning on invalid Discovery packet size

src/Nethermind/Nethermind.Network.Discovery/Kademlia/KBucket.cs, src/Nethermind/Nethermind.Network.Discovery/Kademlia/KBucketTree.cs, src/Nethermind/Nethermind.Network.Discovery/Kademlia/Kademlia.cs
Resolves #[Issue number for tree-based Kademlia implementation]
- Implemented a tree-based structure (KBucketTree) for organizing nodes in the Kademlia network
- Added logging to verify node addition and refreshing in the tree-based implementation
- Updated the Kademlia class to use the new KBucketTree structure alongside the existing array-based implementation
- Implemented a toggle to switch between array-based and tree-based implementations
- [] Yes
Added logs to verify node addition and tree structure. Further comprehensive tests for performance comparison between array-based and tree-based implementations are needed.
If yes, fill in the details here:
Added a new tree-based implementation for Kademlia node organization, potentially improving lookup efficiency and scalability. This …
=> tree based kademlia implementation

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/TestMemColumnDb.cs, src/Nethermind/Nethermind.Db.Rpc/RpcColumnsDb.cs, src/Nethermind/Nethermind.Db/IColumnsDb.cs, src/Nethermind/Nethermind.Db/MemColumnsDb.cs, src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.Trie/PreCachedTrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- TxTries and ReceiptTries don't do any pruning so don't need the ConcurrentDictionaries allocated just for Calculating roots
- Lazy allocate ConcurrenctDictionaries (+DirtyNodes in Trie)
- Change class => struct
- NodeKey class => struct
- Force GCs on archive sync
Seen when processing archive nodes (many blocks at once)
=> Reduce memory use during Archive Sync

src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj, src/Nethermind/Nethermind.Runner/app.manifest
Resolves #7171
- Change to `SegmentHeap` reducing contention in RocksDB
https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#heaptype
=> Change Windows native Allocator

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs
Resolves #7392
Follow up to #7407
- Reduce the backlog threshold trigger to 4 blocks
=> Reduce backlog threshold for GC

src/Nethermind/Nethermind.Core/Buffers/ArrayPoolDisposableReturn.cs, src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/JavaScript/Db.cs, src/Nethermind/Nethermind.Network.Discovery/NettyDiscoveryHandler.cs, src/Nethermind/Nethermind.Network/IMessageSerializationService.cs, src/Nethermind/Nethermind.Network/MessageSerializationService.cs, src/Nethermind/Nethermind.Serialization.Json/JavaScriptObjectConverter.cs
- Alas need to use `ArraySegment<byte>` rather than `Span<byte>` as the DotNetty types don't accept Span
Mild allocation
=> Use ArrayPool for Discovery Deserialization

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
- Direct fail create tx rather than throwing exceptions to immediately catch
=> Direct fail create tx rather than throwing exceptions

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- EXTCODESIZE+POP => NOP; is a common pattern on a large patch of blocks in archive sync (Think it was an exploit). However don't actually need to access any data in this combination.
=> EXTCODESIZE+POP

src/Nethermind/Nethermind.Consensus/GC/GCScheduler.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs
Resolves #7431
- Add min time between forced GCs
- Add periodic timer to GC during idle
- GC on background thread
=> Min time between induced gcs

src/Nethermind/Nethermind.Config/BlocksConfig.cs, src/Nethermind/Nethermind.Config/IBlocksConfig.cs, src/Nethermind/Nethermind.Init/Steps/LoadGenesisBlock.cs
Feature requested in #7361
- Makes genesis timeout configurable, 40s by default.
- Add hint to the error about when this can be useful.
- `GenesisHash` is still in `InitConfig` and now it is inconsistent
- Wondered if it should be `Ms` or `S`, but we always have `Ms` in other places so made it that.
=> Add GenesisTimeoutMs to BlocksConfig

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/IBlockCachePreWarmer.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core/Collections/CollectionExtensions.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TraceRpcModuleTests.cs, src/Nethermind/Nethermind.State/IWorldState.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/PreBlockCaches.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs, src/Nethermind/Nethermind.Trie/PreCachedTrieStore.cs
- Once the ConcurrentDIctionary lock is acquired, recheck if the collection is empty before trying to clear it
- Remove some additional clears of preWarm cache as over clearing them
- Allow prewarm cache to clear in background on prewarm continuation; only forcing at start of next block if not cleared
=> Recheck if empty under lock, early exit

src/Nethermind/Nethermind.TxPool/TxPool.cs
Avoid test runner breaking in `TxPoolTest`
=> Avoid test runner breaking in `TxPoolTest`

src/Nethermind/Nethermind.Config/IBlocksConfig.cs, src/Nethermind/Nethermind.Consensus/IMiningConfig.cs, src/Nethermind/Nethermind.Db/IPruningConfig.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.Optimism/IOptimismConfig.cs
Resolves https://github.com/NethermindEth/docs/issues/199
Revised the configuration options docs for the recent releases.
=> Revise the configuration options docs

.github/workflows/update-docs.yml, tools/docgen/ConfigGenerator.cs, tools/docgen/DBSizeGenerator.cs, tools/docgen/DocGen.csproj, tools/docgen/JsonRpcGenerator.cs, tools/docgen/MetricsGenerator.cs, tools/docgen/Program.cs, tools/docgen/Properties/launchSettings.json, tools/docgen/nuget.config
- Fixed the DB size generator to update the docs for the latest released version along with the next version
- Refactored command line arguments handling
- Refactored file handling to avoid back-and-forth with copying of the docs files. No need to copy doc files that should be modified. Now it knows where to look and what to do.
- Removed "v" from version strings
=> Refactor and improve DB size generator

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
- Currently it does `ReadOnlyMemory<byte>` -> `byte[]` -> `ReadOnlyMemory<byte>`; can just use the `ReadOnlyMemory<byte>` directly
=> Don't convert tx.Data to array unnecessarily

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
- Split `ApplyDaoTransition` into a fast inlinable check path and a slower apply path. Isn't a big performance change but it is only activated for 1 block on 1 chain so its bothering me that it shows up in traces 😅
Before
After
=> Optimize out DaoTransition call

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Core/TransactionReceipt.cs, src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs, src/Nethermind/Nethermind.Optimism/OptimismBlockReceiptTracer.cs
- Calculate the receipt blooms in parallel; saves ~1% on block validation
Before
After
=> Calculate receipt blooms in parallel

src/Nethermind/Nethermind.TxPool/BlobTxStorage.cs
- Use `.ToBigEndianSpanWithoutLeadingZeros` in more places
=> Use non-allocating key in more places

src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs, src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/CompositeTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
- Removes unsafe casts when tracing
=> fix casting when tracing

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Even if cancelled; should wait for all parts to register as cancelled before allowing next block to be processed
=> Always wait for address prewarmer; even if cancelled

src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/ITxPool.cs, src/Nethermind/Nethermind.TxPool/NullTxPool.cs, src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- Move clearing caches to txPool processing new head rather than main processing informing txPool of new head
2.9% of archive since since its processing blocks so fast
=> Move txPool work from Processing loop event to txPool thread

src/Nethermind/Nethermind.Crypto/TransactionExtensions.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/BlockBodiesMessageSerializer.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/TransactionsMessageSerializer.cs, src/Nethermind/Nethermind.Serialization.Rlp/BlockDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs, src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs, src/Nethermind/Nethermind.State/Proofs/TxTrie.cs, src/Nethermind/Nethermind.TxPool/BlobTxStorage.cs, src/Nethermind/Nethermind.TxPool/TransactionExtensions.cs
It's a hotfix that assumes another iteration of full clean up
- Use the same TxDecoder everywhere
=> Hotfix multiple instances of txdecoder usage

src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadHandlerBase.cs
- Is currently outputting 60+ lines per block which is slow and heavily pollutes the logs. Reduce it to be same as regular logging
=> Reduce logging for optimism

src/Nethermind/Nethermind.Api/Extensions/INethermindPlugin.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.EthStats.Test/EthStatsPluginTests.cs, src/Nethermind/Nethermind.Init/Steps/DatabaseMigrations.cs, src/Nethermind/Nethermind.Init/Steps/InitCrypto.cs, src/Nethermind/Nethermind.Init/Steps/InitRlp.cs, src/Nethermind/Nethermind.Init/Steps/InitTxTypesAndRlp.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockTree.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.Optimism.Test/RlpDecoderTests.cs, src/Nethermind/Nethermind.Optimism/InitializeBlockchainOptimism.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs, src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/ITxPool.cs, src/Nethermind/Nethermind.TxPool/NullTxPool.cs, src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
Proper fix instead of #7496
- Prefer manual registration
- Remove fishy public constructor
- Add tests for proper registration
Added tests to ensure that we're using a single `TxDecoder` global instance.
Registration of these global instances is tricky and very error prone. In an ideal world we would use DI to handle these kind of issues. Let's remember this issue next time DI comes into discussion.
=> Fix `TxDecoder` registration

src/Nethermind/Nethermind.Runner/configs/base-mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/base-sepolia.cfg, src/Nethermind/Nethermind.Runner/configs/op-mainnet.cfg, src/Nethermind/Nethermind.Runner/configs/op-sepolia.cfg
- Current default PruningBoundary and CacheMb clash into some very degenerate performance behaviour; reduce to 64 * 3 = 192
=> Op defauts

src/Nethermind/Nethermind.Db.Test/SimpleFilePublicKeyDbTests.cs, src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs
- Fix SimpleFilePublicKeyDb.Clear() not working due to missed `_cache`.
=> Fix clear not working

.github/workflows/codeql.yml
- Pinned the actions to specific commit hashes:
- actions/checkout pinned to d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
- github/codeql-action/init pinned to 5618c9fc1e675841ca52c1c6b1304f5255a905a0 #v2.19.0
- actions/setup-dotnet pinned to 6bd8b7f7774af54e05809fcc5431931b3eb1ddee #v4.0.1
- github/codeql-action/analyze pinned to 5618c9fc1e675841ca52c1c6b1304f5255a905a0 #v2.19.0
=> Pin action versions in `codeql.yml`

src/Nethermind/Nethermind.Merge.Plugin/GC/GCKeeper.cs
- Base has blocks of 2secs to pausing 1sec and triggering GC is too long
=> Reduce GC pause from 1sec to 500ms for faster blocks

src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Network.Test/NodesLoaderTests.cs, src/Nethermind/Nethermind.Network/NodesLoader.cs
- Only add static peer manager and nodes loader to peer pool when OnlyStaticPeers is true.
- Confirmed downloading only from static peers.
=> Make OnlyStaticPeers load only static peers

src/Nethermind/Nethermind.Core.Test/NUnitLogManager.cs, src/Nethermind/Nethermind.Logging.NLog/NLogManager.cs, src/Nethermind/Nethermind.Logging/ILogManager.cs, src/Nethermind/Nethermind.Logging/LimboLogs.cs, src/Nethermind/Nethermind.Logging/NoErrorLimboLogs.cs, src/Nethermind/Nethermind.Logging/NullLogManager.cs, src/Nethermind/Nethermind.Logging/OneLoggerLogManager.cs, src/Nethermind/Nethermind.Logging/SimpleConsoleLogManager.cs, src/Nethermind/Nethermind.Logging/TestErrorLogManager.cs, src/Nethermind/Nethermind.Logging/TestLogManager.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncReportTest.cs
- Reuse ClassLoggers via ConcurrentDictionary like Typed loggers
- Uses `[CallerFilePath]` for a compile time lookup to avoid using StackTrace to stack walk
=> Reuse ClassLoggers

src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Mostly white space changes
- Switch to a return code and two gotos (some white space changes from containing a `using` so `goto` can be used)
=> Remove 5 flow control exceptions

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Core.Test/Encoding/AccessListDecoderTests.cs, src/Nethermind/Nethermind.Core/Eip2930/AccessList.cs, src/Nethermind/Nethermind.State/IWorldState.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs
- Introduce a concurrent safe path for address and storage prewarming where no (non concurrent) storage caches are touched
- In addition prewarm access lists via this path
- Fan out and parallelise sub accesslist storages when there are a lot of them; so as not to cause head of line blocking and seralize prewarming by a large transaction
Resolves a lot of heavy access block issues on higher gas chains (e.g. mainnet) as they mostly use AccessLists; but doesn't completely solve it as on lower gas chains (e.g. Base) access lists aren't as heavily used.
=> Add and parallelise AccessList as part of address prewarming

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Currently TPS is unaligned in logs above 1k; make them aligned
Before
After
=> Improve logs when tps is above 1k/s

src/Nethermind/Ethereum.Test.Base/EofTest.cs, src/Nethermind/Ethereum.Test.Base/EofTestBase.cs, src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs, src/Nethermind/Ethereum.Test.Base/VectorTestJson.cs, src/Nethermind/Nethermind.Evm/EvmObjectFormat/Handlers/EofV1.cs
Fix the remaining EOF validation issues
* Check for required exit from returning code section (RETF or JUMPF)
* prevent JUMPF from non-returning into returning code sections
* consider `ContainerKind` from pyspec tests when running validion tests
* pass the worklet validation mode to validation unadjusted
* validate deep for RETURNCONTRACT
Tests are the pyspec tess
=> Fix remaining EOF validation issues

src/Nethermind/Nethermind.Clique.Test/SnapshotDecoderTests.cs, src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs, src/Nethermind/Nethermind.Consensus.Clique/CliqueRpcModule.cs, src/Nethermind/Nethermind.Consensus.Clique/ICliqueBlockProducer.cs, src/Nethermind/Nethermind.Consensus.Clique/ICliqueRpcModule.cs, src/Nethermind/Nethermind.Consensus.Clique/Snapshot.cs, src/Nethermind/Nethermind.Consensus.Clique/SnapshotDecoder.cs, src/Nethermind/Nethermind.Core/AddressConverter.cs, src/Nethermind/Nethermind.Core/ByteArrayConverter.cs, src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs
- Add clique_proposals
- Allow serialize Address as keys (for JSON Snapshot serialization)
=> Add clique_proposals & fix JSON Snapshot serialization

src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs
- Implement Keccak using Avx512 intrinsics
Inner loop is as follows, with no stack writes or stack spills 
```asm
G_M000_IG04:                ;; offset=0x0284
vpxorq   zmm15, zmm6, zmm7
vpxorq   zmm14, zmm8, zmm9
vpxorq   zmm14, zmm15, zmm14
vpxorq   zmm14, zmm14, zmm10
vpermq   zmm15, zmm0, zmm14
vpsllq   zmm0, zmm15, 1
vpsrlq   zmm15, zmm15, 63
vporq    zmm0, zmm0, zmm15
vpermq   zmm14, zmm1, zmm14
vpxorq   zmm0, zmm14, zmm0
vpxorq   zmm6, zmm6, zmm0
vpxorq   zmm7, zmm7, zmm0
vpxorq   zmm8, zmm8, zmm0
vpxorq   zmm9, zmm9, zmm0
vpxorq   zmm10, zmm10, zmm0
vprolvq  zmm6, zmm6, zmm2
vprolvq  zmm7, zmm7, zmm3
vprolvq  zmm8, zmm8, zmm4
vprolvq  zmm9, zmm9, zmm5
vprolvq  zmm10, zmm10, zmm16
vmovaps  zmm0, zmm6
vpermt2q zmm0, zmm17, zmm7
vpermt2q zmm0, zmm18, zmm8
vpermt2q zmm0, zmm19, zmm9 …
```
=> Avx512 Keccak

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.Blobs.cs, src/Nethermind/Nethermind.TxPool/Collections/BlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/DistinctValueSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/PersistentBlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
- Add test for `engine_getBlobsV1` concurrency
1. failing on master
2. passing on https://github.com/NethermindEth/nethermind/pull/7568
3. passing on https://github.com/NethermindEth/nethermind/pull/7572
=> Add test for `engine_getBlobsV1` concurrency

src/Nethermind/Nethermind.Core.Test/Crypto/BlsSignerTests.cs, src/Nethermind/Nethermind.Crypto/BlsSigner.cs, src/Nethermind/Nethermind.Shutter/Nethermind.Shutter.csproj, src/Nethermind/Nethermind.Shutter/ShutterCrypto.cs, src/Nethermind/Nethermind.Shutter/ShutterKeyValidator.cs, src/Nethermind/Nethermind.Shutter/ShutterTxLoader.cs
- Use SkipLocalsInit in Shutter cryptography
- Rename some variables for clarity
- Remove GetPublicKey function that encourages heap allocation
=> Minor Shutter Optimisation

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/ITransactionProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/SystemTransactionProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
- Don't commit in warmup; is unnecessary busy work
Before
After
=> Skip committing state during warmup

src/Nethermind/Nethermind.Trie/HexPrefix.cs
- Absorb odd outside loop
- Use 16bit LUT to do two nibbles at a time
=> Reduce branches in HexPrefix.FromBytes

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- Set metrics before request completion so Prometheus more reliably picks up the correct values at request end
=> Set metrics consistently before request completion

src/Nethermind/Nethermind.Consensus.Test/ExecutionRequestProcessorTests.cs, src/Nethermind/Nethermind.Consensus/ExecutionRequests/ExecutionRequestProcessor.cs, src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs, src/Nethermind/Nethermind.Core.Test/Builders/TestItem.cs, src/Nethermind/Nethermind.Core/Block.cs, src/Nethermind/Nethermind.Core/ExecutionRequest/ExecutionRequest.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/ExecutionRequestsProcessorMock.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/GetPayloadV4Result.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetPayloadV4Handler.cs
Closes #7525 
Closes #7524 
Closes #7522
Resolves #7521
Implements changes from
* [Update EIP-6110: change request to flat encoding EIPs#8856](https://github.com/ethereum/EIPs/pull/8856)
* [Update EIP-7685: change requests hash to flat hash EIPs#8854](https://github.com/ethereum/EIPs/pull/8854)
* ~[engine: unified list of opaque requests  execution-apis#577](https://github.com/ethereum/execution-apis/pull/577)~
* [engine: Make execution requests a sidecar, take 2 execution-apis#591](https://github.com/ethereum/execution-apis/pull/591)
- PR modifies two existing engine APIs : `engine_getPayloadV4` and `engine_getPayloadV4`, It incorporates suggestions from [pectra-devnet4 doc](https://notes.ethereum.org/@ethpandaops/pectra-devnet-4), which was to exchange `requests` as a side car and …
=> Add flat encoding and requests as a side car

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- The genesis block may be committed twice.
- Fix some engine tests. Also on debug.
=> Fix assertion failure on debug

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- `TryPeek` would get the oldest commit, not the last.
- Tested manually on mainnet archive
=> Fix commitset assertion

.github/workflows/trivy.yml
Trivy is added. Trivy is a lightweight image scanning tool that may discover vulnerabilities and misconfigurations. Actions pinned to specific commit hashes:
- trivy-action@5681af892cd0f4997658e2bacc62bd0a894cf564 #v0.27.0
- checkout@d632683dd7b4114ad314bca15554477dd762a938 #v4.2.0
- codeql-action/init@5618c9fc1e675841ca52c1c6b1304f5255a905a0 #v2.19.0
- setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee #v4.0.1
=> Add Trivy scanner workflow

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.Setup.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconSync.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/PivotUpdator.cs, src/Nethermind/Nethermind.Synchronization/IBeaconSyncStrategy.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
Fixes #6304
- block a start of beacon header sync until global pivot is updated
Beacon header sync can be initialized only when global pivot is already set, otherwise it might result in conflicting pivots and a deadlock
=> Block beacon header sync until global pivot is updated

.github/workflows/sync-supported-chains.yml
Mostly is about handling this PR: https://github.com/kamilchodola/linode-github-runner/pull/4
I've needed to lock VM creation for 5 parallel jobs as Linode have a limit of 5 VM creation requests every 15 seconds.
Because of that just VM creation part was taking up to 10 minutes.
Now is reduced to 5 minutes because everything is triggered at once with 20 seconds pooling if 429 exception a raises.
Also as other issues with Linode removal is handled well I can remove a "try again" step for VM removal.
=> Faster and not locked VM creation

src/Nethermind/Nethermind.JsonRpc/Modules/Trace/ITraceRpcModule.cs
- Marks `trace_get` and `trace_callMany` as implemented
- Adds basic documentation for them
**TBD**
**TBD**
=> Fix RPC methods marked as not implemented

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPruningDiskTest.cs, src/Nethermind/Nethermind.Blockchain.Test/Timeout.cs, src/Nethermind/Nethermind.Core.Test/TestMemColumnDb.cs, src/Nethermind/Nethermind.Core.Test/TestMemDb.cs, src/Nethermind/Nethermind.Db.Rocks/ColumnDb.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Rpc/RpcColumnsDb.cs, src/Nethermind/Nethermind.Db.Rpc/RpcDb.cs, src/Nethermind/Nethermind.Db/CompressingDb.cs, src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs, src/Nethermind/Nethermind.Db/IDb.cs, src/Nethermind/Nethermind.Db/MemColumnsDb.cs, src/Nethermind/Nethermind.Db/MemDb.cs, src/Nethermind/Nethermind.Db/NullDb.cs, src/Nethermind/Nethermind.Db/ReadOnlyColumnsDb.cs, src/Nethermind/Nethermind.Db/ReadOnlyDb.cs, src/Nethermind/Nethermind.Db/SimpleFilePublicKeyDb.cs, src/Nethermind/Nethermind.Init/InitializeStateDb.cs, src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie/INodeStorage.cs, src/Nethermind/Nethermind.Trie/NodeStorage.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs
- Attempts to make writes more reliable.
- Calls FlushWAl on `Flush()`. This ensure that WAL is written to storage, which normally does not happen as it only is written to OS cache until the OS decided to do so.
- This is the default rockdb behaviour and means that a crash of the program is recoverable but not a crash of the whole system.
- This change ensure that the writes is recoverable in the event of a system crash. Or something unexpected happens in the OS.
- Also add flush (but only WAL as memtable flush can run in background safely) to persist commit set in triestore. This ensure no funny business going on with missing writes. This adds about 5-10 percent to the pruning time unfortunately.
- Also change write buffer recommendation to increase write buffer size instead of write …
=> Feature/FlushWAL on flush.

src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetBlobsHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/Metrics.cs
- adding metrics about `engine_getBlobsV1` - `NumberOfRequestedBlobs` and `NumberOfSentBlobs`
Already added to grafana
=> Add metrics for `engine_getBlobsV1`

.github/workflows/sync-supported-chains.yml
Simple change - idea slightly changed so to reduce costs tests on other repo will be executed with cron for master and on commit on release.
cron to be decided but most probably every second or third day
=> Do not trigger tests on master push

Dockerfile, Dockerfile.chiseled, Dockerfile.diag
Removed the redundant `$TARGETPLATFORM` to silence the `RedundantTargetPlatform` warning.
=> Remove the redundant target platform

src/Nethermind/Nethermind.Core/Crypto/Keccak.cs, src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs
- Vectorized Xor to state
- Removed additional temp stackalloc array + copy
- Simplified
- Fast copy to output for 256 and 512 bit sizes
=> Vectorize Keccak state copy, remove temp array use

src/Nethermind/Nethermind.Api/IApiWithStores.cs, src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.Blockchain.Test/Blocks/BadBlockStoreTests.cs, src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Blockchain/Blocks/BadBlockStore.cs, src/Nethermind/Nethermind.Blockchain/Blocks/BlockStore.cs, src/Nethermind/Nethermind.Blockchain/Blocks/IBadBlockStore.cs, src/Nethermind/Nethermind.Blockchain/Blocks/IBlockStore.cs, src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Builders/BlockTreeBuilder.cs, src/Nethermind/Nethermind.Db/MemDb.cs, src/Nethermind/Nethermind.Facade/Simulate/SimulateDictionaryBlockStore.cs, src/Nethermind/Nethermind.Facade/Simulate/SimulateReadOnlyBlocksProcessingEnvFactory.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockTree.cs, src/Nethermind/Nethermind.JsonRpc.Benchmark/EthModuleBenchmarks.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugModuleFactory.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs
- Extract `IBadBlockStore` from `IBlockStore`.
- Otherwise things will get confusing with a different/multiple format for block storage.
- Tested along with #7665 .
- Almost made a `KV<T>` but thought.. nah.
=> Refactor/Separate block store and Bad block store

src/Nethermind/Nethermind.Core.Test/Crypto/BlsSignerTests.cs, src/Nethermind/Nethermind.Crypto/BlsSigner.cs
- Implement BLS aggregate signatures
=> BLS aggregate signatures

src/Nethermind/Nethermind.Consensus.Clique/CliqueRpcModule.cs, src/Nethermind/Nethermind.Consensus.Clique/ICliqueRpcModule.cs, src/Nethermind/Nethermind.Consensus.Clique/Snapshot.cs, src/Nethermind/Nethermind.Consensus.Clique/Tally.cs
- Allow `clique_getSnapshot` retrieves a snapshot of all clique state at a given block (default: latest block)
- Add tally in `clique_getSnapshot` response
Follow https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-clique#clique-getsnapshot
=> Correct clique snapshot rpc api

src/Nethermind/Nethermind.JsonRpc.Test/Data/SerializationTestBase.cs, src/Nethermind/Nethermind.Serialization.Json/EthereumJsonSerializer.cs
Fixes `+` being serialized as `\u002B` in JSON responses to make it consistent with other clients.
=> Fix `+` serialization in JSON RPC

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/FullInfoReceiptFinder.cs, src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptFinder.cs, src/Nethermind/Nethermind.Blockchain/Receipts/IReceiptStorage.cs, src/Nethermind/Nethermind.Blockchain/Receipts/InMemoryReceiptStorage.cs, src/Nethermind/Nethermind.Blockchain/Receipts/NullReceiptStorage.cs, src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/Migrations/ReceiptMigrationTests.cs
- On Get() add option to not recover sender
- This improve era export throughput by 4x.
- On Insert() add option to specify write flags.
- On era export wal writes can reach 150 MBps.
=> Receipts: Add option to not recover sender and write flags

src/Nethermind/Nethermind.Crypto/BlsSigner.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterBlockHandlerTests.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterCryptoTests.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterValidatorRegistryTests.cs, src/Nethermind/Nethermind.Shutter/Config/IShutterConfig.cs, src/Nethermind/Nethermind.Shutter/Config/ShutterConfig.cs, src/Nethermind/Nethermind.Shutter/Config/ShutterValidatorsInfo.cs, src/Nethermind/Nethermind.Shutter/Contracts/ValidatorRegistryContract.cs, src/Nethermind/Nethermind.Shutter/ShutterCrypto.cs, src/Nethermind/Nethermind.Shutter/ShutterPlugin.cs
- Implements V1 of validator registry spec (https://github.com/gnosischain/specs/pull/53)
- Refactor validator registry contact
- Add tests for validator registration check
=> Shutter: validator registry V1

src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerModuleTests.cs, src/Nethermind/Nethermind.Trie/TrieStatsCollector.cs
- Converst TrieStatCollector to contextual tree visitor
- Log path, storage and hash of missing nodes.
- Tested manually
=> Log missing node

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- `block.Header.GasBeneficiary` can be `null` handle this situation
=> Fix null ref in processing stats

.github/workflows/sync-supported-chains.yml, scripts/waitForSync.py
Fix scenario where nethermind stops before capturing extra logs
=> [Tests] Fix scenario where nethermind stops before capturing extra logs - convert script to Python

src/Nethermind/Nethermind.Shutter/Config/IShutterConfig.cs, src/Nethermind/Nethermind.Shutter/Config/ShutterConfig.cs, src/Nethermind/Nethermind.Shutter/ShutterP2P.cs
- Move disconnection log timeout to config
- Increase default to 20 minutes to decrease false positives
=> Shutter: refactor & increase disconnection log timeout

src/Nethermind/Nethermind.Runner/JsonRpc/JsonRpcIpcRunner.cs
Replaced the obsolete `Socket.BeginAccept/EndAccept` with `Socket.AcceptAsync` in `JsonRpcIpcRunner`.
Tested manually as well.
=> Replace `IAsyncResult` pattern in IPC runner

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
- If request is coming from localhost don't use response compression as is both no lag in network or bandwidth issues and it allocates a lot (though native). Using compression also makes more work for both EL & CL that can be skipped
=> Switch off Response Compression for loopback

scripts/syncSettings.py
- Default `totalDifficulty` to 0 when fetching Fast Sync settings
Tested by running our Python script: https://github.com/NethermindEth/nethermind/blob/42a603b49aa7cc975d744daab7e8e8b547b109d9/scripts/syncSettings.py
The `totalDifficulty` field of a block is no longer required by the ETH JSON-RPC spec given the transition to PoS, and we can safely default it to `0` when it's not present (see https://github.com/ethereum/execution-apis/pull/570).
=> Default `totalDifficulty` to 0 when fetching Fast Sync settings

src/Nethermind/Nethermind.Api/Extensions/PluginLoader.cs, src/Nethermind/Nethermind.Runner/Program.cs
- Added backward compatibility for uncommon use cases specifying the `.cfg` extension in the `-c` option. For instance, `-c mainnet.cfg` instead of `-c mainnet`. In this case, Nethermind will handle it with a warning not to use it.
- Added warnings for deprecated command line options.
- Fixed log levels of plugin loader from "warn" to "info".
To be added later.
=> Support the deprecated `.cfg` extension in `-c` option

src/Nethermind/Nethermind.Runner/configs/base-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/base-sepolia_archive.json, src/Nethermind/Nethermind.Runner/configs/op-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/op-sepolia_archive.json
Networking was disabled on archive nodes which is invalid.
=> Enable Networking on OP/Base archive nodes

src/Nethermind/Nethermind.Taiko/TaikoPlugin.cs
- Enables snap sync after single fcu
=> Allow bh sync instantly; use unsafe updater with taiko

src/Nethermind/Nethermind.Blockchain/BeaconBlockRoot/BeaconBlockRootHandler.cs, src/Nethermind/Nethermind.Blockchain/BeaconBlockRoot/IBeaconBlockRootHandler.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/IBlockCachePreWarmer.cs, src/Nethermind/Nethermind.Core/Eip2930/IHasAccessList.cs
- Getting BeaconBlockRootHandler AccessList initializes the rlp cache; move it inside the prewarmer rather than outside otherwise causes "Caches Rlp are not empty. Clearing them" warning.
=> Only initialize cache inside prewarmer

.github/workflows/sync-supported-chains.yml, scripts/waitForSync.py, scripts/workflow_config/sync_testnets_matrix.json
- Added taiko-mainnet and taiko-holesky to sync of supported chains workflow
=> Add taiko setup to sync chains workflow

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
- Only write one log line per invalid block, rather than two
Before
After
=> Don't double log invalid blocks

src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs
- Fix random invalid block at startup due to initialize precompile not completed during blocktreereview.
- Reliably reproducable by adding a `Task.Delay` in `InitializePrecomple`.
- Tested manually
=> Fix random invalid block at startup

src/Nethermind/Chains/taiko-mainnet.json, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
- Don't start snap sync unless it's near the tip enough
Otherwise the following part of of `ShouldBeInStateSyncMode` may be always true
```
bool stateNotDownloadedYet = (best.TargetBlock - best.State > FastSyncLag ||
best.Header > best.State && best.Header > best.Block);
```
=> Don't start snap sync unless it's near the tip enough

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Serialization.Json/EthereumJsonSerializer.cs, src/Nethermind/Nethermind.Serialization.Json/IJsonSerializer.cs, src/Nethermind/Nethermind.Serialization.Json/StreamPipeWriter.cs
- Use the new async Json Pipeline overloads introduced in .NET 9.0 https://github.com/dotnet/runtime/pull/101461 to respond better to back pressure on the Json response.
=> Use new Json Pipeline overloads

src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
- Wrapping a `ConcurrentQueue` in a `BlockingCollection` burns a ton of CPU spinning; whereas its a pattern ideally suited to `Channel`s; and using true `async`
=>  SyncPeerPool to Channels

src/Nethermind/Nethermind.Core/Caching/ClockCache.cs
- Reduce objects used in ClockCache. Comes at the cost of a double ConcurrentDictionary access when changing the value under a key, however saves about ~2M objects (and GC is object count dependent)
=> Reduce objects in ClockCache

src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs
- Wrapping a `ConcurrentQueue` in a `BlockingCollection` burns a ton of CPU spinning; whereas its a pattern ideally suited to `Channel`s; and using true `async`
=> CliqueBlockProducer to Channels

src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs
- Clear object references in ArrayPoolList before returning to pool; otherwise can inadvertently extend object lifetime from reference from array in pool still pointing at large object
=> GC: Clear references in ArrayPoolList before returning to pool

src/Nethermind/Nethermind.Benchmark.Runner/Program.cs, src/Nethermind/Nethermind.Benchmark/Core/ParallelBenchmark.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/RecoverSignature.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Core/Threading/ParallelUnbalancedWork.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
- Added the `ParallelUnbalancedWork` class to efficiently execute parallel loops, handling unbalanced workloads.
- Implemented static For methods to support parallel execution with and without thread-local data, including initialization and finalization functions.
- Utilized thread pooling and a shared counter `SharedCounter` to distribute iterations among threads dynamically.
- Aimed to optimize performance in scenarios where the workload per iteration is uneven, ensuring better resource utilization and reduced execution time; rather than the main thread `.Wait`ing for background threads to complete
- Less allocations than `Parallel.For`
| Method             | Mean     | Error    | StdDev   | Ratio | Allocated | Alloc Ratio |
|------------------- …
=> ParallelUnbalancedWork for efficient unbalanced parallel loops

src/Nethermind/Nethermind.Hive/HivePlugin.cs, src/Nethermind/Nethermind.TxPool/ITxPool.cs, src/Nethermind/Nethermind.TxPool/NullTxPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- Allow Hive tests to send tx when not "synced"
=> Allow hive to submit tx when not synced

src/Nethermind/Nethermind.Runner/configs/base-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/base-sepolia_archive.json, src/Nethermind/Nethermind.Runner/configs/op-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/op-sepolia_archive.json
Add DiscV5 support for archive op/base nodes.
=> Add missing Discv5 support for archive op/base nodes

src/Nethermind/Nethermind.Blockchain/BlockTree.cs
- Remove allocator workaround on windows introduced by https://github.com/NethermindEth/nethermind/pull/6890 and resolved by https://github.com/NethermindEth/nethermind/pull/7418
=> Remove resolved Windows workaround

src/Nethermind/Directory.Build.props
When I checkout old commit, .net version was 6, but it used language version newest which was incompatible with it. This prevents those problems in the future.
=> Hardcode C# version

src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs, src/Nethermind/Nethermind.Runner/configs/holesky.json, src/Nethermind/Nethermind.Runner/configs/holesky_archive.json, src/Nethermind/Nethermind.Runner/configs/mainnet.json, src/Nethermind/Nethermind.Runner/configs/mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/mekong.json, src/Nethermind/Nethermind.Runner/configs/mekong_archive.json, src/Nethermind/Nethermind.Runner/configs/sepolia.json, src/Nethermind/Nethermind.Runner/configs/sepolia_archive.json
- 36M is the current safe limit for all participants pre-Pectra (EIP-7623) and taking into account an active propagation size limit bug in CL clients.
See also: https://ethresear.ch/t/on-increasing-the-block-gas-limit-technical-considerations-path-forward/21225
Also being done by Erigon: https://github.com/erigontech/erigon/pull/13057
=> Increase default gas limit from 30M to 36M

src/Nethermind/Nethermind.Optimism.Test/RlpDecoderTests.cs, src/Nethermind/Nethermind.Optimism/InitializeBlockchainOptimism.cs, src/Nethermind/Nethermind.Optimism/OptimismLegacyTxDecoder.cs, src/Nethermind/Nethermind.Optimism/OptimismPlugin.cs
Partially addresses #7880
- Ensure post-Bedrock Legacy transactions are validated normally.
- Add tests for RLP decoding the original problematic transaction.
Added a test for the problematic transaction that initially caused the snapshot to not work.
=> Optimism post-bedrock Legacy transaction validation

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
When trying to get a missing storage via RPC call, we not handling the missing node well, so we end up returning exception trace into the RPC response. example call & response:
```
curl 172.234.253.190:8545 \
-X POST \
-H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "method": "eth_getStorageAt", "params": ["0x4d9079bb4165aeb4084c526a32695dcfd2f77381", "0x0000000000000000000000000000000000000000000000000000000000000002", "0xda7485"], "id": 662251708906005292}'
```
Response:
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error","data":"Nethermind.Trie.MissingTrieNodeException: Node 0x7624432bf4159f20277937ee01260167ef485023da8e2814c7e5b6dd2665346f is missing from the DB\n ---> Nethermind.Trie.TrieNodeException: Failed to load root hash …
```
=> [Json RPC] Catch Trie exception on eth_getStorage call

.github/workflows/sync-supported-chains.yml
Currently we trigger sync tests on each master commit.
It has one big advantage - it is very easy to narrow down which exact commit breaks sync.
Also a big disadvantage - if there are known issues or for longer period of time everything works well - it is quite costly.
Noticed recently that during 5 days we managed to merge 25 commits - each triggered 15 machines so in total 375 VMs (various ones).
With this change we will trigger 5 times and total of 75 VMs - 5 times smaller cost and only disadvantage will be that we will know on which exact day something get broken.
For now it feels fine to do sth like this as it will be good enough to analyze if we are in good shape for a release cutoff - on release we will keep it on every new commit appearing.
In future I may adjust that action to …
=> Trigger Sync tests less frequently

src/Nethermind/Nethermind.Logging.NLog/NLogManager.cs, src/Nethermind/Nethermind.Runner/Program.cs
This PR prevents file logging before configuration initialization. The reason is that now Nethermind uses the log rules at the very beginning to avoid having sudden log style changes after loading the configuration. However, on some user configurations, the Nethermind directory is inaccessible for the Nethermind process, and that causes an error.
Another approach might be writing that part of the logs in the user's temp directory. But till now, that logs were missing, and perhaps having them in the file somewhere is not that useful.
=> Prevent file logging before configuration initialization

src/Nethermind/Nethermind.Blockchain/Find/BlockParameter.cs, src/Nethermind/Nethermind.Config/ConfigProvider.cs, src/Nethermind/Nethermind.Config/ConfigSourceHelper.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockExtensions.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcLocalStats.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcUrl.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/TransactionsOption.cs, src/Nethermind/Nethermind.KeyStore/FileKeyStore.cs, src/Nethermind/Nethermind.Logging/PathUtils.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Network.Dns/EnrTreeParser.cs, src/Nethermind/Nethermind.Network/StaticNodes/StaticNodesManager.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
- We aren't doing any culture sensitive tests, so just use Ordinal
=> Use Ordinal rather than InvariantCulture

src/Nethermind/Nethermind.Evm/Precompiles/Bls/PairingCheckPrecompile.cs
- Skip exponentiation if infinity point found
Passes state tests
=> Bls Pairing check optimisation: skip exp for infinity

src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Wrapping a `ConcurrentQueue` in a `BlockingCollection` burns a ton of CPU spinning; whereas its a pattern ideally suited to `Channel`s; and using true `async`
=> TrieStore to Channels

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs
- It seems that rocksdb does not crash when bloom filter config is invalid unlike other parameter key. This can be verified by looking into rockdb log directly which have the filter set  to null.
- With `optimize_filters_for_hits` being true by default, the bloom filter is only set for non-last level of the LSM tree which allow a reads to skip the first two level (in case of state) of LSM while saving disk space by not having it on the last level. With cache/prewarming/compaction priority, its unclear if the impact is significant or not except for maybe state sync.
- Also disable `optimize_filters_for_hits` for block info, headers and code, to make sync faster maybe as it will not hit a lot during sync.
- Checked log manually.
=> Fix missed bloom filter

src/Nethermind/Nethermind.Blockchain.Test/FullPruning/FullPrunerTests.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
- Full pruning tests uses nsubstitue triestore so its not detected at first.
=> Fix full pruning crash on hash.

src/Nethermind/Nethermind.Specs/Forks/18_Prague.cs
p256Verify was removed from Prague, but the precompile is still activated, impacting things such like warm address calculations as well as intentional calls.
- Remove p256verify activation from prague
=> Deactivate RIP-7212 for Prague

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs
- Enable `unordered_write` for statedb which helps increase normal peak write rates during snap sync from about 1.5 million writes per sec to around 2.0 writes per sec.
- Increase write buffer count to the same as cpu cores, which eliminate stall due to waiting for flush at higher speed.
- Slightly increase maximum snap response latency from 3 second to 3.5 second.
- Overall impact is not much as it still take time to reach full speed and need some time to download large storage at the end, and I don't think I have a good enough internet.
- Mainnet sync ok.
=> Slight db adjustment for snap sync perf

src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
- We use 0 in one place and 1 in another; leading to over work
=> Snap: Extension Rlp value index is 1

src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/RegisterAuRaRpcModules.cs, src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugModuleFactory.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergeBlockProcessor.cs, src/Nethermind/Nethermind.Merge.AuRa/InitializationSteps/RegisterAuRaMergeRpcModules.cs, src/Nethermind/Nethermind.Optimism/Rpc/RegisterOptimismRpcModules.cs, src/Nethermind/Nethermind.Taiko/Rpc/RegisterTaikoRpcModules.cs
- Fixes tracing in posdao by using correct `AuraBlockProcessor`
@emlautarom1 @deffrian @flcl42 I see very similar approach in Optimism and Taiko plugins. I think we should unify and refactor it in a way that would allow us to inject `BlockProcessor` type into the traces (`ReadOnlyEnvironment`) better. WDYT?
=> fix tracing posdao blocks

.github/workflows/run-a-single-node-from-branch.yml
Fix oneClick - removed flag assignment
=> Fix oneClick (missing nonvalidator flag)

.github/workflows/sync-supported-chains.yml
Using async methods to have few seconds more for post-action cleanup.
Right now we remove VM early right after sync executed - but because Vm is also a runner we can hit a Collison that VM got removed before action cleanup properly so that's why we send the removal request async now to give it more room for this.
=> Check async killing for less errors on shutdown

src/Nethermind/Nethermind.Optimism.Test/OptimismHeaderValidatorTests.cs, src/Nethermind/Nethermind.Optimism.Test/OptimismPayloadPreparationServiceTests.cs, src/Nethermind/Nethermind.Optimism/OptimismBaseFeeCalculator.cs, src/Nethermind/Nethermind.Optimism/OptimismHeaderValidator.cs, src/Nethermind/Nethermind.Optimism/OptimismPayloadPreparationService.cs, src/Nethermind/Nethermind.Optimism/Rpc/OptimismPayloadAttributes.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
Fixes #7903
- Properly set up the Holocene timestamp.
- Always store EIP-1559 parameters in `ExtraData`, even when dealing with defaults.
- Ensure Block Header hash is recalculated when needed.
- Use defaults from Chainspec rather than from constants.
Unit tests were extended to include cases where `NoTxPool = true` which were missing from the original PR.
This PR fixes several issues that were found after running some integration tests leveraging Kurtosis and the [optimism-package](https://github.com/ethpandaops/optimism-package). More details will be provided as discussion comments.
=> OP Holocene - Proper EIP-1559 parameters handling

src/Nethermind/Nethermind.Evm/Precompiles/Bls/G1MSMPrecompile.cs, src/Nethermind/Nethermind.Evm/Precompiles/Bls/G2MSMPrecompile.cs
- For MSM with a single point use MUL
Covered by state tests
=> Bls precompile: Use MUL for single point MSM

src/Nethermind/Nethermind.Core/Collections/CollectionExtensions.cs
- Currently boxes the array enumerator
=> Reduce enumerator boxing in CollectionExtensions

src/Nethermind/Nethermind.Init/MemoryHintMan.cs, src/Nethermind/Nethermind.TxPool/MemoryAllowance.cs
- From 1 << 19 to 1 << 17
Etherscan shows pending txs are more in that range; and is cache so some mild over processing is ok and we are unlikely to see all the tx available in a block.
Currently we have 2 x 16MB arrays (32MB) for this cache size; this change brings it down to 2 x 4MB (8MB)
https://etherscan.io/chart/pendingtx
=> Shrink tx hash cache from 512k to 130k

src/Nethermind/Nethermind.Serialization.Rlp/ValueRlpStream.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs, src/Nethermind/Nethermind.Trie/TrieNode.cs
- Use Span as backing data type rather than CappedArray (converting in constructor)
=> Change ValueRlpStream to be Span based

src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromStorageRangesTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/SnapServerTest.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/StateSyncPivotTest.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncPivot.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProvider.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
Refactoring Storage Range requests in snap sync to pass through original request object when spliting accounts storage range for parallel execution. Additional change to #7733 
=> StorageRange request refactoring for parallel execution

src/Nethermind/Nethermind.Synchronization.Test/IContainerSynchronizerTestExtensions.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/ProgressTrackerTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/StateSyncPivotTest.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncPivot.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncFeed.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
- Should fix chiado missing state issue when using fuzzer. 
- This happens when the persisted state is equal to the sync pivot which on restart causes the start block to be equal to the persisted state block which is a problem as the block may not get downloaded in non validator mode. This can be seen with this log lone `2024-12-20 12:58:13.4925|INFO|Blockchain.BlockTree|16|Start block loaded from reorg boundary - 13411836 -  ` where the persisted block is null.
- This set the state pivot to be at least sync pivot + 1.
=> Set minimum state pivot to be at least the block after

src/Nethermind/Nethermind.Evm/EvmState.cs, src/Nethermind/Nethermind.Evm/StackPool.cs
- We now have lots of prewarming threads, rpc eth_calls and the main processor isn't thread bonded (is async channels); so we should share the `StackPool` across all threads rather than having multiple `StackPool`s as `ThreadLocal`s
=> Share stack pool between threads

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/SystemTransactionProcessor.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Facade/Simulate/SimulateTransactionProcessor.cs, src/Nethermind/Nethermind.Optimism/OptimismTransactionProcessor.cs, src/Nethermind/Nethermind.Taiko/TaikoTransactionProcessor.cs
To prewarm faster than main thread
- `ExecutionOptions.Warmup` => `ExecutionOptions.SkipValidation`
- `ExecutionOptions.NoValidation` => `ExecutionOptions.SkipValidationAndCommit` (which is  `SkipValidation` | `Commit`)
- Then skip validations based on the `SkipValidation` flag rather than the previous `NoValidation` flag which also needed the tx to `Commit` and wasn't the flag prewarming was using
- Use actual tx don't clone them
- Don't clone block header
Fastest code is the code that doesn't run
=> Reduce parallel prewarming overwork

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Core/Threading/ParallelUnbalancedWork.cs
- When prewarming addresses no state is changed, so the state can be reused for all prewarming that happens on the parallel thread and doesn't need to go via reset and pool.
- Also plumb through CancellationToken to complete early if block finishes before prewarming.
=> Reuse thread state when prewarming addresses in parallel

.github/workflows/codeql.yml
- Updated CodeQL actions from the deprecated v2 to v3 as recommended by GitHub
- Added `security-and-quality` suite
- Added the [newly announced](https://github.blog/security/vulnerability-research/announcing-codeql-community-packs/) community packs for analysis
- Restored action versions over commit hashes as these actions are updated quite often, while the pinned hashes don't allow us to get the latest improvements and security updates for them
- Removed disk space free-up action since disabling redundant submodules makes enough room
=> Update CodeQL actions to v3

src/Nethermind/Nethermind.Evm.Benchmark/EvmBenchmarks.cs, src/Nethermind/Nethermind.Evm.Benchmark/MultipleUnsignedOperations.cs, src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs, src/Nethermind/Nethermind.Evm.Test/EvmStateTests.cs, src/Nethermind/Nethermind.Evm/EvmState.cs, src/Nethermind/Nethermind.Evm/StackAccessTracker.cs, src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Saves 8.6MB of allocations per min; reduces worse case from smart contracts that do huge amounts of calls
- Reduce allocations by pooling `StackAccessTracker` collections
- Reduce allocations by pooling `EvmState`
- EvmState, pass large struct via `in`
- Change `StackAccessTracker` and `EvmState` to file level namespaces 
- Rearranged parameters and assignment order to match layout order
EvmState is a super chonky class and currently allocated for every tx and every internal call (and this is after shrinking `StackAccessTracker`)
```
Type layout for 'EvmState'
Size: 368 bytes. Paddings: 10 bytes (%2 of empty space)
|==================================================================================|
| Object Header (8 bytes)                                                          | …
```
=> Reduce per tx execution allocations

src/Nethermind/Nethermind.Core/Eip2935Constants.cs
Change has not been officially merged yet:
https://github.com/ethereum/EIPs/pull/9144
This change is required for latest EELS though
=> New sys address for eip 2935

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
- Change to skip cloning tx to SystemTransaction in https://github.com/NethermindEth/nethermind/pull/7983 meant it can fail to process the full tx due to sender not having enough balance to send value.
This also uses the `ExecutionOptions` to decide whether to run as low validation system tx
=> Use system processor for SkipValidation txs

src/Nethermind/Chains/op-mainnet.json
- Adds Holocene timestamps for both OP and Base (mainnet) according to https://github.com/ethereum-optimism/superchain-registry/pull/726
We'll see how mainnet transitions on `Thu 09 Jan 2025 18:00:01 UTC`
This config update is required to run OP or Base nodes in mainnet.
I don't know if it's currently possible but operators could potentially pass these timestamps as flags instead of updating Nethermind to a new version which contains this updated config.
=> Add Holocene timestamps for OP and Base (mainnet)

src/Nethermind/Nethermind.Synchronization/Trie/TrieNodeRecovery.cs
- It tries multiple peers and don't need full stack trace; the recovery itself isn't an error
- Also add Timeout exception to the skipped
e.g. it currently outputs:
```
03 Jan 18:56:14 | Missing trie node 0xb99865a61902b36805cd8b8a2525bfdf322c747c78d044be48dc83bbdadabccd, trying to recover from network
03 Jan 18:56:14 | Failed to recover missing trie node
03 Jan 18:56:14 | Missing trie node Account: 13, trying to recover from network
03 Jan 18:56:21 | Processing queue wasn't empty added to queue New Block:  21545884 (0x855b2f...a37d12).
03 Jan 18:56:21 | Received ForkChoice: 21545884 (0x855b2f...a37d12), Safe: 21545855 (0xd0165d...695c63), Finalized: 21545791 (0xd89a89...222316)
03 Jan 18:56:21 | Processing 1 blocks, Request: ForkChoice: 21545884 (0x855b2f...a37d12), Safe: 21545855 …
```
=> Recovering trie node message should be less severe

src/Nethermind/Nethermind.Core.Test/BloomTests.cs, src/Nethermind/Nethermind.Core/Bloom.cs, src/Nethermind/Nethermind.Core/Extensions/SpanExtensions.cs, src/Nethermind/Nethermind.Db/Blooms/BloomStorage.cs
- Drops one object reference per Bloom and inline array is smaller than `byte[]` with one less indirection
=> Back Bloom with inline array rather than byte[]

src/Nethermind/Ethereum.Basic.Test/TransactionTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Consensus/ClefSignerTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Consensus/NullSignerTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Consensus/SignerTests.cs, src/Nethermind/Nethermind.Consensus.Clique/CliqueSealer.cs, src/Nethermind/Nethermind.Core.Test/Crypto/SignatureTests.cs, src/Nethermind/Nethermind.Core/Crypto/Signature.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Core/Transaction.cs, src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/AuthorizationListForRpc.cs, src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/LegacyTransactionForRpc.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcSimulateTestsBase.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Parity/ParityTransaction.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Personal/IPersonalRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Personal/PersonalRpcModule.cs, src/Nethermind/Nethermind.Network.Discovery/Serializers/DiscoveryMsgSerializerBase.cs, src/Nethermind/Nethermind.Serialization.Rlp/Eip7702/AuthorizationTupleDecoder.cs
- Drops one object reference per sig and `Vector512` is smaller than `byte[]` with one less indirection
=> Back signature by Vector512 rather than byte[]

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
- Move prewarming as early as possible in block processing (every little helps)
=> Move prewarming as early as possible

src/Nethermind/Nethermind.Core/Eip2935Constants.cs
- update the ring buffer size for eip-2935  as per https://github.com/ethereum/EIPs/pull/9144
=> update ring buffer size for eip-2935

src/Nethermind/Nethermind.Config.Test/ConfigProvider_FindIncorrectSettings_Tests.cs, src/Nethermind/Nethermind.Config/ConfigSourceHelper.cs, src/Nethermind/Nethermind.Config/EnvConfigSource.cs
Fixes #7956 #4952
- Fixed the bug introduced in #7540 when command line options with empty values of `""` are converted to `null`
- Fixed the handling of empty environment variables not to be treated as undefined _for string types only_
This PR sets command line options and env vars on par as, currently, env vars don't support empty values, treating them as null/unset. However, there are a few things to note:
- .NET handling of environment variables has been changed/improved since .NET 9 with the [support of empty values](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/9.0/empty-env-variable)
- Support of empty env var depends on the environment; I couldn't make them work in PowerShell
- Setting an empty env var doesn't work with `launchSettings.json`
=> Fix empty value handling of configuration options

src/Nethermind/Nethermind.JsonRpc/Modules/Admin/IAdminRpcModule.cs
Reverting removed pruning method removed by mistake in #7962
=> Revert removed admin_prune method in interface

src/Nethermind/Nethermind.Evm/EvmPooledMemory.cs
After further investigation, this will only be relevant at 8.7TGas which is impossible
- fix memory expansion cost to support up to uint.max instead of int.max matching Geth
=> fix memory expansion to support up to uint.max instead of int.max

src/Nethermind/Nethermind.sln
- Reorder `Nethermind.sln` so test projects are in the proper folder
A very small PR that moves a couple of `Test` projects to the appropriate Solution folder, making them part of the `Tests` subfolder so that they're listed alongside other tests suites. This makes them look like the following in the test explorer:
The benefit is that you can now run the entire `Tests` folder without missing any tests.
=> Move `Test` projects to proper solution folder

src/Nethermind/Nethermind.Synchronization.Test/SnapSync/RecreateStateFromAccountRangesTests.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/SnapProviderHelper.cs
`moreChildrenToRight` derivation currently excludes nodes exactly at limit path, which I think should be included. When using `limitHash` other than `ValueKeccak.MaxValue` this may lead to missing nodes during sync.
This should also be aligned with snap serve implementation:
https://github.com/NethermindEth/nethermind/blob/7e0c53cd20e51cc83a8cbddfa51302e495b577f5/src/Nethermind/Nethermind.Trie/RangeQueryVisitor.cs#L180
This change will help to merge this change #7733
Failed scenario on Holesky:
- last path in batch `0x206ef92f1f724813b79366c1d32f79f21e9d6fc3e63ee7dc9bc60178a02329b9`
- limit hash `0x2072ae6853c35cc00b267d072d8e17646d4881488979de114b622413bf369197`
- branch exists at path `206` with child at nibble `f`, child is not present in current batch
- `moreChildrenToRight` is …
=> Change more children derivation on snap sync

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
Fix #6560 
- The tx index is removed on second block after reorg to another second block but the canonical tx is in the first block when going to the second block branch.
- Reproducable with unit tests.
=> Fix missing tx index on reorg

src/Nethermind/Nethermind.JsonRpc/JsonRpcConfigExtension.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/ExecutorBase.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/SimulateTxExecutor.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Trace/TraceRpcModule.cs
When debugging JsonRpc modules, including tests, the default configuration causes a timeout after 20s. This PR proposes to not timeout when a debugger is attached. This is done by providing an extension method for `IJsonRpcConfig` and then using it instead of building `CancellationTokenSource` from the `.Timeout` property. All call-sites that are amendable (no `BoundedModule`) are refactored.
- extraction of a timeout method
=> JsonRpc modules cancellation only on Debugger detached

src/Nethermind/Nethermind.Runner/configs/worldchain-mainnet.json, src/Nethermind/Nethermind.Runner/configs/worldchain-mainnet_archive.json, src/Nethermind/Nethermind.Runner/configs/worldchain-sepolia.json, src/Nethermind/Nethermind.Runner/configs/worldchain-sepolia_archive.json, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/AllocationJson.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/ChainSpecJson.cs
Worldchain support
- Adds worldchain mainnet & sepolia configs
- CodeHash based genesis file
=> Add Worldchain support

src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs
Resolves #8015
- Json Rpc should only be trying to parse requests which are `application/json`
=> Json Rpc should only handle application/json requests

src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncPivot.cs, src/Nethermind/Nethermind.Synchronization/FastSync/TreeSync.cs
- In prod, the sync pivot will simply wait until the chain proceed far enough to continue.
- It seems that in the unit tests, there is a manual force update which hide this issue.
- Reproducable on #8055
=> Fix state pivot update on state sync feed not working

src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
In _executionRequestsProcessor, while executing system transaction, we do WorldState.Commit(SystemTransactionReleaseSpec.Instance). In SystemTransactionReleaseSpec Eip158Enabled=false, so we end up persisting empty accounts created while processing withdrawals.
=> fix zero value withdrawals

src/Nethermind/Nethermind.Evm/Precompiles/AddressExtensions.cs
Two precompiles were removed from EIP2537 here - https://github.com/ethereum/EIPs/pull/8945
=> remove precompiles

src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs, src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs, src/Nethermind/Nethermind.Core.Test/Modules/MainBlockProcessingContext.cs, src/Nethermind/Nethermind.State/IWorldState.cs, src/Nethermind/Nethermind.State/WorldState.cs, src/Nethermind/Nethermind.State/WorldStateMetricsDecorator.cs
- Double check that ethereum tests passed with prewarmer and pruning trie store.
- Aside from needing to explicitly clear cache, seems to work fine.
=> Make sure prewarming and pruning trie store is running on ethereum tests

src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.Core/DisposableStack.cs, src/Nethermind/Nethermind.Init/InitializeStateDb.cs, src/Nethermind/Nethermind.Init/PruningTrieStateFactory.cs, src/Nethermind/Nethermind.Runner/Ethereum/EthereumRunner.cs, src/Nethermind/Nethermind.State.Test/WorldStateManagerTests.cs
- Fix reorg boundary not set on dispose as the reorg boundary setter is dispose before trie store.
- Fortunately, triestore does not remove old keys on dispose so the only issue on restart is long reorg depending on cache size.
- The default pruning cache should limit the reorg to around 300 block so this should not be very notable normally.
- Tested to no longer have very long reorg on start when using large cache.
=> Fix reorg boundary not set on dispose

src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs
#8100 
- StartMonitoring depends on itself
=> Fix StartMonitoring dependencies

.github/workflows/sync-supported-chains.yml
Noticed that we have an issue that when action is triggered via new docker image publish for release branch we still keep using master image for sync tests.
=> Fix case when new release commit pushed but still master used for sync

src/Nethermind/Ethereum.Test.Base/BlockchainTest.cs, src/Nethermind/Ethereum.Test.Base/BlockchainTestBase.cs, src/Nethermind/Ethereum.Test.Base/GeneralStateTest.cs, src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs, src/Nethermind/Nethermind.Test.Runner/BlockchainTestsRunner.cs, src/Nethermind/Nethermind.Test.Runner/Program.cs, src/Nethermind/Nethermind.Test.Runner/Properties/launchSettings.json, src/Nethermind/Nethermind.Test.Runner/StateTestRunner.cs
Currently Nethermind BlockchainTestRunner and StateTestRunner does not support running gnosis tests. These changes supports running gnosis tests
-  add new flag `-g (gnosisTest)` flag to Nethermind.Test.Runner,
- if -g flag exists then `chainId = 100` for gnosis
- add GnosisSpecProvider
=> add Gnosis test runner

src/Nethermind/Nethermind.Evm.Test/EvmPooledMemoryTests.cs, src/Nethermind/Nethermind.Evm/EvmState.cs, src/Nethermind/Nethermind.Evm/Tracing/AlwaysCancelTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/BlockReceiptsTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/CancellationTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/CompositeTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/Debugger/DebugTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/JavaScript/GethLikeJavaScriptTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/FourByte/Native4ByteTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Prestate/NativePrestateTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxMemoryTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/ITxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/NullTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/ParityStyle/ParityLikeTxTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/TxTracer.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs, src/Nethermind/Nethermind.Test.Runner/StateTestTxTracer.cs, src/Nethermind/Nethermind.Test.Runner/StateTxTraceEntry.cs
Add the "section" and "functionDepth" tracing fields to correspond to code section and CALLF depth (respectivly). This required some deep plumbing changes to add the field in the interfaces.
nethermind is being fuzzed via an EOF focused fuzzer. These new fields are needed for the differential fuzzing.
=> Add EOF tracing fields

.github/workflows/sync-supported-chains.yml
- Change op-node version on sync-supported-chains github actions from latest to 1.10.3
=> Change op-node to 1.10.3 from latest on actions

src/Nethermind/Nethermind.Core/ChainLevelInfo.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs, src/Nethermind/Nethermind.Serialization.Rlp/HeaderDecoder.cs
Fixes #8063
Blocks downloader requests next headers, next headers are incorrect, containing headers from different forks:
(forkB is main fork)
N-2: forkB
N-1: forkA
N: forkB
which leads to missing parent state when we process block N. 
Happens when:
forkA FCU N-1
beacon header downloaded in sync for forkB N-1
forkB NP N-1
forkB NP N
forkB FCU **N** (but no forkB FCU for N-1)
- Prioritize recently retrieved beacon chain header over previous one
=> Fix wrong parent block due to reorg

src/Nethermind/Nethermind.Evm.Test/BlsG2AddPrecompileTests.cs
Fixed in https://github.com/NethermindEth/nethermind/pull/8138
- Added regression test
=> Regression test for BLS precompile caching consensus issue

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
- Create a `IReadOnlyTxProcessingScope` per prewarmer thread rather than per txn. The scope creates a `VirtualMachine`, `TransactionProcessor`, etc
=> Less Prewarmer work per tx (share scope for thread)

src/Nethermind/Nethermind.Evm/BlobGasCalculator.cs
- Skip expensive 256bit multiplication when factor is 1 (which it is currently)
- Use `ulong` iterator rather than `UInt256` iterator which has much more expensive increments
- Use `.IsZero` rather than `> 0` which is faster as it just vector checks everything is 0
=> Optimize TryCalculateFeePerBlobGas

src/Nethermind/Nethermind.Flashbots/Data/BidTrace.cs, src/Nethermind/Nethermind.Flashbots/Data/BuilderBlockValidationRequest.cs, src/Nethermind/Nethermind.Flashbots/Data/Message.cs, src/Nethermind/Nethermind.Flashbots/Data/RBuilderBlockValidationRequest.cs, src/Nethermind/Nethermind.Flashbots/Data/RExecutionPayloadV3.cs, src/Nethermind/Nethermind.Flashbots/Data/SubmitBlockRequest.cs, src/Nethermind/Nethermind.Flashbots/Modules/Flashbots/FlashbotsRpcModule.cs, src/Nethermind/Nethermind.Flashbots/Modules/Flashbots/IFlashbotsRpcModule.cs, src/Nethermind/Nethermind.Runner/configs/holesky.json
rBuilder payload has slightly different structure than geth builder
=> Add endpoint to support rBuilder payload

src/Nethermind/Nethermind.AuRa.Test/Contract/TxPriorityContractTests.cs, src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingEnv.cs, src/Nethermind/Nethermind.Consensus/Processing/OverridableTxProcessingScope.cs, src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.Evm/StateOverridesExtensions.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTests.cs
Fixes #8130 and #7945
- Doesn't bother trying to revert state root on json rpc, resets environment before accessing it
`eth_call`/`eth_estimateGas`/`eth_simulate`/`debug_traceXXX`/`trace_` fuzzing with state overrides
=> Fix state override accessing state

.github/workflows/update-superchain.yml
- Fix the workflow script to properly copy the autogenerated files
The original script didn't include the required `-r` flag to copy the generated files.
=> Fix workflow flags for "Update OP Superchain chains"

.github/workflows/update-superchain.yml
- Adjust order of steps in workflow.
I wish we could just run the workflows locally.
The workflow had the wrong steps order thus it was removing fast sync settings (Pivot number, hash, etc.) from officially supported chains (OP, Base, Worldchain).
=> Fix Fast Sync settings in "Update OP Superchain chains" worflow

src/Nethermind/Ethereum.Test.Base/JsonToEthereumTest.cs, src/Nethermind/Nethermind.Evm/EvmObjectFormat/EofValidationStrategy.cs, src/Nethermind/Nethermind.Evm/EvmObjectFormat/Handlers/EofV1.cs
* JUMPF is only returning when the target section is returning
* "short data" containers are valid when inside an inticode container. Tweak needed flags to distinguish between a top level runtime container and an embeded container, and adjust "long data" check.
=> Address eof-devnet-0 valdation errors

src/Nethermind/Nethermind.Consensus/Processing/ReadOnlyTxProcessingEnv.cs, src/Nethermind/Nethermind.State/IWorldStateManager.cs, src/Nethermind/Nethermind.State/WorldStateManager.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
- Fix persist cache remove unresolved node at start of full pruning likely due to some kind of caching at world state level which causes the storage root to load but never used and therefore resolved.
- Check if nodetype is unknown.
- Split `CreateResettableWorldState` for prewarming to its own method.
- Tested to work together with #8221 . #8221 have a fix for when storage root is missed under high thread count use.
=> Fix persist cache remove node

src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/BlobTransactionForRpc.cs, src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/SetCodeTransactionForRpc.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcTransaction/BlobTransactionForRpcTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcTransaction/SetCodeTransactionForRpcTests.cs
Fixes #8230 introduced in #7483
- Reintroduce missing 4844 RPC fields (GasPrice and V)
Potentially hotfix release?
=> Reintroduce missing 4844 RPC fields (GasPrice and V)

src/Nethermind/Nethermind.Config/BlocksConfig.cs, src/Nethermind/Nethermind.Config/IBlocksConfig.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Caching/ClockKeyCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Caching/LruKeyCacheTests.cs, src/Nethermind/Nethermind.Core.Test/Modules/TestEnvironmentModule.cs, src/Nethermind/Nethermind.Core/Cpu/RuntimeInformation.cs, src/Nethermind/Nethermind.Flashbots/Handlers/ValidateBuilderSubmissionHandler.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.Merge.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/SnapProtocolTests/StateSyncDispatcherTester.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastSync/StateSyncFeedTestsBase.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SynchronizerTests.cs, src/Nethermind/Nethermind.Synchronization.Test/TestSyncConfig.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/SyncDispatcher.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerAllocation.cs, src/Nethermind/Nethermind.Trie.Test/Pruning/TreeStoreTests.cs, src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
- Unit tests slows down with high core count machine which seems to be due to the spawing of tasks.
- This PR limits those tasks creation.
- Add config to limit prewarming task count.
- Reduce default limit of concurrent task for dispatcher in tests.
- Disable `AllowSynchronousContinuations` as it randomly deadlock tests.
- Seems to be faster but still not passing completely.
=> Limit task count in tests

src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
- If an account's storage is empty; then we can skip db reads for all slots for `SLOAD` and `SSTORE` (extending the self-destruct approach)
- New contract creates, set code, etc
=> Skip SLOAD and SSTORE lookups on empty storage

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
Resolves #8163
- Pass the block stats via params rather than reading them from fields which may have been overwritten by time of log
- Also add blob count when chain supports blobs
=> Capture block stats per log (no block stats bleed)

src/Nethermind/Nethermind.Synchronization.Test/E2ESyncTests.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorFastSyncTests.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/MultiSyncModeSelectorTests.Scenario.cs, src/Nethermind/Nethermind.Synchronization.Test/SnapSync/StateSyncPivotTest.cs, src/Nethermind/Nethermind.Synchronization/Blocks/FastSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/FastSync/StateSyncPivot.cs, src/Nethermind/Nethermind.Synchronization/ParallelSync/MultiSyncModeSelector.cs
- Combine fast sync lag constant with `syncConfig.StateMinDistanceFromHead` which make fast sync lag configurable also.
- Useful in integration tests.
=> Configurable fast sync lag

src/Nethermind/Nethermind.Runner/configs/holesky.json
Removes invalid configuration (typo) from Holesky config.
Also seems like it should not be enabled by default at all in this config.
Introduced in #7335
=> Remove Flashbots from Holesky config

src/Nethermind/Directory.Build.props, src/Nethermind/Nethermind.Db.Test/DbMetricsUpdaterTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.Runner/Nethermind.Runner.csproj, tools/Directory.Build.props
Disabled the satellite resource languages as redundant. _This reduces the final package size and the number of assemblies. The following directories are gone_; thus, the output is now less cluttered:
=> Disable satellite resources

src/Nethermind/Nethermind.Core.Test/Collections/RefList16Tests.cs, src/Nethermind/Nethermind.Core/Collections/RefList16.cs, src/Nethermind/Nethermind.Trie/TrieNode.Visitor.cs
- Improved tree visitor parallelism by estimating the size of subtree and not spawning new task if the size is lower than a set threshold.
- Use `RefArray16` a refstruct instead of arraypoollist.
- Before, After. Nodes read per sec during verify trie on mainnet. Memory limited to 64GB via systemd-run.
- Single thread does not change much. Perhaps cpu utilization is improved but throughput remain.
=> Improved tree visitor parallelism and efficiency.

src/Nethermind/Nethermind.Core/ExecutionRequest/ExecutionRequestExtensions.cs, src/Nethermind/Nethermind.Core/Resettables/RecyclableStream.cs
- Use RecyclableMemoryStream instead of ArrayPoolList<byte> to avoid ToArray when computing hash
=> Request Hash calculation no allocations

src/Nethermind/Nethermind.Evm/Precompiles/Bls/PairingCheckPrecompile.cs
- Instead of returning 1 when infinity point is encountered, should just skip this point
- note: this is preemptive fix, the original spec may be correct
=> BLS fix: don't return 1 because of infinity point

src/Nethermind/Nethermind.Cli/Modules/AdminCliModule.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/AdminModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/AdminRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/IAdminRpcModule.cs
Related #7811
- Added interface method in IAdminRpcModule
- Implemented admin_removeTrustedPeer in AdminRpcModule
- Added unit test for the new method
- Added corresponding CLI function in AdminCliModule
=> Add admin_removeTrustedPeer RPC endpoint

src/Nethermind/Ethereum.Test.Base/ChainUtils.cs, src/Nethermind/Ethereum.Test.Base/GeneralTestBase.cs, src/Nethermind/Nethermind.Specs/GnosisForks/12_LondonGnosis.cs, src/Nethermind/Nethermind.Specs/GnosisForks/17_CancunGnosis.cs, src/Nethermind/Nethermind.Specs/GnosisForks/18_PragueGnosis.cs
Before GeneralTestBase was using TxValidator for Mainnet, which is incorrect for Gnosis
- fix GeneralTestBase: choose appropriate chainId for TxValidator
- Add FeeCollector to PragueGnosis
=> fix txValidator for State test, fix PragueGnosis spec

src/Nethermind/Nethermind.Consensus.Test/ExecutionRequestProcessorTests.cs, src/Nethermind/Nethermind.Consensus/ExecutionRequests/ExecutionRequestProcessor.cs
This resolves a situation on the Sepolia testnet, which has a different deposit contract. The contract on that network emits two kinds of logs, instead of only deposit events like the deposit contract on mainnet. So we need to skip events with mismatched topics.
=> match on deposit contract log topic v2

src/Nethermind/Nethermind.Db.Rocks/Config/DbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/IDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Runner.Test/EthereumRunnerTests.cs
- Fix `EthereumRunnerTest` randomly fail on rocksdb dispose.
- Add option to disable flush on exit.
=> Fix runner test

src/Nethermind/Nethermind.Merge.Plugin.Test/BaseEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.HelperFunctions.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V1.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/TestBlockProcessorInterceptor.Setup.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterBlockHandlerTests.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterIntegrationTests.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterTestsCommon.cs, src/Nethermind/Nethermind.Shutter.Test/ShutterTxLoaderTests.cs
- Some shutter test subclasses `EngineModuleTests` without actually changing any behaviour. It just need the rpc factory method and some util function. This causes it to execute some engine module tests also.
- This PR moves those util class ot `BaseEngineModuleTests` so that shutter tests does not execute the engine tests again.
=> fix shutter test execute engine tests

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
- CI seems to catch exception log and fail. This is the log:
```
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Nethermind.Db.Rocks.DbOnTheRocks.IteratorManager.ManagedIterators.ClearIterators() in /_/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 1694
at Nethermind.Db.Rocks.DbOnTheRocks.IteratorManager.OnTimer(Object state) in /_/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 1610
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at …
```
=> Fix random runner test failure in CI

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
Fixes #8256
Not tested, not merge, requires adding tests, draft for now
=> A potential fix to raw typed tx encoding

src/Nethermind/Nethermind.Core/Extensions/DisposableExtensions.cs, src/Nethermind/Nethermind.Evm.Test/Tracing/GethLikeCallTracerTests.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/JavaScript/GethLikeBlockJavaScriptTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Call/NativeCallTracerCallFrame.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeBlockFileTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeBlockMemoryTracer.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/GethLikeTxTraceCollection.cs, src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/RpcModuleProviderTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/TestRpcModuleProvider.cs, src/Nethermind/Nethermind.JsonRpc.Test/RpcTest.cs, src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcConfig.cs, src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.V3.cs, src/Nethermind/Nethermind.Runner.Test/EthereumRunnerTests.cs, src/Nethermind/Nethermind.Runner/Ethereum/Api/ApiBuilder.cs, src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs, src/Nethermind/Nethermind.Serialization.Json/EthereumJsonSerializer.cs
Resolves #8295
- Make EthereumJsonSerializer MaxDepth configurable. 
- Increase default to 128.
- Fixes some ArrayPoolList not-disposed issues in tracing
Some traces can get very deep, deeper than 64. For edge cases even 128 might be to low, but lets keep it sane for now. It is configurable if needs to be higher.
=> Make EthereumJsonSerializer MaxDepth configurable

src/Nethermind/Directory.Packages.props
Fixes #8336 
- Bump BLS bindings version. New version is compiled with portable flag so should not crash on old CPUs
=> Fix BLS on old CPUs

src/Nethermind/Nethermind.Flashbots/Handlers/ValidateBuilderSubmissionHandler.cs
The arguments for `KzgPolynomialCommitments.AreProofsValid` where not in correct order.
=> Kzg correct arg ordering

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/Processing/IReadOnlyTxProcessingEnvFactory.cs, src/Nethermind/Nethermind.Consensus/Processing/ReadOnlyTxProcessingEnvFactory.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Flashbots.Test/FlashbotsModuleTests.Setup.cs, src/Nethermind/Nethermind.Flashbots/Flashbots.cs, src/Nethermind/Nethermind.Flashbots/Handlers/ValidateBuilderSubmissionHandler.cs, src/Nethermind/Nethermind.Flashbots/Modules/Flashbots/FlashbotsRpcModuleFactory.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs
- Fix flashbots's rpc module prewarmer not wired correctly. Implicitly the read only processing env factory should have the world state to warm up.
- Fix block processor re-created on each call, which make sense for some application, but generally we keep the instance and recycle it.
- Create `ReadOnlyProcessingEnvFactory.CreateForWarmingUp` which require passing the world state to warm up.
- Prewarmer now need the world state to warm up passed in its constructor to make it clear which world state it is warming up instead of implicitly in the instance of `ReadOnlyProcessingEnvFactory`.
=> Fix flashbots prewarmer not wired correctly

src/Nethermind/Nethermind.Consensus/Processing/BlockExtensions.cs, src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs, src/Nethermind/Nethermind.Consensus/Producers/IBlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Core/Address.cs, src/Nethermind/Nethermind.Core/Block.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.DelayBlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.MockBlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.StoringBlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContext.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/Boost/BoostBlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/NoBlockImprovementContextFactory.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs, src/Nethermind/Nethermind.Optimism/OptimismPayloadPreparationService.cs, src/Nethermind/Nethermind.Shutter/ShutterBlockImprovementContext.cs
The less controversial changes from https://github.com/NethermindEth/nethermind/pull/7640
- Improve the block production logs to match rest of logs 
(Image also highlighting PR built block vs released Nethermind built block)
- Use previous block production time to inform next, rather than set value (500ms) for remaining time
- Build more frequently (500ms rather than 3000ms)
- Only accept improved block as replacement when it actually improved
- Use shortened address when used instead of extra data (so doesn't spill the logs to new line)
=> Build more profitable blocks and improve production logs

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Removes the try/catch from `ExecuteEvmCall`. All EvmException OverFlowExceptions should be caught by the inner try/catch inside the `Run` method.
=> Small refactor to make ExecuteEvmCall error handling clearer.

src/Nethermind/Nethermind.Db.Test/MemDbTests.cs, src/Nethermind/Nethermind.Db/MemDb.cs
- `MemDb` now respects ordering parameter in `GetAll`
=> Fix: order memdb

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
- We have this check right above: https://github.com/NethermindEth/nethermind/pull/8340/files#diff-b8ea3d5dd4a8bedda3ec0900ae86bf6c3352c28fcec738e3064511be8c9c52e7R279-R283
=> Remove redundant `authorizationTuple.Nonce == ulong.MaxValue` check

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Removes not needed check for `AuthorizationTuple`. Chain id cannot be embedded in V since EIP-155 does not apply to non-tx signatures, and we already have a check for V == 0 || V == 1 in https://github.com/NethermindEth/nethermind/blob/3fa523dab07944f62b79142259a592759579725a/src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs?plain=1#L280C1-L280C88.
Verified with Geth as having the same check in:
https://github.com/ethereum/go-ethereum/blob/master/core/types/tx_setcode.go#L119
=> Remove redundant check for delegations

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.TxPool/Filters/MalformedTxFilter.cs
- adding message with exact error to `AcceptTxResult.Invalid`
so there will be e.g.:
`Invalid, BlobTxGasLimitExceeded: Transaction's totalDataGas=393216 exceeded MaxBlobGas per transaction=262144.`
instead of just:
`Invalid`
We need to ensure that it will be compatible with our RPC users as error code will be changed (extended) now.
=> Add message with exact error to `AcceptTxResult.Invalid`

src/Nethermind/Nethermind.Config/NetworkNode.cs, src/Nethermind/Nethermind.Network.Discovery.Test/DiscoveryManagerTests.cs, src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs, src/Nethermind/Nethermind.Network.Discovery.Test/NodeLifecycleManagerTests.cs, src/Nethermind/Nethermind.Network.Discovery.Test/NodesLocatorTests.cs, src/Nethermind/Nethermind.Network.Discovery/CompositeDiscoveryApp.cs, src/Nethermind/Nethermind.Network.Discovery/DiscoveryApp.cs, src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs, src/Nethermind/Nethermind.Network.Discovery/IDiscoveryManager.cs, src/Nethermind/Nethermind.Network.Discovery/Lifecycle/INodeLifecycleManagerFactory.cs, src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManager.cs, src/Nethermind/Nethermind.Network.Discovery/Lifecycle/NodeLifecycleManagerFactory.cs
Resolves #2157
Simpler https://github.com/NethermindEth/nethermind/pull/7026
- Disfavour nodes with same ip addresses of nodes tried recently
- Don't connect to self even with external ip
=> Peers ignore self and recent ips

src/Nethermind/Nethermind.Merge.Plugin/Data/ExecutionPayload.cs, src/Nethermind/Nethermind.Merge.Plugin/Data/IExecutionPayloadParams.cs, src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs, src/Nethermind/Nethermind.Trie/TrackingCappedArrayPool.cs
- Only lookup the TxDecoder once per block, rather than for each tx
- Optimize ExecutionPayloadParams.ValidateParams
- Devirtualize shared array pool
Before
After
=> Lookup TxDecoder once per block

src/Nethermind/Nethermind.Evm.Test/TransactionProcessorTests.cs
- Regression test for bug [fixed](https://github.com/NethermindEth/nethermind/pull/7406/files#diff-b8ea3d5dd4a8bedda3ec0900ae86bf6c3352c28fcec738e3064511be8c9c52e7R179) in #7406. Before this change `CallAndRestore` would throw exception due to underflow error when decrementing nonce caused by prewarm cache
=> Add prewarm cache to TransactionProcessorTests

src/Nethermind/Nethermind.HealthChecks/HealthChecksPlugin.cs
Contributes to #7575
- Clarify that the missing messages are ForkChoice, as may be receiving blocks, which makes this message confusingly ambiguous
=> Clarify missing messages are Fork Choice

src/Nethermind/Nethermind.Core/Crypto/Hash256.cs, src/Nethermind/Nethermind.Trie/Pruning/TrieStoreDirtyNodesCache.cs
- Split into two methods, and outer one with `using` and one with hot loop. The presence of `catch`/`finally` alters the quality of surrounding code forcing more to be pushed to stack rather than registers (so it has persistence from a throw). This is worse for methods with loops.
- Move (not hot path) throws and logging to local functions, so their asm doesn't form part of loop code
- Refactor 3 occurrences of same code to `RemoveNodeFromCache` local function
- Pass `Key` into `CanDelete` so `ValueKeccak` doesn't need to allocate via `.ToCommitment()`
It still ends up with a try/finally from the foreach on an interface enumerator; but doesn't have a double try/finally
Before `PruneCache`
```asm
G_M000_IG01:  
...
mov      rax, 1152                                 ; clear 1kb of stack …
```
=> Increase hot code in PruneCache

src/Nethermind/Nethermind.Serialization.Rlp/Rlp.cs
This PR optimizes RLP encoding by reducing unnecessary array allocations and improving memory usage. Key changes include:
- Eliminating a second array creation when serializing lengths.
- Refactoring the SerializeLength method to use spans and uninitialized arrays.
- Introducing the [SkipLocalsInit] attribute on key methods for potential performance benefits.
=> Rlp.Encode skip second array creation for length

src/Nethermind/Benchmarks.slnx, src/Nethermind/Directory.Packages.props, src/Nethermind/Nethermind.Evm.Benchmark/StaticCallBenchmarks.cs, src/Nethermind/Nethermind.Evm.Test/Secp256r1PrecompileTests.cs, src/Nethermind/Nethermind.Evm/Nethermind.Evm.csproj, src/Nethermind/Nethermind.Evm/Precompiles/Secp256r1Precompile.cs, src/Nethermind/Nethermind.Precompiles.Benchmark/PrecompileBenchmarkBase.cs
- Switches to the [secp256r1 package](https://github.com/NethermindEth/secp256r1-bindings) using BoringSSL for signature verification (see https://github.com/NethermindEth/secp256r1-bindings/pull/6)
- Adds a bunch of random test cases
- Small fixes for Benchmarks solution:
- Broken build because of missing projects
- Precompile benchmarks runnable only from specific directory
- 2 baseline methods in single benchmark
Related:
- https://github.com/NethermindEth/nethermind/pull/8252
=> Secp256r1 precompile: switch to BoringSSL

src/Nethermind/Nethermind.Core.Test/Json/UInt256ConverterTests.cs, src/Nethermind/Nethermind.Serialization.Json/UInt256Converter.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/Json/BlockRewardConverter.cs
- Handle cases of big integers in form of decimal number passed in json
Example:
```
{"jsonrpc":"2.0","id":2,"method":"taikoAuth_txPoolContentWithMinTip","params": ["0x0000000000000000000000000000000000000000", 
15974323677659503371917880, 
10000, 10000, [], 1, 1 ]}
```
=> Deserialize JSON of a decimal number > MAX_UINT64

src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs
Related:
Closes [#8171](https://github.com/NethermindEth/nethermind/issues/8171)
What was changed:
Replaced the outdated and broken documentation link shown in the Engine API misconfiguration error message with a working one:
Old (404): https://docs.nethermind.io/nethermind/ethereum-client/engine-jsonrpc-configuration-examples
New (valid): https://docs.nethermind.io/interacting/json-rpc-server/#engine-api
Why:
The original link pointed to a non-existent page, which could confuse users trying to configure the Engine API.
This fix ensures the error message now points to the correct setup guide.
=> Fix broken Engine API documentation link in error message

src/Nethermind/Nethermind.Era1/EraPathUtils.cs, src/Nethermind/Nethermind.Era1/EraReader.cs, src/Nethermind/Nethermind.Hive/HivePlugin.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.BlockProducer.cs, src/Nethermind/Nethermind.Merge.Plugin/MergePlugin.cs, src/Nethermind/Nethermind.Shutter/ShutterPlugin.cs, src/Nethermind/Nethermind.TxPool/Collections/SortedPool.cs
- Use `ArgumentNullException.ThrowIfNull` is better for hot code than having `throw new exception` in main code
=> Use ArgumentNullException.ThrowIfNull

src/Nethermind/Nethermind.Core.Test/RequestSizer/LatencyAndMessageSizeBasedRequestSizerTests.cs, src/Nethermind/Nethermind.Core/Collections/SlicedReadOnlyList.cs, src/Nethermind/Nethermind.Core/RequestSizer/LatencyAndMessageSizeBasedRequestSizer.cs, src/Nethermind/Nethermind.Core/RequestSizer/LatencyBasedRequestSizer.cs, src/Nethermind/Nethermind.Network.Stats/INodeStats.cs, src/Nethermind/Nethermind.Network.Stats/INodeStatsManager.cs, src/Nethermind/Nethermind.Network.Stats/NodeStatsLight.cs, src/Nethermind/Nethermind.Network.Stats/NodeStatsManager.cs, src/Nethermind/Nethermind.Network.Test/NodeStatsTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V62/Eth62ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network.Test/SnapProtocolHandlerTests.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/SyncPeerProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/ProtocolHandlers/ZeroProtocolHandlerBase.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V63/Eth63ProtocolHandler.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Snap/SnapProtocolHandler.cs, src/Nethermind/Nethermind.Serialization.Rlp/OwnedBlockBodies.cs, src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/BodiesSyncFeedTests.cs, src/Nethermind/Nethermind.Synchronization.Test/FastBlocks/FastHeadersSyncTests.cs, src/Nethermind/Nethermind.Synchronization.Test/ParallelSync/SyncDispatcherTests.cs, src/Nethermind/Nethermind.Synchronization.Test/ReceiptSyncFeedTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/BodiesSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/ReceiptsSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/Peers/ISyncPeerPool.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs, src/Nethermind/Nethermind.Synchronization/SnapSync/ProgressTracker.cs
- To reduce timeout and high allocation, we limit the size of the bodies, receipts and snap request at protocol handler level.
- This information however is not exposed to the sync code, so sync code still try to request in a large batch, potentially causing a large portion of the request to be retried later.
- This is not a big deal for downloads that is paralelizable, bit it can be a problem for sync that requires order. 
- No change in performance, but helpful for #8255
=> Perf/More accurate request limit.

src/Nethermind/Nethermind.Merge.Plugin.Test/EngineModuleTests.PayloadProduction.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs, src/Nethermind/Nethermind.TxPool/Metrics.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
- If no new txs have been added to pool since last block build; skip the improvement and wait for next delay.
- Is no reason to build a block if it will build the same as previous
=> Skip block build if no new tx have been added

src/Nethermind/Nethermind.Network.Discovery.Test/NodeLifecycleManagerTests.cs, src/Nethermind/Nethermind.Network.Discovery/DiscoveryManager.cs, src/Nethermind/Nethermind.Network.Discovery/IDiscoveryManager.cs, src/Nethermind/Nethermind.Network.Discovery/NodeFilter.cs
- On a low peer network the retry mechanism from peers being pushed out of the filter may not kick in; so also add a 5 min timeout after which the peer is also reconsidered.
=> Add timeout to node filter

src/Nethermind/Nethermind.Config/BlocksConfig.cs, src/Nethermind/Nethermind.Core/ProductInfo.cs, src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs, src/Nethermind/Nethermind.Runner/Program.cs
- Include version number in default extra data, meaning it is easier to determine if any issues are fixed issues or different
- Convert `-unsable` to `a` so as not to use up too much space
```
JSON RPC     : http://127.0.0.1:8545 ; http://localhost:8551
Genesis hash : 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
Gaslimit     : 36,000,000
ExtraData    : Nethermind v1.32.0a
```
=> Include version number in default extra data

src/Nethermind/Nethermind.Synchronization/FastBlocks/SyncStatusList.cs
```
Unhandled exception. System.InvalidOperationException: ArrayPoolList hasn't been disposed. Created    at Nethermind.Core.Collections.ArrayPoolList`1..ctor(ArrayPool`1 arrayPool, Int32 capacity, Int32 startingCount)
at Nethermind.Core.Collections.ArrayPoolList`1..ctor(Int32 capacity, Int32 count)
at Nethermind.Synchronization.FastBlocks.SyncStatusList.TryGetInfosForBatch(Int32 batchSize, Func`2 blockExist, BlockInfo[]& infos)
at Nethermind.Synchronization.FastBlocks.BodiesSyncFeed.PrepareRequest(CancellationToken token)
at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DispatchLoop(CancellationToken cancellationToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at …
```
=> Fix: dispose ArrayPoolList in SyncStatusList

src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs
- fix `ForkchoiceUpdatedV1Result` in simulated block production scenarios
Currently, during simulated block production (when payload attributes are added by us), we return a `payloadId` even though it wasn't requested by CL. This PR corrects that behavior by returning `null` in such cases, ensuring the simulation remains internal to Nethermind and is not exposed to the CL.
=> Fix FCU result in simulated block production scenarios

src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs
- We output far too much data in JsonRpc error lines, reduce to a single line
- Currently causing issue for ethPandaOps as logging is the predominate performance hog for them
- No one really uses the additional detail; and it is a very serious issue we output other Error logs
Open question on whether we want to log the error at all by default as do keep its metric
=> Dial back JsonRpc log spam

src/Nethermind/Nethermind.Blockchain/ChainHeadInfoProvider.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.Blobs.cs, src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
Contributes to #8484; test passed so can't recreate
- Added test for regular tx reorgs
- Changed reorged txs to PersistentBroadcast
- Cleared more caches on reorg
- Increased "Not syncing" distance
- Changed Debug message to Warn message when TxPool can't be updated
- Add ReaderWriterLock around HeadUpdate and AddTx; so new tx don't mess with the changes from changing head
- Update head takes a write lock
- Submitting Tx takes a read lock
=> Handle tx reorged blocks better

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs, src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
- Prefer the value of the mev tx `.Value` when calculating mev-boost block mev; as sometimes the beneficiary has their own tx in the block making straight balance calc unreliable (can currently sometimes outputs 0)
- Change block mev value for local production and block to 4 decimals as it tracks the individual improvements better since are more often now
=> Prefer mev reward tx value when calculating mev

src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetBlobsHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/Metrics.cs
- add metrics `NumberOfGetBlobsSuccesses` and `NumberOfGetBlobsFailures`
A successful response to `engine_getBlobsV1` may include some (or even all) `null` values, indicating that the requested blobs are not available. We already track metrics for the number of blobs requested and the number of blobs sent, and based on that, we estimate the return rate on mainnet to be around 85%. For now, partial responses (some blobs returned, some `nulls`) are useful for the CL.
However, after Fusaka's PeerDAS, partial responses will no longer be useful - CL will require either all requested blobs or none. This PR introduces new metrics to track fully successful responses (where all requested blobs are returned) versus successful but incomplete responses (where some blobs are missing). These metrics …
=> Add metrics for `engine_getBlobsV1` full and partial responses

src/Nethermind/Nethermind.Evm/Tracing/GasEstimator.cs
Fixes #XXX
- Removed mutation of the original `Transaction` object during gas estimation
- Introduced safe cloning via `Transaction.CopyTo()` to solve `TODO` in `GasEstimator.TryExecutableTransaction`
Existing coverage is sufficient. This change preserves logic and only affects internal transaction handling during estimation.
This PR resolves the inline `// TODO: Workaround to not mutate the original Tx` by introducing a proper, non-mutating transaction cloning process using `Transaction.CopyTo()`. This improves safety and code clarity in gas estimation routines.
=> Fix GasEstimator TODO by cloning Transaction instead of mutating original

src/Nethermind/Nethermind.Api/IApiWithBlockchain.cs, src/Nethermind/Nethermind.Api/NethermindApi.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/InitializeBlockchainAuRa.cs, src/Nethermind/Nethermind.Core.Test/Modules/PseudoNethermindModule.cs, src/Nethermind/Nethermind.Core.Test/Modules/PsudoNetworkModule.cs, src/Nethermind/Nethermind.Init/InitializeStateDb.cs, src/Nethermind/Nethermind.Init/Modules/NethermindModule.cs, src/Nethermind/Nethermind.Init/Modules/WorldStateModule.cs, src/Nethermind/Nethermind.Init/PruningTrieStateFactory.cs, src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs, src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/AdminModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/PruningTrieStateAdminModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/AdminRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/IAdminRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/IPruningTrieStateAdminRpc.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/IPruningTrieStateAdminRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Admin/PruningTrieStateAdminRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/IContainerBuilderExtensions.cs, src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/MergePluginTests.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/ContextWithMocks.cs, src/Nethermind/Nethermind.Synchronization/Synchronizer.cs
- Move `InitializeStateDb` to DI.
- Move out pruning trie state related rpc method out of `AdminRpcModule` into `PruningTrieStateAdminRpcModule`. 
- Move trie state related code out of INethermindApi.
=> Refactor/move worldstate to DI

src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/PayloadPreparationService.cs
- Add block requested
- Add empty block produced
- Also add which block number, when duplicate requests come in
We have issues around multiple requests to produce same block and potentially a contention on block production lock; so these logs will provide valuable insight
=> Add additional block production logs

src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/BeaconHeadersSyncTests.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/BeaconHeadersSyncFeed.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs
- There seems to be a chance that the next header difficulty is not updated by about one batch.
- Unfortunately this is not reliably reproducable nor can I figureout how can that be.
- Anyway, this combine the next header hash and next header difficulty into one so that they are both updated at the same time.
- Also set the next expected header in a finally block in case an exception happen in blocktree maybe. But that would also mean next header hash also not updated, so what happen? I don't know.
- Can't reproduce issue.
=> Maybe fix incorrect total difficulty

src/Nethermind/Nethermind.Consensus.Test/TargetAdjustedGasLimitCalculatorTests.cs, src/Nethermind/Nethermind.Consensus/TargetAdjustedGasLimitCalculator.cs
- TargetAdjustedGasLimitCalculator will not go below spec.MinGasLimit
=> Fix minimum gas limit when producing blocks

src/Nethermind/Nethermind.Merge.Plugin/Handlers/GetBlobsHandlerV2.cs, src/Nethermind/Nethermind.Merge.Plugin/Metrics.cs, src/Nethermind/Nethermind.TxPool/Collections/BlobTxDistinctSortedPool.cs, src/Nethermind/Nethermind.TxPool/ITxPool.cs, src/Nethermind/Nethermind.TxPool/NullTxPool.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs
This PR renames execution metrics for the new engine_getBlobsV2 rpc for peerdas.
This rename is for unifying the execution metric naming, shown in [this proposal](https://testinprod.notion.site/Proposal-for-Unified-EL-metrics-for-PeerDAS-1d28fc57f54680f2a3cbfe408d7db4b8?pvs=4).
To correctly identify the number of blobs in the blobpool, this PR modifies `AreBlobsAvailable` to `GetBlobCounts` which will return the number of blobs in the blobpool, then use that blob count to compare against the number of blobhashes requested.
Because this is naming change for metric that isn't public yet, so I think the naming changes won't be breaking change.
=> Rename peerdas getBlobsV2 metrics

src/Nethermind/Nethermind.AuRa.Test/Transactions/PermissionTxComparerTests.cs, src/Nethermind/Nethermind.Blockchain.Test/TransactionSelectorTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxPriorityTxSource.cs, src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Core/Extensions/EnumerableExtensions.cs, src/Nethermind/Nethermind.Core/Transaction.cs, src/Nethermind/Nethermind.Core/TransactionExtensions.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Call/NativeCallTracer.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/FeeHistoryOracleTests.cs
- Evaultate less (Perf good): When adding txs to consider during block production, stop adding from same address (don't add later nonces) when 
- The sum of the dependency chain exceeds blob count or block gaslimit
-  As soon as one of the txs fails tx filters e.g. gas below base fee
- Evaluate deeper (Bug fix): If dependency on blobs tx, only include blob tx in optimal list if also included parent tx
Two hive tests check for a suboptimal built block result; testing for a lower profit blocks (will submit fix to hive)
Have had added variant tests around that; including the variant hive thinks its testing (but it's taking into account profit, so changed priority fees to produce same output), and the max profit result of what it is testing.
=> Consider dependency chains in optimal blob packing

src/Nethermind/Nethermind.Test.Runner/StateTestTxTracer.cs
Fixes #8548
Fixes #8471
* Makes `StateTestTxTracer.ReportOperationError` and `StateTextTxTracer.ReportOperationRemainingGas` no-op in the case there's no active operation
* This is needed in the case of top-level precompile calls since there is no associated opcode
* It was considered that while we could do the same for the `StateTextTxTracer.SetOperation*` methods, semantically it makes more sense to keep them as they are, and this does not impact the issue
* Adds a very minor refactoring
To test the fix, `nethtest` can be executed with e.g. the input provided in #8548, as such:
`nethtest --trace -m --input input.json`
Being `input.json` the following:
```JSON
{
"00000030-mixed-0": {
"env": {
"currentCoinbase": "b94f5374fce5edbc8e2a8697c15331677e6ebf0b",
"currentDifficulty": "0x200000", …
```
=> Fix StateTestTxTracer top-level precompile calls tracing

src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs, src/Nethermind/Nethermind.Core/Collections/ArrayPoolList.cs, src/Nethermind/Nethermind.Era1/EraReader.cs, src/Nethermind/Nethermind.Evm/Tracing/GethStyle/Custom/Native/Call/NativeCallTracer.cs, src/Nethermind/Nethermind.Shutter/ShutterTxLoader.cs, src/Nethermind/Nethermind.Synchronization.Test/Trie/HealingTreeTests.cs, src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs, src/Nethermind/Nethermind.Taiko/Rpc/TaikoEngineRpcModule.cs
- Use non-boxing return of `ArrayPoolListEnumerator` for `ArrayPoolList<T>.GetEnumerator()`
- Convert to `.AsSpan` in `foreach` loops as the C# compiler converts enumeration of spans to a bounds check eliminated `for i` loop
=> Use faster span enumerator for ArrayPoolList

src/Nethermind/Nethermind.Network/Rlpx/ZeroSnappyEncoder.cs
- Cap snappy output span, as at infinite length Snappy thinks are overlapping ranges (change from dependency upgrade)
=> Cap snappy output span

src/Nethermind/Nethermind.Core/ManualTimestamper.cs, src/Nethermind/Nethermind.Synchronization.Test/E2ESyncTests.cs
- E2ESyncTests fails after pectra as post merge EIP is activated. 
- ParentBeaconBlockRoot must not be null so that header is encoded correctly.
- Now the `ITimestamper` changed so that any EIP post merge is not activated in pre merge tests.
=> Fix E2ESyncTest

src/Nethermind/Nethermind.TxPool.Test/TxPoolTests.cs
Just a small refactor to emphasize that any tx type can be used as replacement, when account is pending delegation.
=> Use all tx types in pending delegation test

src/Nethermind/Nethermind.Optimism/Rpc/OptimismEthRpcModule.cs
Fixes #8515
- Be even more conservative when casting to avoid `InvalidCastException`s.
The user did not provide a reproducible scenario and the logs are not enough. We are mostly guessing what could be the issue.
Originally reported through Discord: https://discord.com/channels/629004402170134531/1364406090779070585/1370824352450482196
=> Safely cast Optimism subtypes (2)

src/Nethermind/Nethermind.Consensus/Tracing/GethStyleTracer.cs, src/Nethermind/Nethermind.Consensus/Tracing/IGethStyleTracer.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugBridge.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/DebugRpcModule.cs, src/Nethermind/Nethermind.JsonRpc/Modules/DebugModule/IDebugBridge.cs
Fixes #8600
Closes #8607
- Resolve and check block state availability in each of the `DebugRpcModule` calls, similarly to `EthRpcModule`
- Add relevant utilities to `DebugBridge`
A similar scenario to #8600 could be tested in a running node.
One detail is that with these changes there are now some duplicate operations - as a block search is done for the state availability check and done again for the actual tracing inside `GethStyleTracer`. There doesn't seem to be a very good way to avoid this without bigger changes or with error catching, which would be hacky.
=> Add state availability checks before debug module tracing

src/Nethermind/Nethermind.Core.Test/AddressTests.cs, src/Nethermind/Nethermind.Core/Address.cs
Removes `SkipLocalsInit` from `Address.ToHash()` to avoid garbage in the first 12 bytes of hash.
=> Remove SkipLocalsInit to avoid garbage in first bytes of hash

src/Nethermind/Nethermind.TxPool/TxPool.cs
- Fixed `Block.AccountChanges` not being disposed when rerunning blocks during syncing.
=> Fix for `Block.AccountChanges` not being disposed in some cases

src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs
Fixes issue from #8521
- When we don't find receipt for transaction we already don't have TxHash->BlockHash mapping. We cannot assume it is because pruned history as it can also be because of not yet included transaction. Thus we should keep old logic.
=> Revert wrong code on missing receipt

src/Nethermind/Nethermind.Facade/Eth/RpcTransaction/LegacyTransactionForRpc.cs
Fixes #8316
- Set the default gas price to `0` in `LegacyTransactionForRpc.ToTransaction`, standardizing it with geth
- Testing can be done based on #8316 scenario.
=> Set default `LegacyTransactionForRpc` gas price to zero

src/Nethermind/Nethermind.Trie/PatriciaTree.cs
-I was reading the PatriciaTree code for fun and to improve my understanding, and I came across unused _ignoreMissingDelete_ (always true)
=> PatriciaTree ignoreMissingDelete is not used

src/Nethermind/Nethermind.Core/IKeyValueStore.cs, src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Serialization.Rlp/KeyValueStoreRlpExtensions.cs
- Reduces allocation and additional copy from RocksDB; which is good for large objects like Blocks
- Better performance when downloading receipts (as they load blocks)
=> Use RocksDB PinnableSlice when available

src/Nethermind/Nethermind.Consensus.Clique/SnapshotDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpStream.cs
- Call single `virtual Write(ReadOnlySpan<byte>)` rather than multiple `virtual WriteByte(byte)` calls
=> Optimize RlpStream.Encode(ulong)

src/Nethermind/Nethermind.Core/ExecutionRequest/ExecutionRequestExtensions.cs
- Use static `SHA256.HashData` rather than creating new instance of `SHA256` each time
=> Use static SHA256.HashData

src/Nethermind/Nethermind.Blockchain.Test/BlockchainProcessorTests.cs, src/Nethermind/Nethermind.Config.Test/ConfigFileTestsBase.cs, src/Nethermind/Nethermind.Core/Tasks/WaitForPassingTasks.cs, src/Nethermind/Nethermind.Db.Rocks/Config/PerTableDbConfig.cs, src/Nethermind/Nethermind.Era1/EraPathUtils.cs, src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs, src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs, src/Nethermind/Nethermind.Specs/ChainSpecStyle/ChainSpecLoader.cs
- Switches ContainsKey+indexer to TryGetValue for single-dictionary lookups  
- Replaces LINQ `.Any()` with `Count` or `IsEmpty` checks on collections  
- Uses char overloads instead of string for simple checks
=> Mild performance tweaks

src/Nethermind/Nethermind.Core/Account.cs, src/Nethermind/Nethermind.Core/Caching/ClockCache.cs
Resolves #8488
- Fix race condition in ClockCache.Set when not under lock
=> Fix ClockCache.Set

src/Nethermind/Nethermind.Optimism/CL/Rpc/IOptimismOptimismRpcModule.cs, src/Nethermind/Nethermind.Optimism/IOptimismConfig.cs
- Hide OP-CL `optimism` RPC namespace
- Hide OP-CL specific configurations
- [] No
Until all OP-CL features are to be included in a release we want to hide configurations and RPC modules from user facing docs like CLI help and official Nethermind docs.
=> Hide OP-CL specific options

src/Nethermind/Nethermind.AuRa.Test/AuRaPluginTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaPlugin.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/AuRaNethermindApi.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/InitializeBlockchainAuRa.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/StartBlockProducerAuRa.cs, src/Nethermind/Nethermind.Consensus.AuRa/InitializationSteps/TxAuRaFilterBuilders.cs, src/Nethermind/Nethermind.Core.Test/Modules/TestNethermindModule.cs, src/Nethermind/Nethermind.Merge.AuRa.Test/AuRaMergeEngineModuleTests.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergeBlockProducerEnvFactory.cs, src/Nethermind/Nethermind.Merge.AuRa/AuRaMergePlugin.cs
- Remove `AuraNethermindApi` from `StartBlockProducerAuRa`, `TxAuraFiltersBuilder` and `AuRaMergeBlockProducerEnvFactor`.
- `MergeAuRaTestBlockchain` uses a completely different initialization so I kept it mostly the same instead of trying to remove `AuraNethermindApi` from it in this PR.
- Gnosis mainnet can sync with simulate block production.
=> Refactor/Reduce `AuraNethermindApi` usage.

src/Nethermind/Nethermind.Core/Address.cs, src/Nethermind/Nethermind.Evm/EvmStack.cs
- Rather than doing multiple memory writes; prepare value in Vector256<byte> register and do single write to memory.
=> Perform stack writes as single 32 vector

src/Nethermind/Nethermind.TxPool/ITxPoolConfig.cs, src/Nethermind/Nethermind.TxPool/TxPool.cs, src/Nethermind/Nethermind.TxPool/TxPoolConfig.cs
Resolves https://github.com/NethermindEth/nethermind/issues/8234
- Allow whether to accept or reject txs when syncing to be set via config
=> Surface acceptTx on sync via config

src/Nethermind/Nethermind.Evm/BlobGasCalculator.cs
Fixes small bug within the EIP-7918 blob gas calculator.
The bug essentially triggered the reserve price 6x higher than it should, due to the incorrect variable in the calculation. We caught this with a boundary test, afaik essentially any test with the block base fee set < 48 will catch it.
Now passes all the latest fusaka-devnet-1 EEST tests:
- https://github.com/ethereum/execution-spec-tests/releases/tag/fusaka-devnet-1%40v1.0.0
=> chore(evm): fix 7918 blob gas calculator

src/Nethermind/Nethermind.Core/Crypto/KeccakHash.cs, src/Nethermind/Nethermind.Crypto/EthereumEcdsaExtensions.cs, src/Nethermind/Nethermind.Crypto/KeccakRlpStream.cs, src/Nethermind/Nethermind.Serialization.Rlp/TxDecoder.cs, src/Nethermind/Nethermind.Serialization.Rlp/TxDecoders/BlobTxDecoder.cs
- Encode to KeccakRlpStream rather than RlpStream, create array, keccak array
=> Recover signer direct from keccak without intermediary array

src/Nethermind/Ethereum.Trie.Test/TrieTests.cs, src/Nethermind/Nethermind.Blockchain.Test/Proofs/ReceiptTrieTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/ReceiptsRootCalculator.cs, src/Nethermind/Nethermind.Core.Test/Builders/BlockBuilder.cs, src/Nethermind/Nethermind.Core.Test/Builders/BlockTreeBuilder.cs, src/Nethermind/Nethermind.Core.Test/Builders/TrieBuilder.cs, src/Nethermind/Nethermind.Era1/EraReader.cs, src/Nethermind/Nethermind.JsonRpc/Modules/Proof/ProofRpcModule.cs, src/Nethermind/Nethermind.State/Healing/HealingStateTree.cs, src/Nethermind/Nethermind.State/Healing/HealingStorageTree.cs, src/Nethermind/Nethermind.State/Proofs/PatriciaTrieT.cs, src/Nethermind/Nethermind.State/Proofs/ReceiptTrie.cs, src/Nethermind/Nethermind.State/Proofs/TxTrie.cs, src/Nethermind/Nethermind.State/Proofs/WithdrawalTrie.cs, src/Nethermind/Nethermind.State/StateTree.cs, src/Nethermind/Nethermind.State/StorageTree.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs, src/Nethermind/Nethermind.Trie.Test/TrieTests.cs, src/Nethermind/Nethermind.Trie/PatriciaTree.cs, tools/Evm/T8n/JsonTypes/T8nExecutionResult.cs
- Remove unused `_parallelBranches` field
- Seal
- `HealingStateTree`
- `HealingStorageTree`
- `TxTrie`
- `WithdrawalTrie`
- `ReceiptTrie`
- Make `ReceiptTrie` non-generic (only used with one type)
=> PatriciaTree remove unused field

src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.Consensus/Processing/IBlockProcessingQueue.cs, src/Nethermind/Nethermind.Core/Threading/ThreadExtensions.cs, src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs, src/Nethermind/Nethermind.Merge.Plugin/TimeoutUtils.cs
- When no blocks queued (regular processing) skip the recovery queue and queue direct to the block processing queue to reduce latency
=> Skip recovery queue when no blocks queued

src/Nethermind/Nethermind.AuRa.Test/AuRaSealValidatorTests.cs, src/Nethermind/Nethermind.Benchmark/Core/RecoverSignaturesBenchmark.cs, src/Nethermind/Nethermind.Clique.Test/CliqueTests.cs, src/Nethermind/Nethermind.Clique.Test/SnapshotManagerTests.cs, src/Nethermind/Nethermind.Consensus.AuRa/AuRaSealValidator.cs, src/Nethermind/Nethermind.Consensus.Clique/CliqueSealer.cs, src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs, src/Nethermind/Nethermind.Consensus/ISigner.cs, src/Nethermind/Nethermind.Consensus/NullSigner.cs, src/Nethermind/Nethermind.Consensus/Signer.cs, src/Nethermind/Nethermind.Core.Test/SignerTests.cs, src/Nethermind/Nethermind.Crypto/BlockHeaderExtensions.cs, src/Nethermind/Nethermind.Crypto/Ecdsa.cs, src/Nethermind/Nethermind.Crypto/EthereumEcdsa.cs, src/Nethermind/Nethermind.Crypto/EthereumEcdsaExtensions.cs, src/Nethermind/Nethermind.Crypto/IEcdsa.cs, src/Nethermind/Nethermind.Crypto/IEthereumEcdsa.cs, src/Nethermind/Nethermind.Crypto/KeccakRlpStream.cs, src/Nethermind/Nethermind.Crypto/NullEthereumEcdsa.cs, src/Nethermind/Nethermind.Evm.Test/CodeInfoRepositoryTests.cs, src/Nethermind/Nethermind.ExternalSigner.Plugin/ClefSigner.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcSimulateTestsBase.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/Simulate/EthSimulateTestsSimplePrecompiles.cs, src/Nethermind/Nethermind.Network.Discovery/Messages/NodeIdResolver.cs, src/Nethermind/Nethermind.Network.Discovery/Serializers/DiscoveryMsgSerializerBase.cs, src/Nethermind/Nethermind.Network.Enr/NodeRecordSigner.cs, src/Nethermind/Nethermind.Network/Rlpx/Handshake/HandshakeService.cs, src/Nethermind/Nethermind.Optimism/OptimismEthereumEcdsa.cs, src/Nethermind/Nethermind.Serialization.Rlp/Eip7702/AuthorizationTupleDecoder.cs
Saves 96 bytes per tx recovery
- `Signature.BytesWithRecovery` allocates as 65 byte array; can skip this allocation
- Skip `Hash256` allocation
=> Allocate 96 bytes less per tx sender recovery

src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Storage.cs, src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.cs
- Split SSTORE to two opcodes to simplify branching/nesting
- InstructionSStoreUnmetered (pre Eip1283)
- InstructionSStoreMetered (post Eip1283, Eip2200)
=> Split SSTORE to two Opcodes

src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs, src/Nethermind/Nethermind.Consensus/StandardBlockProducerRunner.cs, src/Nethermind/Nethermind.Core.Test/Builders/Build.ChainSpec.cs, src/Nethermind/Nethermind.Core.Test/Builders/ChainSpecBuilder.cs, src/Nethermind/Nethermind.Core.Test/Modules/TestNethermindModule.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Trace/ParityStyleTracerTests.cs
- `ITraceRpcModule` not created the same way in tests and in prod. 
- Use of writable world state, causes assertion failure due to block commit set not sealing due to null root ref.
- One of the block processing context uses trace execution instead of execute, which result in error as the sender balance is null which is a path not reached as on process it is validated.
- Not throwing in debug mode anymore.
=> Fix ParityStyleTracerTests in debug mode

src/Nethermind/Nethermind.Blockchain/BlockTree.cs, src/Nethermind/Nethermind.Blockchain/BlockTreeOverlay.cs, src/Nethermind/Nethermind.Blockchain/ChainHeadInfoProvider.cs, src/Nethermind/Nethermind.Blockchain/IBlockTree.cs, src/Nethermind/Nethermind.Blockchain/ReadOnlyBlockTree.cs, src/Nethermind/Nethermind.Consensus/Processing/BlockchainProcessor.cs, src/Nethermind/Nethermind.TxPool/IChainHeadInfoProvider.cs, src/Nethermind/Nethermind.TxPool/TxBroadcaster.cs
-  Don't broadcast txs while producing a block as it allocates a lot and we want to minimize GCs at this time also head about to change which could change the filter results; reducing variance during long blocks
=> Don't broadcast txs while processing a block

src/Nethermind/Nethermind.Runner/NLog.config
- Add the `BuilerNet` consortium to the highlighted log brands https://buildernet.org/blog/introducing-buildernet
=> Add BuilderNet to highlighted log brands

src/Nethermind/Nethermind.Core/Transaction.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcProcessor.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcResult.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs, src/Nethermind/Nethermind.Network/P2P/Subprotocols/Eth/V62/Messages/BlockBodiesMessageSerializer.cs, src/Nethermind/Nethermind.Runner/Ethereum/JsonRpcRunner.cs, src/Nethermind/Nethermind.Runner/JsonRpc/HostingApplication.cs, src/Nethermind/Nethermind.Runner/JsonRpc/HttpContextFactory.cs, src/Nethermind/Nethermind.Runner/JsonRpc/NullDiagnosticListener.cs, src/Nethermind/Nethermind.Runner/JsonRpc/Startup.cs, src/Nethermind/Nethermind.Runner/JsonRpc/WebHost.cs, src/Nethermind/Nethermind.Serialization.Rlp/RlpDecoderExtensions.cs, src/Nethermind/Nethermind.State/Proofs/TxTrie.cs
- Rewrite the aspnet webhost to remove all the additional work an allocations for `Activity`, `DiagnosticListener` and `Metric`s; as we have our own metrics and Prometheus adds it's on metrics; and there isn't a ay to switch it off in the framework directly (Empty and Slim webhost both still add them)
- If we have the Rlp for the tx already (as haven't converted it into hash yet, case for newpayload) then use that directly when calculating the TxTrie hash rather than reencoding the tx to get it.
- Move anything not hot-path in JsonRpc to non-inlined methods rather than than part of main code
=> Trim JsonRpc Webhost for lower latency

src/Nethermind/Nethermind.Facade/Eth/BlockForRpc.cs, src/Nethermind/Nethermind.Optimism/Rpc/OptimismEthRpcModule.cs
- Use static `BlockDecoder` rather than creating it each time
- Generate `.Transactions` manually rather than with Linq allocating closure
- Generate `.Uncles` manually rather than with Linq allocating closure
=> Optimize BlockForRpc for eth_getBlockByNumber

src/Nethermind/Nethermind.Runner/configs/surge-hoodi.json
Fixes incorrect genesis hash from https://github.com/NethermindEth/nethermind/pull/8890 to the one specified here https://github.com/NethermindEth/simple-surge-node/blob/main/.env.hoodi#L30
- Changes `GenesisHash`
=> Fix Surge Hoodi Genesis Hash in Config

src/Nethermind/Nethermind.Init/Steps/EthereumStepsManager.cs, src/Nethermind/Nethermind.Init/Steps/StepInitializationException.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/EthereumStepsLoaderTests.cs, src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/EthereumStepsManagerTests.cs
- Bubble up `InvalidConfigurationException` so that it is less spammy. Looks like this:
```
9 
01 Jul 07:28:19 | Address 0x9b9020f7f9b1074d4776952639468d53c68b3976 is configured for signing blocks. 
01 Jul 07:28:19 | Initializing 6 plugins 
01 Jul 07:28:19 |   Ethash by Nethermind 
01 Jul 07:28:19 |   Ethash by Nethermind initialized in 0ms 
01 Jul 07:28:19 |   Merge by Nethermind 
01 Jul 07:28:19 | Client started with TTD: 58750000000000000000000, TTD reached: True, Terminal Block Number , FinalTotalDifficulty: 58750003716598352816469 
01 Jul 07:28:19 |   Merge by Nethermind initialized in 18ms 
01 Jul 07:28:19 |   HealthChecks by Nethermind 
01 Jul 07:28:19 |   HealthChecks by Nethermind initialized in 4ms 
01 Jul 07:28:19 |   EthStats by Nethermind 
01 Jul 07:28:19 |   EthStats by …
```
=> Unwrap invalid configuation exception

src/Nethermind/Nethermind.Evm/CodeAnalysis/IL/EvmToIlEmitter.cs, src/Nethermind/Nethermind.Evm/CodeAnalysis/IL/IlAnalyzer.cs
- Fix subsegment  metadata for segments starting at jumpdest after call or create. The proceeding subsegments should have entry point set to true but were being overwritten by the jumpdest metdata and being set to false. Hence Ilevm was not able to return to the original call frame if jumpdest followed a call or create
- Fix blob hash : TxExecutionContext is a ref field, that shouldn't be loaded as an address
=> Fix Failing Ethereum Tests

src/Nethermind/Nethermind.Core.Test/Container/OrderedComponentsTests.cs, src/Nethermind/Nethermind.Core/Container/OrderedComponents.cs, src/Nethermind/Nethermind.Core/Container/OrderedComponentsContainerBuilderExtensions.cs, src/Nethermind/Nethermind.Core/ContainerBuilderExtensions.cs, src/Nethermind/Nethermind.JsonRpc/Modules/IContainerBuilderExtensions.cs
- The auto collection resolver have a weird ordering behaviour with nested module causing the default engine api to be used instead of taiko's engine api as its registration appear later than taiko's. 
- This PR add some explicit DSL to ensure ordering.
- Logged the registered module order.
=> Fix Taiko Engine Api

tools/DocGen/JsonRpcGenerator.cs
- Updated JSON-RPC docs generation to include namespaces like `flashbots`, `rbuilder`, `health`. Also, included lots of methods that were missing in the `admin` namespace. Generation results are available [here](https://docs.nethermind.io/next/interacting/json-rpc-ns/admin) (see sidebar namespaces too).
- Revised markdown
=> Revise JSON-RPC docs generation

src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs, src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs, src/Nethermind/Nethermind.Merge.Plugin/Synchronization/MergeBlockDownloader.cs, src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
- Block downloader can download block faster than nethermind can process.
- This causes OOM when syncing from genesis as the blocks are buffered in block processing queue.
- This PR stop spawing request when the size of the processing queue exceed certain configured threshold.
- This and previous download buffer size is not configured as MB, although internally it still use TX count.
=> Fix/OOM when downloading from genesis.

src/Nethermind/Nethermind.Core/Collections/TypeAsKey.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcService.cs
- Cache PropertyInfo lookups for JsonRpc rather than searching with reflection each time
Before
After
=> Cache PropertyInfo lookups for JsonRpc

src/Nethermind/Nethermind.Trie/PatriciaTree.cs
- Remove code duplication on branches
- Branch eliminate Tracing with generics
- Use virtual NodeType once before node rather than multiple times
Before asm
```
; Total bytes of code: 6201
```
After asm
```
; Total bytes of code 1525
```
=> More hot code in ConnectNodes

src/Nethermind/Benchmarks.slnx, src/Nethermind/Nethermind.Core/Extensions/ByteArrayExtensions.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Evm.Precompiles/ModExpPrecompile.cs, src/Nethermind/Nethermind.Evm.Precompiles/ModExpPrecompilePreEip2565.cs, src/Nethermind/Nethermind.Evm.Test/Eip2565Tests.cs, src/Nethermind/Nethermind.Evm.Test/Eip7823Tests.cs, src/Nethermind/Nethermind.Evm/Instructions/EvmInstructions.Math2Param.cs, src/Nethermind/Nethermind.Precompiles.Benchmark/ModExpBenchmark.cs
- Do more maths in 64/32 bit space than 256 bit
- Vectorize overflow checks
- Don't allocate input arrays unless completely needed
- Don't throw and catch exception for overflow
- Don't try catch in `CalculateIterationCount`
=> Optimize ModExp

src/Nethermind/Nethermind.Consensus.Clique/SnapshotManager.cs, src/Nethermind/Nethermind.Crypto/EthereumEcdsa.cs, src/Nethermind/Nethermind.Crypto/IEthereumEcdsa.cs, src/Nethermind/Nethermind.Crypto/NullEthereumEcdsa.cs, src/Nethermind/Nethermind.Optimism/OptimismEthereumEcdsa.cs
- Remove unused ecdsa overloads
=> Tidy up ecdsa overloads

src/Nethermind/Nethermind.Consensus.Clique/CliqueBlockProducer.cs, src/Nethermind/Nethermind.Consensus/Producers/BlockProducerBase.cs, src/Nethermind/Nethermind.Taiko/Rpc/TaikoEngineRpcModule.cs, src/Nethermind/Nethermind.Taiko/TaikoPayloadPreparationService.cs
- Remove unnecessary `SetBaseBlock` to make it clearer the code that manage worldstate lifecycle.
- These are mainly noop.
=> Cleanup/Remove unnecessary SetBaseBlock

src/Nethermind/Nethermind.Core.Test/Container/KeyedMapperRegistrationSourceTests.cs, src/Nethermind/Nethermind.Core/Container/KeyedMapperRegistrationSource.cs, src/Nethermind/Nethermind.Core/ContainerBuilderExtensions.cs
- Fix error on exit as the keyed mapper used to resolved derived type for database assume the object is new it which then attempt to dispose out of order.
- Reproducable locally.
=> Fix error on exit

src/Nethermind/Nethermind.Core/BlockInfo.cs, src/Nethermind/Nethermind.Core/Collections/IHashSetEnumerableCollection.cs, src/Nethermind/Nethermind.Core/Collections/IToArrayCollection.cs, src/Nethermind/Nethermind.Core/Collections/JournalCollection.cs, src/Nethermind/Nethermind.Core/Collections/JournalSet.cs, src/Nethermind/Nethermind.Evm.Test/TransactionSubstateTests.cs, src/Nethermind/Nethermind.Evm/TransactionSubstate.cs, src/Nethermind/Nethermind.JsonRpc/JsonRpcUrl.cs, src/Nethermind/Nethermind.JsonRpc/Modules/RpcModuleProvider.cs, src/Nethermind/Nethermind.Serialization.Rlp/ChainLevelDecoder.cs
- Use faster direct `.ToArray()`
- Use faster `ReadOnlySpan.Contains(null)`
- Use faster direct `HashSet<T>.Enumerator`
- Validate JsonRpc url with `IReadOnlySet` rather than `IEnumerable`
=> Remove Linq from Block Processing

src/Nethermind/Nethermind.Core/Reorganization.cs, src/Nethermind/Nethermind.Db/IPruningConfig.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/BeaconPivotTests.cs, src/Nethermind/Nethermind.Merge.Plugin.Test/Synchronization/StartingSyncPivotUpdaterTests.cs
This reverts commit 845095d56ad07867ce4267c159db4e1d53c85668.
Resolves #9031
- Revert pruning boundary changes
=> Revert "Set default pruning boundary to 128 (#8863)"

src/Nethermind/Nethermind.Core.Test/Json/ByteArrayConverterTests.cs, src/Nethermind/Nethermind.Core/Extensions/Bytes.cs, src/Nethermind/Nethermind.Core/JsonConverters/ByteArrayConverter.cs
- Read `ValueSequence` rather than copying to array to parse when input is multiple segments (usually large hex data e.g. blocks)
- ArrayPool normally allocates for very large arrays so skips that allocation path.
=> Lower allocation ByteArrayConverter for large hex strings

src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs, src/Nethermind/Nethermind.Db.Test/DbOnTheRocksTests.cs, src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs
- Fix segmentation fault after db dispose such as after full pruning due to metric trying to get rocksdb property.
- Fix concurrent full pruning start when rpc is called multiple time quickly due to slow db creation.
- Can continuously prune and reprune and so on.
=> Fix crash on after db dispose and concurrent full pruning start

src/Nethermind/Nethermind.Trie/NibbleExtensions.cs
- Risc-v doesn't support 128bit vectors
=> Fix for RISC-V

src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
Making `CalculateClaimableRefund` overridable in tx processing because Arbitrum needs to have its own implementation.
See [arbitrum PR](https://github.com/NethermindEth/nethermind-arbitrum/pull/126)
=> feat: Make CalculateClaimableRefund overridable in tx processing

src/Nethermind/Nethermind.Evm/VirtualMachine.Warmup.cs, src/Nethermind/Nethermind.Evm/VirtualMachine.cs
Arbitrum has its own custom implementation for `GasPrice` opcode.
See [Arbitrum's PR](https://github.com/NethermindEth/nethermind-arbitrum/pull/127).
In my suggested modifications here, the virtual machine warmup `RunOpCodes` will not have the updated GasPrice opcode. To have it, I would need to override the whole `VirtualMachine.WarmUpEvmInstructions();`, which seems a bit overkill. Let me know it's still better to have the update there too.
=> feat: Make `GenerateOpCodes` and `ExecuteTransaction` overridable in VM

src/Nethermind/Nethermind.Consensus/Processing/ProcessingStats.cs
- If we process blocks; always output the stats regardless of how long the reorg
- Less confusing when looking at logs
=> Always output logs for processed blocks

src/Nethermind/Nethermind.Synchronization.Test/SyncPeerPoolTests.cs, src/Nethermind/Nethermind.Synchronization.Test/SyncServerTests.cs, src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerPool.cs
- Return `FailedAllocation` when cancelled
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at Nethermind.Synchronization.FastBlocks.HeadersSyncFeed.PrepareRequest(CancellationToken cancellationToken) in /src/Nethermind/Nethermind.Synchronization/FastBlocks/FastHeadersSyncFeed.cs:line 350
at Nethermind.Synchronization.ParallelSync.SyncDispatcher`1.DispatchLoop(CancellationToken cancellationToken)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object …
```
=> Handle Cancellation in SyncPeerPool.Allocate

src/Nethermind/Nethermind.Synchronization.Test/BlockDownloaderTests.cs, src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs
- Add extra validation in case `IForwardHeaderProvider` return non consecutive block headers.
=> Extra validation in case `IForwardHeaderProvider` skip header.

src/Nethermind/Nethermind.Blockchain.Test/Receipts/PersistentReceiptStorageTests.cs, src/Nethermind/Nethermind.Blockchain/Receipts/PersistentReceiptStorage.cs
- Only delete receipts with history pruning, not when disabled
=> Fix receipts deletion

src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs, src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
Fixes an issue when you set empty value (clear) for a storage cell that was not previously read (using `Get`). In such case, new value (empty) would not be set as code assumes non existent values as empty, which in turn fails on value comparison (new vs old) when commiting changes.
- `PerContractState` will load value from tree if not found in block cache when saving a new change
=> Clear storage cell / trie without reading cell's value first fails

src/Nethermind/Nethermind.Blockchain.Test/Producers/BlockProducerBaseTests.BaseFee.cs, src/Nethermind/Nethermind.Blockchain.Test/Producers/BlockProducerBaseTests.FeeCollector.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/InvalidBlockDetector.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchain.cs, src/Nethermind/Nethermind.Core.Test/Blockchain/TestBlockchainUtil.cs, src/Nethermind/Nethermind.Core.Test/Modules/TestEnvironmentModule.cs, src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcSocketsClientTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/DebugRpcModuleTests.TraceTransaction.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcModuleTests.cs, src/Nethermind/Nethermind.JsonRpc.Test/Modules/Eth/EthRpcSimulateTestsBase.cs
- Fix randomly failing test due to genesis loader waiting for `NewHead` event while `AddBlock` wait for `BlockAdded` event.
- Ensure that the head after the context init is of the right block number.
- Ensure TX pool tx removed at end of `AddBlock`.
- Make components lazy to make unit test run faster.
- Do not allow additional tx in the created block unless explicitly allowed.
- Fail test when invalid block is detected in `AddBlock`.
- Waiting....
=> Fix inconsistent test.

src/Nethermind/Nethermind.Runner/configs/taiko-alethia.json, src/Nethermind/Nethermind.Runner/configs/taiko-hekla.json
Fixes 
https://github.com/NethermindEth/nethermind/issues/9280
Taiko can no longer snap sync, since the older state is required to process bigger batches (100-200+ L2 blocks), which is not present when performing snap sync. Modify the default config to not use snap/fast sync and ensure the pruning boundary is big enough to cover the blocks for one batch.
- Remove fast/snap sync
- Add Pruning.PruningBoundary
=> Fix Taiko Chains Default Config

src/Nethermind/Nethermind.Evm.Test/Eip1283Tests.cs, src/Nethermind/Nethermind.Evm.Test/Eip2200Tests.cs, src/Nethermind/Nethermind.Evm.Test/Eip2935Tests.cs, src/Nethermind/Nethermind.Evm.Test/Eip3529RefundsTests.cs, src/Nethermind/Nethermind.Evm.Test/Eip6780Tests.cs, src/Nethermind/Nethermind.Evm.Test/Tracing/ProofTxTracerTests.cs, src/Nethermind/Nethermind.Evm/State/IWorldState.cs, src/Nethermind/Nethermind.Evm/State/IWorldStateExtensions.cs, src/Nethermind/Nethermind.Evm/State/IWorldStateScopeProvider.cs, src/Nethermind/Nethermind.State.Test/TrieStoreScopeProviderTests.cs, src/Nethermind/Nethermind.State/PartialStorageProviderBase.cs, src/Nethermind/Nethermind.State/PersistentStorageProvider.cs, src/Nethermind/Nethermind.State/StateProvider.cs, src/Nethermind/Nethermind.State/StateTree.cs, src/Nethermind/Nethermind.State/StorageTree.cs, src/Nethermind/Nethermind.State/TrieStoreScopeProvider.cs, src/Nethermind/Nethermind.State/WorldState.cs, src/Nethermind/Nethermind.Trie.Test/TrieTests.cs
Require #9089 
- Make the interface nicer and more future proof.
- Remove `IStateTree`, storage root and update storage root. 
- Comes at a downside of an additional dictionary and concurrent queue. 
- All set goes through a single write batch.
=> Refactor/Nicer IWorldStateScopeProvider interface

src/Nethermind/Nethermind.Flashbots/Flashbots.cs, src/Nethermind/Nethermind.Flashbots/FlashbotsConfig.cs, src/Nethermind/Nethermind.JsonRpc/Modules/ModuleType.cs
- Disable the Flashbots module and it's associated RPC endpoints (`flashbots`, `rbuilder`) by default. 
Tested a couple of configs to verify that the module is not being loaded or any RPC method is added.
We should not need to update anything since the docs are generated from configuration attributes, which listed the Flashbot module as disabled by default (this was actually not the case though).
Despite the config listing Flashbots as a disabled module by default, our code actually enabled it. This PR disables the plugin by default.
To explicitly enable the plugin include the flag `--Flashbots.Enabled=true`. Also, to enable the RPC endpoints include `--JsonRpc.EnabledModules=flashbots,rbuilder,...` as appropriate (it could be argued that enabling the plugin should automatically include …
=> Disable `Flashbots` module by default

src/Nethermind/Nethermind.Evm/VirtualMachine.cs
For Arbitrum, we actually want to override `ExecutePrecompile()` because precompiles can both revert and fail (without reverting) impacting any returned output as well as any gas refund (to sender if top-level, or to calling contract if nested call).
See [Arbitrum PR](https://github.com/NethermindEth/nethermind-arbitrum/pull/279)
For example, one case where the base implementation of `ExecutePrecompile()` does not work for Arbitrum: anytime a precompile reverts (not an ungraceful failure). The base implem will either set the result as a failure (not a revert) or will set the gas left as 0 (no refund).
I guess it's normal behaviour for Ethereum as it's been working so far, but i thought reverting ethereum precompiles would refund caller..?
_Please choose one of the …
=> Make ExecutePrecompile overridable instead of RunPrecompile
